### ISSUE TITLE
Volatility returns no suggested profile

### ISSUE THREAD

**Issue by ali-haidar** [volatilityfoundation/volatility#100]
I am working on a ram image of a windows 8.1 x64 , and using volatility 2.4 standalone ,

when i run volatility with the arg -f ET-20141007-185504.raw imageinfo 

the result is :
          Suggested Profile(s) : No suggestion (Instantiated with no profile)
                     AS Layer1 : FileAddressSpace (D:\d\volatility_2.4.win.stand
alone\volatility_2.4.win.standalone\ET-20141007-185504.raw)
                      PAE type : No PAE

if i run it with kbdgscan option i get nothing a blank screen when i am done,

it works on other windows ram images fine ?

Help please.

**Comment by jersten** [comment]
To add to this; experience same issue. If using a tool such as `WinPmem`, make sure you dump as raw with `--format raw`.
