### ISSUE TITLE
Unable to read from registry/keys for Windows 8.1 x86 and x64 dumps

### ISSUE THREAD

**Issue by jahil** [volatilityfoundation/volatility#104]
Unable to read  from registry/keys for Windows 8.1 x86 dump. (**DumpIt.exe**)

hashdump

```
python vol.py --profile=Win8SP1x86 -f ~/win8.raw hashdump
Volatility Foundation Volatility Framework 2.4
ERROR   : volatility.plugins.registry.lsadump: Unable to read hashes from registry
```

lsadump:

```
python vol.py --profile=Win8SP1x86 -f ~/win8.raw lsadump
Volatility Foundation Volatility Framework 2.4
ERROR   : volatility.plugins.registry.lsadump: Unable to read LSA secrets from registry
```

hivelist

```
python vol.py --profile=Win8SP1x86 -f ~/win8.raw hivelist
Volatility Foundation Volatility Framework 2.4
Virtual    Physical   Name
---------- ---------- ----
```

Unable to read  from registry/keys for Windows 8.1 x64 dump. (**winpmem.exe**)

hashdump:

```
python vol.py --profile=Win8SP1x64 -f ~/usman.dump hashdump
Volatility Foundation Volatility Framework 2.4
ERROR   : volatility.plugins.registry.lsadump: Unable to read hashes from registry
```

lsadump

```
python vol.py --profile=Win8SP1x64 -f ~/usman.dump lsadump
Volatility Foundation Volatility Framework 2.4
ERROR   : volatility.plugins.registry.lsadump: Unable to read LSA secrets from registry
```

hivelist

```
python vol.py --profile=Win8SP1x64 -f ~/usman.dump hivelist
Volatility Foundation Volatility Framework 2.4
Virtual            Physical           Name
------------------ ------------------ ----
```

**Comment by ATrashInTheWorld** [comment]
Sorry to ask, I'm new to GitHub. 
I don't where is the appropriate place to ask that:
I'm actually having the same problem and result as the top.
No result or error from any hive commands.

```
ex;
volatility -f DUMPFILE.dmp --profile=Win10x64_15063 hivelist
Volatility Foundation Volatility Framework 2.6
Virtual            Physical           Name
------------------ ------------------ ----
```

Here are more specification about my machine. Tell me if you need more:
`      Suggested Profile(s) : Win10x64_10586, Win10x64_14393, Win10x64, Win2016x64_14393, Win10x64_15063 (Instantiated with Win10x64_15063)
                     AS Layer1 : SkipDuplicatesAMD64PagedMemory (Kernel AS)
                     AS Layer2 : WindowsCrashDumpSpace64 (Unnamed AS)
                     AS Layer3 : FileAddressSpace (/root/lol/ANALYSIS_FORENSICS/BOGANEL-20180114-004634.dmp)
                      PAE type : No PAE
                           DTB : 0x1ab000L
                          KDBG : 0xf801d65ee4d0L
          Number of Processors : 4
     Image Type (Service Pack) : 0
                KPCR for CPU 0 : 0xfffff801d4e66000L
                KPCR for CPU 1 : 0xffffb681e4e20000L
                KPCR for CPU 2 : 0xffffb681e4ec0000L
                KPCR for CPU 3 : 0xffffb681e4f4d000L
             KUSER_SHARED_DATA : 0xfffff78000000000L
           Image date and time : 2018-01-14 00:47:05 UTC+0000
     Image local date and time : 2018-01-13 19:47:05 -0500


`
volatility -f BOGANEL-20180114-004634.dmp --profile=Win10x64_15063 kdbgscan
Volatility Foundation Volatility Framework 2.6
**************************************************
Instantiating KDBG using: Unnamed AS Win10x64_15063 (6.4.15063 64bit)
Offset (V)                    : 0xf801d65ee4d0
Offset (P)                    : 0x228bee4d0
KdCopyDataBlock (V)           : 0xf801d649c9c4
Block encoded                 : Yes
Wait never                    : 0xaf3e333b00b90bc3
Wait always                   : 0x5c85cd77419ad800
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win10x64_15063
Version64                     : 0xf801d65f1678 (Major: 15, Minor: 16299)
Service Pack (CmNtCSDVersion) : 0
Build string (NtBuildLab)     : 16299.15.amd64fre.rs3_release.17
PsActiveProcessHead           : 0xfffff801d65fdaa0 (215 processes)
PsLoadedModuleList            : 0xfffff801d6604fd0 (218 modules)
KernelBase                    : 0xfffff801d629e000 (Matches MZ: True)
Major (OptionalHeader)        : 10
Minor (OptionalHeader)        : 0
KPCR                          : 0xfffff801d4e66000 (CPU 0)
KPCR                          : 0xffffb681e4e20000 (CPU 1)
KPCR                          : 0xffffb681e4ec0000 (CPU 2)
KPCR                          : 0xffffb681e4f4d000 (CPU 3)
