### ISSUE TITLE
compilation error module.c against CentOS 5.11 kernel 2.6.18-398.el5

### ISSUE THREAD

**Issue by jahil** [volatilityfoundation/volatility#111]
compilation error module.c again kernel centos 5.11 2.6.18-398.el5.

uname: ``` 2.6.18-398.el5 #1 SMP Tue Sep 16 20:50:52 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux```

make:
```
make
make -C //lib/modules/2.6.18-398.el5/build CONFIG_DEBUG_INFO=y M="/tmp/volatility-master/tools/linux" modules
make[1]: Entering directory `/usr/src/kernels/2.6.18-398.el5-x86_64'
  CC [M]  /tmp/volatility-master/tools/linux/module.o
/tmp/volatility-master/tools/linux/module.c:345:5: warning: "STATS" is not defined
/tmp/volatility-master/tools/linux/module.c:361:5: warning: "DEBUG" is not defined
/tmp/volatility-master/tools/linux/module.c:213: error: storage size of ‘module_sect_attrs’ isn’t known
make[2]: *** [/tmp/volatility-master/tools/linux/module.o] Error 1
make[1]: *** [_module_/tmp/volatility-master/tools/linux] Error 2
make[1]: Leaving directory `/usr/src/kernels/2.6.18-398.el5-x86_64'
make: *** [dwarf] Error 2

```

**Comment by Abyss-W4tcher** [comment]
This line doesn't really make any sense I think :

https://github.com/volatilityfoundation/volatility/blob/master/tools/linux/module.c#L235C42-L235C42

I am not a C expert, but if we go in the "else", "struct module_sect_attrs" is never defined for "struct module_sections module_sect_attrs;". 

I ran into the same error as the author, and commenting the line : 

```c
struct module_sections module_sect_attrs;
```

made the kernel (Debian 2.6.23-1-amd64_2.6.23-2) compile successfully...
