### ISSUE TITLE
compilation error module.c against RHEL 7 kernel 3.10

### ISSUE THREAD

**Issue by jahil** [volatilityfoundation/volatility#112]
release: ```Red Hat Enterprise Linux Server release 7.0 (Maipo)```

uname: ```3.10.0-123.8.1.el7.x86_64 #1 SMP Mon Aug 11 13:37:49 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux```

compilation error module.c:
```
[root@ip-10-10-100-243 linux]# make
make -C //lib/modules/3.10.0-123.8.1.el7.x86_64/build CONFIG_DEBUG_INFO=y M="/opt/volatility/tools/linux" modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-123.8.1.el7.x86_64'
  CC [M]  /opt/volatility/tools/linux/module.o
/opt/volatility/tools/linux/module.c:183:0: warning: "RADIX_TREE_MAX_TAGS" redefined [enabled by default]
 #define RADIX_TREE_MAX_TAGS     2
 ^
In file included from include/linux/fs.h:13:0,
                 from /opt/volatility/tools/linux/module.c:9:
include/linux/radix-tree.h:61:0: note: this is the location of the previous definition
 #define RADIX_TREE_MAX_TAGS 3
 ^
/opt/volatility/tools/linux/module.c:185:8: error: redefinition of ‘struct radix_tree_node’
 struct radix_tree_node {
        ^
In file included from include/linux/fs.h:13:0,
                 from /opt/volatility/tools/linux/module.c:9:
include/linux/radix-tree.h:87:8: note: originally defined here
 struct radix_tree_node {
        ^
make[2]: *** [/opt/volatility/tools/linux/module.o] Error 1
make[1]: *** [_module_/opt/volatility/tools/linux] Error 2
make[1]: Leaving directory `/usr/src/kernels/3.10.0-123.8.1.el7.x86_64'
make: *** [dwarf] Error 2
```

**Comment by atcuno** [comment]
Can you try the latest git pul of Volatility and see if it fixes it? I believe I have found a solution

**Comment by jahil** [comment]
release: ```Red Hat Enterprise Linux Server release 7.0 (Maipo)```

uname: ```3.10.0-123.20.1.el7.x86_64 #1 SMP Wed Jan 21 09:45:55 EST 2015 x86_64 x86_64 x86_64 GNU/Linux```
[ec2-user@ip-10-169-49-57 linux]$ sudo make
make -C //lib/modules/3.10.0-123.20.1.el7.x86_64/build CONFIG_DEBUG_INFO=y M="" modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-123.20.1.el7.x86_64'
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf --silentoldconfig Kconfig
make[1]: Leaving directory `/usr/src/kernels/3.10.0-123.20.1.el7.x86_64'
make[2]: *** No rule to make target `/usr/src/kernels/3.10.0-123.20.1.el7.x86_64/arch/x86/syscalls/syscall_32.tbl', needed by `arch/x86/syscalls/../include/generated/uapi/asm/unistd_32.h'.  Stop.
make[1]: *** [archheaders] Error 2
make: *** [dwarf] Error 2

**Comment by juju4** [comment]
Here, have initial error on Centos7 and volatility 2.4.1, ok with upstream volatility

**Comment by atcuno** [comment]
Is this still an any issue for anyone that commented? We made some module.c changes recently that hopefully address the issue. If not please let us know.

**Comment by juju4** [comment]
On my side, today's upstream volatility is ok
tested on vagrant image: puppetlabs/centos-7.0-64-puppet-enterprise

```
[vagrant@localhost linux]$ uname -a
Linux localhost.localdomain 3.10.0-123.20.1.el7.x86_64 #1 SMP Thu Jan 29 18:05:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[vagrant@localhost linux]$ cd ~/volatility/tools/linux/
[vagrant@localhost linux]$ make
make -C //lib/modules/3.10.0-229.7.2.el7.x86_64/build CONFIG_DEBUG_INFO=y M="/home/vagrant/volatility/tools/linux" modules
make[1] : on entre dans le répertoire « /usr/src/kernels/3.10.0-229.7.2.el7.x86_64 »
  CC [M]  /home/vagrant/volatility/tools/linux/module.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/vagrant/volatility/tools/linux/module.mod.o
  LD [M]  /home/vagrant/volatility/tools/linux/module.ko
make[1] : on quitte le répertoire « /usr/src/kernels/3.10.0-229.7.2.el7.x86_64 »
dwarfdump -di module.ko > module.dwarf
make -C //lib/modules/3.10.0-229.7.2.el7.x86_64/build M="/home/vagrant/volatility/tools/linux" clean
make[1] : on entre dans le répertoire « /usr/src/kernels/3.10.0-229.7.2.el7.x86_64 »
  CLEAN   /home/vagrant/volatility/tools/linux/.tmp_versions
  CLEAN   /home/vagrant/volatility/tools/linux/Module.symvers
make[1] : on quitte le répertoire « /usr/src/kernels/3.10.0-229.7.2.el7.x86_64 »
```

**Comment by jahil** [comment]
module compiled successfully on RHEL 7.0
'''
[root@ip-10-171-98-178 linux]# make
make -C //lib/modules/3.10.0-123.20.1.el7.x86_64/build CONFIG_DEBUG_INFO=y M="/home/ec2-user/volatility/tools/linux" modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-123.20.1.el7.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
make[1]: Leaving directory `/usr/src/kernels/3.10.0-123.20.1.el7.x86_64'
dwarfdump -di module.ko > module.dwarf
make -C //lib/modules/3.10.0-123.20.1.el7.x86_64/build M="/home/ec2-user/volatility/tools/linux" clean
make[1]: Entering directory `/usr/src/kernels/3.10.0-123.20.1.el7.x86_64'
  CLEAN   /home/ec2-user/volatility/tools/linux/.tmp_versions
  CLEAN   /home/ec2-user/volatility/tools/linux/Module.symvers
make[1]: Leaving directory `/usr/src/kernels/3.10.0-123.20.1.el7.x86_64'
'''

**Comment by sandy1224** [comment]
@atcuno  I tested in Centos7,and In volatility/tools/linux/Makefile, change "M="$(PWD)"" to "M=$(shell pwd)", compiles ok.
