### ISSUE TITLE
_vicinity_scan in impscan

### ISSUE THREAD

**Issue by TakahiroHaruyama** [volatilityfoundation/volatility#126]
The logic in _vicinity_scan (line 157) seems to be incorrect.
I noticed during checking whether the candidate of IAT entry is continued or not.

            if (not call_dest or
                    call_dest < base_address or
                    call_dest > base_address + data_len):

This should be the following, right?

            if (not call_dest or (call_dest > base_address and call_dest < base_address + data_len)):

**Comment by iMHLv2** [comment]
Thank you - sorry for the delay getting it merged.
