### ISSUE TITLE
module.c compilation error against Linux debian 2.6.18-6-686

### ISSUE THREAD

**Issue by sam-b** [volatilityfoundation/volatility#132]
![screenshot from 2014-12-02 22 37 06](https://cloud.githubusercontent.com/assets/997395/5272331/cec337c6-7a73-11e4-9f70-0a85e1db2fb6.png)
Build module.c is failing - sorry for the image but its in a qemu vm.

**Comment by atcuno** [comment]
Can you try with the latest verison of Volatility from github? I think I found a solution.
