### ISSUE TITLE
module.c error generating android profile

### ISSUE THREAD

**Issue by antonianis** [volatilityfoundation/volatility#150]
Hi Im trying to genarate a Linux profile for Android 4.3 Samsung Galaxy S3 ( kernel: 3.0.31-2168382 ) but im getting the following error 

make[1]: Entering directory `/home/volatilityandroid/Desktop/Kernel'
  CC [M]  /home/volatilityandroid/volatility/tools/linux/module.o
/home/volatilityandroid/volatility/tools/linux/module.c:183:1: error: "RADIX_TREE_MAX_TAGS" redefined
In file included from include/linux/fs.h:391,
                 from /home/volatilityandroid/volatility/tools/linux/module.c:9:
include/linux/radix-tree.h:54:1: error: this is the location of the previous definition
make[2]: *** [/home/volatilityandroid/volatility/tools/linux/module.o] Error 1
make[1]: *** [_module_/home/volatilityandroid/volatility/tools/linux] Error 2
make[1]: Leaving directory `/home/volatilityandroid/Desktop/Kernel'
make: *** [dwarf] Error 2

**Comment by atcuno** [comment]
Hello,

How are you acquiring memory? It is strange that the translation would work but the process list would be so busted. Did any other plugins run?

**Comment by antonianis** [comment]
I used lime to acquire the memory dump. Yes i tried other plugins but i got similar results for all. I check my dump and the it's not empty or damaged.

**Comment by atcuno** [comment]
Can you try the latest git pull and test if your results are still busted? If so, I am thinking that it was ab ad memory capture and not a Volatility issue
