### ISSUE TITLE
linux_strings weird error

### ISSUE THREAD

**Issue by em0vskangoura** [volatilityfoundation/volatility#157]
Hello again,

I tried to play with linux_strings a little bit using an Android RAM image. Here is the traceback and the command I am running: https://bpaste.net/show/37d55fcf17e6

So basically the issue is at line 202 of file /volatility/plugins/linux.py and for some reason kpage is always None.

Am I doing something wrong ?

EDIT: I realized that I was also providing wrong string file, since I put a simple check to bypass that issue like:

      if kpage == None:
                continue

but then I got error "String file format invalid."

Any help is much appreciated!

**Comment by atcuno** [comment]
Can you paste your strings file (or some lines of it)? It requires a pretty specfic format for the offsets and the strings.

**Comment by em0vskangoura** [comment]
Hey thanks for the reply. I am sorry I do not have access to the strings file I was trying to use. The odds of me using a wrong input file are high if you say that requires specific format.

Where can I see an example of it ? So I can later on try it.

**Comment by gleeda** [comment]
You can find information on how to create a proper strings file here: https://github.com/volatilityfoundation/volatility/wiki/Command%20Reference#strings

**Comment by em0vskangoura** [comment]
Ok, thank you very much gleeda! I'll look it on the next days and report back if there's a problem.
