### ISSUE TITLE
WARNING : volatility.renderers.dot: Dot output will be unhelpful since the TreeGrid is a flat list

### ISSUE THREAD

**Issue by evild3ad** [volatilityfoundation/volatility#166]
Error while rendering dot output (psscan):

Mac OS X 10.9.5
Volatility 2.4
dot - graphviz version 2.38.0 (20140413.2041)

$ python vol.py --profile=Win7SP1x86 -f /opt/memory-samples/Dridex.mem psscan --tz=Europe/Berlin --output=dot --output-file=test.dot

WARNING : volatility.renderers.dot: Dot output will be unhelpful since the TreeGrid is a flat list

Volatility Foundation Volatility Framework 2.4 (Beta) => works! ;-)

**Comment by gleeda** [comment]
The warning isn't really an error, it's just letting you know that the graph that is created may not be very informational.  For example, if the graph is just mostly lonely nodes, then it loses meaning as a graph.  How did your output look?  was it as expected?

**Comment by evild3ad** [comment]
When I'm using Volatility 2.4 Beta I get a processtree...in Volatility 2.4 I get everything in one flat line...without lines between the bubbles...no hierarchical view.
-------------------------------------------------------------------------------------
Volatility Foundation Volatility Framework 2.4 (Beta)
digraph processtree { 
graph [rankdir = "TB"];
pid2516 -> pid3544 [];
pid2680 -> pid1072 [];
pid800 -> pid1532 [];
pid492 -> pid1524 [];
pid1556 -> pid2516 [];
pid492 -> pid1076 [];
pid0 -> pid4 [];
pid492 -> pid3432 [];
pid492 -> pid1596 [];
pid492 -> pid2028 [];
pid336 -> pid344 [];
pid380 -> pid432 [];
pid336 -> pid396 [];
pid396 -> pid508 [];
pid2680 -> pid3780 [];
pid492 -> pid1680 [];
pid492 -> pid2744 [];
pid492 -> pid3032 [];
pid1556 -> pid2680 [];
pid492 -> pid672 [];
pid380 -> pid388 [];
pid848 -> pid3620 [];
pid492 -> pid1472 [];
pid1556 -> pid2444 [];
pid3032 -> pid3340 [];
pid492 -> pid1300 [];
pid492 -> pid2308 [];
pid2680 -> pid3440 [];
pid1488 -> pid1556 [];
pid492 -> pid800 [];
pid492 -> pid1628 [];
pid492 -> pid1096 [];
pid492 -> pid1864 [];
pid492 -> pid2592 [];
pid492 -> pid760 [];
pid492 -> pid824 [];
pid396 -> pid492 [];
pid492 -> pid956 [];
pid1556 -> pid2432 [];
pid4 -> pid252 [];
pid1680 -> pid1756 [];
pid492 -> pid1264 [];
pid1628 -> pid1668 [];
pid492 -> pid848 [];
pid492 -> pid1456 [];
pid396 -> pid500 [];
pid492 -> pid596 [];
pid2744 [label="2744 | msiexec.exe |running" shape="record" ];
pid3544 [label="3544 | sbservice.exe |running" shape="record" ];
pid2432 [label="2432 | SharedIntApp.e |running" shape="record" ];
pid800 [label="800 | svchost.exe |running" shape="record" ];
pid396 [label="396 | wininit.exe |running" shape="record" ];
pid4 [label="4 | System |running" shape="record" ];
pid1532 [label="1532 | dwm.exe |running" shape="record" ];
pid3340 [label="3340 | SearchProtocol |exited\n2014-12-07 09:34:40 CET+0100" shape="record"  style = "filled" fillcolor = "lightgray" ];
pid3780 [label="3780 | SnagPriv.exe |running" shape="record" ];
pid1756 [label="1756 | prl_tools.exe |running" shape="record" ];
pid1668 [label="1668 | coherence.exe |running" shape="record" ];
pid1300 [label="1300 | svchost.exe |running" shape="record" ];
pid848 [label="848 | svchost.exe |running" shape="record" ];
pid760 [label="760 | svchost.exe |running" shape="record" ];
pid1628 [label="1628 | coherence.exe |running" shape="record" ];
pid2592 [label="2592 | msdtc.exe |running" shape="record" ];
pid1556 [label="1556 | explorer.exe |running" shape="record" ];
pid2308 [label="2308 | svchost.exe |running" shape="record" ];
pid1096 [label="1096 | svchost.exe |running" shape="record" ];
pid3032 [label="3032 | SearchIndexer. |running" shape="record" ];
pid3432 [label="3432 | wmpnetwk.exe |running" shape="record" ];
pid508 [label="508 | lsm.exe |running" shape="record" ];
pid956 [label="956 | svchost.exe |running" shape="record" ];
pid2028 [label="2028 | UI0Detect.exe |running" shape="record" ];
pid1076 [label="1076 | svchost.exe |running" shape="record" ];
pid344 [label="344 | csrss.exe |running" shape="record" ];
pid2516 [label="2516 | SecureBanking. |running" shape="record" ];
pid1596 [label="1596 | svchost.exe |running" shape="record" ];
pid388 [label="388 | csrss.exe |running" shape="record" ];
pid3620 [label="3620 | taskeng.exe |running" shape="record" ];
pid1456 [label="1456 | dllhost.exe |running" shape="record" ];
pid432 [label="432 | winlogon.exe |running" shape="record" ];
pid1472 [label="1472 | taskhost.exe |running" shape="record" ];
pid500 [label="500 | lsass.exe |running" shape="record" ];
pid1524 [label="1524 | armsvc.exe |running" shape="record" ];
pid2680 [label="2680 | Snagit32.exe |running" shape="record" ];
pid3440 [label="3440 | TscHelp.exe |running" shape="record" ];
pid1864 [label="1864 | dllhost.exe |running" shape="record" ];
pid252 [label="252 | smss.exe |running" shape="record" ];
pid824 [label="824 | svchost.exe |running" shape="record" ];
pid596 [label="596 | svchost.exe |running" shape="record" ];
pid1264 [label="1264 | spoolsv.exe |running" shape="record" ];
pid1680 [label="1680 | prl_tools_serv |running" shape="record" ];
pid1072 [label="1072 | SnagitEditor.e |running" shape="record" ];
pid492 [label="492 | services.exe |running" shape="record" ];
pid672 [label="672 | svchost.exe |running" shape="record" ];
pid2444 [label="2444 | prl_cc.exe |running" shape="record" ];
-------------------------------------------------------------------------------------
Volatility Foundation Volatility Framework 2.4
WARNING : volatility.renderers.dot: Dot output will be unhelpful since the TreeGrid is a flat list
digraph output {
  node[shape = Mrecord];
  # rankdir=LR;
  Node1 [label="{Offset(P): 0x3e414b38|Name: svchost.exe|PID: 1596|PPID: 492|PDB: 0x3ee22360|Time Created: 2014-12-07 08:09:56 CET+0100|Time Exited: }"];
  Node2 [label="{Offset(P): 0x3e41aa80|Name: coherence.exe|PID: 1628|PPID: 492|PDB: 0x3ee22380|Time Created: 2014-12-07 08:09:56 CET+0100|Time Exited: }"];
  Node3 [label="{Offset(P): 0x3e426a60|Name: prl_tools_serv|PID: 1680|PPID: 492|PDB: 0x3ee223c0|Time Created: 2014-12-07 08:09:57 CET+0100|Time Exited: }"];
  Node4 [label="{Offset(P): 0x3e427d40|Name: coherence.exe|PID: 1668|PPID: 1628|PDB: 0x3ee223a0|Time Created: 2014-12-07 08:09:56 CET+0100|Time Exited: }"];
  Node5 [label="{Offset(P): 0x3e43bb40|Name: SecureBanking.|PID: 2516|PPID: 1556|PDB: 0x3ee22540|Time Created: 2014-12-07 09:10:57 CET+0100|Time Exited: }"];
  Node6 [label="{Offset(P): 0x3e44c030|Name: prl_tools.exe|PID: 1756|PPID: 1680|PDB: 0x3ee22400|Time Created: 2014-12-07 08:09:58 CET+0100|Time Exited: }"];
  Node7 [label="{Offset(P): 0x3e497908|Name: dllhost.exe|PID: 1456|PPID: 492|PDB: 0x3ee222e0|Time Created: 2014-12-07 09:10:13 CET+0100|Time Exited: }"];
  Node8 [label="{Offset(P): 0x3e521d40|Name: svchost.exe|PID: 2308|PPID: 492|PDB: 0x3ee22160|Time Created: 2014-12-07 09:10:35 CET+0100|Time Exited: }"];
  Node9 [label="{Offset(P): 0x3e529d40|Name: SharedIntApp.e|PID: 2432|PPID: 1556|PDB: 0x3ee224a0|Time Created: 2014-12-07 09:10:44 CET+0100|Time Exited: }"];
  Node10 [label="{Offset(P): 0x3e534030|Name: SnagPriv.exe|PID: 3780|PPID: 2680|PDB: 0x3ee22440|Time Created: 2014-12-07 09:12:40 CET+0100|Time Exited: }"];
  Node11 [label="{Offset(P): 0x3e53fd40|Name: prl_cc.exe|PID: 2444|PPID: 1556|PDB: 0x3ee22500|Time Created: 2014-12-07 09:10:50 CET+0100|Time Exited: }"];
  Node12 [label="{Offset(P): 0x3e54ad40|Name: msdtc.exe|PID: 2592|PPID: 492|PDB: 0x3ee22560|Time Created: 2014-12-07 09:11:08 CET+0100|Time Exited: }"];
  Node13 [label="{Offset(P): 0x3e57bd40|Name: SnagitEditor.e|PID: 1072|PPID: 2680|PDB: 0x3ee226e0|Time Created: 2014-12-07 09:13:56 CET+0100|Time Exited: }"];
  Node14 [label="{Offset(P): 0x3e5896c8|Name: Snagit32.exe|PID: 2680|PPID: 1556|PDB: 0x3ee224c0|Time Created: 2014-12-07 09:11:16 CET+0100|Time Exited: }"];
  Node15 [label="{Offset(P): 0x3e679358|Name: csrss.exe|PID: 388|PPID: 380|PDB: 0x3ee220a0|Time Created: 2014-12-07 08:09:29 CET+0100|Time Exited: }"];
  Node16 [label="{Offset(P): 0x3e67d648|Name: wininit.exe|PID: 396|PPID: 336|PDB: 0x3ee220c0|Time Created: 2014-12-07 08:09:29 CET+0100|Time Exited: }"];
  Node17 [label="{Offset(P): 0x3e6d6d40|Name: winlogon.exe|PID: 432|PPID: 380|PDB: 0x3ee22040|Time Created: 2014-12-07 08:09:29 CET+0100|Time Exited: }"];
  Node18 [label="{Offset(P): 0x3e6f79f0|Name: svchost.exe|PID: 672|PPID: 492|PDB: 0x3ee22140|Time Created: 2014-12-07 08:09:37 CET+0100|Time Exited: }"];
  Node19 [label="{Offset(P): 0x3e6ff030|Name: services.exe|PID: 492|PPID: 396|PDB: 0x3ee22080|Time Created: 2014-12-07 08:09:31 CET+0100|Time Exited: }"];
  Node20 [label="{Offset(P): 0x3e701a10|Name: lsm.exe|PID: 508|PPID: 396|PDB: 0x3ee22100|Time Created: 2014-12-07 08:09:31 CET+0100|Time Exited: }"];
  Node21 [label="{Offset(P): 0x3e707458|Name: lsass.exe|PID: 500|PPID: 396|PDB: 0x3ee220e0|Time Created: 2014-12-07 08:09:31 CET+0100|Time Exited: }"];
  Node22 [label="{Offset(P): 0x3e7246e0|Name: svchost.exe|PID: 596|PPID: 492|PDB: 0x3ee22120|Time Created: 2014-12-07 08:09:35 CET+0100|Time Exited: }"];
  Node23 [label="{Offset(P): 0x3e762030|Name: svchost.exe|PID: 760|PPID: 492|PDB: 0x3ee22180|Time Created: 2014-12-07 08:09:38 CET+0100|Time Exited: }"];
  Node24 [label="{Offset(P): 0x3e76d568|Name: svchost.exe|PID: 800|PPID: 492|PDB: 0x3ee221a0|Time Created: 2014-12-07 08:09:40 CET+0100|Time Exited: }"];
  Node25 [label="{Offset(P): 0x3e776d40|Name: svchost.exe|PID: 824|PPID: 492|PDB: 0x3ee221c0|Time Created: 2014-12-07 08:09:40 CET+0100|Time Exited: }"];
  Node26 [label="{Offset(P): 0x3e777d40|Name: svchost.exe|PID: 848|PPID: 492|PDB: 0x3ee221e0|Time Created: 2014-12-07 08:09:40 CET+0100|Time Exited: }"];
  Node27 [label="{Offset(P): 0x3e78d7d0|Name: svchost.exe|PID: 956|PPID: 492|PDB: 0x3ee22220|Time Created: 2014-12-07 08:09:42 CET+0100|Time Exited: }"];
  Node28 [label="{Offset(P): 0x3e7b4d18|Name: dllhost.exe|PID: 1864|PPID: 492|PDB: 0x3ee22460|Time Created: 2014-12-07 08:10:01 CET+0100|Time Exited: }"];
  Node29 [label="{Offset(P): 0x3e7ccb38|Name: taskhost.exe|PID: 1472|PPID: 492|PDB: 0x3ee222c0|Time Created: 2014-12-07 08:09:54 CET+0100|Time Exited: }"];
  Node30 [label="{Offset(P): 0x3e7ddd40|Name: dwm.exe|PID: 1532|PPID: 800|PDB: 0x3ee22320|Time Created: 2014-12-07 08:09:54 CET+0100|Time Exited: }"];
  Node31 [label="{Offset(P): 0x3e7dea28|Name: armsvc.exe|PID: 1524|PPID: 492|PDB: 0x3ee22300|Time Created: 2014-12-07 08:09:54 CET+0100|Time Exited: }"];
  Node32 [label="{Offset(P): 0x3e7e45c8|Name: explorer.exe|PID: 1556|PPID: 1488|PDB: 0x3ee22340|Time Created: 2014-12-07 08:09:55 CET+0100|Time Exited: }"];
  Node33 [label="{Offset(P): 0x3e92d930|Name: spoolsv.exe|PID: 1264|PPID: 492|PDB: 0x3ee22260|Time Created: 2014-12-07 08:09:50 CET+0100|Time Exited: }"];
  Node34 [label="{Offset(P): 0x3e94bb38|Name: svchost.exe|PID: 1300|PPID: 492|PDB: 0x3ee22280|Time Created: 2014-12-07 08:09:52 CET+0100|Time Exited: }"];
  Node35 [label="{Offset(P): 0x3e952530|Name: csrss.exe|PID: 344|PPID: 336|PDB: 0x3ee22060|Time Created: 2014-12-07 08:09:28 CET+0100|Time Exited: }"];
  Node36 [label="{Offset(P): 0x3e968030|Name: svchost.exe|PID: 1096|PPID: 492|PDB: 0x3ee22240|Time Created: 2014-12-07 08:09:44 CET+0100|Time Exited: }"];
  Node37 [label="{Offset(P): 0x3f1fe930|Name: smss.exe|PID: 252|PPID: 4|PDB: 0x3ee22020|Time Created: 2014-12-07 08:09:08 CET+0100|Time Exited: }"];
  Node38 [label="{Offset(P): 0x3f686d40|Name: SearchProtocol|PID: 3340|PPID: 3032|PDB: 0x3ee22520|Time Created: 2014-12-07 09:33:32 CET+0100|Time Exited: 2014-12-07 09:34:40 CET+0100}"];
  Node39 [label="{Offset(P): 0x3fa40888|Name: sbservice.exe|PID: 3544|PPID: 2516|PDB: 0x3ee224e0|Time Created: 2014-12-07 09:20:57 CET+0100|Time Exited: }"];
  Node40 [label="{Offset(P): 0x3fafd128|Name: taskeng.exe|PID: 3620|PPID: 848|PDB: 0x3ee22720|Time Created: 2014-12-07 09:26:00 CET+0100|Time Exited: }"];
  Node41 [label="{Offset(P): 0x3fb75a50|Name: UI0Detect.exe|PID: 2028|PPID: 492|PDB: 0x3ee22200|Time Created: 2014-12-07 09:24:25 CET+0100|Time Exited: }"];
  Node42 [label="{Offset(P): 0x3fc86d40|Name: SearchIndexer.|PID: 3032|PPID: 492|PDB: 0x3ee225e0|Time Created: 2014-12-07 09:11:40 CET+0100|Time Exited: }"];
  Node43 [label="{Offset(P): 0x3fc93308|Name: TscHelp.exe|PID: 3440|PPID: 2680|PDB: 0x3ee22640|Time Created: 2014-12-07 09:12:29 CET+0100|Time Exited: }"];
  Node44 [label="{Offset(P): 0x3fc9db38|Name: wmpnetwk.exe|PID: 3432|PPID: 492|PDB: 0x3ee22620|Time Created: 2014-12-07 09:12:28 CET+0100|Time Exited: }"];
  Node45 [label="{Offset(P): 0x3fd33938|Name: svchost.exe|PID: 1076|PPID: 492|PDB: 0x3ee226c0|Time Created: 2014-12-07 09:13:12 CET+0100|Time Exited: }"];
  Node46 [label="{Offset(P): 0x3fd40748|Name: msiexec.exe|PID: 2744|PPID: 492|PDB: 0x3ee225a0|Time Created: 2014-12-07 09:27:03 CET+0100|Time Exited: }"];
  Node47 [label="{Offset(P): 0x3ffb3a48|Name: System|PID: 4|PPID: 0|PDB: 0x185000|Time Created: 2014-12-07 08:09:08 CET+0100|Time Exited: }"];
}

**Comment by gleeda** [comment]
That is the "dot" output [1].  Did you use a viewer or convert it to a PNG/PDF or something else using Graphviz [2] ?

[1] http://www.graphviz.org/doc/info/lang.html

[2] http://www.graphviz.org/Documentation/dotguide.pdf

**Comment by evild3ad** [comment]
I opened the dot file with Graphviz GUI and Omnigraffle...and I converted the dot file with Graphviz commandline to PNG...always the same.

**Comment by gleeda** [comment]
Just to confirm: this is with the latest code from the master branch here on github?  do you get what you would expect if you run the `pstree` plugin?

**Comment by gleeda** [comment]
weird.. i get the appropriate data for `psscan` and `pslist` against my samples.  maybe your data has an issue.  Can you copy and paste output from `pstree` here or email it to me?

**Comment by evild3ad** [comment]
Ah...nice...it works with pstree now! ;-)
Yes...I downloaded the latest code from the master branch on github.

**Comment by evild3ad** [comment]
Thank you very much!!!

**Comment by gleeda** [comment]
no problem.  not sure why it didn't work with `psscan` earlier for you.  I'll see if i can duplicate it anywhere else.  i looked at the output and there were definitely some parent/child relationships that should have resulted in some graphs.

**Comment by evild3ad** [comment]
I'll upload the memory sample I used and my outputs for you tomorrow...and send you a download link via email.

**Comment by ikelos** [comment]
Just as a note.  Pslist (and probably psscan) produce text tables normally, pstree is one of the only plugins that produces an actual tree structure.  The dot renderer warns on plugins that only produce tables, because the output will be pretty useless.  Previously when we manually created the dot rendering code for each of the individual plugins, it will have constructed the tree appropriately.  If we want that functionality back, it'll either need to be two plugins (very bad idea), or custom text rendering code to ignore the tree data (uglyish idea), or we simply accept that the output will look like a tree in the text version (simplest, but potentially annoying and will definitely break programs relying on the existing output)...

**Comment by gleeda** [comment]
I'm closing this out for now.  I've added the render_dot function back to `pslist` and `psscan` in the `unified-binary` branch, which will be merged back to trunk at some point.
