### ISSUE TITLE
Error When I made Linux Profile

### ISSUE THREAD

**Issue by sinamanavi** [volatilityfoundation/volatility#168]
hello, I created Linux profile, from the ARM linux. so I created  the linux profile and when I try to readt it using the Volatility v2.4
I tried all all the plugins and none of the worked, 

volatility-2.4# python vol.py  -f '/root/Desktop/Captured/fmem-count524288bs1024.dd' kdbgscan
Volatility Foundation Volatility Framework 2.4
*** Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.ssdt (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.mac.apihooks (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.linux.apihooks (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.malware.threads (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.mac.apihooks_kernel (ImportError: No module named distorm3)
ERROR   : volatility.plugins.fileparam: The requested file doesn't exist

**Comment by atcuno** [comment]
Hello,

Can you please re-capture with LiME? fmem is not officially supported as it requires great care to get a proper sample with it.

Also, the file you passed as -f does not exist accoridng to Volatility. Can you please re-check your path?

Also, kdbgscan is a Windows only plugin. Can you try linux_pslist?

And finally, you need to specify the profile you created by passing --profile.

I am going to close this for now, but please re-open if you encounter any further issues.
