### ISSUE TITLE
Windows 8.1 x64 hibernation file cannot be read

### ISSUE THREAD

**Issue by vixtor** [volatilityfoundation/volatility#176]
Here are the steps to reproduce:
1. Turn off fast startup in Windows 8.1
2. Turn hibernation on and set hibernation file to 50% (powercfg –h -size 50)
3. Hibernate Windows (shutdown /H)
4. Start Fedora 20. Mount NTFS system partition as read-only
5. Start volatility 2.4 (from master branch)
6. run vol.py -f hiberfil.sys --profile=Win8SP1x64 hibinfo

Outputs:
No suitable address space mapping found
Tried to open image as:
...
WindowsHiberFileSpace32 - EXCEPTION: Struct PO_MEMORY_IMAGE has no member FirstTablePage
...

**Comment by gleeda** [comment]
We do not have support for Windows 8/8.1/2012 hibernation files yet.  There is an earlier issue that documents this as well.

**Comment by gleeda** [comment]
If you have the paid version of the the moonsols windows memory toolkit [1] you can try to use the hibr2bin utility to convert the hibernation file into a raw memory sample.  it worked fine on Windows 8 hibernation files, but may (or may not) work on Windows 8.1, you'll have to try for yourself.  I'm merging this issue into the original one (issue #25) and closing this out for now.

[1] http://www.moonsols.com/windows-memory-toolkit/

merging into (duplicate) issue: https://github.com/volatilityfoundation/volatility/issues/25

**Comment by Keegoal** [comment]
We've analyzed the hiberfil.sys file format of Windows 8, and will release a Decompressor a month later. Anybody who want to joint us or want to own the Decompressor may mail to us, flyingdreaming@bupt.edu.cn.
