### ISSUE TITLE
OverflowError: Python int too large to convert to SQLite INTEGER

### ISSUE THREAD

**Issue by Sebastienbr** [volatilityfoundation/volatility#191]
Seems there's a problem with long value (>0x7FFFFFFFFFFFFFFF) and sqlite...

C:\Volatility\volatility-e9cbdcc6c7>python vol.py -f Win7-64.vmem --profile=Win7SP1x64 pslist --output=sqlite --output-file=test.sqlite
Volatility Foundation Volatility Framework 2.4
INSERT INTO PSList VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [1, 0, 18446738026408463152L, 'System', 4, 0, 81, 526, -1, 0, '2013-11-29 16:39:19 UTC+0000', '']
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "C:\Volatility\volatility-e9cbdcc6c7\volatility\commands.py", line 140, in execute
    func(outfd, data)
  File "C:\Volatility\volatility-e9cbdcc6c7\volatility\commands.py", line 284, in render_sqlite
    self._render(outfd, SqliteRenderer(self.__class__.__name__, self._config), data)
  File "C:\Volatility\volatility-e9cbdcc6c7\volatility\commands.py", line 269, in _render
    renderer.render(outfd, output)
  File "C:\Volatility\volatility-e9cbdcc6c7\volatility\renderers\sqlite.py", line 44, in render
    grid.visit(None, self._add_row, {None: 0})
  File "C:\Volatility\volatility-e9cbdcc6c7\volatility\renderers\__init__.py", line 254, in visit
    accumulator = self._visit(children, function, accumulator, sort_key)
  File "C:\Volatility\volatility-e9cbdcc6c7\volatility\renderers\__init__.py", line 261, in _visit
    accumulator = function(n, accumulator)
  File "C:\Volatility\volatility-e9cbdcc6c7\volatility\renderers\sqlite.py", line 32, in _add_row
    self._db.execute(insert, [accumulator[node], accumulator[node.parent]] + list(node.values))

Thanks!

Sebastien

**Comment by gleeda** [comment]
verified.  though this is weird, because you can actually insert the values into the DB itself, so it's an issue with python inserting into sqlite:

```
sqlite> INSERT INTO PSList VALUES (1, 0, 18446738026408463152, 'System', 4, 0, 81, 526, -1, 0, '2013-11-29 16:39:19 UTC+0000', '');
sqlite> select * from pslist where Name is "System";
1|0|1.84467380264085e+19|System|4|0|81|526|-1|0|2013-11-29 16:39:19 UTC+0000|
```

The end of the error message is missing:

```
OverflowError: Python int too large to convert to SQLite INTEGER
```

Adding @ikelos in case he has a quick fix

**Comment by Sebastienbr** [comment]
Thanks gleeda.

If it can help, here's what I have found about this problem:

```
>>> import sqlite3
>>> sqlite3.connect(':memory:').execute('select ? + ?;', (18446738026408463152L, None))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python int too large to convert to SQLite INTEGER
```
> src: https://github.com/sampsyo/beets/issues/348#issuecomment-22616675

I think the error was generated from:

https://github.com/python/cpython/blob/master/Modules/_sqlite/util.c

**Comment by iMHLv2** [comment]
Ah nice catch Sebastien. IIRC sqlite3 doesn't support storing unsigned 64-bit integers. If you insert 18446738026408463152 into an INTEGER column, it actually gets stored as a string. 

There is no good solution to this in my previous encounters. We could explicitly store them as a string (i.e. call str before INSERT) and then cast back to int() on SELECT. Another option is masking the upper bits on INSERT and restoring them on SELECT. For example:

before insert: 

```
if value & (1 << 47):
      value = value & 0xFFFFFFFFFFFF
```

after select: 

```
if value & (1 << 47):
    value = value | 0xFFFF000000000000
```

**Comment by Sebastienbr** [comment]
Thanks Michael.

I think the value is already stored as TEXT in the db?

```
i.type = <class 'volatility.renderers.basic.Address'>

self._column_type(i.type) = TEXT
```
> https://github.com/volatilityfoundation/volatility/blob/master/volatility/renderers/sqlite.py#L42

**Comment by iMHLv2** [comment]
Kind of...the schema defines the column as TEXT, but we don't call str() before inserting Address types, so it ends up trying to insert them as integers. For example from your debug output:

```
 INSERT INTO PSList VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [1, 0, 18446738026408463152L, 'System', 4, 0, 81, 526, -1, 0, '2013-11-29 16:39:19 UTC+0000', '']
```

If we wanted to explicitly store it as a string, we'd have to call str(18446738026408463152L) first rather than inserting 18446738026408463152L.

**Comment by ikelos** [comment]
Hmmmm, it looks as though there is no neat way of allowing arithmetic operations against it (meaning people trying to do < or > will get text-< and text-> operations.  It might well be worth doing the sign extension check, but we'd have to remember that we've done this if we ever come to add true 64-bit support to volatility 2.  My hope is we won't have to deal with that until volatility 5, though!  5:P  The str conversion feels a little more of a hack, but it would certainly be easier to code up and keep the data intact.  Your call, I'm happy to help on the code if you need it?

**Comment by gleeda** [comment]
it seems like it might just be easier to store as a string (within the sqlite renderer only).  conversions can be made by whomever is accessing the data afterwards.

**Comment by Sebastienbr** [comment]
Yes, I agree: store as a string will be a good solution until Volatility 5 :-)

**Comment by gleeda** [comment]
Sabastien, please update and try again.

**Comment by Sebastienbr** [comment]
Thank you Jamie, it works :-)
