### ISSUE TITLE
patch for adding more than one item to a sqlite db

### ISSUE THREAD

**Issue by gleeda** [volatilityfoundation/volatility#192]
the real point of using sqlite is to be able to query across different tables of data.  Here's a patch to be able to accomplish this.  Hacky as it may be, we really should try to allow this:

```
diff --git a/volatility/commands.py b/volatility/commands.py
index 5f55841..ff67c65 100644
--- a/volatility/commands.py
+++ b/volatility/commands.py
@@ -116,7 +116,7 @@ class Command(object):
         ## Then we render the result in some way based on the
         ## requested output mode:
         function_name = "render_{0}".format(self._config.OUTPUT)
-        if self._config.OUTPUT_FILE:
+        if self._config.OUTPUT_FILE and not self._config.OUTPUT == "sqlite":
             if os.path.exists(self._config.OUTPUT_FILE):
                 debug.error("File " + self._config.OUTPUT_FILE + " already exists.  Cowardly refusing to overwrite it...")
             outfd = open(self._config.OUTPUT_FILE, 'wb')
diff --git a/volatility/renderers/sqlite.py b/volatility/renderers/sqlite.py
index 43a4c30..6727a5d 100644
--- a/volatility/renderers/sqlite.py
+++ b/volatility/renderers/sqlite.py
@@ -38,7 +38,7 @@ class SqliteRenderer(Renderer):
             debug.error("Please specify a valid output file using --output-file")
 
         self._db = sqlite3.connect(self._config.OUTPUT_FILE, isolation_level = None)
-        create = "CREATE TABLE " + self._plugin_name + "( id INTEGER, rowparent INTEGER, " + \
+        create = "CREATE TABLE IF NOT EXISTS " + self._plugin_name + "( id INTEGER, rowparent INTEGER, " + \
                  ", ".join(['"' + self._sanitize_name(i.name) + '" ' + self._column_type(i.type) for i in grid.columns]) + ")"
         self._db.execute(create)
         grid.visit(None, self._add_row, {None: 0})
```

**Comment by gleeda** [comment]
please let me know what you think about this, @ikelos

**Comment by gleeda** [comment]
if this doesn't work, then maybe we can add another flag just for the sqlite output file.  

I know we talked about it before, but it just doesn't make much sense to me to have sqlite without being able to add data from other plugins.  I can't imagine that most users would expect the current behavior either...  However, if everyone's cool with the way things are right now, i'll drop it.

**Comment by ikelos** [comment]
Hiya, I completely agree with what you're saying, but just be aware of how incredibly, incredibly hacky this is.  Since it's for the 2.x codebase, and 3.x won't suffer the same issue, you're welcome to solve this how you'd like (and yes, this patch appears as if it would solve it)...

**Comment by gleeda** [comment]
thanks, ikelos!  yeah, i know it's hacky, but i realize it won't be a "long term" thing.  so it should be good enough for now :-)

**Comment by ikelos** [comment]
Well, it will be long term if 2.5 will be the last big release before 3, so we'll just add this to the long list of reasons to work harder/faster on volatility 3...  5;)

**Comment by gleeda** [comment]
heh, i guess that's true... i'm just thinking about the big 3.0 on the horizon though ;-)
