### ISSUE TITLE
Volatility not working with QEMU

### ISSUE THREAD

**Issue by phambinh** [volatilityfoundation/volatility#198]
Hi folks,
I am trying to use volatility to analyze a memory dump from my guest VM, which is running Ubuntu server 12.04 on QEMU + KVM. The memory dump was gotten using QEMU's pmemsave command.
After that, I checked out volatility and created a profile to use, following the instructions described here:
http://resources.infosecinstitute.com/obtaining-information-dumping-memory/
Test to see that my newly created profile is there:
python vol.py --info | grep Linux
Volatility Foundation Volatility Framework 2.4
LinuxUbuntu12044x64 - A Profile for Linux Ubuntu12044 x64

Next, I got errors while trying to parse the memory dump gotten from previous step:
 python vol.py -f ../vm8.1G.dump memmap
Volatility Foundation Volatility Framework 2.4
No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareAddressSpace: No base Address Space
 QemuCoreDumpElf: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VMWareMetaAddressSpace: VMware metadata file is not available
 VirtualBoxCoreDumpElf64: ELF Header signature invalid
 VMWareAddressSpace: Invalid VMware signature: 0xf000ff53
 QemuCoreDumpElf: ELF Header signature invalid
 WindowsCrashDumpSpace32: Header signature invalid
 AMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 IA32PagedMemoryPae: No valid DTB found
 IA32PagedMemory: No valid DTB found
 OSXPmemELF: ELF Header signature invalid
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: No valid DTB found

I have searched around and seen that most likely this is caused by an invalid profile. However, I have no idea what I could be doing wrong in creating volatility profile. Furthermore, I also tried to use one of the provided profile for Ubuntu1204, but it didn't work either. 
Does anyone know what is wrong here?
Thanks!

**Comment by iMHLv2** [comment]
In your command "python vol.py -f ../vm8.1G.dump memmap" you didn't actually specify the profile. Try using --profile=NameOfYourProfile. Also, memmap is a Windows only plugin. There's a linux equivalent called linux_proc_maps that you can use instead.

**Comment by phambinh** [comment]
Thanks for your response. However, I just tried your suggestion and I got the same error:
python vol.py --profile=LinuxUbuntu1204x64 -f ../vm8.1G.dump linux_proc_maps
Volatility Foundation Volatility Framework 2.4
No suitable address space mapping found
....
 IA32PagedMemoryPae: Incompatible profile LinuxUbuntu1204x64 selected
 IA32PagedMemory: Incompatible profile LinuxUbuntu1204x64 selected
.....

Those two particular error lines tell me that there is something wrong with the profile I used...
Thanks!

**Comment by atcuno** [comment]
Hello,

Can you look for the error line for AMD64 (or just paste the whole
output?). The lines you selected are for 32 bit address spaces and they
are just saying they can't handle a 64 bit profile.

**Comment by phambinh** [comment]
Sorry, here is the full output:
python vol.py --profile=LinuxUbuntu12044x64 -f ../vm8.1G.dump linux_proc_maps
Volatility Foundation Volatility Framework 2.4
No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareAddressSpace: No base Address Space
 QemuCoreDumpElf: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: PO_MEMORY_IMAGE is not available in profile
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 VMWareMetaAddressSpace: VMware metadata file is not available
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VirtualBoxCoreDumpElf64: ELF Header signature invalid
 VMWareAddressSpace: Invalid VMware signature: 0xf000ff53
 QemuCoreDumpElf: ELF Header signature invalid
 WindowsCrashDumpSpace32: Header signature invalid
 AMD64PagedMemory: Failed valid Address Space check
 IA32PagedMemoryPae: Incompatible profile LinuxUbuntu12044x64 selected
 IA32PagedMemory: Incompatible profile LinuxUbuntu12044x64 selected
 OSXPmemELF: ELF Header signature invalid
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: Failed valid Address Space check

**Comment by iMHLv2** [comment]
there was an issue with volatility and qemu in general - see if this fixes it

**Comment by phambinh** [comment]
No, it doesn't fix it although I see some changes from the output:
python vol.py --profile=LinuxUbuntu1204x64 -f ../vm8.1G.dump linux_proc_maps
Volatility Foundation Volatility Framework 2.4
Pid      Start              End                Flags               Pgoff Major  Minor  Inode      File Path
-------- ------------------ ------------------ ------ ------------------ ------ ------ ---------- ---------
No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 QemuCoreDumpElf: No base Address Space
 VMWareAddressSpace: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: PO_MEMORY_IMAGE is not available in profile
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VMWareMetaAddressSpace: VMware metadata file is not available
 VirtualBoxCoreDumpElf64: ELF Header signature invalid
 QemuCoreDumpElf: ELF Header signature invalid
 VMWareAddressSpace: Invalid VMware signature: 0xf000ff53
 WindowsCrashDumpSpace32: Header signature invalid
 AMD64PagedMemory: Failed valid Address Space check
 IA32PagedMemoryPae: Incompatible profile LinuxUbuntu1204x64 selected
 IA32PagedMemory: Incompatible profile LinuxUbuntu1204x64 selected
 OSXPmemELF: ELF Header signature invalid
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: Failed valid Address Space check
