### ISSUE TITLE
Volatility 2.4 netscan plugin vs Win7SP1x86

### ISSUE THREAD

**Issue by The-Betrayer** [volatilityfoundation/volatility#199]
Hi all,

 I'm running Volatility 2.4 trying to analyze a dump from a Win7SP1 x86 image and when I run the netscan plugin the first 61 lines look like this: "WARNING : volatility.obj      : NoneObject as string: Pointer Owner invalid".
 Then I see the "expected" output. I use quotes for expected because some of the established connections correspond to a PID of -1. 

 Has anyone seen this (the "pointer owner invalid" entries)? Can it simply be ignored?

Thank you,
Alex.

**Comment by gleeda** [comment]
it looks like the net_object.Owner pointers are invalid (most likely partially overwritten records).  I've verified this on a sample of mine.  While it's technically not something you have to worry about and can be ignored, I can see how it's annoying.  I've issued a change at  730bf6ea1ef0f8228840bcb6e7094f296fe7abc6 to avoid these warnings.  Please update and let me know if you have any issues.

**Comment by gleeda** [comment]
I'm going to close this issue out now.  feel free to reopen if needed.

**Comment by The-Betrayer** [comment]
Thank you Gleeda!
