### ISSUE TITLE
Volatility 2.4 Win8.1 16G Issues

### ISSUE THREAD

**Issue by tonplan** [volatilityfoundation/volatility#200]
Just wondered if anyone has experienced issues with a combination of this new profile, and large memory size?

Some of the plugins/commands didn't work such as :
IMAGEINFO - takes forever as if hung, 3 days later is time to give up!
PSLIST - returns a blank list, but PSSCAN is good
PROCEXEDUMP - returns an error and suggests PROCDUMP with offset
PROCDUMP with offset - returns error "can't acquire AS"

On the other hand NETSCAN was great, suggesting it isn't a problem with the particular dump file.

**Comment by atcuno** [comment]
What tool did you use to perform acquisition?

It sounds like you actually have a corrupt memory dump as psscan and
netscan just scan physical memory looking for structures, while the
other plugins attempt to enumerate process through the kernel's list.

It is very common in corrupt dumps from tools such as DumpIt to get some
of the pages correctly (which lets the scanner plugin works), but to
break on a great deal of other pages, which breaks the stricter plugins
such as imageinfo and pslist.

**Comment by gleeda** [comment]
Try checking out the win81update1 branch (https://github.com/volatilityfoundation/volatility/tree/win81update1).  From your cloned repository:

```
$ git checkout win81update1
```

If that doesn't work, could you please send me the kernel file?  (usually ntoskrnl.exe, ntkrnlmp.exe, ntkrnlpa.exe, or ntkrpamp.exe).  you can email it to me.

**Comment by iMHLv2** [comment]
@tonplan were you able to test the win81update1 branch or copy the kernel file? Feel free to reopen if you get a chance to run these additional commands.
