### ISSUE TITLE
Cant run volatility command Pslist from Eclipse(python IDE)

### ISSUE THREAD

**Issue by AeeyAhmed** [volatilityfoundation/volatility#210]
I am using this code to print Pslist:
 python
>>> import volatility.conf as conf
>>> import volatility.registry as registry
>>> registry.PluginImporter()
<volatility.registry.PluginImporter object at 0x7f9608f3ac10>
>>> config = conf.ConfObject()
>>> import volatility.commands as commands
>>> import volatility.addrspace as addrspace
>>> registry.register_global_options(config, commands.Command)
>>> registry.register_global_options(config, addrspace.BaseAddressSpace)
>>> config.parse_options()
>>> config.PROFILE="WinXPSP2x86"
>>> config.LOCATION = "file:///media/memory/private/image.dmp"
>>> import volatility.plugins.taskmods as taskmods
>>> p = taskmods.PSList(config)
>>> for process in p.calculate():
...   print process
Output:
Traceback (most recent call last):
  File "C:\Users\ALi pc\workspace\RunningProcesses\main.py", line 20, in <module>
    for process in p.calculate():
  File "C:\Python27\lib\site-packages\volatility\cache.py", line 592, in wrapper
    return f(s, *args, **kwargs)
  File "C:\Python27\lib\site-packages\volatility\plugins\taskmods.py", line 127, in calculate
    addr_space = utils.load_as(self._config)
  File "C:\Python27\lib\site-packages\volatility\utils.py", line 65, in load_as
    raise error
volatility.exceptions.AddrSpaceError: No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VMWareAddressSpace: No base Address Space
 QemuCoreDumpElf: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 FileAddressSpace: Location is not of file scheme
 ArmAddressSpace: No base Address Space

But in command prompt i am successfully executing command "python vol.py -f be2.vmem --profile=WinXPSP2x86 pslist"
![capture](https://cloud.githubusercontent.com/assets/12435041/7620212/c0742d0e-f9d7-11e4-9bdb-4b1d9bfb789f.PNG)

**Comment by iMHLv2** [comment]
Your config.LOCATION is set to our example in the wiki (config.LOCATION = "file:///media/memory/private/image.dmp") rather than the actual path to be2.vmem on your own machine.
