### ISSUE TITLE
Cant run volatility command Pslist from Eclipse(python IDE)

### ISSUE THREAD

**Issue by AeeyAhmed** [volatilityfoundation/volatility#211]
I am using this code to print Pslist:
 python
>>> import volatility.conf as conf
>>> import volatility.registry as registry
>>> registry.PluginImporter()
<volatility.registry.PluginImporter object at 0x7f9608f3ac10>
>>> config = conf.ConfObject()
>>> import volatility.commands as commands
>>> import volatility.addrspace as addrspace
>>> registry.register_global_options(config, commands.Command)
>>> registry.register_global_options(config, addrspace.BaseAddressSpace)
>>> config.parse_options()
>>> config.PROFILE="WinXPSP2x86"
>>> config.LOCATION = "be2.vmem"
>>> import volatility.plugins.taskmods as taskmods
>>> p = taskmods.PSList(config)
>>> for process in p.calculate():
...   print process
Output:
Traceback (most recent call last):
  File "C:\Users\ALi pc\workspace\RunningProcesses\main.py", line 20, in <module>
    for process in p.calculate():
  File "C:\Python27\lib\site-packages\volatility\cache.py", line 592, in wrapper
    return f(s, *args, **kwargs)
  File "C:\Python27\lib\site-packages\volatility\plugins\taskmods.py", line 127, in calculate
    addr_space = utils.load_as(self._config)
  File "C:\Python27\lib\site-packages\volatility\utils.py", line 65, in load_as
    raise error
volatility.exceptions.AddrSpaceError: No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VMWareAddressSpace: No base Address Space
 QemuCoreDumpElf: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 FileAddressSpace: Location is not of file scheme
 ArmAddressSpace: No base Address Space

I am using Volatility-2.4.Win32 installed in Python27 on 64bit Windows 8.1 

But in command prompt i am successfully executing command "python vol.py -f be2.vmem --profile=WinXPSP2x86 pslist"
![capture](https://cloud.githubusercontent.com/assets/12435041/7620212/c0742d0e-f9d7-11e4-9bdb-4b1d9bfb789f.PNG)

**Comment by iMHLv2** [comment]
config.LOCATION is set wrong...it needs the file:// prefix....i would need to check the proper syntax for windows, however....its something like file://C:/Users/You/Path/be2.vmem or file://C:\Users\You\Path\be2.vmem.

**Comment by AeeyAhmed** [comment]
Thanks a lot for your important time.
Now the code is running but i am unable to understand the output.
Output.
2164987488
4280987680
4280208800
4280207736
4280578080
4280635424
4280386096
2164230360
4280382816
2163996944
4280472920
4280302464
4280122784
4279995176
4280278152
4279515944
4280657888
4281746192
4281906680
2163608992
4281886160
4281755624
4281813376
2163819912
4280249760
2163322912
4282064248
4281860808
 How to i get the actual attributes of pslist?

**Comment by iMHLv2** [comment]
Look at the pslist plugin
(https://github.com/volatilityfoundation/volatility/blob/master/volatility/plugins/taskmods.py#L253)
and find out the names of the attributes you want to print.
