### ISSUE TITLE
Windows x64 raw2dmp problem

### ISSUE THREAD

**Issue by dragosb91** [volatilityfoundation/volatility#217]
Hello. I dumped over firewire the raw dump memory of a Windows 7 SP1 x64 that was running on a 4 GB RAM machine. Due to the limitations of firewire I got only 3.5 GB RAM. When using the raw2dmp to convert it to a crash dump format I got an error of "No suitable address space mapping found" and as a result I got a dmp file with the size of 3.5 GB. When I try to open the dmp file with windbg I get the error
Unable to read KLDR_DATA_TABLE_ENTRY at fffffa80`0361a890 - HRESULT 0x80004002. I did the same procedure on Windows 7 SP1 x86, running on the same 4GB RAM machine, and I managed to run windbg with no problems.on the resulting dmp file, even tough I got the "No suitable address space mapping found" error at the end of the conversion. 
So is there a problem with converting x64 windows versions ?
I ran volatility version 2.4 on a windows 8.1.

**Comment by iMHLv2** [comment]
my guess is that fffffa80`0361a890 translates to an offset in RAM not captured by firewire (i.e. outside of the 3.5 GB range)

few questions: 

1) does volatility work against your 3.5 gb raw dump? for example, can you list processes with pslist? 
2) if you acquire memory from your target x64 system with a software tool (in raw format) can you convert to a crash dump and analyze in windbg? 

In the past, we have not encountered issues converting x64 raw images to crash

**Comment by dragosb91** [comment]
Thank you for the reply. My guess was the same as yours but it seemed odd that for the 32 bit version it worked, both 32 and 64 bit versions running on only 4 GB RAM. I dumped multiple times the raw RAM and I always got the error message for the 64 bit windows.
1) volatility does not work against the x64 windows 7 raw dump for the process list command, I get the "No suitable address space mapping found". But for example imageinfo gives me valid suggested profiles.
2) I will try this tomorrow.

PS...do you have any resource indicating how address translation (from virtual to physical) is done by volatility. From what I understand I only need the contents of the CR3 register and then it is straightforward... but how do I find it ?

**Comment by iMHLv2** [comment]
The CR3 register on windows is located in _EPROCESS.Pcb.DirectoryTableBase (its the PDB column of pslist and psscan plugins) 

For windbg, you need to switch into x64 context. I forget the exact command, but you can google around for it.

**Comment by iMHLv2** [comment]
Feel free to reopen if you still are having issues with this.

**Comment by lzbaer** [comment]
I realize this is an old thread, but I'm getting the same error when trying to examine a win7sp0 snapshot with windbg x64. After using raw2dmp to get the .dmp file and loading it into windbg, the error message is as follows:
"
Loading unloaded module list
.....Unable to enumerate user-mode unloaded modules. NTSTATUS 0xC0000147
Loading Wow64 Symbols
...........................................................
Unknown exception - code 45474150 (first/second chance not available)
The context is partially valid. Only x86 user-mode context is available.
"
Was there ever a resolution?

**Comment by sculida** [comment]
> The CR3 register on windows is located in _EPROCESS.Pcb.DirectoryTableBase (its the PDB column of pslist and psscan plugins)
> 
> For windbg, you need to switch into x64 context. I forget the exact command, but you can google around for it.

Thank you For your suggestion. Calling

> !wow64exts.sw

in windbg can resolute the problem.
