### ISSUE TITLE
linux_dentry_cache timestamps

### ISSUE THREAD

**Issue by ngkogkos** [volatilityfoundation/volatility#220]
Hello everyone.

I was playing with linux_dentry_cache on an Android dump. It seems that the output is not correct (I am not sure however). So today I tried creating a simple file called testmacs (via an adb shell to the Android emulator), and then reading it. Here is the output:

`0|testmacs|45|0|1023|1023|9|3628277948|3628277956|0|3628277964`
`0|testmacs|3093315872|0|0|1028|9|3594678380|3594678388|0|3594678396`

Assuming the timestamps are in Unix Epoch format, they are way bigger. Then I tried providing --tz='Europe/Athens' to the plugin and the output remains the same, which makes sense since that plugin outputs timestamps and not datetime info.

Any ideas? Should I upload my android dump somewhere ?

Thanks a bunch!

**Comment by gleeda** [comment]
Please look at this @atcuno

--
Jamie Levy (@gleeda)

**Comment by em0vskangoura** [comment]
Hello, 

did any of you check this?
