### ISSUE TITLE
Some files include wrong address to FSF in the license text

### ISSUE THREAD

**Issue by xambroz** [volatilityfoundation/volatility#229]
Hello,
during build for Fedora I have noticed that some files do contain old address to FSF in the license text.
This could possibly have some impact to validity of the license.
Please could you fix?

Old address: 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
New address: 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
See: https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html

Files affected:
volatility/plugins/linux/info_regs.py
volatility/plugins/addrspaces/vmem.py
volatility/plugins/linux/process_info.py
volatility/plugins/overlays/mac/macho.py
volatility/plugins/linux/linux_strings.py
volatility/plugins/mac/mac_strings.py
volatility/plugins/linux/threads.py
volatility/plugins/overlays/linux/elf.py
volatility/plugins/registry/auditpol.py
volatility/tools/linux/kcore/elf.h
volatility/plugins/bigpagepools.py
volatility/plugins/linux/process_stack.py
volatility/plugins/mac/apihooks_kernel.py
volatility/plugins/heaps.py
volatility/plugins/linux/library_list.py
volatility/plugins/pooltracker.py

Thank you 
Michal Ambroz

**Comment by gleeda** [comment]
fixed in cde51b9f9497e903d5cbd73df4558e63bb10df68 thanks for reporting!
