### ISSUE TITLE
No error checking for a valid render_text function

### ISSUE THREAD

**Issue by wroersma** [volatilityfoundation/volatility#235]
So if you do the unfied_output format and you don't have the render_text function it doesn't use any of your code and doesn't give an error letting the developer know they need it. It shouldn't simply carry on and run some random code basically.

**Comment by iMHLv2** [comment]
Gonna mark this "won't fix" for now, but if you have a use case that I'm not understanding, feel free to reopen. The render_text method isn't required per plugin. There's one in the base class from which all plugins inherit. Thus, if you don't add your own render_text, then the default one gets used. Its not running random code in this case, its doing what it should do if you don't override it and tell it to do something else.
