### ISSUE TITLE
You must not use 8-bit bytestrings unless you use a text_factory

### ISSUE THREAD

**Issue by JamesHabben** [volatilityfoundation/volatility#237]
I am getting this error running LDRModules against an image using SQLite output.

ldrmodules: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.

![vol-ldrmodules-error](https://cloud.githubusercontent.com/assets/6327329/9074611/18b514c8-3ac0-11e5-8dd6-bf4a2b4bf40a.png)

**Comment by JamesHabben** [comment]
Found that it is also coming from the DLLList module output with an odd character. 
output from ldrmodules stdout:
    5956 iexplore.exe         0x0000000074120000 False  False  False ᖸ￿ᖸ￿Ԁ

Output from stdout from a different process with a similar problem:
0x000007fefa140000            0x35000                0x1 ¢:\WINDOWS\system32\tscfgwmi.dll

**Comment by gleeda** [comment]
Would you like to submit a pull request? :-)

**Comment by HomeSen** [comment]
A tad bit late, but here it is ;)

**Comment by JamesHabben** [comment]
I did some testing with this and the change by @HomeSen seems to do the trick. Did a PR get submitted?

**Comment by HomeSen** [comment]
@JamesHabben: Yes, I submitted a pull-request, here: https://github.com/volatilityfoundation/volatility/pull/445
On my local copy I already had the change lingering around for quite a while. I just didn't have the time to submit it, back then ;)
