### ISSUE TITLE
Volatility-2.3.1 on CentOS 6.6 

### ISSUE THREAD

**Issue by joywsx** [volatilityfoundation/volatility#238]
Hi there, 

I've met some errors that I couldn't solve and would hope someone would be able to help me with it. I'm currently doing a project with regards to introspection of one of the PV guests VM from the host VM. 

Both host and PV guest VM versions are CentOS 6.6. On the host, I installed Xen, LibVMI, dwarfdump, Volatility-2.3.1 and copied the pyvmiaddressspace.py of libvmi to Volatility. The host VM kernel is System.map-3.18.12-11.el6.x86_64

Am i right to download volatility on the host VM? I've did that and I created a CentOS.zip file with the module.dwarf and for the boot system, I get the PV guest kernel information(System.map-2.6.32-504.30.3.el6.x86_64) from /boot/System* of the host VM. 

To get the PV guest image dump, I downloaded LiME on PV guest to acquire the .lime memory dump and then scp it over to the host VM's root directory.

Back at the host VM, i then use the volatility command indicating the profile, .lime and the plugins such as (linux_pslist). 

But the result is: No suitable address space mapping found with many address spacing errors.

Did i miss out any step?

Thank you! :)

**Comment by gleeda** [comment]
Could you please try to install the latest code from here on github and see if that fixes your issue ?

**Comment by atcuno** [comment]
Hello,

Analysis from PV guests is currently not supported. This is something we have to fix by the end of November. Please let us know if analysis is still broken after these patches go in.
