### ISSUE TITLE
Improper parsing of the plugins directory

### ISSUE THREAD

**Issue by deeso** [volatilityfoundation/volatility#241]
The system is Ubuntu Linux x64. My plugins directory is also a Git repository, so when Volatility reads the plugins directory, I get the following error:

```
/research_data/vol_profiles$ vol.py --info
Volatility Foundation Volatility Framework 2.4
*** Failed to import volatility.plugins.overlays.linux.linux (IOError: [Errno 22] Invalid argument)
<snip/>
```
The directory structure looks like:
```
/research_data/vol_profiles$ ls -1
.git/
Ubuntu14.04.02-LTS.zip
Ubuntu1404x64.zip
Ubuntu1404.zip
Ubuntu1504.zip
```

The ```.volatilityrc``` looks like:
```
$ cat ~/.volatilityrc 
[DEFAULT]
plugins=/research_data/vol_profiles/
```

**Comment by iMHLv2** [comment]
Hmm, there shouldn't be any issue if your plugins or profiles directory is also a git repository. Where is your vol_profiles git repository in relationship to vol.py (and the rest of the volatility installation)? Above it looks like you ran vol.py from the vol_profiles directory, indicating the two git repos have been merged into one, but I can't exactly tell (vol.py may be an alias you've set up in the environment). 

In any case, you should be perfectly fine if you:

1) checkout volatility to /path/volatility
2) checkout your plugins to /path/vol_profiles 
3) set /path/vol_profiles in your .volatilityrc file 

Reopen if that doesn't work!
