### ISSUE TITLE
Volatility 2.4- mac_tasks hangs (Therefore multiple other commands too)

### ISSUE THREAD

**Issue by Stubatiger** [volatilityfoundation/volatility#242]
Hey all,

Im using Volatility 2.4 on a Mac with 16GB Ram and Yosemite 10.10.5 and Python 2.7.10

I captured the Ram via osxpmem in elf format (osxpmem -o test.elf --elf)

When i try to use the commands mac_netstat, mac_pstree and mac_psaux they all do not return i.e. hang. 
netstat is showing me some output and then just "stops". The same with psaux. Mac_pstree is only showing the header and then hangs. With the mac_pstree command, if i try to quit via Command+C than sometimes it continues, showing me the correct output and exiting properly.

I have digged myself a little bit through the code, and from what i have gathered i assume that in pstasks.py is the bug.
In 

        for task in queue_entry.walk_list(list_head = tasksaddr):
            if (task.bsd_info and task.obj_offset not in seen):
                proc = task.bsd_info.dereference_as("proc") 
                yield proc

            seen.append(task.obj_offset)

the loop does not exit. I am not sure why though.
I have tried this with multiple images i created. For one image the mac_pslist command warned me before a recursive process list, but in another image there was no warning, still the other commands (netstat, psaux, pstree)  did not exit properly.  

Did anyone experience something similar and can help me with this?

Edit: Don't know if this is of any help, but sometimes if i just use mac_tasks and quit via Command+C i get the following error message:

       ^CTraceback (most recent call last):
         File "vol.py", line 192, in <module>
           main()
         File "vol.py", line 183, in main
           command.execute()
         File "/Users/vtc/Downloads/volatility-2.4/volatility/plugins/mac/common.py", line 46, in execute
           commands.Command.execute(self, *args, **kwargs)
         File "/Users/vtc/Downloads/volatility-2.4/volatility/commands.py", line 127, in execute
           func(outfd, data)
         File "/Users/vtc/Downloads/volatility-2.4/volatility/plugins/mac/pslist.py", line 78, in render_text
           for proc in data:
         File "/Users/vtc/Downloads/volatility-2.4/volatility/plugins/mac/pstasks.py", line 60, in calculate
           for proc in self.allprocs():
         File "/Users/vtc/Downloads/volatility-2.4/volatility/plugins/mac/pstasks.py", line 43, in allprocs
           for task in queue_entry.walk_list(list_head = tasksaddr):
         File "/Users/vtc/Downloads/volatility-2.4/volatility/plugins/overlays/mac/mac.py", line 588, in walk_list
           n = n.tasks.next.dereference_as("task")
       AttributeError: 'function' object has no attribute 'dereference_as'

**Comment by 0sx** [comment]
Hi,

I'm using volatility 2.4 on 10.10.5 with Python 2.7.10 as well.  Are you using osxpmem to capture the RAM of that same machine or a different one?  If it's a different machine which version of the OS is it running?  I am able to successfully run those commands but am doing so on VMWare Fusion snapshots.

**Comment by Stubatiger** [comment]
Im capturing and trying to analyze the RAM on the same Machine. If you can succesfully run the commands on VMWare Fusion snapshots, than it seems the commands itself are okay. Sadly osxpmem only allow capturing the Ram in ELF or AFF4 format.

**Comment by Stubatiger** [comment]
I just tested my problem with a new image i made, and now all is working fine. Sadly i don't have the old images anymore, I'm still not sure what went actually wrong the last time. 
Thanks for the help, and sorry for bothering anyone, probably should have waited some days before creating an issue here :)

**Comment by atcuno** [comment]
Thanks for the report and follow up. I will close this issue, but look into the WARNING messages that you triggered. It is likely a missing call to is_valid() before using the member. Should be a simple fix.
