### ISSUE TITLE
Windows commands should have prefix "windows_"

### ISSUE THREAD

**Issue by vi** [volatilityfoundation/volatility#253]
like with mac and linux.

That may allow commands not tied to any particular OSes to stand out.

**Comment by iMHLv2** [comment]
Hi Vitaly...I can tell you off the top of my head that there's only a small number of plugins that work for all OS - and that's imagecopy (for converting from one format to another) and some of the file format meta data plugins like vmwareinfo. 

What exactly are you trying to achieve? If you run vol.py --info you'll see all plugins (mac, linux, and windows) but if you run vol.py --profile=PROFILE -h then you'll only see plugins for whatever profile you specify. A lot of documentation and automation/scripting is based on the names of plugins that we've had for many years, so changing them on everyone now isn't a good idea for user friendliness.
