### ISSUE TITLE
Running multiple plugins at once

### ISSUE THREAD

**Issue by noxdafox** [volatilityfoundation/volatility#254]
Greetings,

I'd like to run multiple plugins at once as in the example.

volatility mutantscan psscan -p Win7SP1x64 -f memdump.bin

I saw a multiscan command but it's not documented and I don't think it suits my use case.

Is there a way to achieve so?

**Comment by JamesHabben** [comment]
It isn't supported right now and I don't know if there are plans to support this natively, but there are several other projects that have built multi-threading/processing into running these plugins. I built a web GUI that runs the volatility commands in the background with multi-processing to take full advantage of the CPU.

**Comment by noxdafox** [comment]
Guessed so, i built my own wrapper for that.
