### ISSUE TITLE
Additional Columns in SQLite Ouput

### ISSUE THREAD

**Issue by JamesHabben** [volatilityfoundation/volatility#255]
Unified output is great! Let me say that first.

I would like to see the ability to add user specified columns into the table schema for a plugin's output. Currently, those columns are hardcoded by the plugin dev. The added column would have a label, and then all of the rows in that batch would hold the same value for that column.

For example, I would like to be able to add the memfile name into a column. This would allow for multiple runs with the same plugin against different memory dumps. In the current state, there would be no way to distinguish the data from one dump or another.

Maybe something like this:
vol.py -f memdump.dd --profile=WinXPSP2x86 --output=SQLite --addcolumns=system:abc123

**Comment by gleeda** [comment]
Could you mock up a patch for this, please?

**Comment by JamesHabben** [comment]
Do I have to fork this project to submit a patch?

Here is a screenshot of evolve. I would like to add a column to store the profile that was used to run the module since I am now allowing the user to dynamically switch to a different profile using the same dump.

![vol-profile-column](https://cloud.githubusercontent.com/assets/6327329/11055000/2161f222-8727-11e5-9854-11531fb7e366.PNG)
![vol-sqlite-changes](https://cloud.githubusercontent.com/assets/6327329/11055007/3b7aa758-8727-11e5-961e-8313f68db619.PNG)

The SQLite render code was inserting values, but wasn't specifying the column names for those values. This caused an error when I tried to modify the schema behind volatility since the columns weren't getting updated when outputting the row data. It works fine on the first run, but having volatility add data to an already existing table causes the error. This code will fix that by specifying which columns to insert the values into.

I can submit the code, but I just don't know the right way to do it. Seems like too much to fork just to change a couple lines like this.

**Comment by JamesHabben** [comment]
I would like to be able to insert an additional column to identify the dump name. This would allow for analyzing and comparing multiple dump files at once.

![evolve-profile-system-columns](https://cloud.githubusercontent.com/assets/6327329/11055229/b2e27c4c-8729-11e5-99f4-5972c03bd959.PNG)

**Comment by atcuno** [comment]
Hey,

You don't have to fork, just do a pull request and then we can bring it
directly into volatility and you will get credit for the patch.


https://help.github.com/articles/using-pull-requests/

Otherwise if you just send a plain patch it doesn't get the nice github
trackign features and whichever one of us applied the patch would get
the commit line and not you =)

Thanks,
Andrew (@attrc)

**Comment by JamesHabben** [comment]
From what I read on that link, it looks like I do have to fork. Then I can edit and submit a pull.

**Comment by gleeda** [comment]
you can copy and paste the patch here if you don't want to fork and submit a pull request

**Comment by JamesHabben** [comment]
Here is a small change to allow for inserts to proceed even if there are extra columns in the table.

https://github.com/volatilityfoundation/volatility/pull/262
