### ISSUE TITLE
servicediff: services_from_memory_list() signature not found Win 7 x86 

### ISSUE THREAD

**Issue by gleeda** [volatilityfoundation/volatility#259]
After adding in debug statements (2f5644467558122e9797c0226a235320c8ece19f and afa14273e28479d6fd0da3430050aa32855b9f7e) it turns out the signature isn't found.  

Not sure if this plugin was supposed to work on all versions of Win 7 x86, but the signature isn't found on some of my samples.

**Comment by iMHLv2** [comment]
Its either swapped or the signature changed...however in the later case, PlugX would fail to find the list too. Send me a `procdump`ed services.exe and I can check on it.

**Comment by gleeda** [comment]
ahh ok that makes sense.  i'll close this then.
