### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by eribertomota** [volatilityfoundation/volatility#261]
Hi,

The README.txt file says that Volatility is GPL-2+. However, several files have GPL-2 only in its headers. Considering that I think that currently all files are GPL-2+ (Am I wrong?), can you update the headers? This action will make the Debian packaging a bit more easy.

Regards,

Eriberto

**Comment by eribertomota** [comment]
Complementing...

$ egrep 'public license version 2' -sri *

volatility/plugins/linux/kernel_opened_files.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/ld_env.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/hidden_modules.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/netfilter.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/route_cache.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/check_modules.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/find_file.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/malfind.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/procdump.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/check_fops.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/librarydump.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/common.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/lsmod.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/bash_hash.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/process_hollow.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/psxview.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/proc_maps_rb.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/lime.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/check_inline_kernel.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/keyboard_notifiers.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/ldrmodules.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/list_raw.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/psenv.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/check_syscall.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/libc_env.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/recover_filesystem.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/linux/iomem.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/dumpfiles.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/overlays/linux/linux.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/overlays/windows/win8.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/overlays/windows/win8_kdbg.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/overlays/windows/win10.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/overlays/windows/pe_vtypes.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/overlays/windows/ssdt_vtypes.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/overlays/windows/hibernate_vtypes.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/overlays/windows/crash_vtypes.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/overlays/windows/vad_vtypes.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/drivermodule.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/addrspaces/crashbmp.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/tcaudit.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/mac/dump_map.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/mac/compressed_swap.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/mac/malfind.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/mac/bash_hash.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/mac/ldrmodules.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/mac/list_raw.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/mac/threads.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/mac/bash_env.py:# it under the terms of the GNU General Public License Version 2 as
volatility/plugins/mac/recover_filesystem.py:# it under the terms of the GNU General Public License Version 2 as
volatility/poolscan.py:# it under the terms of the GNU General Public License Version 2 as

**Comment by gleeda** [comment]
i think this will be fixed in future versions, starting with 3.0
