### ISSUE TITLE
Registry issue on Windows 10

### ISSUE THREAD

**Issue by JohnEbert** [volatilityfoundation/volatility#263]
When analyzing a memory dump collected by ramcapture64.exe and volatility2.5.standalone on a Windows 10 Pro x64 machine, and the dump being analyzed is from the machine doing the analysis, is it possible that the "userassist" analysis mistakenly tries to access the live machine instead of the memory image for userassist here? I'm confused about the cause for the error 32.

volatility-2.5.standalone.exe --profile=Win10x64 --filename=..\ir_output\Audits\%computername%\ramcapdump.mem userassist --output=xlsx --output-file=..\ir_output\Audits\%computername%\ramcapuserassist.xlsx

Volatility Foundation Volatility Framework 2.5
ERROR   : volatility.debug    : The requested key could not be found in the hive(s) searched
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\Jake\Documents\GitHub\volatility\build\pyinstaller\out00-PYZ.pyz\atexit", line 24, in _run_exitfuncs
  File "C:\Users\Jake\Documents\GitHub\volatility\build\pyinstaller\out00-PYZ.pyz\openpyxl.writer.write_only", line 39, in _openpyxl_shutdown
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\users\user1\appdata\local\temp\openpyxl.o4aipg'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "C:\Users\Jake\Documents\GitHub\volatility\build\pyinstaller\out00-PYZ.pyz\atexit", line 24, in _run_exitfuncs
  File "C:\Users\Jake\Documents\GitHub\volatility\build\pyinstaller\out00-PYZ.pyz\openpyxl.writer.write_only", line 39, in _openpyxl_shutdown
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\users\user1\appdata\local\temp\openpyxl.o4aipg'

**Comment by JohnEbert** [comment]
A new look at this today produced similar results without the error. I may have been running the first session as standard user instead of Administrator. I am however still searching as to why there are no results and exploring whether or not I have userassist disabled, possibly accounting for the missing information.

volatility-2.5.standalone.exe --profile=Win10x64 --filename=..\ir_output\Audits\%computername%\ramcapdump.mem userassist

Volatility Foundation Volatility Framework 2.5
The requested key could not be found in the hive(s) searched

**Comment by gleeda** [comment]
You wrote a previous issue that hivescan didn't work on your Windows 10 sample, therefore this issue is related to that.  It makes sense, because if you can't find the registry hives then you also unable to query the keys within it (and userassist are just registry keys).

Probably what has happened is that the structures for the registry have changed since the Windows 10 vtypes were created.  Could you please dump out the ntoskrnl.exe from the modules (or get it from disk) and send it to us to confirm? 



--
Jamie Levy (@gleeda)

**Comment by JohnEbert** [comment]
Userassitview by nirsoft.net reports 227 items present. There are 9 keys reported in reg key HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\UserAssist

**Comment by JohnEbert** [comment]
Can you reword the meaning of "dump out"  ntoskrnl.exe from the modules; I'm sure it is clear but I am slightly unsure of your request

**Comment by iMHLv2** [comment]
Hey John....I think "dump out" referred to using moddump to extract the ntoskrnl.exe file from memory. However, if you have access to the file system, then copying it off is just as good. You can send it via email to me at michael @ memoryanalysis [dot] net or you can post it on dropbox or another file sharing site and post a link here. Thanks!

**Comment by JohnEbert** [comment]
OK. Got ntoskrnl.exe using moddump. It is posted as the moddump file "driver.fffff801d4876000.sys" at 
https://mega.nz/#!5Mh3UJZS!zXguzeKZ-efMsgHvNnOos8GSdeHQ-1HBkWFc-ZVw-uI

volatility-2.5.standalone.exe --profile=Win10x64 --filename=..\ir_output\Audits\%computername%\ramcapdump.mem --kdbg=0xf801d4a656d8 --base=0xfffff801d4876000 moddump --dump-dir=..\ir_output\Audits\%computername%\
Volatility Foundation Volatility Framework 2.5
Module Base        Module Name          Result
------------------ -------------------- ------
0xfffff801d4876000 ntoskrnl.exe         OK: driver.fffff801d4876000.sys

**Comment by gleeda** [comment]
I think this was probably fixed when we added more support for Windows 10.  I'm going to close this for now, but feel free to open it if you have another issue.
