### ISSUE TITLE
Volatility-2.5.standalone --profile=Win10x64 "hivelist" returns no information.

### ISSUE THREAD

**Issue by JohnEbert** [volatilityfoundation/volatility#264]
Using volatility-2.5.standalone analyzing a Win10x64 ramcapture64 image, hivelist comes back empty?

E:\1_mini_tigerkit\1_volatility>volatility-2.5.standalone.exe --profile=Win10x64 --filename=..\ir_output\Audits\%computername%\ramcapdump.mem hivelist
Volatility Foundation Volatility Framework 2.5
Virtual            Physical           Name
------------------ ------------------ ----

E:\1_mini_tigerkit\1_volatility>

**Comment by pchouseboy** [comment]
I only get the column headings: Virtual, Physical and Name with underline:

Virtual          Physical          Name
-------------------------------------
