### ISSUE TITLE
whether volatility can provide dynamic information of a process?

### ISSUE THREAD

**Issue by rainkin1993** [volatilityfoundation/volatility#269]
Hi Volatility is an amazing memory forensic tool. 
But I met some problems: I want to find whether we can get some dynamic info through volatility.
For example, there is a process called suspicious.exe, we want to find the following info related to the suspicious.exe:

+ Files Created by suspicious.exe
+ Files Changed by suspicious.exe
+ Files Deleted by suspicious.exe
+ Processes created by suspicious.exe
...

I noticed that there are some plugins can be used to list the file/dll related to the certain process, but what we want is the event(read,write,fork) related to the process.

So I want to know whether volatility can do it or not ?

Thx

**Comment by iMHLv2** [comment]
Volatility is not a debugger or a dynamic analysis tool, so its probably not going to provide the type of granularity you are looking for. It can tell you which processes were created by suspicious.exe based on parent/child relationships, and it can provide evidence such as suspicious.exe was running as user XYZ who was the only person logged on at the time when file ABC was deleted. Hope this helps...feel free to post future questions on vol-users (http://lists.volatilesystems.com/mailman/listinfo/vol-users).
