### ISSUE TITLE
hidden_modules broken by 49f99f627c9c5a6187f63dbff156299db1dbb90e

### ISSUE THREAD

**Issue by dl9rdz** [volatilityfoundation/volatility#273]
The hidden_modules module in pre-49f99f6 works fine. The new version ("greatly improve performance of hidden_module") is almost completely broken.

The new version replaces (on 64-architecture) sequences of N>=9  0-bytes with N-8 0xff bytes and 8 0x00 bytes, before checking for valid module states signatures (int value of 0/1/2).  If the byte after the (8-byte-aligned) module state is 0, this replacement results in the module state (0x00000000) being replaced by (0x000000ff), causing the module not to be found.

A very simple approach for hiding a module is just using the kernel function 
list_del(&THIS_MODULE->list);
This removes a module from the module double linked lists and sets the module's "next" pointer (which is the value after the module state) to LIST_POISON1,which is "0xdead000000100100L" with LSB 0x00.  As a result, the hidden_modules plugin fails to detect even the simplest module that hides itself using this one-liner...

**Comment by atcuno** [comment]
Hey,

Thanks for the report. I have updated this to not sub out smaller strings of 0s. Please let me know if this fix makes your module(s) appear again:

https://github.com/volatilityfoundation/volatility/commit/2ff525da7de115cc9e4f04156ef1acfcc6fa62cf

**Comment by atcuno** [comment]
I am going to close this for now since there has been no response in a long time. Please file a new issue if you still experience this behavior.
