### ISSUE TITLE
linux_bash_env:  struct.error: unpack requires a string argument of length 8

### ISSUE THREAD

**Issue by fpusersuggest** [volatilityfoundation/volatility#276]
Hi,
I have found many bugs with volatility and Centos 7.1.
OS version: **Linux Centos 7.1**
Kernel: **Linux forensics 3.10.0-327.3.1.el7.x86_64** #1 SMP Wed Dec 9 14:09:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Volatility version: 2.5 downloaded from github 27 december 2015 
Plugin affected: **linux_bash_env**

Short error:

    [root@forensics volatility]# ./vol.py   -f /root/4ensix.lime --profile=Linuxcentos7_1x64 linux_bash_env
    Volatility Foundation Volatility Framework 2.5
    Pid      Name                 Vars
    -------- -------------------- ----
           1 systemd
           2 kthreadd
           3 ksoftirqd/0
           5 kworker/0:0H
           6 kworker/u4:0
           7 migration/0
           8 rcu_bh
           9 rcuob/0
          10 rcuob/1
          11 rcu_sched
          12 rcuos/0
          13 rcuos/1
          14 watchdog/0
          15 watchdog/1
          16 migration/1
          17 ksoftirqd/1
          19 kworker/1:0H
          20 khelper
          21 kdevtmpfs
          22 netns
          23 perf
          24 writeback
          25 kintegrityd
          26 bioset
          27 kblockd
          28 md
          29 kworker/0:1
          30 kworker/1:1
          34 khungtaskd
          35 kswapd0
          36 ksmd
          37 khugepaged
          38 fsnotify_mark
          39 crypto
          47 kthrotld
          48 kworker/u4:1
          49 kmpath_rdacd
          50 kpsmoused
          51 ipv6_addrconf
          70 deferwq
          71 kworker/0:2
         109 kauditd
         229 ata_sff
         232 scsi_eh_0
         233 scsi_tmf_0
         234 scsi_eh_1
         235 scsi_tmf_1
         239 events_power_ef
         243 ttm_swap
         263 kworker/1:2
         275 jbd2/vda1-8
         276 ext4-rsv-conver
         277 ext4-unrsv-conv
         350 systemd-journal
         369 systemd-udevd
         384 auditd
         422 dbus-daemon
         429 avahi-daemon
         433 irqbalance
         435 NetworkManager
         436 systemd-logind
         438 rsyslogd
         441 avahi-daemon
         444 vballoon
         469 wpa_supplicant
         470 polkitd
         474 crond
         513 agetty              �=�
         532 kvm-irqfd-clean
         729 tuned
        1071 master              �=#�
        1087 pickup
        1088 qmgr
        6753 sshd
    Traceback (most recent call last):
      File "./vol.py", line 192, in <module>
        main()
      File "./vol.py", line 183, in main
        command.execute()
      File "/root/volatility/volatility/plugins/linux/common.py", line 63, in execute
        commands.Command.execute(self, *args, **kwargs)
      File "/root/volatility/volatility/commands.py", line 145, in execute
        func(outfd, data)
      File "/root/volatility/volatility/plugins/linux/libc_env.py", line 47, in render_text
        for (key, val) in task.bash_environment():
      File "/root/volatility/volatility/plugins/overlays/linux/linux.py", line 1654, in bash_environment
        for key, val in self._shell_variables(proc_as, pack_format, addr_sz):
      File "/root/volatility/volatility/plugins/overlays/linux/linux.py", line 1614, in _shell_variables
        ptr = struct.unpack(pack_format, ptr_test)[0]
    struct.error: unpack requires a string argument of length 8

Error with debug:

    Volatility Foundation Volatility Framework 2.5
    DEBUG   : volatility.debug    : centos7.1: Found dwarf file boot/System.map-3.10.0-327.3.1.el7.x86_64 with 760 symbols
    DEBUG   : volatility.debug    : centos7.1: Found system file boot/System.map-3.10.0-327.3.1.el7.x86_64 with 1 symbols
    DEBUG   : volatility.debug    : Applying modification from BashHashTypes
    DEBUG   : volatility.debug    : Applying modification from BashTypes
    DEBUG   : volatility.debug    : Applying modification from BasicObjectClasses
    DEBUG   : volatility.debug    : Applying modification from ELF32Modification
    DEBUG   : volatility.debug    : Applying modification from ELF64Modification
    DEBUG   : volatility.debug    : Applying modification from ELFModification
    DEBUG   : volatility.debug    : Applying modification from EditBoxObjectClasses
    DEBUG   : volatility.debug    : Applying modification from HPAKVTypes
    DEBUG   : volatility.debug    : Applying modification from LimeTypes
    DEBUG   : volatility.debug    : Applying modification from LinuxIDTTypes
    DEBUG   : volatility.debug    : Applying modification from LinuxTruecryptModification
    DEBUG   : volatility.debug    : Applying modification from MachoModification
    DEBUG   : volatility.debug    : Applying modification from MachoTypes
    DEBUG   : volatility.debug    : Applying modification from MbrObjectTypes
    DEBUG   : volatility.debug    : Applying modification from VMwareVTypesModification
    DEBUG   : volatility.debug    : Applying modification from VirtualBoxModification
    DEBUG   : volatility.debug    : Applying modification from LinuxGate64Overlay
    DEBUG   : volatility.debug    : Applying modification from LinuxIntelOverlay
    DEBUG   : volatility.debug    : Applying modification from LinuxKmemCacheOverlay
    DEBUG   : volatility.debug    : Requested symbol cache_chain not found in module kernel

    DEBUG   : volatility.debug    : Applying modification from LinuxMountOverlay
    DEBUG   : volatility.debug    : Applying modification from LinuxObjectClasses
    DEBUG   : volatility.debug    : Applying modification from LinuxOverlay
    DEBUG   : volatility.debug    : centos7.1: Found dwarf file boot/System.map-3.10.0-327.3.1.el7.x86_64 with 760 symbols
    DEBUG   : volatility.debug    : centos7.1: Found system file boot/System.map-3.10.0-327.3.1.el7.x86_64 with 1 symbols
    DEBUG   : volatility.debug    : Applying modification from BashHashTypes
    DEBUG   : volatility.debug    : Applying modification from BashTypes
    DEBUG   : volatility.debug    : Applying modification from BasicObjectClasses
    DEBUG   : volatility.debug    : Applying modification from ELF32Modification
    DEBUG   : volatility.debug    : Applying modification from ELF64Modification
    DEBUG   : volatility.debug    : Applying modification from ELFModification
    DEBUG   : volatility.debug    : Applying modification from EditBoxObjectClasses
    DEBUG   : volatility.debug    : Applying modification from HPAKVTypes
    DEBUG   : volatility.debug    : Applying modification from LimeTypes
    DEBUG   : volatility.debug    : Applying modification from LinuxIDTTypes
    DEBUG   : volatility.debug    : Applying modification from LinuxTruecryptModification
    DEBUG   : volatility.debug    : Applying modification from MachoModification
    DEBUG   : volatility.debug    : Applying modification from MachoTypes
    DEBUG   : volatility.debug    : Applying modification from MbrObjectTypes
    DEBUG   : volatility.debug    : Applying modification from VMwareVTypesModification
    DEBUG   : volatility.debug    : Applying modification from VirtualBoxModification
    DEBUG   : volatility.debug    : Applying modification from LinuxGate64Overlay
    DEBUG   : volatility.debug    : Applying modification from LinuxIntelOverlay
    DEBUG   : volatility.debug    : Applying modification from LinuxKmemCacheOverlay
    DEBUG   : volatility.debug    : Requested symbol cache_chain not found in module kernel

    DEBUG   : volatility.debug    : Applying modification from LinuxMountOverlay
    DEBUG   : volatility.debug    : Applying modification from LinuxObjectClasses
    DEBUG   : volatility.debug    : Applying modification from LinuxOverlay
    DEBUG   : volatility.debug    : Voting round
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.macho.MachOAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.lime.LimeAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hibernate.WindowsHiberFileSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crashbmp.WindowsCrashDumpSpace64BitMap'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hpak.HPAKAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmem.VMWareMetaAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.VirtualBoxCoreDumpElf64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.QemuCoreDumpElf'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmware.VMWareAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.amd64.AMD64PagedMemory'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.intel.IA32PagedMemoryPae'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.intel.IA32PagedMemory'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.osxpmemelf.OSXPmemELF'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.standard.FileAddressSpace'>
    DEBUG   : volatility.debug    : Succeeded instantiating <volatility.plugins.addrspaces.standard.FileAddressSpace object at 0x737a250>
    DEBUG   : volatility.debug    : Voting round
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.macho.MachOAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.lime.LimeAddressSpace'>
    DEBUG   : volatility.debug    : Succeeded instantiating <volatility.plugins.addrspaces.lime.LimeAddressSpace object at 0x737a210>
    DEBUG   : volatility.debug    : Voting round
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.macho.MachOAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.lime.LimeAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hibernate.WindowsHiberFileSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crashbmp.WindowsCrashDumpSpace64BitMap'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hpak.HPAKAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmem.VMWareMetaAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.VirtualBoxCoreDumpElf64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.QemuCoreDumpElf'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmware.VMWareAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.amd64.AMD64PagedMemory'>
    DEBUG   : volatility.debug    : Succeeded instantiating <volatility.plugins.addrspaces.amd64.AMD64PagedMemory object at 0x737a5d0>
    DEBUG   : volatility.debug    : Voting round
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.macho.MachOAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.lime.LimeAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hibernate.WindowsHiberFileSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crashbmp.WindowsCrashDumpSpace64BitMap'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hpak.HPAKAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmem.VMWareMetaAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.VirtualBoxCoreDumpElf64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.QemuCoreDumpElf'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmware.VMWareAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.amd64.AMD64PagedMemory'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.intel.IA32PagedMemoryPae'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.intel.IA32PagedMemory'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.osxpmemelf.OSXPmemELF'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.standard.FileAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.arm.ArmAddressSpace'>
    DEBUG   : volatility.debug    : Voting round
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.macho.MachOAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.lime.LimeAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hibernate.WindowsHiberFileSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crashbmp.WindowsCrashDumpSpace64BitMap'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hpak.HPAKAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmem.VMWareMetaAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.VirtualBoxCoreDumpElf64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.QemuCoreDumpElf'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmware.VMWareAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.amd64.AMD64PagedMemory'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.intel.IA32PagedMemoryPae'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.intel.IA32PagedMemory'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.osxpmemelf.OSXPmemELF'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.standard.FileAddressSpace'>
    DEBUG   : volatility.debug    : Succeeded instantiating <volatility.plugins.addrspaces.standard.FileAddressSpace object at 0x737aad0>
    DEBUG   : volatility.debug    : Voting round
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.macho.MachOAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.lime.LimeAddressSpace'>
    DEBUG   : volatility.debug    : Succeeded instantiating <volatility.plugins.addrspaces.lime.LimeAddressSpace object at 0x737a910>
    DEBUG   : volatility.debug    : Voting round
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.macho.MachOAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.lime.LimeAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hibernate.WindowsHiberFileSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crashbmp.WindowsCrashDumpSpace64BitMap'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hpak.HPAKAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmem.VMWareMetaAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.VirtualBoxCoreDumpElf64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.QemuCoreDumpElf'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmware.VMWareAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.amd64.AMD64PagedMemory'>
    DEBUG   : volatility.debug    : Succeeded instantiating <volatility.plugins.addrspaces.amd64.AMD64PagedMemory object at 0x737aa90>
    DEBUG   : volatility.debug    : Voting round
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.macho.MachOAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.lime.LimeAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hibernate.WindowsHiberFileSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crashbmp.WindowsCrashDumpSpace64BitMap'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hpak.HPAKAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmem.VMWareMetaAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.VirtualBoxCoreDumpElf64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.QemuCoreDumpElf'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmware.VMWareAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.amd64.AMD64PagedMemory'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.intel.IA32PagedMemoryPae'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.intel.IA32PagedMemory'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.osxpmemelf.OSXPmemELF'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.standard.FileAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.arm.ArmAddressSpace'>
    Pid      Name                 Vars
    -------- -------------------- ----
           1 systemd
           2 kthreadd
           3 ksoftirqd/0
           5 kworker/0:0H
           6 kworker/u4:0
           7 migration/0
           8 rcu_bh
           9 rcuob/0
          10 rcuob/1
          11 rcu_sched
          12 rcuos/0
          13 rcuos/1
          14 watchdog/0
          15 watchdog/1
          16 migration/1
          17 ksoftirqd/1
          19 kworker/1:0H
          20 khelper
          21 kdevtmpfs
          22 netns
          23 perf
          24 writeback
          25 kintegrityd
          26 bioset
          27 kblockd
          28 md
          29 kworker/0:1
          30 kworker/1:1
          34 khungtaskd
          35 kswapd0
          36 ksmd
          37 khugepaged
          38 fsnotify_mark
          39 crypto
          47 kthrotld
          48 kworker/u4:1
          49 kmpath_rdacd
          50 kpsmoused
          51 ipv6_addrconf
          70 deferwq
          71 kworker/0:2
         109 kauditd
         229 ata_sff
         232 scsi_eh_0
         233 scsi_tmf_0
         234 scsi_eh_1
         235 scsi_tmf_1
         239 events_power_ef
         243 ttm_swap
         263 kworker/1:2
         275 jbd2/vda1-8
         276 ext4-rsv-conver
         277 ext4-unrsv-conv
         350 systemd-journal
         369 systemd-udevd
         384 auditd
         422 dbus-daemon
         429 avahi-daemon
         433 irqbalance
         435 NetworkManager
         436 systemd-logind
         438 rsyslogd
         441 avahi-daemon
         444 vballoon
         469 wpa_supplicant
         470 polkitd
         474 crond
         513 agetty              ^R<B3>=<F3>^?
         532 kvm-irqfd-clean
         729 tuned
        1071 master              <92>=#<F9>^?
        1087 pickup
        1088 qmgr
        6753 sshd
    > /root/volatility/volatility/plugins/overlays/linux/linux.py(1614)_shell_variables()
    -> ptr = struct.unpack(pack_format, ptr_test)[0]
    (Pdb) (Pdb) Traceback (most recent call last):
      File "./vol.py", line 195, in <module>
        debug.post_mortem()
      File "/root/volatility/volatility/debug.py", line 96, in post_mortem
        pdb.post_mortem()
      File "/usr/lib64/python2.7/pdb.py", line 1267, in post_mortem
        p.interaction(None, t)
      File "/usr/lib64/python2.7/pdb.py", line 210, in interaction
       self.cmdloop()
      File "/usr/lib64/python2.7/cmd.py", line 130, in cmdloop
        line = raw_input(self.prompt)
    KeyboardInterrupt

**Comment by atcuno** [comment]
Hey, sorry, I fixed this a while back but forgot to update the tracker:

https://github.com/volatilityfoundation/volatility/commit/f58808f96d3f43b937b8228857f3a02dd359b37c

Thank you for reporting the bug.
