### ISSUE TITLE
linux_check_afinfo: TypeError: unsupported operand type(s) for &: 'CType' and 'int'

### ISSUE THREAD

**Issue by fpusersuggest** [volatilityfoundation/volatility#277]
Hi,
I have found many bugs with volatility and Centos 7.1.
OS version: **Linux Centos 7.1**
Kernel: Linux forensics **3.10.0-327.3.1.el7.x86_64** #1 SMP Wed Dec 9 14:09:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Volatility version: 2.5 downloaded from github 27 december 2015 
Plugin affected: **linux_check_afinfo**

Short error:

    # ./vol.py    -f /root/4ensix.lime --profile=Linuxcentos7_1x64 linux_check_afinfo
    Volatility Foundation Volatility Framework 2.5
    Symbol Name                                Member                         Address       
    ------------------------------------------ ------------------------------ ------------------
    Traceback (most recent call last):
      File "./vol.py", line 192, in <module>
        main()
      File "./vol.py", line 183, in main
        command.execute()
      File "/root/volatility/volatility/plugins/linux/common.py", line 63, in execute
        commands.Command.execute(self, *args, **kwargs)
      File "/root/volatility/volatility/commands.py", line 145, in execute
        func(outfd, data)
      File "/root/volatility/volatility/plugins/linux/check_afinfo.py", line 86, in render_text
        for (what, member, address) in data:
      File "/root/volatility/volatility/plugins/linux/check_afinfo.py", line 77, in calculate
        for (name, member, address) in self.check_afinfo(global_var_name, global_var, op_members, seq_members, modules):
      File "/root/volatility/volatility/plugins/linux/check_afinfo.py", line 42, in check_afinfo
        for (hooked_member, hook_address) in self.check_members(var.seq_fops, var_name, op_members,  modules):
      File "/root/volatility/volatility/plugins/linux/check_afinfo.py", line 37, in check_members
        for (hooked_member, hook_address) in self.verify_ops(var_ops, members, modules):
      File "/root/volatility/volatility/plugins/linux/common.py", line 94, in verify_ops
        known = self.is_known_address(addr, modules)
      File "/root/volatility/volatility/plugins/linux/common.py", line 74, in is_known_address
        return (self.addr_space.address_compare(addr, text) != -1 and self.addr_space.address_compare(addr, etext) == -1) or self.address_in_module(addr, modules)
      File "/root/volatility/volatility/addrspace.py", line 167, in address_compare
        return cmp(cls.address_mask(a), cls.address_mask(b))
      File "/root/volatility/volatility/plugins/addrspaces/amd64.py", line 264, in address_mask
        return addr & 0xffffffffffff
    TypeError: unsupported operand type(s) for &: 'CType' and 'int'

and with debug:

    Volatility Foundation Volatility Framework 2.5
    DEBUG   : volatility.debug    : centos7.1: Found dwarf file boot/System.map-3.10.0-327.3.1.el7.x86_64 with 760 symbols
    DEBUG   : volatility.debug    : centos7.1: Found system file boot/System.map-3.10.0-327.3.1.el7.x86_64 with 1 symbols
    DEBUG   : volatility.debug    : Applying modification from BashHashTypes
    DEBUG   : volatility.debug    : Applying modification from BashTypes
    DEBUG   : volatility.debug    : Applying modification from BasicObjectClasses
    DEBUG   : volatility.debug    : Applying modification from ELF32Modification
    DEBUG   : volatility.debug    : Applying modification from ELF64Modification
    DEBUG   : volatility.debug    : Applying modification from ELFModification
    DEBUG   : volatility.debug    : Applying modification from EditBoxObjectClasses
    DEBUG   : volatility.debug    : Applying modification from HPAKVTypes
    DEBUG   : volatility.debug    : Applying modification from LimeTypes
    DEBUG   : volatility.debug    : Applying modification from LinuxIDTTypes
    DEBUG   : volatility.debug    : Applying modification from LinuxTruecryptModification
    DEBUG   : volatility.debug    : Applying modification from MachoModification
    DEBUG   : volatility.debug    : Applying modification from MachoTypes
    DEBUG   : volatility.debug    : Applying modification from MbrObjectTypes
    DEBUG   : volatility.debug    : Applying modification from VMwareVTypesModification
    DEBUG   : volatility.debug    : Applying modification from VirtualBoxModification
    DEBUG   : volatility.debug    : Applying modification from LinuxGate64Overlay
    DEBUG   : volatility.debug    : Applying modification from LinuxIntelOverlay
    DEBUG   : volatility.debug    : Applying modification from LinuxKmemCacheOverlay
    DEBUG   : volatility.debug    : Requested symbol cache_chain not found in module kernel

    DEBUG   : volatility.debug    : Applying modification from LinuxMountOverlay
    DEBUG   : volatility.debug    : Applying modification from LinuxObjectClasses
    DEBUG   : volatility.debug    : Applying modification from LinuxOverlay
    DEBUG   : volatility.debug    : centos7.1: Found dwarf file boot/System.map-3.10.0-327.3.1.el7.x86_64 with 760 symbols
    DEBUG   : volatility.debug    : centos7.1: Found system file boot/System.map-3.10.0-327.3.1.el7.x86_64 with 1 symbols
    DEBUG   : volatility.debug    : Applying modification from BashHashTypes
    DEBUG   : volatility.debug    : Applying modification from BashTypes
    DEBUG   : volatility.debug    : Applying modification from BasicObjectClasses
    DEBUG   : volatility.debug    : Applying modification from ELF32Modification
    DEBUG   : volatility.debug    : Applying modification from ELF64Modification
    DEBUG   : volatility.debug    : Applying modification from ELFModification
    DEBUG   : volatility.debug    : Applying modification from EditBoxObjectClasses
    DEBUG   : volatility.debug    : Applying modification from HPAKVTypes
    DEBUG   : volatility.debug    : Applying modification from LimeTypes
    DEBUG   : volatility.debug    : Applying modification from LinuxIDTTypes
    DEBUG   : volatility.debug    : Applying modification from LinuxTruecryptModification
    DEBUG   : volatility.debug    : Applying modification from MachoModification
    DEBUG   : volatility.debug    : Applying modification from MachoTypes
    DEBUG   : volatility.debug    : Applying modification from MbrObjectTypes
    DEBUG   : volatility.debug    : Applying modification from VMwareVTypesModification
    DEBUG   : volatility.debug    : Applying modification from VirtualBoxModification
    DEBUG   : volatility.debug    : Applying modification from LinuxGate64Overlay
    DEBUG   : volatility.debug    : Applying modification from LinuxIntelOverlay
    DEBUG   : volatility.debug    : Applying modification from LinuxKmemCacheOverlay
    DEBUG   : volatility.debug    : Requested symbol cache_chain not found in module kernel

    DEBUG   : volatility.debug    : Applying modification from LinuxMountOverlay
    DEBUG   : volatility.debug    : Applying modification from LinuxObjectClasses
    DEBUG   : volatility.debug    : Applying modification from LinuxOverlay
    DEBUG   : volatility.debug    : Voting round
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.macho.MachOAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.lime.LimeAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hibernate.WindowsHiberFileSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crashbmp.WindowsCrashDumpSpace64BitMap'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hpak.HPAKAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.VirtualBoxCoreDumpElf64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmem.VMWareMetaAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.QemuCoreDumpElf'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmware.VMWareAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.amd64.AMD64PagedMemory'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.intel.IA32PagedMemoryPae'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.intel.IA32PagedMemory'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.osxpmemelf.OSXPmemELF'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.standard.FileAddressSpace'>
    DEBUG   : volatility.debug    : Succeeded instantiating <volatility.plugins.addrspaces.standard.FileAddressSpace object at 0x8483250>
    DEBUG   : volatility.debug    : Voting round
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.macho.MachOAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.lime.LimeAddressSpace'>
    DEBUG   : volatility.debug    : Succeeded instantiating <volatility.plugins.addrspaces.lime.LimeAddressSpace object at 0x8483210>
    DEBUG   : volatility.debug    : Voting round
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.macho.MachOAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.lime.LimeAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hibernate.WindowsHiberFileSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crashbmp.WindowsCrashDumpSpace64BitMap'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hpak.HPAKAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.VirtualBoxCoreDumpElf64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmem.VMWareMetaAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.QemuCoreDumpElf'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmware.VMWareAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.amd64.AMD64PagedMemory'>
    DEBUG   : volatility.debug    : Succeeded instantiating <volatility.plugins.addrspaces.amd64.AMD64PagedMemory object at 0x84835d0>
    DEBUG   : volatility.debug    : Voting round
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.macho.MachOAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.lime.LimeAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hibernate.WindowsHiberFileSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crashbmp.WindowsCrashDumpSpace64BitMap'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hpak.HPAKAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.VirtualBoxCoreDumpElf64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmem.VMWareMetaAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.QemuCoreDumpElf'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmware.VMWareAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.amd64.AMD64PagedMemory'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.intel.IA32PagedMemoryPae'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.intel.IA32PagedMemory'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.osxpmemelf.OSXPmemELF'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.standard.FileAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.arm.ArmAddressSpace'>
    DEBUG   : volatility.debug    : Voting round
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.macho.MachOAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.lime.LimeAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hibernate.WindowsHiberFileSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crashbmp.WindowsCrashDumpSpace64BitMap'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hpak.HPAKAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.VirtualBoxCoreDumpElf64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmem.VMWareMetaAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.QemuCoreDumpElf'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmware.VMWareAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.amd64.AMD64PagedMemory'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.intel.IA32PagedMemoryPae'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.intel.IA32PagedMemory'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.osxpmemelf.OSXPmemELF'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.standard.FileAddressSpace'>
    DEBUG   : volatility.debug    : Succeeded instantiating <volatility.plugins.addrspaces.standard.FileAddressSpace object at 0x8483a90>
    DEBUG   : volatility.debug    : Voting round
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.macho.MachOAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.lime.LimeAddressSpace'>
    DEBUG   : volatility.debug    : Succeeded instantiating <volatility.plugins.addrspaces.lime.LimeAddressSpace object at 0x8483ad0>
    DEBUG   : volatility.debug    : Voting round
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.macho.MachOAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.lime.LimeAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hibernate.WindowsHiberFileSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crashbmp.WindowsCrashDumpSpace64BitMap'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hpak.HPAKAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.VirtualBoxCoreDumpElf64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmem.VMWareMetaAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.QemuCoreDumpElf'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmware.VMWareAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.amd64.AMD64PagedMemory'>
    DEBUG   : volatility.debug    : Succeeded instantiating <volatility.plugins.addrspaces.amd64.AMD64PagedMemory object at 0x8483b10>
    DEBUG   : volatility.debug    : Voting round
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.macho.MachOAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.lime.LimeAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hibernate.WindowsHiberFileSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crashbmp.WindowsCrashDumpSpace64BitMap'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.hpak.HPAKAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.VirtualBoxCoreDumpElf64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmem.VMWareMetaAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.elfcoredump.QemuCoreDumpElf'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.vmware.VMWareAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.amd64.AMD64PagedMemory'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.intel.IA32PagedMemoryPae'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.intel.IA32PagedMemory'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.osxpmemelf.OSXPmemELF'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.standard.FileAddressSpace'>
    DEBUG   : volatility.debug    : Trying <class 'volatility.plugins.addrspaces.arm.ArmAddressSpace'>

**Comment by atcuno** [comment]
Hello,

Thank you for the bug report. This should be fixed now:

https://github.com/volatilityfoundation/volatility/commit/f85cb934d9b92f6302e0f6e695f431459708097c

I will close the ticket, but please reopen if you have any issues.
