### ISSUE TITLE
cmdscan plugin is not working properly on Windows 8 32bit and 64bit image

### ISSUE THREAD

**Issue by DevboostMadatnis** [volatilityfoundation/volatility#283]
On Windows 8 32bit & 64bit image "cmdscan" plugin is not working/unable find command history.

---

volatility-2.5.standalone.exe cmdscan -f "F:\vm\Win8_32\564d663a-b45f-9966-2ea6-0ce40b2df563.vmem" --profile=Win8SP1x86
**Volatility Foundation Volatility Framework 2.5**

---

It displays only version info and no result.

**Comment by gleeda** [comment]
Your question was answered in email:

```
Hello,

cmdscan and consoles don't yet support Windows 8 systems. I would
suggest using the brute force command history technique description in
the User Activity section of our cheat sheet (page 3):

https://github.com/volatilityfoundation/volatility/raw/gh-pages/docs/VolatilityCheatSheet.pdf

MHL
```
