### ISSUE TITLE
archlinux profile creation failed

### ISSUE THREAD

**Issue by benoitne** [volatilityfoundation/volatility#285]
Hi,
I try here as I don't have any feedback on the profile issues

I have been able to suscessfuly create a .zip in Archlinux but not able to import it.
When I try I got this error message :
Volatility Foundation Volatility Framework 2.5
*** Failed to import volatility.plugins.overlays.linux.linux (ValueError: too many values to unpack)

My steps:
git clone https://github.com/volatilityfoundation/volatility.git
cd volatility/tools/linux
make -C /lib/modules/4.3.3-gnu-3/build CONFIG_DEBUG_INFO=y M=$PWD modules
dwarfdump -di ./module.o > module.dwarf
cp /proc/kallsyms /boot/System.map-4.3.3-gnu-2 (as there is no system.map in ArchLinux)

cd volatility
zip volatility/plugins/overlays/linux/ArchLinux64.zip tools/linux/module.dwarf /boot/System.map-4.3.3-gnu-2
adding: tools/linux/module.dwarf (deflated 91%)
adding: boot/System.map-4.3.3-gnu-2 (deflated 79%)

Importing a profile built from github is working well so I assume something wrong when I build mine...
Many thanks if you have any idea :)

**Comment by sunil16** [comment]
Hello Sir 
I am analyzing dump  memory based on Virtual Box with the help of volatility memory forensic tool as we know that there are so many pre -build windows based profile except linux based profile. So
after downloading per-built linux  profile from :- https://github.com/volatilityfoundation/profiles/tree/master/Linux/Ubuntu/x64
profile name:- LinuxUbuntu14043x64 
downloaded profile properly I have add into my  volatility-2.4 software
but after run command :- vol.py  -- f[image] -- profile=[profile]   [plugin]
there is an  Error described as following in screen shots 
![screenshot from 2016-04-21 17 12 02](https://cloud.githubusercontent.com/assets/13816959/14707999/8915290e-07e5-11e6-95a4-efd7c1f4f6aa.png)

**Comment by floryst** [comment]
@benoitne I had the same issue as you, but I resolved it. `System.map` is supposed to have only 3 fields per line, but `/proc/kallsyms` on Archlinux has 4 fields for symbols that AFAIK are part of kernel modules.

To fix this, run `cat /proc/kallsyms | cut -f1 > System.map` to generate a working System.map for volatility.

**Comment by benoitne** [comment]
@floryst thanks ! I think I have been able to build it right now as I can see it on my available profiles.
The thing is now when I try to use it I keep having the same error : 

`  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/volatility/volatility/plugins/linux/common.py", line 63, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "/volatility/volatility/commands.py", line 116, in execute
    if not self.is_valid_profile(profs[self._config.PROFILE]()):
  File "/volatility/volatility/plugins/overlays/linux/linux.py", line 214, in __init__
    obj.Profile.__init__(self, *args, **kwargs)
  File "/volatility/volatility/obj.py", line 862, in __init__
    self.reset()
  File "/volatility/volatility/plugins/overlays/linux/linux.py", line 224, in reset
    self.load_vtypes()
  File "/volatility/volatility/plugins/overlays/linux/linux.py", line 261, in load_vtypes
    vtypesvar = dwarf.DWARFParser(dwarfdata).finalize()
  File "/volatility/volatility/dwarf.py", line 71, in __init__
    self.feed_line(line)
  File "/volatility/volatility/dwarf.py", line 162, in feed_line
    self.process_statement(**parsed) #pylint: disable-msg=W0142
  File "/volatility/volatility/dwarf.py", line 204, in process_statement
    self.vtypes[name] = [ int(data['DW_AT_byte_size'], self.base), {} ]
KeyError: 'DW_AT_byte_size'
`
Have you been able to use your profile right ?
Many thanks

**Comment by atcuno** [comment]
Hello,

Using /proc/kallsyms is not a supported way to replace System.map as kallsyms does not have all of the global variable addresses needed. 

imageinfo is a Windows only plugin, which is why it generated that error. 

I am going to close this issue but please make a new one if you have any further questions.

**Comment by benoitne** [comment]
Thanks for your reply, so should I consider impossible to create an ArchLinux profile then ?

**Comment by phocean** [comment]
Same issue on Fedora 25, please reopen this issue.

**Comment by 2Belette** [comment]
I am not able to do it but please do on your side then we'll get a chance to get another view on this case

**Comment by jose-016al** [comment]
He creado un perfil de debian 11, pero al importarlo en voaltility me da este mismo fallo "*** Failed to import volatility.plugins.overlays.linux.linux (ValueError: too many values to unpack)"
