### ISSUE TITLE
mac_threads - El Capitan no longer has vm_map_entry.alias member

### ISSUE THREAD

**Issue by williamshowalter** [volatilityfoundation/volatility#289]
I've come across a problem where I'm unable to use the mac_threads plugin. It's attempting to resolve the type of memory allocation using the 'alias' field, which is no longer present in the structure. I've checked the Kernel Debug symbols to make sure it wasn't a mistake in the profile, but the structure definitions given by dwarfdump confirm that there is no longer an alias member. The vm_map_entry struct does have two new one bit flags, and 6 bits that are undefined.

This can be seen in the source code (https://opensource.apple.com/source/xnu/xnu-3248.20.55/osfmk/vm/vm_map.h). I'm not sure where the data can be obtained now that it isn't in the vm_map_entry struct, but I'll continue looking into it. 

```
python vol.py -f ~/OSX_10.11.3.vmem --profile MacElCapitan_10_11_3_15D13bx64 mac_threads
Volatility Foundation Volatility Framework 2.5
Offset             Pid      Tid      UID      State                          Is Active? Options                        Priority Startup Addr       Stack Start Addr   Stack Size (bytes) HW Debugged DTraced Arguments
------------------ -------- -------- -------- ------------------------------ ---------- ------------------------------ -------- ------------------ ------------------ ------------------ ----------- ------- ---------
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/Users/william/SW/volatility/volatility/plugins/mac/common.py", line 48, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "/Users/william/SW/volatility/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "/Users/william/SW/volatility/volatility/plugins/mac/threads.py", line 426, in render_text
    for proc, thread, stack_start, stack_size, args, registers, is_active, dtraced, debugged, uid in data:
  File "/Users/william/SW/volatility/volatility/plugins/mac/threads.py", line 322, in calculate
    maps = self.get_stack_map(proc, thread_list, bit_string)
  File "/Users/william/SW/volatility/volatility/plugins/mac/threads.py", line 219, in get_stack_map
    map_type = str(dict_alias.get(int(map.alias), "UNKNOWN"))
  File "/Users/william/SW/volatility/volatility/obj.py", line 538, in __getattr__
    return getattr(result, attr)
  File "/Users/william/SW/volatility/volatility/obj.py", line 748, in __getattr__
    return self.m(attr)
  File "/Users/william/SW/volatility/volatility/obj.py", line 730, in m
    raise AttributeError("Struct {0} has no member {1}".format(self.obj_name, attr))
AttributeError: Struct next has no member alias
```

**Comment by williamshowalter** [comment]
It seems strange to me, but the source code seems to indicate that the alias flags are being stored in the vm_map_entry.vme_offset variable. The flags are only a byte, and that offset item is 8 bytes. I'm able to get the command running by replacing map.alias with map.vme_offset, but I don't know if the results are reliable yet.

**Comment by atcuno** [comment]
Hey,

I fixed this for the special path function last month:

https://github.com/volatilityfoundation/volatility/commit/885077d6118d301c11e41757b81afe52c4b3eabe

I missed that the threads plugin touched alias directly. You can use the
logic from that patch to get threads working asap but I will also update
it in git soon.

Thanks for the bug report!

Thanks,
Andrew (@attrc)

**Comment by williamshowalter** [comment]
Thanks! I got it working in my copy.
