### ISSUE TITLE
unified_output example on wiki is missing closing bracket

### ISSUE THREAD

**Issue by hiddenillusion** [volatilityfoundation/volatility#292]
The `unified_output()` on the [wiki](https://github.com/volatilityfoundation/volatility/wiki/Unified-Output#plugin-developers) is missing its closing bracket:

```python
    def unified_output(self, data):
        ...
        return TreeGrid([("Offset", Address),
                        ("Name", str),
                        ("ID", int),
                        ("Count", Hex),
                        self.generator(data))
```

should be ("Count", Hex)**]** based on other plugins that have it implemented

**Comment by gleeda** [comment]
Good catch! it should now be fixed.
