### ISSUE TITLE
Dumpregistry issue/question

### ISSUE THREAD

**Issue by hakija** [volatilityfoundation/volatility#298]
When using dumpregistry on stuxnet memory image i dont get the desired hives in the System reg file:
S) MRxCls
  (S) MRxDAV
  (S) MRxNet
  (S) MRxSmb

But when doing it manualy throgh printkey command i will see them no problem. Is this me/my knowledge or is the command not exporting everything?

**Comment by gleeda** [comment]
These are registry keys, not registry hives:
```
(S) MRxCls
(S) MRxDAV
(S) MRxNet
(S) MRxSmb
```

How did you try to find them?  I'm looking at a public `stuxnet.vmem` file and I see them fine:

```
$ python vol.py -f stuxnet.vmem hivelist
Virtual    Physical   Name
---------- ---------- ----
[removed]
0xe1035b60 0x02a9eb60 \Device\HarddiskVolume1\WINDOWS\system32\config\system
0xe102e008 0x02a98008 [no name]

$ python vol.py -f stuxnet.vmem dumpregistry -o 0xe1035b60 -D OUTPUT/
```

Now I'm going to use an offline script (https://github.com/gleeda/misc-scripts/blob/master/misc_python/printkey.py) which uses `python-registry` (https://github.com/williballenthin/python-registry) in order to read the registry keys:

```
$ python printkey.py OUTPUT/registry.0xe1035b60.system.reg "controlset001\services" | less -I
[removed]
$$$PROTO.HIV\ControlSet001\Services\MRxCls
$$$PROTO.HIV\ControlSet001\Services\MRxDAV
$$$PROTO.HIV\ControlSet001\Services\MRxNet
$$$PROTO.HIV\ControlSet001\Services\MRxSmb
[removed]

$ python printkey.py OUTPUT/registry.0xe1035b60.system.reg "controlset001\services\mrxsmb"
Processing OUTPUT/registry.0xe1035b60.system.reg
************************************************************************
$$$proto.hiv\controlset001\services\mrxsmb
VALUENAME: Type
VALUE: 2

VALUENAME: Start
VALUE: 1

VALUENAME: ErrorControl
VALUE: 1

VALUENAME: Tag
VALUE: 5

VALUENAME: ImagePath
VALUE: system32\DRIVERS\mrxsmb.sys

VALUENAME: DisplayName
VALUE: MRXSMB

VALUENAME: Group
VALUE: Network

VALUENAME: Description
VALUE: MRXSMB

VALUENAME: LastLoadStatus
VALUE: 0

Subkeys: 
$$$PROTO.HIV\ControlSet001\Services\MRxSmb\Parameters
$$$PROTO.HIV\ControlSet001\Services\MRxSmb\Security
************************************************************************
```

Let me know if that helps.

**Comment by gleeda** [comment]
I haven't heard back, but I believe that I answered your question.  Please feel free to reopen if you need to.

**Comment by hakija** [comment]
Hi sorry, was super busy and just forgot about this. Also i dint get any notifications about your reply for some reason....
Since I'm lazy, what I did was used standalone Volatility and:

vol.exe -f stuxnet.vmem dumpregistry -D c:\temp

This way I get all registry files in one place and then I can use whatever tool I want for analyzing them such as FTK Registry viewer. But... when I did it this way, I could not see the aforementioned keys. When I did the way you described, print each key manually through separate commands, I could see them no problem. 

I did it just now again (dumping all registry files at once) and all is good?!? I have no explanation except that I used a different system for analysis...

Please see the SS below:
![image](https://cloud.githubusercontent.com/assets/14116246/15282714/52a11afe-1b45-11e6-807f-4897c70fba7e.png)

On the left is the registry without the keys and on the right with the keys. Same procedure but different results on different systems.

Thank you for getting back to me, it seams that I have issues rather then volatility :)
