### ISSUE TITLE
Netscan 'established' connections show PID as -1.  Psscan doesn't work.  Overlays???

### ISSUE THREAD

**Issue by walkr113** [volatilityfoundation/volatility#302]
When running netscan on either X64 or X86 images all 'established' connections show -1 as the PID.  Also, psscan no longer works.  I believe it has to do with the overlays and am looking for a way to fix this.

**Comment by walkr113** [comment]
using vol.py 2.5,  Python 2.6.6 or 2.7 doesn't work for either one.

**Comment by iMHLv2** [comment]
Yes, this is likely an overlay (more like vtypes) issue. Its a couple of
steps, but you can fix it by:

1) getting ntoskrnl.exe from disk (or using moddump on the memory image)
2) clone the pdbparse python library and run symcheck.py against ntos to
get the pdb
3) run pdb_tpi_vtypes.py on the pdb and redirect the output to a file
4) copy that new file to
volatility/plugins/overlays/windows/<profile>_vtypes.py for the
corresponding profile

Let me know if that doesn't fix it.

MHL

**Comment by iMHLv2** [comment]
We recently added various new profiles to handle this. Git pull master and then run vol.py --info to see the new ones. If this doesn't solve your problem, or if you saw similar issues on machines running an OS besides Win7, Win8, or Win10, please feel free to reopen.
