### ISSUE TITLE
Timeliner body output missing timestamps

### ISSUE THREAD

**Issue by dptom** [volatilityfoundation/volatility#314]
I'm running version Framework 2.5. When I run timeliner or mftparser where I want the output as a body file, it appears the output is missing the timestamps. Here is a quick look at two output files, the first set output=text, the second output=body... Note in the body output, the timestamps are missing. 

root@ubuntu:/mnt/hgfs/Documents/FOR508-partial/Mem-practice# head -2 mem_timeline.txt 
2011-06-03 04:31:36 UTC+0000|[LIVE RESPONSE]| (System time)|
2010-08-22 17:38:12 UTC+0000|[IEHISTORY]| explorer.exe->Visited: Administrator@about:Home| PID: 1196/Cache type "URL " at 0x17f5100 End: 2010-08-22 17:38:12 UTC+0000
root@ubuntu:/mnt/hgfs/Documents/FOR508-partial/Mem-practice# head -2 mem_timeline.body 
0|[LIVE RESPONSE] (System time)|0|---------------|0|0|0|1307075496|1307075496|1307075496|1307075496
0|[IEHISTORY] explorer.exe->Visited: Administrator@about:Home PID: 1196/Cache type "URL " at 0x17f5100|0|---------------|0|0|0|1282498692|1282498692|1282498692|1282498692

**Comment by gleeda** [comment]
Hi dptom,

Actually the timestamps are there, they are just in a raw format.  You can use the 'mactime' script from the sleuthkit to make them human readable.  

All the best,

--
Jamie Levy (@gleeda)

**Comment by dptom** [comment]
My bad. I was caught off guard by the response at the top that looks like this....

Xxx Xxx 00 0000 00:00:00,0,m...,---------------,0,0,0,"[PROCESS] Procmon.exe PID: 660/PPID: 1196/POffset: 0x01e543a0"
Xxx Xxx 00 0000 00:00:00,0,m...,---------------,0,0,0,"[PROCESS] TSVNCache.exe PID: 324/PPID: 1196/POffset: 0x02086978"

You're correct, the timestamps for the rest of the file are there and it was my bad for not paging down...
