### ISSUE TITLE
Getting Volatility to analyse a win10 dump 

### ISSUE THREAD

**Issue by HJTP** [volatilityfoundation/volatility#316]
My goal is to make a dump of a Windows 10 VM with a bunch of applications running, and then extract all processes' memory from that dump. Volatility seems like the perfect fit for the job, but I am having trouble to make it play nicely with my Windows 10 dump. 

I run Windows 10 education x64 in Virtualbox 5.0.24 (Windows 10 cannot be run in Virtualbox 4 as far as I know), host is a Windows 7 machine. I opened the Edge browser with a bunch of tabs in the VM, and then I run:
`VBoxManage.exe debugvm "windows_10_new" dumpvmcore --filename win10dump.elf`
which gives me a proper elf file with the VM dump. The file can be read by readelf, I can extract the RAM from it, etc. 

First, I tried just running Volatility on it:
`volatility-2.5.standalone.exe pslist -f win10dump.elf --profile=Win10x64`
but this gave an error about the ELF-header (which it had validated twice already), or no suitable address space could be found, or it just hung. I also tried  the Python version directly, which gave the same results. I dug through the source code to try and find out what was going wrong, but I couldn't. 

However, it turned out I had been too impatient. I left a kdbgscan running for more than three hours, and it gave results: Win10x64 (6.4.9841) with two KdCopyDataBlock values. The first didn't work with pslist, but the second kind of does: 
`Offset(V)          Name                    PID   PPID   Thds     Hnds   Sess  Wow64 Start                          Exit`
`------------------ -------------------- ------ ------ ------ -------- ------ ------`
`0xffffe0014023b700                           4      0 11...8        0 ------      0 2016-07-01 16:37:33 UTC+0000`
`0xffffe00141cae040 ►??A☺???smss.exe        316      4 11...0        0 ------      0 2016-07-01 16:37:34 UTC+0000`
`0xffffe00141c88080 ?|?A☺???csrss.ex        404    396 11...6        0      0      0 2016-07-01 16:37:42 UTC+0000`

Interestingly, the names seem to be off by 8 bytes. I changed 0x448 to 0x450 in win10_x64_vtypes.py at ImageFileName, that seems to do it, but the names are still chopped off too short: 
`0xffffe001433aa340 MicrosoftEdgeC         4984   2532 10...4        0      1      0 2016-07-01 16:38:54 UTC+0000`. 

Nonetheless, it seems the kdbg value works. So, next step, extracting process memory:
`python vol.py -f win10dump.elf --kdbg=value --profile=Win10x64 memdump -D memdumps -p 4984`
This takes a long time as well, it turns out it is just filling up the output file until my disk is full, and then it crashes. Same goes for memmap it seems, and other tools (vadinfo, vadwalk) just print the pid. 

Suggestions? I'm open to anything, like using another hypervisor, another way to dump, other plugins, or even another memory analysis tool.

**Comment by npetroni** [comment]
Hi,

Would you mind giving this branch a try? 
https://github.com/npetroni/volatility/tree/issue-316

In particular, hopefully `pslist` and `memdump` will work if you use `--profile=Win10x64_1AC738FB` (the rest of the arguments should match what you used before). This isn't a long-term solution, but might help you make progress while we work on something more permanent. Let me know how it goes.

Thanks.

**Comment by HJTP** [comment]
The output of `pslist` does indeed seem to be correct now! Nice. The memdump did not fill my complete disk, which is good. The dump it extracted is about 500 MB (Microsoft Edge), which is a lot more than the dump Rekall produces (175 MB). Interesting. By the way, I switched to Rekall, which has allowed me to do memdumps and everything. So I do not need Volatility any more, but I'd be happy to help make its Windows 10 analysis a bit better!

**Comment by npetroni** [comment]
I'm glad to hear you got something working. Thanks for testing out the branch. I'll update this issue once we push more support into the master branch. Any testing or feedback you can provide at that point would be great.

Thanks again.

**Comment by n3sfox** [comment]
I have encountered the same problem with process names when analyzing memory dump of Windows 10 Enterprise Evaluation, 32bit, Version 1511 Build 10586.494. 

Using @npetroni patch fixed the problem but few commands (eg. psscan, netscan) started throwing "KeyError: 'PoolTag'" exception. Original version of Volatility when using the same commands is returning empty results - which also isn't quite correct.

```
Volatility Foundation Volatility Framework 2.5
Offset(P)          Name                PID   PPID PDB        Time created                   Time exited                   
------------------ ---------------- ------ ------ ---------- ------------------------------ ------------------------------
Traceback (most recent call last):
  File "./vol.py", line 192, in <module>
    main()
  File "./vol.py", line 183, in main
    command.execute()
  File ".../npetroni-volatility/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File ".../npetroni-volatility/volatility/plugins/filescan.py", line 423, in render_text
    for eprocess in data:
  File ".../npetroni-volatility/volatility/poolscan.py", line 225, in scan
    pool_tag_offset = space.profile.get_obj_offset("_POOL_HEADER", "PoolTag")
  File ".../npetroni-volatility/volatility/obj.py", line 1015, in get_obj_offset
    offset, _cls = tmp.members[member]
KeyError: 'PoolTag'
```

**Comment by npetroni** [comment]
Would you mind trying this branch instead?

https://github.com/npetroni/volatility/tree/win10-2016-08-16

Let me know how it goes.

Thanks,
Nick

**Comment by n3sfox** [comment]
Haven't done throughout testing, but win10-2016-08-16 branch seems to be working much better. No more KeyError exception and netscan/psscan/thrdscan/... commands started working correctly. Thank you.

**Comment by npetroni** [comment]
Great, thank you. Let me know if you run into any other trouble. We'll be merging these capabilities into the master branch soon.
