### ISSUE TITLE
Issue while using Volatility within Cuckoo.

### ISSUE THREAD

**Issue by jdpadro** [volatilityfoundation/volatility#320]
I installed Volatility from source and it seems to work but I get the following warnings, and would like to ask what they mean. 
2016-07-15 14:25:30,897 [volatility.debug] WARNING: NoneObject as string: No path, service isn't running
2016-07-15 14:25:30,906 [volatility.debug] WARNING: NoneObject as string: No path, service isn't running
2016-07-15 14:25:30,910 [volatility.debug] WARNING: NoneObject as string: No path, service isn't running
2016-07-15 14:25:30,920 [volatility.debug] WARNING: NoneObject as string: No path, service isn't running
2016-07-15 14:26:38,044 [volatility.debug] WARNING: NoneObject as string: Pointer Local invalid

The victim system is Win7SP164. 
The analysis system is Ubuntu Server 16.04 using Python 2.7 I also have installed the following PIP packages. 

alembic (0.8.0)
androguard (3.0)
backports.shutil-get-terminal-size (1.0.0)
beautifulsoup4 (4.4.1)
cffi (1.6.0)
chardet (2.3.0)
click (6.6)
colorama (0.3.7)
cryptography (1.3.2)
decorator (4.0.10)
distorm3 (3.3.4)
distribute (0.7.3)
Django (1.8.4)
dpkt (1.8.6.2)
ecdsa (0.13)
elasticsearch (2.2.0)
enum34 (1.0.4)
Flask (0.10.1)
html5lib (0.999)
HTTPReplay (0.1.15)
idna (2.0)
ipaddress (1.0.14)
ipython (5.0.0)
ipython-genutils (0.1.0)
itsdangerous (0.24)
jdcal (1.0)
Jinja2 (2.8)
jsbeautifier (1.5.10)
lxml (3.6.0)
M2Crypto (0.24.0)
Mako (1.0.1)
MarkupSafe (0.23)
ndg-httpsclient (0.4.0)
oletools (0.42)
openpyxl (2.3.0)
pathlib2 (2.1.0)
peepdf (0.3.1)
pefile2 (1.2.11)
pexpect (4.2.0)
pickleshare (0.7.3)
Pillow (3.2.0)
pip (8.1.2)
prompt-toolkit (1.0.3)
ptyprocess (0.5.1)
py (1.4.31)
pyasn1 (0.1.8)
pycparser (2.14)
pycrypto (2.6.1)
Pygments (2.1.3)
pymisp (2.4.36)
pymongo (3.0.3)
pyOpenSSL (0.15.1)
pytest (2.8.7)
python-dateutil (2.4.2)
python-editor (0.3)
python-magic (0.4.6)
pythonaes (1.0)
pytz (2014.10)
requests (2.7.0)
setuptools (20.7.0)
simplegeneric (0.8.1)
six (1.9.0)
SQLAlchemy (1.0.8)
ssdeep (3.1.1)
tlslite-ng (0.6.0a3)
traitlets (4.2.2)
ujson (1.35)
urllib3 (1.16)
vboxapi (1.0)
volatility (2.5)
wakeonlan (0.2.2)
wcwidth (0.1.7)
Werkzeug (0.10.4)
wheel (0.29.0)
yara-python (3.4.0.0)

Thank you 
Jesus

**Comment by iMHLv2** [comment]
In most cases, the NoneObject warnings you see are indicative of pointers that can't be dereferenced (because the memory regions they point to are swapped to disk or freed). Nothing to worry about. If you see thousands of them, it could mean your memory sample is corrupt, but that isn't likely to happen if you're using VMs with Cuckoo.

**Comment by JReming85** [comment]
If you dont want to get this error anymore you need to turn off your page file on the windows vm.
