### ISSUE TITLE
mac_create_all_profiles.py typo 

### ISSUE THREAD

**Issue by wroersma** [volatilityfoundation/volatility#325]
https://github.com/volatilityfoundation/volatility/blob/master/tools/mac/mac_create_all_profiles.py#L138
Currently:
```
elif version.startwith("10.11"):
```
Should be: 
```
elif version.startswith("10.11"):
```
Just missing the "s" in "startswith"

**Comment by gleeda** [comment]
fixed in 3399683aee4a4b7dcb3f20556271c0c570cfd918 thanks, Wyatt!
