### ISSUE TITLE
OS X 10.11.6 profile creation issue 

### ISSUE THREAD

**Issue by andrejas** [volatilityfoundation/volatility#327]
Hi, I'm excited to start learning Volatility and tried creating a profile for a version of OS X for which I have a memory dump. 

Following https://github.com/volatilityfoundation/volatility/wiki/Mac, I ran the following commands: 

```
# dwarfdump -arch x86_64 -i /Library/Developer/KDKs/KDK_10.11.6_15G31.kdk/System/Library/Kernels/kernel.dSYM/ > 10.11.6_15G31.dwarfdump
# python tools/mac/convert.py 10.11.6_15G31.dwarfdump converted-10.11.6_15G31.dwarfdump
# python tools/mac/convert.py converted-10.11.6_15G31.dwarfdump 10.11.6_15G31.vtypes
# dsymutil -s -arch x86_64 /Library/Developer/KDKs/KDK_10.11.6_15G31.kdk/System/Library/Kernels/kernel > 10.11.6_15G31.symbol.dsymutil
# zip El_Capitan_10.11.6_15G31.zip 10.11.6_15G31.symbol.dsymutil 10.11.6_15G31.vtypes
# cp El_Capitan_10.11.6_15G31.zip volatility/plugins/overlays/mac/
```

When running Volatility I get this error.

`volatility $ ./vol.py --info
Volatility Foundation Volatility Framework 2.5
*** Failed to import volatility.plugins.overlays.mac.mac (SyntaxError: invalid syntax (<string>, line 3))`

I tried to create the profile with both the default `convert.py` that came with version 2.5 and the one submitted by William on https://github.com/volatilityfoundation/volatility/issues/246. Saw issues with both. This is my first attempt at creating a profile so I may have missed something. The new OS X Kernel Debug Kit has a different directory structure and naming convention than the one in the Volatility Wiki, so that could be related.

Can anyone point me in the right direction?

**Comment by wroersma** [comment]
I was able to get the profile after extracting out Kernel directory from the .pkg file that gets mounted when you click the .dmg. I was able to successfully create the profile myself without any import issues but I haven't done extensive testing on analysis with it yet.

**Comment by gleeda** [comment]
@wroersma could you please submit a pull request with the new profile to the profiles repo?

**Comment by wroersma** [comment]
@gleeda just created the pull request!

**Comment by gleeda** [comment]
Thank you!  I merged it in.  @andrejas could you try to use the profile @wroersma uploaded?  https://github.com/volatilityfoundation/profiles/raw/4a6019cb2d06584f50bc5d8e653aaa2530d1b936/Mac/10.11/ElCapitan_10.11.6_15G1004.zip

**Comment by andrejas** [comment]
@gleeda @wroersma I really appreciate the assistance and the overlay, but I was really looking for a solution for the import issue. My sample's version of OSX is a different one (15G31, not the patched 15G1004). 
  
Rather than having to ask someone else to create a profile for every different OSX memory image going forward, I'd like to understand if the sequence of commands should work. @wroersma I also extracted the KDK files from the .dmg file. Did you use the same commands or something different? Are you also using the 2.5 release from October 28th 2015?

**Comment by wroersma** [comment]
Sorry for the long delay I don't have a great solution for this right now. I manually changed the values in this script https://github.com/volatilityfoundation/volatility/blob/master/tools/mac/mac_create_all_profiles.py#L60 from "/Volumes/KernelDebugKit/kernel.dSYM" to "/Extracted_dir/KernelDebugKit/kernel.dSYM" and ran it from there. If you want to try that it's not pretty but it does work.

**Comment by atcuno** [comment]
Hello,

We should have all the available profiles for OS X now in our profiles repository. Please let us know if you encounter any issues with them. I will close this issue for now.
