### ISSUE TITLE
Memory Samples was not found. Error 404.

### ISSUE THREAD

**Issue by RAlexeev** [volatilityfoundation/volatility#328]
Hello!
I couldn't download Memory Samples provided by http://malwarecookbook.googlecode.com/... (For example, when I try download http://malwarecookbook.googlecode.com/svn-history/r26/trunk/17/1/zeus.vmem.zip I get the error 404). Maybe you could upload these memory samples in other file hosting service.
Thank you in advance.

**Comment by iMHLv2** [comment]
Sorry for the delay...a link to the DVD contents for malware cookbook is located on the cookbook website: http://malwarecookbook.com.
