### ISSUE TITLE
New release 2.5.1 or 2.6?

### ISSUE THREAD

**Issue by mika** [volatilityfoundation/volatility#331]
The latest stable release v2.5 dates back to Oct 29, 2015 while quite some changes took place since then. It would be nice to see a new official stable release of volatility, especially since that might get included in the upcoming Debian stable release then in time. :)

Thanks for volatility!

(Cc @eribertomota as he's also working on the volatility packaging in Debian)

**Comment by eribertomota** [comment]
Yeap! Is a good idea a new version with #330 fixed!

Thanks in advance!

**Comment by iMHLv2** [comment]
Thanks guys, we plan to wrap up a stable release before the end of the month. We'll keep you posted on the progress, but it shouldn't be an issue to meet your Nov/Dec time frame.

**Comment by eribertomota** [comment]
Any news?

**Comment by iMHLv2** [comment]
Sorry for the delay...2.6 should be out next week.

**Comment by eribertomota** [comment]
2016-12-16 14:24 GMT-02:00 iMHLv2 <notifications@github.com>:

> Sorry for the delay...2.6 should be out next week.
>

Thanks!

Eriberto

**Comment by eribertomota** [comment]
Hi!

Thanks for the new release. I uploaded the 2.6 version to Debian now. I sent it to 4-day/delay queue[1]. In other words, Volatility 2.6 will be available in Debian in 4 days.

Happy New Year!

Cheers,

Eriberto

[1] https://ftp-master.debian.org/deferred.html

**Comment by mika** [comment]
Release 2.6 is available, closing the issue therefore. Thanks everyone.
