### ISSUE TITLE
Psscan not working on Windows 7 x64 profiles

### ISSUE THREAD

**Issue by Heat-Miser** [volatilityfoundation/volatility#336]
Hello,

we have a problem to run psscan plugin on Windows 7 SP1 x64 machines (3 different dumps).

Pslist / netscan work perfectly, but psscan output contains only this:

Offset(P)          Name                PID   PPID PDB                Time created                   Time exited                   
------------------ ---------------- ------ ------ ------------------ ------------------------------ ------------------------------
0x000000013bfdf180                       0      0 0xfffffa8006bdf1a0                                                     

Do you have any idea ?

Thanks

**Comment by tomchop** [comment]
It seems that some people have encountered this in the past, changing the _EPROCESS size from from `0x4d0` to `0x4e8` in `overlays/windows/win7_sp1_x64_vtypes.py` fixed it for them.

**Comment by Heat-Miser** [comment]
This patch works indeed ! 

Thanks !

**Comment by gleeda** [comment]
If you just do a `git pull` you should see an update that fixes this as well.  It was fixed in a9136d70243af045033695f5f7fd774b3b411696
