### ISSUE TITLE
Feature request: support for ARM-based Linux images

### ISSUE THREAD

**Issue by kenion** [volatilityfoundation/volatility#337]
The LiME kernel module is able to capture memory images from ARM-based Linux systems like Raspberry Pi, but as far as I know, there is no tool available to analyze these images.

Despite Volatility's lack of documented support for the ARM architecture outside of Android, I have tried to create a Volatility profile of my RPi running Raspbian Jessie.  The process encountered an error during vtype creation with the following result:

`pi@raspberrypi:~/Desktop/volatility/tools/linux $: sudo make`
`make -C //lib/modules/4.4.23-v7+/build CONFIG_DEBUG_INFO=y M="" modules`
`make[1]: Entering directory '/usr/src/linux-headers-4.4.23-v7+'`
`CHK     include/config/kernel.release`
`CHK     include/generated/uapi/linux/version.h`
`CHK     include/generated/utsrelease.h`
`make[2]: 'include/generated/mach-types.h' is up to date.`
`CHK     include/generated/bounds.h`
`CHK     include/generated/timeconst.h`
`CHK     include/generated/asm-offsets.h`
`CALL    scripts/checksyscalls.sh`
`grep: scripts/../arch/x86/entry/syscalls/syscall_32.tbl: No such file or directory`
`make[2]: *** No rule to make target 'arch/arm/crypto/aes-armv4.o', needed by 'arch/arm/crypto/aes-arm.o'.  Stop.`
`Makefile:959: recipe for target 'arch/arm/crypto' failed`
`make[1]: *** [arch/arm/crypto] Error 2`
`make[1]: Leaving directory '/usr/src/linux-headers-4.4.23-v7+'`
`Makefile:10: recipe for target 'dwarf' failed`
`make: *** [dwarf] Error 2`

So, I wonder if it would be feasible to introduce support for images of ARM-based Linux systems. If not, or if you believe there is insufficient demand to justify the necessary development, please feel free to close this issue.  I lack the technical knowledge to implement this alone, but would be happy to help with coding and testing if someone more familiar with Volatility could point me in the right direction.

**Comment by atcuno** [comment]
Hello,

Volatility has support for all ARM based Linux versions, not just Android. It looks like you need to set your cross compiler variables, as the error line:

"grep: scripts/../arch/x86/entry/syscalls/syscall_32.tbl: No such file or directory"

references the arch/x86 directory, which does not seem right. Can you paste your makefile and also any environment variables that you set related to cross compiling? You will need to follow a similar process that you used for cross compiling LiME for ARM to get the Volatility for ARM module compiled. 

I also see that this bug has been reported before on the RPI github:

https://github.com/amescon/raspicomm-module/issues/9

But I still think its a cross compile issue based on the error message.

**Comment by kenion** [comment]
Thanks for your response, @atcuno.  I should mention that I was not cross-compiling, but attempting to compile directly on the RPi device.  I'm new to dealing with kernel modules, so I didn't realize that cross-compiling was more commonly used for the RPi.

If it's still relevant:
- The Makefile I used is the one in that ships in the tools/linux/ directory in the source code ([here](https://github.com/volatilityfoundation/volatility/blob/master/tools/linux/Makefile)).  
- The environment variables were unchanged from Raspbian defaults.

**Comment by atcuno** [comment]
Yes, many people choose to cross compile as your host desktop/laptop/server or a dev VM on the host will be more powerful than the ARM device in most cases.

I am curious -- did you get LiME compiled successfully for your device? LiME and volatility require the same setup and environment so if LiME compiled and Volatility didn't then it would be strange or a bug in Volatility's build system.
