### ISSUE TITLE
Unable to convert a win10x64 raw memory image to crash dump

### ISSUE THREAD

**Issue by iMHLv2** [volatilityfoundation/volatility#338]
`ERROR   : volatility.debug    : Unexpected error (integer out of range for 'I' format code) during copy, recorded data up to offset 0`

The `_KDDEBUGGER_DATA64.dbgkd_version64()` method appears to be failing to find the `_DBGKD_GET_VERSION64`

**Comment by ladipro** [comment]
_DBGKD_GET_VERSION64 is not that close to KDBG on Win10. Can you give this commit a try? https://github.com/ladipro/volatility/commit/4c5b1f699ba99dfab32d505b59e0b14b92a150f1
