### ISSUE TITLE
Problems with doxygen docs

### ISSUE THREAD

**Issue by eribertomota** [volatilityfoundation/volatility#343]
Dear upstream,

When packaging Volatility in Debian, I get these warnings and errors:

P: volatility source: insane-line-length-in-source-file tools/doxygen/d3/d3.js line length is 32018 characters (>512)
P: volatility source: source-contains-prebuilt-javascript-object tools/doxygen/d3/d3.js line length is 32018 characters (>512)
E: volatility source: source-is-missing tools/doxygen/d3/d3.js line length is 32018 characters (>512)

Could you fix these issues? To help, I will put a full explanation below.

Thanks a lot in advance.

Regards,

Eriberto

P: volatility source: insane-line-length-in-source-file tools/doxygen/d3/d3.js line length is 32018 characters (>512)
N: 
N:    The source file includes a line length that is well beyond the normally
N:    human made code line length.
N:    
N:    This very long line length does not allow lintian to do correctly some
N:    source file checks.
N:    
N:    This line could also be the result of some text injected by a computer
N:    program, and thus could lead to FTBFS bugs.
N:    
N:    Last but not least, long line in source code could be used to obfuscate
N:    the source code and to hide stuff like backdoors or security problems.
N:    
N:    It could be due to jslint source comments or other build tool comments.
N:    
N:    You may report this issue upstream.
N:    
N:    Severity: pedantic, Certainty: certain
N:    
N:    Check: cruft, Type: source
N: 
P: volatility source: source-contains-prebuilt-javascript-object tools/doxygen/d3/d3.js line length is 32018 characters (>512)
N: 
N:    The source tarball contains a prebuilt (minified) JavaScript object.
N:    They are usually left by mistake when generating the tarball by not
N:    cleaning the source directory first. You may want to report this as an
N:    upstream bug, in case there is no sign that this was intended.
N:    
N:    Severity: pedantic, Certainty: possible
N:    
N:    Check: cruft, Type: source
N: 
E: volatility source: source-is-missing tools/doxygen/d3/d3.js line length is 32018 characters (>512)
N: 
N:    The source of the following file is missing. Lintian checked a few
N:    possible paths to find the source, and do not find it.
N:    
N:    Please repack your package to include the source or add it to
N:    "debian/missing-sources" directory.
N:    
N:    If this is a false-positive, please report a bug against Lintian.
N:    
N:    Severity: serious, Certainty: possible
N:    
N:    Check: cruft, Type: source

**Comment by iMHLv2** [comment]
Hi @eribertomota, I believe this file is auto-generated by doxygen, and despite the warnings, I don't think it poses any serious risks. Feel free to reopen if you want to discuss further (or potentially exclude the doxygen directory from the package, if possible).

**Comment by gleeda** [comment]
I'll take care of this soon.

**Comment by eribertomota** [comment]
2016-10-28 12:59 GMT-02:00 gleeda <notifications@github.com>:

> I'll take care of this soon.


Thanks!
