### ISSUE TITLE
Windows 10 netscan shows 'established' PID's as -1

### ISSUE THREAD

**Issue by walkr113** [volatilityfoundation/volatility#346]
I had this issue previously with Windows 7 x64 images but was able to fix it by changing the 'owner' entry in tcpip_vtypes.py.  However, I do not see anything for Win10x64 in that file.  Any idea on how to fix this on windows 10?  

Thank you!

**Comment by iMHLv2** [comment]
Try using one of these profiles:

Win10x64_1AC738FB        - A Profile for Windows 10 x64 from PDB 1AC738FB
Win10x64_DD08DD42        - A Profile for Windows 10 x64 from PDB DD08DD42

**Comment by walkr113** [comment]
Thank you!   That unfortunately didn't fix the netscan PID  '-1' issue but it did fix the issue with ldrmodules and malfind as those were not producing output using just the Win7x64 profile.   Any other ideas?

**Comment by iMHLv2** [comment]
Hmm...are we talking about Win10 or Win7?

**Comment by walkr113** [comment]
Windows 10 Pro

**Comment by iMHLv2** [comment]
Can you paste or upload a txt file with the full netscan output? Are all pids -1 or just some?

**Comment by walkr113** [comment]
Only the 'established', 'closed' and 'syn-sent' connections have -1 as the process id.  Attached is the output with the IP's removed.  
[netscan.xlsx](https://github.com/volatilityfoundation/volatility/files/566948/netscan.xlsx)

**Comment by iMHLv2** [comment]
I agree it looks a little odd. Seems to be limited to the TCP connections. Its entirely possible that they're all old/historical (ESTABLISHED doesn't necessarily mean its established, we could just be picking up the structure in RAM from a while back when it /was/ established). 

Would you happen to be able to extract and share the ntoskrnl.exe and tcpip.sys files from disk from the target system? If not, try dumping them from memory with moddump.

**Comment by walkr113** [comment]
Yes I can extract that for you shortly and I'll send it via email to your email @ memoryanalysis.net.  email will come from Kim

**Comment by iMHLv2** [comment]
This should be fixed as of 014f495c267cf2a3be41080d2cb2a5d62eac6dfd - please let us know if you find otherwise. Thanks!
