### ISSUE TITLE
Windows 10 Mem file not getting scanned..

### ISSUE THREAD

**Issue by Quietiger** [volatilityfoundation/volatility#347]
I am Using Ram capturer 64 bit to capture the RAM and volatility command(in \windows 10 command prompt) for image info is in loop showing 4-5 profile names, and kpcrscan and kdbgscan just stopped.. tried in kali too same issue.

**Comment by iMHLv2** [comment]
Do you know what build of Windows 10? I would recommend skipping imageinfo if you already know its Win 10 and just try pslist with one of these profiles:

Win10x64
Win10x64_1AC738FB
Win10x64_DD08DD42

**Comment by iMHLv2** [comment]
Hi, I'm going to close this out for lack of additional details. Please feel free to reopen if you git pull the latest Volatility and still have issues. I'd also recommend trying a different memory acquisition tool.
