### ISSUE TITLE
Windows server 2012 VMEM + VMSN from ESX not being parsed

### ISSUE THREAD

**Issue by swappage** [volatilityfoundation/volatility#348]
Hello everyone,
i'm having an issue with a vmem that i'm dealing with.

The memory dump is from a windows server 2012 x64 and i've tried different profiles.
appearently volatility cant parse the dump (vmem) done from vmware ESX

volatility version is 2.5 standalone, but i've also tried pulling the latest trunk from github

if i try to run a kdbgscan it returns nothing
if i try to run pslist it returns an empty list

i thought the dump was corrupted
but if i run a psscan it returns the process list, so i'm assuming something is wrong with the data structure.

I'm dubious about a thing tho
when i took the snapshot, it generated 2 files, a .vmem which is as big as the ram and a .vmsn file which is about 100MB or so.
I've read that ESX should produce vmsn files which should be a more complex structure of the memory layout, with the addition of metadata needed by vmware, but in my scenario that file is very small.
can it be that the ESX is separating the informations? the memory run stat is in the vmem and the metadata needed are in the vmss?

in that specific case how am i supposed to deal with this memory dump? can i still parse it with volatility?

for the records, i've tried all the windows 2012 plugins because i wasn't sure of the exact version, but everyone returns me the exact same result.

looking forward for your help
Sincerely
Swappage.

**Comment by swappage** [comment]
For anyone who might be interested i managed to find a workaround that allows me to parse the memory correctly, it was, indeed, an issue with the metadata and the fact that the needed informations are stored into two different files: both the vmem and vmsn.

what i did was to convert the files into a windows core dump using vmss2core directly from vmware

vmss2core -W8 memory.vmsn memory.vmem

it created a memory.dmp that is a consistent crash dump
now volatility 2.5 parses it perfectly

**Comment by iMHLv2** [comment]
Thanks for the update!
