### ISSUE TITLE
macOS Sierra 10.12.1 Profile

### ISSUE THREAD

**Issue by roshanmaskey** [volatilityfoundation/volatility#349]
I have created profile for macOS Sierra 10.12.1 using following commands

dwarfdump -arch x86_64 -i /Library/Developer/KDKs/KDK_10.12.1_16B2657.kdk/System/Library/Kernels/kernel.dSYM > 10.12.1_16B2657.dwarfdump
python tools/mac/convert.py 10.12.1_16B2657.dwarfdump converted-10.12.1_16B2657.dwarfdump
python tools/mac/convert.py converted-10.12.1_16B2657.dwarfdump > 10.12.1_16B2657.vtypes
dsymutil -s -arch x86_64 /Library/Developer/KDKs/KDK_10.12.1_16B2657.kdk/System/Library/Kernels/kernel > 10.12.1_16B2657.symbol.dsymutil
zip Sierra_10_12_1_16B2657.zip 10.12.1_16B2657.symbol.dsymutil 10.12.1_16B2657.vtypes 

The profile is detected but when I use the profile with 10.12.1 memory image, it complains no suitable memory address found.

rrmaskey@rmirz:~$ vol.py --info | grep Mac
Volatility Foundation Volatility Framework 2.5
MacElCapitan_10_11_4_15E65x64   - A Profile for Mac ElCapitan_10.11.4_15E65 x64
MacElCapitan_10_11_6_15G1004x64 - A Profile for Mac ElCapitan_10.11.6_15G1004 x64
MacSierra_10_12_0_16A323x64     - A Profile for Mac Sierra_10.12.0_16A323 x64
MacSierra_10_12_1_16B2657x64    - A Profile for Mac Sierra_10.12.1_16B2657 x64
MachOAddressSpace             - Address space for mach-o files to support atc-ny memory reader

rmaskey@rmirz:~$ vol.py -f /media/rmaskey/FORENSIC_US/sweta_10.12.1.img --profile=MacSierra_10_12_1_16B2657x64 mac_psaux
Volatility Foundation Volatility Framework 2.5
Pid      Name                 Bits             Stack              Length   Argc     Arguments
-------- -------------------- ---------------- ------------------ -------- -------- ---------
No suitable address space mapping found

I have attached the profile.
[Sierra_10.12.1_16B2657.zip](https://github.com/volatilityfoundation/volatility/files/629777/Sierra_10.12.1_16B2657.zip)

**Comment by roshanmaskey** [comment]
rmaskey@rmirz:~$ vol.py -f /media/rmaskey/FORENSIC_US/sweta_10.12.1.img --profile=MacSierra_10_12_1_16B2657x64 mac_psaux
Volatility Foundation Volatility Framework 2.5
Pid      Name                 Bits             Stack              Length   Argc     Arguments
-------- -------------------- ---------------- ------------------ -------- -------- ---------
No suitable address space mapping found

**Comment by OM602** [comment]
I tried the same, also with Kernel.debug instead of kernel from KDK. Same result

**Comment by jbeley** [comment]
It seems that 16B2555 is the latest version available from Apple (I've tried updating many, many times). However the symbols available from Apple are 16B2657, which may the issue.

**Comment by iMHLv2** [comment]
Sorry about that, we need to update the Wiki with some new instructions required for more recent Mac OS versions. In the meantime, we generated the Mac profiles that were missing from the repository: 

https://github.com/volatilityfoundation/profiles/commit/bbe6ea7a91d1022916b16e73e60483356341f088

Thanks!
