### ISSUE TITLE
psscan not working on virtualbox elf dump

### ISSUE THREAD

**Issue by kobi3028** [volatilityfoundation/volatility#350]
Hii,
I new with volatility, so if that noob question sorry..
I try to run psscan plugin on .elf dump and i get no result, in the other hand if i run pslist i get all the linking task, is there a problem with .elf dump to get unliniking task?
OS profile is Win7SP1x86
thanks,

**Comment by iMHLv2** [comment]
Try using the `Win7SP1x86_BBA98F40` profile and let me know if that helps.

**Comment by kobi3028** [comment]
hi thanks for trying to help, 
it didn't work this is the output:

> Volatility Foundation Volatility Framework 2.5 
ERROR   : volatility.debug    : Invalid profile Win7SP1x86_BBA98F40 selected

**Comment by iMHLv2** [comment]
Are you using Volatility from source or one of the standalone executables? If from source, make sure to `git pull` first (or download the current zip from GitHub)...otherwise you won't have that profile.

**Comment by kobi3028** [comment]
It helped thank you, I can always use this profile?

**Comment by iMHLv2** [comment]
Yes!

**Comment by kobi3028** [comment]
Just let you know that I get empty atom table with that OS profile...

**Comment by gleeda** [comment]
Since this looks like it was addressed, I'm going to close this issue.  Please feel free to reopen if needed.
