### ISSUE TITLE
Invalid profile Win10x64 selected

### ISSUE THREAD

**Issue by Dj-jom2x** [volatilityfoundation/volatility#351]
Invalid profile Win10x64 selected xD im on  Win10x64 build 14971

**Comment by iMHLv2** [comment]
Hello, 

Can you check out this branch (https://github.com/volatilityfoundation/volatility/tree/win10-14968) and try again? Use profile `Win10x64_054EC405` which is built from 14968 (hopefully similar enough to work on your 14971).

**Comment by Dj-jom2x** [comment]
: Invalid profile Win10x64_054EC405 selected

**Comment by iMHLv2** [comment]
Are you using the `win10-14968` branch?  Try `vol.py --info` to make sure...you should see `Win10x64_054EC405` in the output under Profiles.

**Comment by Dj-jom2x** [comment]
nope im using Win10x64 build 14971 and i also tried all 4 win 10 profile there :)

**Comment by iMHLv2** [comment]
A few questions for you in that case...the more detail you can provide, the better:

1. What tool/method did you use to acquire memory?
2. What format is the memory dump in (i.e. crash, hibernation, raw, VMware)?
3. How large is the memory dump and how much RAM was installed on the system?
4. Does Volatility's psscan plugin work with the `Win10x64_054EC405` profile?
5. Can you confirm that you see `Win10x64_054EC405` in the output of vol.py --info? 
6. Can you confirm that the memory dump is not all zeros, etc? 

Thanks!

**Comment by iMHLv2** [comment]
Gonna close this out for lack of further details. We know Win10x64 is a valid profile. Feel free to reopen if you're willing to run a few additional tests (the ones above).
