### ISSUE TITLE
Some Memory Dump Links in Wiki are Dead (Malware Cookbook links)

### ISSUE THREAD

**Issue by jaredthecoder** [volatilityfoundation/volatility#355]
All of the Malware Cookbook memory samples in the wiki are dead links, as they point to the now non-existent Google Code SVN system. Do we have new links to these?

**Comment by jaredthecoder** [comment]
Any news on this?

**Comment by iMHLv2** [comment]
The cookbook DVD is at https://www.sendspace.com/pro/dl/p87m18.

**Comment by jaredthecoder** [comment]
Sweet, thanks.
