### ISSUE TITLE
Network connections not supported in Windows 10

### ISSUE THREAD

**Issue by strandjs** [volatilityfoundation/volatility#363]
Currently, many of the network connection modules for Windows 10 are not supported.  Any idea when, if ever they will be?  

netscan kind of works.  Which is awesome.  But, notice that established remote connections of a pid of -1:

C:\Tools>volatility_2.6_win64_standalone.exe -f ./memdump.mem netscan  --profile=Win10x64_10586
Volatility Foundation Volatility Framework 2.6
Offset(P)          Proto    Local Address                  Foreign Address      State            Pid      Owner          Created
0xba88e1de1010     UDPv4    0.0.0.0:0                      *:*                                   3832     chrome.exe     2017-02-01 19:55:41 UTC+0000
0xba88e2213770     UDPv4    127.0.0.1:16576                *:*                                   3020     svchost.exe    2017-02-01 18:05:27 UTC+0000
0xba88e2507370     UDPv4    169.254.183.70:8386            *:*                                   3020     svchost.exe    2017-02-01 18:05:27 UTC+0000
0xba88e27290f0     UDPv4    0.0.0.0:0                      *:*                                   1192     svchost.exe    2017-02-01 20:05:26 UTC+0000
0xba88e27290f0     UDPv6    :::0                           *:*                                   1192     svchost.exe    2017-02-01 20:05:26 UTC+0000
0xba88e2732e20     UDPv4    0.0.0.0:0                      *:*                                   1192     svchost.exe    2017-02-01 20:05:25 UTC+0000
0xba88e27fe740     UDPv4    0.0.0.0:0                      *:*                                   1192     svchost.exe    2017-02-01 20:05:26 UTC+0000
0xba88e27fe740     UDPv6    :::0                           *:*                                   1192     svchost.exe    2017-02-01 20:05:26 UTC+0000
0xba88e2bd2560     UDPv4    169.254.183.70:8386            *:*                                   4        System         2017-01-31 20:43:34 UTC+0000
0xba88e2befda0     UDPv6    ::1:16496                      *:*                                   3020     svchost.exe    2017-02-01 18:05:27 UTC+0000
0xba88e2c10880     UDPv4    127.0.0.1:16576                *:*                                   3020     svchost.exe    2017-02-01 18:05:27 UTC+0000
0xba88e2c39010     UDPv4    0.0.0.0:0                      *:*                                   1192     svchost.exe    2017-02-01 18:05:29 UTC+0000
0xba88e2c39010     UDPv6    :::0                           *:*                                   1192     svchost.exe    2017-02-01 18:05:29 UTC+0000
0xba88e2c4ad00     TCPv4    192.168.244.163:2317           131.253.34.233:443   ESTABLISHED      -1
0xba88e2ce0250     UDPv4    0.0.0.0:0                      *:*                                   1192     svchost.exe    2017-02-01 20:05:26 UTC+0000
0xba88e2d05010     UDPv4    192.168.244.163:53443          *:*                                   4        System         2017-02-01 18:05:29 UTC+0000
0xba88e2de7780     UDPv4    0.0.0.0:0                      *:*                                   3832     chrome.exe     2017-02-01 19:55:41 UTC+0000
0xba88e2fbc010     UDPv6    fe80::b562:351a:c3db:b746:114  *:*                                   3020     svchost.exe    2017-02-01 18:05:27 UTC+0000
0xba88e301f5e0     UDPv4    0.0.0.0:0                      *:*                                   1192     svchost.exe    2017-02-01 18:05:29 UTC+0000
0xba88e305a180     UDPv6    fe80::344d:e53a:a0db:6cf0:113  *:*                                   3020     svchost.exe    2017-02-01 18:05:27 UTC+0000
0xba88e32f99c0     TCPv4    192.168.244.163:2414           136.147.96.35:80     CLOSED           -1
0xba88e3316900     UDPv4    0.0.0.0:0                      *:*                                   1192     svchost.exe    2017-02-01 18:05:29 UTC+0000
0xba88e3316900     UDPv6    :::0                           *:*                                   1192     svchost.exe    2017-02-01 18:05:29 UTC+0000
0xba88e3b94340     UDPv4    169.254.183.70:8386            *:*                                   4        System         2017-01-31 20:43:34 UTC+0000
0xba88e3b9a3b0     UDPv6    fe80::b562:351a:c3db:b746:114  *:*                                   3020     svchost.exe    2017-02-01 18:05:27 UTC+0000
0xba88e3bd32e0     UDPv6    ::1:16496                      *:*                                   3020     svchost.exe    2017-02-01 18:05:27 UTC+0000
0xba88e4a1eec0     UDPv6    fe80::344d:e53a:a0db:6cf0:113  *:*                                   3020     svchost.exe    2017-02-01 18:05:27 UTC+0000
0xba88e4a2e630     UDPv4    0.0.0.0:0                      *:*                                   604      svchost.exe    2017-01-31 20:43:34 UTC+0000
0xba88e4a2e630     UDPv6    :::0                           *:*                                   604      svchost.exe    2017-01-31 20:43:34 UTC+0000
0xba88e4a2eae0     UDPv4    0.0.0.0:0                      *:*                                   604      svchost.exe    2017-01-31 20:43:34 UTC+0000
0xba88e4a32cb0     UDPv4    0.0.0.0:0                      *:*                                   604      svchost.exe    2017-01-31 20:43:34 UTC+0000
0xba88e4a34b60     UDPv4    0.0.0.0:0                      *:*                                   604      svchost.exe    2017-01-31 20:43:34 UTC+0000
0xba88e4a34b60     UDPv6    :::0                           *:*                                   604      svchost.exe    2017-01-31 20:43:34 UTC+0000
0xba88e4a37750     UDPv4    0.0.0.0:0                      *:*                                   604      svchost.exe    2017-01-31 20:43:34 UTC+0000
0xba88e4a5ab70     UDPv4    0.0.0.0:0                      *:*                                   604      svchost.exe    2017-01-31 20:43:34 UTC+0000
0xba88e4a5ab70     UDPv6    :::0                           *:*                                   604      svchost.exe    2017-01-31 20:43:34 UTC+0000
0xba88e4a89ec0     UDPv4    192.168.244.163:53443          *:*                                   3020     svchost.exe    2017-02-01 18:05:27 UTC+0000
0xba88e4b05010     UDPv4    0.0.0.0:0                      *:*                                   1848     svchost.exe    2017-01-31 20:43:35 UTC+0000
0xba88e4b18cf0     UDPv4    0.0.0.0:0                      *:*                                   1848     svchost.exe    2017-01-31 20:43:35 UTC+0000
0xba88e4b18cf0     UDPv6    :::0                           *:*                                   1848     svchost.exe    2017-01-31 20:43:35 UTC+0000
0xba88e4b97010     UDPv4    192.168.244.163:53443          *:*                                   3020     svchost.exe    2017-02-01 18:05:27 UTC+0000
0xba88e4bfb010     UDPv4    0.0.0.0:0                      *:*                                   1132     svchost.exe    2017-01-31 20:45:36 UTC+0000
0xba88e5b10bc0     TCPv4    192.168.244.163:2402           136.147.96.34:80     CLOSED           -1
0xba88e5bbc260     TCPv4    192.168.244.161:2227           13.107.21.200:443    CLOSED           -1
0xba88e5bf3010     UDPv4    0.0.0.0:0                      *:*                                   3832     chrome.exe     2017-02-01 19:55:41 UTC+0000
0xba88e5bf3010     UDPv6    :::0                           *:*                                   3832     chrome.exe     2017-02-01 19:55:41 UTC+0000
0xba88e6a26ec0     UDPv6    fe80::b562:351a:c3db:b746:114  *:*                                   3020     svchost.exe    2017-02-01 14:57:16 UTC+0000
0xba88e6a4a610     UDPv4    0.0.0.0:0                      *:*                                   3832     chrome.exe     2017-02-01 19:55:41 UTC+0000
0xba88e6a4a610     UDPv6    :::0                           *:*                                   3832     chrome.exe     2017-02-01 19:55:41 UTC+0000
0xba88e6b08a60     UDPv4    169.254.183.70:8386            *:*                                   3020     svchost.exe    2017-02-01 18:05:27 UTC+0000
0xba88e6b00d00     TCPv4    192.168.244.163:445            192.168.244.1:50025  ESTABLISHED      -1
0xba88e6b82800     UDPv4    192.168.244.163:53443          *:*                                   4        System         2017-02-01 18:05:29 UTC+0000

Thanks!

John

**Comment by iMHLv2** [comment]
Can you git pull and try again? This should be fixed as of 014f495c267cf2a3be41080d2cb2a5d62eac6dfd
