### ISSUE TITLE
Debian Stretch 4.9 + KASLR: No suitabe address space mapping found

### ISSUE THREAD

**Issue by bneuburg** [volatilityfoundation/volatility#365]
Hi,

I am having some issues using volatility with Debian Stretch RC1 Kernel `4.9.0-1-amd64 #1 SMP Debian 4.9.2-2`.

I could succesfully create a profile and acquire LiME dumps in raw and lime format. Right at the start I got the same error as referenced in #285, second comment  by 2Bellete, but could solve this with pull request #335.

However Volatility states that `No suitable address space mapping` was found. It successfully applies `FileAddressSpace` in both cases and `LimeAddressSpace` with the lime formatted image, but will not find a base address with `LinuxAMD64PagedMemory`.

Reading up on #330 and #344 I confirmed the kernel is relocatable (addresses `/proc/kallsyms` and `System.map` differ) and calculated the "shift" (address in `kallsyms` - the one in `System.map`), which in the case of my first dumps was 0x1ee00000. However I did not manage to properly pass this shift to Volatility.

To figure out if this was the only problem, I added `nokaslr` to the kernel command line of my test machine and took another 2 dumps via LiME. In lime format the image can now be worked on, the raw format image still yields `No base Address Space` for `LinuxAMD64PagedMemory`.

Here is the output when applying the `linux-diff.txt` from #330 for the KASLR booted kernel lime image:
 ```
Volatility Foundation Volatility Framework 2.6
Offset             Name                 Pid             PPid            Uid             Gid    DTB                Start Time
good_dtb: -1
scanning
possible: 181862f8
possible: 21a0e500
new: 1ee00000 | 20a07000
possible: 23708cd9
possible: 24ae8140
possible: 2819f919
suggestions: ffffffff80000000 | 20a0e500 | ffffffffa0a0e500 | None
suggestions: ffffffff7f000000 | 21a0e500 | ffffffffa0a0e500 | None
suggestions: ffffffff7fe00000 | 20c0e500 | ffffffffa0a0e500 | None
suggestions: ffffffff80000000 | 20a0e500 | ffffffffa0a0e500 | None
suggestions: ffffffff7f000000 | 21a0e500 | ffffffffa0a0e500 | None
suggestions: ffffffff7fe00000 | 20c0e500 | ffffffffa0a0e500 | None
No suitable address space mapping found
Tried to open image as:
...
 LimeAddressSpace: lime: need base
 LinuxAMD64PagedMemory: No base Address Space
...
 LimeAddressSpace: Invalid Lime header signature
 LinuxAMD64PagedMemory: Failed valid Address Space check
 AMD64PagedMemory: Failed valid Address Space check
...
```
Note that even though it claims an invalid Lime header signature, debug output state:
`Succeeded instantiating <volatility.plugins.addrspaces.lime.LimeAddressSpace object at 0x7f46d88c9090>`

KASLR raw image:
```
Volatility Foundation Volatility Framework 2.6
Offset             Name                 Pid             PPid            Uid             Gid    DTB                Start Time
good_dtb: -1
scanning
possible: 55f4519
possible: f88e119
possible: 219ad100
possible: 3b5b0df0
suggestions: ffffffff80000000 | 1c0e500 | ffffffff81c0e500 | None
suggestions: ffffffff7f000000 | 2c0e500 | ffffffff81c0e500 | None
suggestions: ffffffff7fe00000 | 1e0e500 | ffffffff81c0e500 | None
suggestions: ffffffff80000000 | 1c0e500 | ffffffff81c0e500 | None
suggestions: ffffffff7f000000 | 2c0e500 | ffffffff81c0e500 | None
suggestions: ffffffff7fe00000 | 1e0e500 | ffffffff81c0e500 | None
No suitable address space mapping found
Tried to open image as:
...
 LimeAddressSpace: lime: need base
 LinuxAMD64PagedMemory: No base Address Space
...
 LimeAddressSpace: Invalid Lime header signature
 LinuxAMD64PagedMemory: Failed valid Address Space check
 AMD64PagedMemory: Failed valid Address Space check
...
```

nokaslr lime image:
```
Offset             Name                 Pid             PPid            Uid             Gid    DTB                Start Time
good_dtb: 1c07000
suggestions: ffffffff80000000 | 1c0e500 | ffffffff81c0e500 | 29418752
good_dtb: 1c07000
suggestions: ffffffff80000000 | 1c0e500 | ffffffff81c0e500 | 29418752
```
Plus the actual process list.

nokaslr raw image:
```
Offset             Name                 Pid             PPid            Uid             Gid    DTB                Start Time
good_dtb: -1
scanning
possible: 1bad100
possible: 269e1d00
possible: 2bb61900
possible: 3b5b0df0
suggestions: ffffffff80000000 | 1c0e500 | ffffffff81c0e500 | None
suggestions: ffffffff7f000000 | 2c0e500 | ffffffff81c0e500 | None
suggestions: ffffffff7fe00000 | 1e0e500 | ffffffff81c0e500 | None
suggestions: ffffffff80000000 | 1c0e500 | ffffffff81c0e500 | None
suggestions: ffffffff7f000000 | 2c0e500 | ffffffff81c0e500 | None
suggestions: ffffffff7fe00000 | 1e0e500 | ffffffff81c0e500 | None
No suitable address space mapping found
Tried to open image as:
...
 LimeAddressSpace: lime: need base
 LinuxAMD64PagedMemory: No base Address Space
...
 LimeAddressSpace: Invalid Lime header signature
 LinuxAMD64PagedMemory: Failed valid Address Space check
 AMD64PagedMemory: Failed valid Address Space check
...
```

On a side note: debug output also mentioned:
`DEBUG   : volatility.debug    : Requested symbol do_fork not found in module kernel`
which indeed is true since this symbol has been renamed to `_do_fork`

I'd be glad to assist in debugging this further.
Could you provide a human readable step by step guide on how KASLR shifts are determined (e.g. Step 1: Scan for `swapper`....)

**Comment by bneuburg** [comment]
As a follow up: I installed libvmi with debug enabled since they also dealt with KASLR (libvmi/libvmi#448) and successfully communicated to a VM with KASLR enabled and could retrieve e.g. the process list via `vmi-process-list`. 

The debug output got me the following information:

``` $ grep -i dtb /tmp/vmi.out | uniq
--PTLookup: dtb = 0x000000003b731000
```

and
``` $ grep -i kaslr /tmp/vmi.out 
**calculated KASLR offset: 0x2d000000
```

So I created a lime and raw image in that VM.
I tried to pass these values with `--dtb 0x3b731000` respectively `--shift 0x2d000000`  and both options but that didn't yield success. Any suggestions on how to proceed?

Here is the dtb finder debug output for the lime image:
```
good_dtb: -1
scanning
possible: 2bc0e500
new: 2a000000 | 2bc07000
possible: 3fc121f0
suggestions: ffffffff80000000 | 2bc0e500 | ffffffffabc0e500 | None
suggestions: ffffffff7f000000 | 2cc0e500 | ffffffffabc0e500 | None
suggestions: ffffffff7fe00000 | 2be0e500 | ffffffffabc0e500 | None
suggestions: ffffffff80000000 | 2bc0e500 | ffffffffabc0e500 | None
suggestions: ffffffff7f000000 | 2cc0e500 | ffffffffabc0e500 | None
suggestions: ffffffff7fe00000 | 2be0e500 | ffffffffabc0e500 | None
```

**Comment by bneuburg** [comment]
Another follow up:

# LiME format discrepancy
I also tested LiME acquiration with padded format which works fine for ```nokaslr``` systems but leads to the same problems with KASLR enabled as the lime formatted dumps. Maybe raw format for LiME doesn't work anymore for 4.8+ kernels.

# KASLR Address Space Validation, vtop problem
I also dug a little bit deeper into the adress space validation issue for KASLR dumps (for this I exclusively worked with lime formatted images).

As mentioned above Volatility successfully instantiates `FileAdddressSpace` and `LimeAddressSpace`, then finds a DTB for `LinuxAMD64PagedMemory` but fails the validation.
I added some debug statements to  `volatility/plugins/addrspaces/amd64.py` in order to find out at which step of the Virtual-to-Physical translation fails.

Everything goes according to plan for 

- Page Map Level 4 entry, 
- Page Directory Pointer Table entry

but for the Page Directory entry I get a physical address which returns the value 0 (the index calculated from the virtual address points to an entry that contains 0x0000 0000 0000 0000.

I used `addrspace().self.translate` to retrieve the physical offsets for PML4E and PDPTE and used `dd` to extract 4096 bytes (512 entries x 8 bytes length) starting at these offsets. When running this through `xxd -c 8` both of these outputs really look like address directories/tables. Of course I am not a MMU and only compared the `nokaslr` versions of these structures but besides varying offsets they look quite similar.

So I am stuck here, since `phys` in the following snippet from the Linux overlay will return 0.
```
# volatility/plugins/overlays/linux/linux.py#L2386
# init_task_addr is the static virtual address for 
#  the symbol init_task from System.map of the chosen profile
            phys  = self.obj_vm.vtop(init_task_addr)
            check = init_task_addr - shift
```

And even if `phys` returns a useful address the check after will probably fail because with KASLR on Linux >= 4.8 the physical starting address for kernel text will be randomized separately from the random shift for the virtual addresses in System.map if I understand [Kees Cook](https://outflux.net/blog/archives/2016/10/04/security-things-in-linux-v4-8/) correctly.

# Some questions:
1. Are there any chances to eventually deal with KASLR? 
1. Are there any flaws in my thinking? 
1. Could this be a LiME acquisiton problem (don't think so because even though the row for the page table index is all zeroes there are multiple lines in that 4096 dump that look like valid PTEs)?

**Comment by bneuburg** [comment]
Just for upstream information: This topic itched me a lot and after reading up a lot on memory mangement and KASLR I created a plugin that will determine (works 80% of the time right now) all values required for succesful processing with Volatility. Next week I will do a longer write up on what I did.

**Comment by bneuburg** [comment]
As promised: Created pull request of kaslr_shift for Linux.

**Comment by gleeda** [comment]
@atcuno could you please have a look at this and see if we want to merge it :-)

**Comment by bneuburg** [comment]
Just a quick follow up: In my third post in this issue I posed the following question

> Could this be a LiME acquisiton problem (don't think so because even though the row for the page table index is all zeroes there are multiple lines in that 4096 dump that look like valid PTEs)?

and thanks to pagabuc_ from the Volatility IRC channel I found the answer: 

> FYI: if you're taking a dump with lime from a vm you have to tweak the (non documented) "timeout" parameter, or set to it 0, otherwise some slow memory region are not dumped at all

I could reproduce by rebooting and LiMEing a Debian Stretch VM until my `linux_kaslr_shift` plugin couldn't determine the shifts, then `rmmod`ed LiME and `modprobe`d it again, this time with the `timeout=0` parameter, after that `linux_kaslr_shift` worked like a charm and Volatility could succesfully work on the dump.

Maybe that information could be added on the Linux wiki page, I think pagabuc_ and me are not the only ones encountering this issue.
