### ISSUE TITLE
Developers guide for writing plugins

### ISSUE THREAD

**Issue by Warchant** [volatilityfoundation/volatility#368]
Is there any guide for writing plugins for volatility? 

I couldn't find any, except [this](https://code.google.com/archive/p/volatility/wikis/PluginWritersGuide.wiki), but seems files with guide are missing.

Thank you for help in advance!

**Comment by iMHLv2** [comment]
Thomas Chopitea wrote a good tutorial here: 

http://tomchop.me/2016/11/21/tutorial-volatility-plugins-malware-analysis/

Aside from that, The Art of Memory Forensics book is useful for learning the basic framework. The best resource is really just using an existing plugin as an example and modifying it for your use case.
