### ISSUE TITLE
Windows 12 R2 profile issue

### ISSUE THREAD

**Issue by malwareandme** [volatilityfoundation/volatility#384]
Hi,
Please can one of the gurus advice me on what profile to use. I have tried all the profiles suggested on the site.  I tried with memory captured with Dumpit and with ramcapturer. Same issue. I get the same with 64bit  Windows 10 too.

See below
Name=Microsoft Windows Server 2012 R2 Standard
Version=6.3.9600

C:\tools\volatility26\volatility_2.6_win64_standalone>volatility_2.6_win64_standalone.exe -f c:\analysis\4353.raw  --profile Win2012R2x64 pslist

 Win10AMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 VMWareMetaAddressSpace: VMware metadata file is not available
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VirtualBoxCoreDumpElf64: ELF Header signature invalid
 VMWareAddressSpace: Invalid VMware signature: 0x0
 QemuCoreDumpElf: ELF Header signature invalid
 WindowsCrashDumpSpace32: Header signature invalid
 Win10AMD64PagedMemory: Incompatible profile Win2012R2x64_18340 selected
 WindowsAMD64PagedMemory: No valid DTB found
 LinuxAMD64PagedMemory: Incompatible profile Win2012R2x64_18340 selected
 AMD64PagedMemory: No valid DTB found
 IA32PagedMemoryPae: Incompatible profile Win2012R2x64_18340 selected
 IA32PagedMemory: Incompatible profile Win2012R2x64_18340 selected
 OSXPmemELF: ELF Header signature invalid
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: No valid DTB found

C:\tools\volatility26\volatility_2.6_win64_standalone>volatility_2.6_win64_standalone.exe -f c:\analysis\4353.raw  --profile Win2012R2x64 pslist

Volatility Foundation Volatility Framework 2.6
No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 QemuCoreDumpElf: No base Address Space
 VMWareAddressSpace: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 Win10AMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 VMWareMetaAddressSpace: VMware metadata file is not available
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VirtualBoxCoreDumpElf64: ELF Header signature invalid
 QemuCoreDumpElf: ELF Header signature invalid
 VMWareAddressSpace: Invalid VMware signature: 0x0
 WindowsCrashDumpSpace32: Header signature invalid
 Win10AMD64PagedMemory: Incompatible profile Win2012R2x64 selected
 WindowsAMD64PagedMemory: No valid DTB found
 LinuxAMD64PagedMemory: Incompatible profile Win2012R2x64 selected
 AMD64PagedMemory: No valid DTB found
 IA32PagedMemoryPae: Incompatible profile Win2012R2x64 selected
 IA32PagedMemory: Incompatible profile Win2012R2x64 selected
 OSXPmemELF: ELF Header signature invalid
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: No valid DTB found

**Comment by npetroni** [comment]
I tested the latest Volatility with 2012R2 x64. I tested kernels 6.3.9600.18589 (latest, as far as I know) and 6.3.9600.18505. Both `Win2012R2x64` and `Win2012R2x64_18340` work for `pslist`.

Can you provide the specific kernel version for your image, or share the image?
