### ISSUE TITLE
Error while getting Threads data in JSON Format

### ISSUE THREAD

**Issue by AnkitKundariya** [volatilityfoundation/volatility#392]
> > python vol.py --profile=Linuxbookx64 -f dump/linux/linux-sample-1.bin linux_threads --output=json
> 
> Volatility Foundation Volatility Framework 2.6
> Traceback (most recent call last):
>   File "vol.py", line 192, in <module>
>     main()
>   File "vol.py", line 183, in main
>     command.execute()
>   File "/home/ram/Ankit/Volatility/volatility-master/volatility/plugins/linux/common.py", line 64, in execute
>     commands.Command.execute(self, *args, **kwargs)
>   File "/home/ram/Ankit/Volatility/volatility-master/volatility/commands.py", line 147, in execute
>     func(outfd, data)
>   File "/home/ram/Ankit/Volatility/volatility-master/volatility/commands.py", line 294, in render_json
>     self._render(outfd, JSONRenderer(), data)
>   File "/home/ram/Ankit/Volatility/volatility-master/volatility/commands.py", line 276, in _render
>     renderer.render(outfd, output)
>   File "/home/ram/Ankit/Volatility/volatility-master/volatility/renderers/html.py", line 47, in render
>     if data.max_depth() > 1:
>   File "/home/ram/Ankit/Volatility/volatility-master/volatility/renderers/__init__.py", line 228, in max_depth
>     return self.visit(None, lambda n, a: max(a, self.path_depth(n)), )
>   File "/home/ram/Ankit/Volatility/volatility-master/volatility/renderers/__init__.py", line 248, in visit
>     self.populate()
>   File "/home/ram/Ankit/Volatility/volatility-master/volatility/renderers/__init__.py", line 149, in populate
>     for (level, item) in self._generator:
>   File "/home/ram/Ankit/Volatility/volatility-master/volatility/plugins/linux/threads.py", line 51, in generator
>     addr_limit = self.get_addr_limit(thread)
>   File "/home/ram/Ankit/Volatility/volatility-master/volatility/plugins/linux/threads.py", line 74, in get_addr_limit
>     return addr_space.read_long_phys(offset)
> AttributeError: 'LinuxAMD64PagedMemory' object has no attribute 'read_long_phys'

@gleeda

**Comment by bneuburg** [comment]
@gleeda: It seems that in case of LinuxAMD64PagedMemory `read_long_long_phys`  needs to be called in `get_addr_limit`

**Comment by AnkitKundariya** [comment]
dear  @gleeda  what's the solution for this problem what action i have to do,to solve this problem.

**Comment by bneuburg** [comment]
@AnkitKundariya modify volatility/plugins/linux/threads.py according to [this](https://github.com/volatilityfoundation/volatility/pull/394/files), the json output should just work.

**Comment by AnkitKundariya** [comment]
thank you dear @bneuburg now it's work fine and gives output in JSON formate.

**Comment by bneuburg** [comment]
@AnkitKundariya could you please reopen this issue since it is not yet fixed in master.

**Comment by gleeda** [comment]
Closing the issue, since the solution was merged to master.
