### ISSUE TITLE
Ubuntu 16.04.2 LTS profile issue

### ISSUE THREAD

**Issue by gcmoreira** [volatilityfoundation/volatility#395]
Hey

Apparently, Volatility struggles to get the initial _DTB_ address. 
I'm using the latest Volatility git version.
```
$ git pull origin master
From https://github.com/volatilityfoundation/volatility
 * branch            master     -> FETCH_HEAD
Already up-to-date.
```
```
$ git rev-parse HEAD
1ace3c4e0e1b85e97f5357a3b1f35b198868ac75
```
Also I'm using a custom profile created as you suggest here
[https://github.com/volatilityfoundation/volatility/wiki/Linux#creating-a-new-profile](url) 
I've attached the profile [Ubuntu16042custom.zip](https://github.com/volatilityfoundation/volatility/files/892303/Ubuntu16042custom.zip)
The VM kernel is **`Linux ubuntu 4.8.0-45-generic #48~16.04.1-Ubuntu.`**
And the memory dump was generated using _Virtualbox debugvm_ feature.

I've tried many ways to get it fixed having some partial success but I couldn't get it working. 
I've found that any of the shifts are working with this kernel version but I've found that a _shift_ of **0xffffffff74200000** works and it finds the **swapper/0**. **VolatilityDTB** passes with that value however when it comes to validate it, **VolatilityLinuxIntelValidAS** fails getting the _DTB_ (Yes, I've updated that shift in both classes ;) ).

The Volatility output is:
```
$ python /usr/local/bin/vol.py --profile=LinuxUbuntu16042customx64 -f memory.dmp linux_pslist

Volatility Foundation Volatility Framework 2.6
Offset             Name                 Pid             PPid            Uid             Gid    DTB                Start Time
------------------ -------------------- --------------- --------------- --------------- ------ ------------------ ----------
No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareAddressSpace: No base Address Space
 QemuCoreDumpElf: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 Win10AMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: PO_MEMORY_IMAGE is not available in profile
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 VMWareMetaAddressSpace: VMware metadata file is not available
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: PO_MEMORY_IMAGE is not available in profile
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 VMWareMetaAddressSpace: VMware metadata file is not available
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VirtualBoxCoreDumpElf64: ELF Header signature invalid
 VMWareAddressSpace: Invalid VMware signature: 0xf000ff53
 QemuCoreDumpElf: ELF Header signature invalid
 WindowsCrashDumpSpace32: Header signature invalid
 Win10AMD64PagedMemory: Incompatible profile LinuxUbuntu16042customx64 selected
 WindowsAMD64PagedMemory: Incompatible profile LinuxUbuntu16042customx64 selected
 LinuxAMD64PagedMemory: Failed valid Address Space check
 AMD64PagedMemory: Failed valid Address Space check
 IA32PagedMemoryPae: Incompatible profile LinuxUbuntu16042customx64 selected
 IA32PagedMemory: Incompatible profile LinuxUbuntu16042customx64 selected
 OSXPmemELF: ELF Header signature invalid
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: Failed valid Address Space check
```

Full debug output attached [vol.txt](https://github.com/volatilityfoundation/volatility/files/892377/vol.txt)

Cheers,
Gus

**Comment by bneuburg** [comment]
@gcmoreira you could try to use the `linux_kaslr_shift` plugin from volatilityfoundation/volatility#385 in order to determine DTB candidates. As stated in the accompanying issue volatilityfoundation/volatility#365 starting with kernel 4.8 there can be two different shifts to consider, a physical one and a virtual one (unless your `/proc/cmdline` contains `nokaslr`) and the master branch is not yet equipped to deal with both of them.

**Comment by gcmoreira** [comment]
Thanks for your prompt reply.
It didn't work on the first try. I think that the pull request author @bneuburg forgot to include in the fix one file. Without this fix the `linux_kaslr_shift` plugin doesn't work failing with "EXCEPTION: Parameter PHYSICALSHIFT is not configured - try setting it on the command line (-h for help)"

```diff
diff --git a/volatility/plugins/linux/common.py b/volatility/plugins/linux/common.py
index 0c1f7d9..3d49b3c 100644
--- a/volatility/plugins/linux/common.py
+++ b/volatility/plugins/linux/common.py
@@ -54,6 +54,10 @@ class AbstractLinuxCommand(commands.Command):
         self.known_fops  = {}
         commands.Command.__init__(self, *args, **kwargs)
 
+    @staticmethod
+    def register_options(config):
+        config.add_option("PHYSICALSHIFT", type = 'int', default = 0, help = "KASLR physicalshift address")
+
     @property
     def profile(self):
         if self.addr_space:

```
After applying the latter I could get the virtual and physical shift and then it worked like a charm.

Thanks,
Gus

**Comment by bneuburg** [comment]
Thank you for testing the plugin. Indeed I forgot to include the changes to `linux/common.py` in my pull request.

Just out of curiosity: Did the plugin only find one DTB/phys shift/vshift combination or did it return more?

**Comment by gcmoreira** [comment]
Thank you mate. Yes, luckily in my tests it only returned one row ;)

Btw, just one detail, the "--shift" parameter is being used from the
plugins/mac/common.py that was why it wasn't needed to add that to the
linux one in your pull request. I don't know if you could override that but
I think it would be needed to adjust the parameter description, overriding
or making it more general.
Cheers,
Gus

On Wed., 5 Apr. 2017, 6:36 pm bneuburg, <notifications@github.com> wrote:

Thank you for testing the plugin. Indeed I forgot to include the changes to
linux/common.py in my pull request.

Just out of curiosity: Did the plugin only find one DTB/phys shift/vshift
combination or did it return more?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/volatilityfoundation/volatility/issues/395#issuecomment-291792828>,
or mute the thread

**Comment by atamlir** [comment]
I tried to take the changes and ran the command 
python vol.py -f /home/ubuntu.lime --profile==LinuxUbuntu16x64 linux_kaslr_shit 

I get that

ERROR: Volatility.debug     : You must specify something to do (try -h)

Any idea ?

**Comment by atcuno** [comment]
Are you able to process the sample with the latest Volatility? I put in changes to support KASLR versions. Please perform a git pull and let me know if you still have processing issues.

**Comment by gcmoreira** [comment]
Sorry for the delay. 
I've just tested it and it isn't working anymore.  The **linux_aslr_shif**t plugin returns "No suitable address space mapping found". But using the values obtained from the previous **linux_kaslr_shift** code with the **--physical_shift** and **--virtual_shift** arguments and executing the **linux_pslist** plugin doesn't work either.
I've double checked it with the old code using the same profile and memory dump and it worked. 
Sorry that I cannot give you more details than these results, unfortunately I've not had time to check the code in depth.

**Comment by openfoamtutorials** [comment]
Just my experience, I did not have this issue after building the custom profile. Can you share your build process? The link you posted no longer exists.

**Comment by letitbezh** [comment]
can you solve this question? I am in troubled!

**Comment by letitbezh** [comment]
> 
> 
> Just my experience, I did not have this issue after building the custom profile. Can you share your build process? The link you posted no longer exists.

can you  share your profile. I have Experienced the same problem

**Comment by atcuno** [comment]
What issue are you having @letitbezh ?
