### ISSUE TITLE
mac_get_profile dosen't return json or greptext data

### ISSUE THREAD

**Issue by AnkitKundariya** [volatilityfoundation/volatility#397]
`python vol.py mac_get_profile -f dump/Mac/mac-sample-1.bin --output=json`

```

ram@ram-H81M-S:~/Ankit/django3/webtool/volatility$ python vol.py mac_get_profile -f dump/Mac/mac-sample-1.bin --output=json
Volatility Foundation Volatility Framework 2.6
ERROR   : volatility.debug    : Rendering using the unified output format has not been implemented for this plugin.

```
@bneuburg  @gleeda

**Comment by bneuburg** [comment]
I don't have a Mac image available but still tried to correctly implement unified_output to the `mac_get_profile` plugin. Can you check if bneuburg/volatility@35984c0dddbd2e8e660fd156b1b6b45bf4d83ff6 (branch issue-397 in my fork) works for you? If it does I'll file a pull request.

**Comment by AnkitKundariya** [comment]
well done @bneuburg it's work perfectly
_thank you_
