### ISSUE TITLE
Vaddump Flink and Blink

### ISSUE THREAD

**Issue by hakija** [volatilityfoundation/volatility#399]
Hi, not an issue but rather a question....in previous version of Volatiltiy (I tested on 2.0) while doing vaddump output would contain Flink and Blink addresses as shown below:

VAD node @821f1be0 Start 7ffdd000 End 7ffddfff Tag Vadl
Flags: MemCommit, NoChange, PrivateMemory
Commit Charge: 1 Protection: 4
ControlArea @821bceb8 Segment 81344bf0
Dereference list: Flink 81344bf0, Blink 0a060006
NumberOfSectionReferences: 3999626821 NumberOfPfnReferences:           2
NumberOfMappedViews:                1 NumberOfUserReferences:          0
WaitingForDeletion Event:  8204b501
Flags: CollidedFlush, DebugSymbolsLoaded, DeleteOnClose, File, GlobalMemory, Networked, PhysicalMemory
FileObject: none
First prototype PTE: 821bceb8 Last contiguous PTE: 82036a80
Flags2: LongVad, OneSecured
File offset: 00000000

With the newer version that part and some other parts are now gone and the same look as below:
VAD node @ 0x821f1be0 Start 0x7ffdd000 End 0x7ffddfff Tag Vadl
Flags: CommitCharge: 1, MemCommit: 1, NoChange: 1, PrivateMemory: 1, Protection: 4
Protection: PAGE_READWRITE
First prototype PTE: 821bceb8 Last contiguous PTE: 82036a80
Flags2: LongVad: 1, OneSecured: 1

The outputs above are form the same image created using Volatility 2.0 and 2.6

Thnx!

**Comment by iMHLv2** [comment]
We stopped printing the Flink and Blink members because they don't lend any significance to analysis. Feel free to post non-issues on the mailing list also (https://lists.volatilityfoundation.org/mailman/listinfo/vol-users).
