### ISSUE TITLE
What are the supported memory acquisition tools?

### ISSUE THREAD

**Issue by jersten** [volatilityfoundation/volatility#400]
I spent a few hours using `WinPmem` (using 2.1) only to find out that it does not work with 2.6 (does it work with any version?). I tried `--mode PhysicalMemory` and `--format raw`; `pslist` and `cmdscan`, `imageinfo` does not work on the dumps. Eventually, `dumpit.exe` worked. So, which memory acquisition methods are supported?

**Comment by iMHLv2** [comment]
Volatility doesn't support or not support acquisition tools per se. Volatility supports valid/non-corrupt memory dumps in raw, crash, hibernation, vmware, virtualbox (etc) file formats. IIRC with `WinPmem`, even using `--format raw` will output an AFF4 file, so you would then need to extract the memory stream from the AFF4 archive. You got extremely lucky if dumpit.exe worked. We recommend Volexity Surge Collect Pro and GMG KnTTools to our training classes, as they are the only two that are reliable enough in the field, especially when capturing memory from Win7 or later systems, and systems with greater than 4GB RAM.
