### ISSUE TITLE
problem on win7x64sp1 16g memory

### ISSUE THREAD

**Issue by MrJeffyw** [volatilityfoundation/volatility#402]
When i use volatility to analysis 16g memory of win7x64sp1, it can't get the right result . It don't support 16g memory , how can i analysis  16g memory?

**Comment by gleeda** [comment]
We've had people analyze memory from machines of 100GB or more with no issues.  What steps have you taken so far?  What do you mean you didn't get the right result?  Please include a commandline usage so we can see what you tried to do, and any error messages you received.

In case you haven't tried yet, run the `kdbgscan` plugin with the `--force` flag to see if you get any valid output (a profile with processes and modules).
