### ISSUE TITLE
Raspberry / Raspbian

### ISSUE THREAD

**Issue by MatthiasZuber** [volatilityfoundation/volatility#408]
Hello, I have the problem that i can't create a profile for my Raspberry PI (Raspbian). The Problem is, that I haven't the System.map file. Have you any ideas?

**Comment by bneuburg** [comment]
I am not aware of a way to recreate the System.map from a binary kernel, however it is possible the System.maps [here](https://github.com/RPi-Distro/firmware/tree/debian/extra) are what you are looking for.

**Comment by cpuu** [comment]
I'm in the same issue.

Raspberry pi 2 with 2017-04-10-raspbian-jessie.img

pi@raspberrypi:~/lmg $ uname -a
Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux

Requirements
- $ sudo apt-get install raspberrypi-kernel-headers     (* for linux-headers-4.4.50-v7+ )
- $ wget http://cdn-fastly.deb.debian.org/debian/pool/main/d/dwarfutils/dwarfdump_20120410-2_armhf.deb
$ sudo dpkg -i dwarfdump_20120410-2_armhf.deb
$ cp /usr/bin/dwarfdump ./dwarfdump-$(uname -m)

and I download System.maps which is given [here](https://github.com/RPi-Distro/firmware/tree/debian/extra) as @bneuburg said.

unfortunately, it does not work.
`ERROR   : volatility.debug    : Invalid profile Linuxraspberrypi-2017-05-03_06_03_16-profilex7l selected`
