### ISSUE TITLE
Any plan to support newer hibernation file versions?

### ISSUE THREAD

**Issue by rolfrennemo** [volatilityfoundation/volatility#410]
Newer than the now supported:
Hibernation file (from Windows 7 and earlier)

**Comment by gleeda** [comment]
yes, there is.  refs issue #25

**Comment by rolfrennemo** [comment]
Great!

I came across a paper on newer formats. See link enclosed.

Rolf

**Comment by gleeda** [comment]
Cool!  We also accept patches :-)
