### ISSUE TITLE
Body format support request

### ISSUE THREAD

**Issue by SpeedyGonzales1234** [volatilityfoundation/volatility#411]
You know what? Body format support would be very handy here...
Any plan on doing so in a near future?

**Comment by gleeda** [comment]
For which plugin are you requesting this?  Some plugins already support body file format

**Comment by Signus** [comment]
What body formats are you looking for? Most plugins at this point support the following formats:

- Dot
- Greppable Text
- HTML
- JSON
- SQLite
- Text
- XLSX

**Comment by gleeda** [comment]
Closing due to lack of information.  Please reopen if you decide to fill in details.
