### ISSUE TITLE
Why there is no output for the volatility when I get a big memory?

### ISSUE THREAD

**Issue by malforen** [volatilityfoundation/volatility#424]
Hello,

    I have a strange issue.  

   When I use the volatility to analyze a small linux memory (such as the size is 1GB or 2GB), it works and has the right outputs. However, when I use the same way to analyze a big linux memory (such as the size is 32GB ),  it  has the right outputs for some commands but has no output for some other commands. It shows as follows.

root@kali:/usr/share/volatility# python vol.py --profile=Linuxcentos2_6_32-504_8_1_e16x64 -f /mnt/hgfs/mem/memdmp.lime linux_pslist
Volatility Foundation Volatility Framework 2.5
Offset             Name                 Pid             Uid             Gid    DTB                Start Time
------------------ -------------------- --------------- --------------- ------ ------------------ ----------
0xffff880874b73500                      0               -               -      ------------------ 2017-05-04 03:38:06 UTC+0000
root@kali:/usr/share/volatility# 

root@kali:/usr/share/volatility# python vol.py --profile=Linuxcentos2_6_32-504_8_1_e16x64 -f /mnt/hgfs/mem/memdmp.lime linux_netstat
Volatility Foundation Volatility Framework 2.5
root@kali:/usr/share/volatility# 

root@kali:/usr/share/volatility# python vol.py --profile=Linuxcentos2_6_32-504_8_1_e16x64 -f /mnt/hgfs/mem/memdmp.lime linux_check_idtVolatility Foundation Volatility Framework 2.5
             Index Address            Symbol                        
------------------ ------------------ ------------------------------
               0x0 0xffffffff8100bf20 divide_error                  
               0x1 0xffffffff8152d220 debug                         
               0x2 0xffffffff8152d600 nmi                           
               0x3 0xffffffff8152d260 int3                          
               0x4 0xffffffff8100bf40 overflow                      
               0x5 0xffffffff8100bf60 bounds                        
               0x6 0xffffffff8100bf80 invalid_op                    
               0x7 0xffffffff8100bfa0 device_not_available          
               0x8 0xffffffff8100bfc0 double_fault                  
               0x9 0xffffffff8100bff0 coprocessor_segment_overrun   
               0xa 0xffffffff8100c010 invalid_TSS                   
               0xb 0xffffffff8100c040 segment_not_present           
               0xc 0xffffffff8152d2a0 stack_segment                 
               0xd 0xffffffff8152d340 general_protection            
               0xe 0xffffffff8152d370 page_fault                    
               0xf 0xffffffff8100c070 spurious_interrupt_bug        
              0x10 0xffffffff8100c090 coprocessor_error             
              0x11 0xffffffff8100c0b0 alignment_check               
              0x12 0xffffffff8152d3a0 machine_check                 
              0x13 0xffffffff8100c0e0 simd_coprocessor_error        
              0x80 0xffffffff81054140 ia32_syscall                  
root@kali:/usr/share/volatility# 

      I hope I can get an answer here.

Thank you!

**Comment by pagabuc** [comment]
Can you share the profile and the memory dump?

**Comment by gleeda** [comment]
@malforen did you ever figure out what the issue was?  Are you able to share the memory sample/profile if not?
