### ISSUE TITLE
linux_procdump Command dosen't gives output and Dumps a process's executable image to disk

### ISSUE THREAD

**Issue by AnkitKundariya** [volatilityfoundation/volatility#425]
i try to perform flowing action on my dump
`python vol.py linux_procdump -f dump/linux-sample-1.bin --profile=Linuxbookx64 --pid=15  --dump-dir = ../
`

it's return nothing i try it on different Linux sample but it's not work 

here I'm attaching Screen shot of output  

![image](https://cloud.githubusercontent.com/assets/24821294/26234696/27e57452-3c84-11e7-9c3d-8327cb7fd3f4.png)

if I'm change in command and add one more thing `--output=greptext` it gives me

`python vol.py linux_procdump -f dump/linux-sample-1.bin --profile=Linuxbookx64 --pid=15  --dump-dir = ../ --output=greptext`

![image](https://cloud.githubusercontent.com/assets/24821294/26234834/1906d72c-3c85-11e7-9c37-f9a560d7c50e.png)

 **In both Command i didn't get my process in specified destination folder**

**Comment by msaw** [comment]
Hello,
try to install distorm3
`$ pip install distorm3`

**Comment by AnkitKundariya** [comment]
i did it but still it's not work @msaw
