### ISSUE TITLE
Broken link in wiki

### ISSUE THREAD

**Issue by zappeee** [volatilityfoundation/volatility#427]
The link to http://blogs.mcafee.com/mcafee-labs/zeroaccess-misleads-memory-file-link ZeroAccess Misleads Memory-File Link in https://github.com/volatilityfoundation/volatility/wiki/Command-Reference-Mal#ldrmodules is broken.

**Comment by gleeda** [comment]
Did you manage to find the new link?

**Comment by zappeee** [comment]
I'm afraid it seems to be removed by McAfee

**Comment by gleeda** [comment]
Ah, yes, I think you're right.  We'll probably just leave it like that for historical reasons just in case then.
