### ISSUE TITLE
Ram Capturer windows 7 no suitable address space mapping found

### ISSUE THREAD

**Issue by mikerary** [volatilityfoundation/volatility#428]
I did a Ram Capturer image of a windows 7 sp 1 pc.  Trying to run imageinfo and pslist i get the same no suitable address. I have tried several profiles and also the python and standalone version of Volatility

**Comment by Signus** [comment]
Three questions:

1. What is the architecture of your Windows 7 SP1 system (32/64?
2. How much RAM is in the system (or was used during the capture)?
3. What utility are you utilizing for dumping the memory of your system(s)?

**Comment by mikerary** [comment]
It is 64. 8gb of ram using belkasoft RAM Capturer


The Network Essentials
Mike Rary
Director of Technology
The Network Essentials
310 Arlington Ave
Suite 333
Charlotte, NC 28203
Email: mike@tneus.com
Tel: 704 206 8909

**Comment by Signus** [comment]
Ensure you have the latest version of both RamCapturer and double check the build you have of Volatility. I tested 2.6 on a Windows 7 SP1 x64 machine with no issues in detection.

If that still does not work, please supply output using the debug (`-d` or `--debug`) flag.

**Comment by openfoamtutorials** [comment]
Try using DumpIt (from Comae). It fixed my error, though I was using Windows 10; but it should still work for Windows 7.

**Comment by gleeda** [comment]
I'm going to close this for now, since I think it was originally due to acquisition.  Please reopen if you still have an issue.
