### ISSUE TITLE
volatility strings result zero hits when using 10 character offset as stringfile.

### ISSUE THREAD

**Issue by jtingkir** [volatilityfoundation/volatility#432]
I was using volatility with strings I created using:
`strings -o staging_http.raw | grep -i stdapi > strings_stdapi.txt
`
it resulted in 10 offset before string: 
> 1750233540 stdapi
> 2267001720 ext_server_stdapi.x86.dll
> 3341407340 stdapi_net_config_get_routes
> 3372330020 stdapi_net_socket_tcp_shutdown
> 3372330060 stdapi_ui_enable_mouse
> 3372330110 stdapi_ui_enable_keyboard
> 3372330144 stdapi_ui_get_idle_time
> 3372330174 stdapi_ui_start_keyscan
> 3372330224 stdapi_ui_stop_keyscan

and when I used as input for volatility strings command, it didn't result any hit.
manually delete the offset to 9 character resolve the problem.
I know it is advisable to use -td as opposed to -o when outputting strings.
However I don't know if this related to the problem.

**Comment by gleeda** [comment]
I'm not sure I understand what you mean: "offset to 9 character".  Could you show me the data after you made the adjustment?

**Comment by jtingkir** [comment]
1750233540 stdapi -> the offset had 10 char
175023354 stdapi -> I delete one zero the offset had 9 char

I am using the one available at mint repo, I think it's version 2.3.1
