### ISSUE TITLE
GUI for Volatility

### ISSUE THREAD

**Issue by ProactiveNode** [volatilityfoundation/volatility#434]
Hello, I wanted to work on creating a GUI for volatility using either PyQt4 or Node.js. I wanted to know if it were possible for me to work on it since I am not quite sure how licensing would work. I am fairly new to understanding how licensing works so I don't know if I am allowed to use these to create a GUI for Volatility.

**Comment by cdminigun** [comment]
As per the README and LICENSE, it is provided under GNU GPL. Making code contributions is fine, can't guarantee that it'll be merged into source. You're more than welcome to make a GUI wrapper for your needs. 

Go and read up on GNU GPL if you're looking for a more verbose response.

**Comment by Antiever** [comment]
There is a lot of GUI for Volatility btw.  
Most of them browser based but some (like VolatilityWorkbench and  WMDF) are standalone ones.

**Comment by gleeda** [comment]
I think PyQt4 is definitely the way to go.  Like previously mentioned, a GUI is something that many people have implemented, but I still think there is room for improvement.  You should give it a shot, if that's what you really want to do :-)

**Comment by ProactiveNode** [comment]
Thanks for the answers everyone. I'll start to work on it with PyQt4 and I'll do some more reading on GNU GPL. Thank you!
