### ISSUE TITLE
Quick dumpcert question

### ISSUE THREAD

**Issue by DigiAngel** [volatilityfoundation/volatility#435]
What format are the key files in?  For the life of me I'm not finding an easy way to view these.  Thank you.

**Comment by iMHLv2** [comment]
Take a look at the plugin: https://github.com/volatilityfoundation/volatility/blob/master/volatility/plugins/dumpcerts.py 

Both of the classes (`_X509_PUBLIC_CERT` and `_PKCS_PRIVATE_CERT`) have an `as_openssl()` method which shows you the commands to use with openssl to parse them.

**Comment by DigiAngel** [comment]
Excellent..thank you.
