### ISSUE TITLE
Malware Cookbook DVD Memory Sample Link broken(Wiki)

### ISSUE THREAD

**Issue by omri9741** [volatilityfoundation/volatility#439]
Malware Cookbook DVD Link is broken - just need to add the closing -> ']'

_`[Malware Cookbook DVD**]** (https://www.sendspace.com/pro/dl/p87m18)`_

[Memory-Samples](https://github.com/volatilityfoundation/volatility/wiki/Memory-Samples)

**Comment by iMHLv2** [comment]
Thanks
