### ISSUE TITLE
unalbe install on windows7(x64)

### ISSUE THREAD

**Issue by b09780978** [volatilityfoundation/volatility#440]
Hi, I try to follow this wiki step by step to install volatility,but it show this error message.
when I type command: python setup.py install.
error: [Errno 2] No such file or directory: 'C:\\Python27\\lib\\site-packages\\setuptools\\script.tmpl'
the source code is git clone from github(https://github.com/volatilityfoundation/volatility.git)

enviroment:
OS: Windows7(x64) sp1
processer: intel i5
RAM: 8G

**Comment by dsgz1234** [comment]
you should check the setup tools if it's installed correct.

**Comment by iMHLv2** [comment]
Running `setup.py` is unnecessary unless you're building a development environment and you want it installed as a Python package. Just unzip the archive and run `vol.py` to use it. Also, there are compiled Windows executables that don't require Python or any dependencies that may be better for you.
