### ISSUE TITLE
AddrSpaceError: No suitable address space mapping found

### ISSUE THREAD

**Issue by hyperdallas** [volatilityfoundation/volatility#441]
I have googled, trawled and scraped most of the web to try find a resolution for this issue.  Appears I am getting the (AddrSpaceError: No suitable address space mapping found) error. 

Here is a dump of the error from cuckoo.

2017-06-27 09:07:07,300 [cuckoo.auxiliary.sniffer] INFO: Started sniffer with PID 3841 (interface=vboxnet0, host=192.168.56.101, pcap=/home/xxxx/.cuckoo/storage/analyses/2/dump.pcap)
2017-06-27 09:07:14,270 [cuckoo.core.guest] INFO: Starting analysis on guest (id=Windows7, ip=192.168.56.101)
2017-06-27 09:10:23,510 [cuckoo.core.scheduler] ERROR: Error from the Cuckoo Guest: The analysis hit the critical timeout, terminating.
2017-06-27 09:10:26,481 [cuckoo.machinery.virtualbox] INFO: Successfully generated memory dump for virtual machine with label Windows7 to path /home/xxxx/.cuckoo/storage/analyses/2/memory.dmp
2017-06-27 09:11:52,872 [cuckoo.core.plugins] ERROR: Failed to run the processing module "Memory" for task #2:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 238, in process
    data = current.run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1118, in run
    return VolatilityManager(self.memory_path, osprofile).run()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 1000, in __init__
    self.vol = VolatilityAPI(self.memfile, self.osprofile)
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 79, in __init__
    self.init_config()
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/processing/memory.py", line 150, in init_config
    self.addr_space = utils.load_as(self.config)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/utils.py", line 65, in load_as
    raise error
AddrSpaceError: No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareAddressSpace: No base Address Space
 QemuCoreDumpElf: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 Win10AMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VMWareMetaAddressSpace: VMware metadata file is not available
 VirtualBoxCoreDumpElf64: ELF error: did not find any PT_NOTE segment with VBCORE
 VMWareAddressSpace: Invalid VMware signature: 0x464c457f
 QemuCoreDumpElf: ELF error: did not find any PT_NOTE segment with CORE
 WindowsCrashDumpSpace32: Header signature invalid
 Win10AMD64PagedMemory: Incompatible profile Win7SP1x86 selected
 WindowsAMD64PagedMemory: Incompatible profile Win7SP1x86 selected
 LinuxAMD64PagedMemory: Incompatible profile Win7SP1x86 selected
 AMD64PagedMemory: Incompatible profile Win7SP1x86 selected
 IA32PagedMemoryPae: Failed valid Address Space check
 IA32PagedMemory: Failed valid Address Space check
 OSXPmemELF: No PT_LOAD segments found
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: Profile does not have valid Address Space check

For my VM, I am running Win7 SP1 x86 N Ultimate, Build 677597. To try resolve this, I have done the following:

1. Used git clone to install using python.
2. Removed git clone and installed from master.zip using install instructions (in case of differences).
3. Tried all memory profiles applicable to vm build (Win7SP1x86_23418, Win7SP0x86, Win7SP1x86).
4. Ensured profile name was same in cuckoo conf and memory conf with no blanks.
5. Tried an imageinfo on DMP file to get suggested profiles, results as per below.  

xxxx@ubuntu:/home/app/volatility-master$ sudo vol.py -f memory.dmp imageinfo
Volatility Foundation Volatility Framework 2.6
INFO    : volatility.debug    : Determining profile based on KDBG search...
          Suggested Profile(s) : Win7SP1x86_23418, Win7SP0x86, Win7SP1x86
                     AS Layer1 : FileAddressSpace (/home/app/volatility-master/memory.dmp)
                      PAE type : No PAE
                           DTB : 0x185000L
                          KDBG : 0x2749150L
          Number of Processors : 0
     Image Type (Service Pack) : -
             KUSER_SHARED_DATA : 0xffdf0000L

Happy to extract whatever other logs is needed to work this out, but might need help with the commands. TIA!

**Comment by gleeda** [comment]
Could you run the kdbgscan plugin fan paste in the output here?

**Comment by hyperdallas** [comment]
Can u tell me the cmd and i will happily run it and paste output

**Comment by hyperdallas** [comment]
anyone?

**Comment by hyperdallas** [comment]
Am I best using another package other than volatility to do this? Can't seem to find a resolution here...

**Comment by iMHLv2** [comment]
Try the following and paste the output (if any):

`sudo vol.py -f memory.dmp kdbgscan --dtb=0x185000 --profile=Win7SP1x86`
`sudo vol.py -f memory.dmp psscan --profile=Win7SP1x86_23418`

If still nothing works and you can post the memory sample somewhere, one of us can take a look.

**Comment by hyperdallas** [comment]
sudo vol.py -f memory.dmp kdbgscan --dtb=0x185000 --profile=Win7SP1x86
OUTPUT:
Volatility Foundation Volatility Framework 2.6
**************************************************
Instantiating KDBG using: /home/app/volatility-master/memory.dmp Win7SP1x86 (6.1.7601 32bit)
Offset (P)                    : 0x2749150
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win7SP1x86_23418
Version64                     : 0x2749128 (Major: 15, Minor: 7601)
PsActiveProcessHead           : 0x8275ef18
PsLoadedModuleList            : 0x82766850
KernelBase                    : 0x8261c000

**************************************************
Instantiating KDBG using: /home/app/volatility-master/memory.dmp Win7SP1x86 (6.1.7601 32bit)
Offset (P)                    : 0x2749150
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win7SP1x86
Version64                     : 0x2749128 (Major: 15, Minor: 7601)
PsActiveProcessHead           : 0x8275ef18
PsLoadedModuleList            : 0x82766850
KernelBase                    : 0x8261c000

**************************************************
Instantiating KDBG using: /home/app/volatility-master/memory.dmp Win7SP1x86 (6.1.7601 32bit)
Offset (P)                    : 0x2749150
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win7SP0x86
Version64                     : 0x2749128 (Major: 15, Minor: 7601)
PsActiveProcessHead           : 0x8275ef18
PsLoadedModuleList            : 0x82766850
KernelBase                    : 0x8261c000

sudo vol.py -f memory.dmp psscan --profile=Win7SP1x86_23418
OUTPUT:
Volatility Foundation Volatility Framework 2.6
Offset(P)          Name                PID   PPID PDB        Time created                   Time exited                   
------------------ ---------------- ------ ------ ---------- ------------------------------ ------------------------------
0x000000002e148030                       0      0 0x856de900

**Comment by iMHLv2** [comment]
Still looks undesirable. Can post the memory sample somewhere? What version of Virtualbox?

**Comment by hyperdallas** [comment]
Virtual box version is : 5.1.22r115126

Memory dump is about 1gb...  Not sure where I could post a file of that size?

**Comment by hyperdallas** [comment]
Memory dump uncompressed is about 1gb...  Compressed is 150mb. Will upload to a host and post link in 15 mins.

**Comment by hyperdallas** [comment]
Here is the mem dump as a gz file.

https://expirebox.com/download/b24de2938557e602bc4349a4f1055693.html

**Comment by hyperdallas** [comment]
So do i need to make that change to that file or do i just delete volatility, clone, reinstall and retry the dump?

**Comment by iMHLv2** [comment]
It depends how you accessed volatility in the first place. If you checked it out with `git clone` then you can just type `git pull` in the directory and it will update. Manually changing the single file will work of course, but its not practical to do every time we commit a patch. If you ran `setup.py` during initial install, you can clone again, run `setup.py` again and hopefully that will overwrite your old file with the new one.

**Comment by superponible** [comment]
I had noticed a similar error recently with a vbox dump.  I hadn't looked
into it, but saw this thread and thought I'd take a look.

Looks like in volatility/plugins/overlays/linux/elf.py, is_valid() checks
that p_vaddr > 0x1000:

    def is_valid(self):
         return self.p_vaddr > 0x1000 and self.p_filesz > 0 and
self.p_memsz > 0

But the readelf.py output below shows that that's 0 in the vbox dump
below.  This ends up giving the error below when it checks for a vbox
address space.

    VirtualBoxCoreDumpElf64: ELF error: did not find any PT_NOTE segment
with VBCORE

As a quick test, I changed that p_vaddr check to be >= 0x0 and pslist now
works.  Not sure what other effects that might have so there's probably a
better fix, but that should at least help point in the right direction.

I've got vbox 5.0.14 r105127.  I don't think I have an older dump from vbox
to see what the ELF headers looked like before.


$ readelf.py -e ~/mem.elf
ELF Header:
  Magic:   7f 45 4c 46 02 01 00 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           0
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              CORE (Core file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          0 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         10
  Size of section headers:           64 (bytes)
  Number of section headers:         0
  Section header string table index: 0

Section Header:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), l (large)
  I (info), L (link order), G (group), T (TLS), E (exclude), x (unknown)
  O (extra OS processing required) o (OS specific), p (processor specific)

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
*  NOTE           0x0000000000000270 0x0000000000000000 0x0000000000000000*
*                 0x00000000000044b4 0x00000000000044b4  R      0*
*  LOAD           0x0000000000004724 0x0000000000000000 0x0000000000000000*
*                 0x0000000080000000 0x0000000080000000  R      0*
  LOAD           0x0000000080004724 0x0000000000000000 0x00000000e0000000
                 0x0000000000800000 0x0000000000800000  R      0
  LOAD           0x0000000080804724 0x0000000000000000 0x00000000f0000000
                 0x0000000000000000 0x0000000000020000  R      0
  LOAD           0x0000000080804724 0x0000000000000000 0x00000000f0400000
                 0x0000000000400000 0x0000000000400000  R      0
  LOAD           0x0000000080c04724 0x0000000000000000 0x00000000f0800000
                 0x0000000000004000 0x0000000000004000  R      0
  LOAD           0x0000000080c08724 0x0000000000000000 0x00000000f0820000
                 0x0000000000000000 0x0000000000020000  R      0
  LOAD           0x0000000080c08724 0x0000000000000000 0x00000000fec00000
                 0x0000000000000000 0x0000000000001000  R      0
  LOAD           0x0000000080c08724 0x0000000000000000 0x00000000fee00000
                 0x0000000000000000 0x0000000000001000  R      0
  LOAD           0x0000000080c08724 0x0000000000000000 0x00000000ffff0000
                 0x0000000000010000 0x0000000000010000  R      0

**Comment by hyperdallas** [comment]
I git pulled it originally. 

So just now, I deleted the volatility dir, git pulled it again, setup.py built then setup.py installed it. I then ran cuckoo with the same volatility profile i used from the beginning (Win7SP1x86). 

... and it is working perfectly now!  Thank you so much!  I have closed off the thread.

**Comment by iMHLv2** [comment]
Cool, glad it worked. @superponible, indeed, that's almost exactly what we changed to get it working again. Cheers!
