### ISSUE TITLE
Win10x64 sockscan,connscan plugins

### ISSUE THREAD

**Issue by mrevros** [volatilityfoundation/volatility#444]
Hi All,

 Are these 2 plugins suitable for Win10 or am i missing something?

Thanks
![image](https://user-images.githubusercontent.com/15263586/27771520-7fac8cf6-5f58-11e7-918a-8615aee59d86.png)
![image](https://user-images.githubusercontent.com/15263586/27771522-8f441aa8-5f58-11e7-8159-7030b9db6356.png)

**Comment by munez07** [comment]
Hi,
No, sockscan and connscan don't support Windows 10, they support Windows XP and Windows 2003 Server only. (see the [wiki here](https://github.com/volatilityfoundation/volatility/wiki/Command%20Reference#connscan))
Anyway you can use netscan (see info [here](https://github.com/volatilityfoundation/volatility/wiki/Command%20Reference#netscan))

**Comment by mrevros** [comment]
Thank you @munez07
