### ISSUE TITLE
Python3 support in pdbparse – check if it works with Volatility?

### ISSUE THREAD

**Issue by moyix** [volatilityfoundation/volatility#447]
@lucasg very kindly recently put together a pull request porting `pdbparse` to python3. Given that you guys are (I think) one of the heaviest users of pdbparse right now, could one of you check that it doesn't break vtypes generation for Volatility?

The pull request can be found here:

https://github.com/moyix/pdbparse/pull/35

**Comment by gleeda** [comment]
Thank you for the heads up, @moyix !

cc @ikelos @npetroni

**Comment by ikelos** [comment]
Hmmm, I don't have any files to run this over since I wasn't involved in profile generation so much.  It definitely won't impact volatility 3 since I believe we'll be using LLVM for that, but @iMHLv2 might want to take a look from a windows/volatility 2 perspective...

**Comment by npetroni** [comment]
Sorry, I've been traveling for a couple of weeks -- just got around to this. I do still use pdbparse for vol2 work. It looks like `pdb_tpi_vtypes.py` is currently broken on master. Do you want me to file issues in the pdbparse project or is the merge still in progress? I'd be happy to run it against my PDB data set.

**Comment by moyix** [comment]
The merge should be finished now, so please file issues!

**Comment by npetroni** [comment]
Tracking here: https://github.com/moyix/pdbparse/issues/39.

**Comment by npetroni** [comment]
Closed upstream.
