### ISSUE TITLE
Problem with heaps plugin

### ISSUE THREAD

**Issue by Salinero27** [volatilityfoundation/volatility#453]
Hi,

According to "The Art of Memory Forensics" book , there is a heaps plugin that can extract out information from the heap memory of a process. But I'm using latest version of volatility - 2.6 , and the heaps plugin is not working.

The Heaps plugin is inside the plugins folder but still the plugin does not work. That is the output that volatility shows  when I launch the plugin.

_volatility -f sample005.bin --profile=Win2003SP0x86 heaps -p 508
Volatility Foundation Volatility Framework 2.6
Usage: Volatility - A memory forensics analysis platform.

volatility: error: no such option: -p_

**Comment by openfoamtutorials** [comment]
Why is there an underscore after the "-p"? What does it say when you run without "-p"?

**Comment by iMHLv2** [comment]
The heaps plugin was never released. The file you see named heaps.py just contains some of the data structures for heaps, which are used by other plugins. Our end goal for the heap analysis was to create the notepad plugin, which we were able to do without a full blown heaps plugin.
