### ISSUE TITLE
Profile Win10x64_10586 not recognized

### ISSUE THREAD

**Issue by alexverboon** [volatilityfoundation/volatility#454]
HI, 

Although the documentation https://github.com/volatilityfoundation/volatility/wiki/2.6-Win-Profiles lists the profile: Win10x64_15063 Volatility Foundation Volatility Framework 2.6 does not recognize this profile:

ERROR   : volatility.debug    : Invalid profile Win10x64_Win10x64_15063 selected

i used DumpIt 3.0.20170818.1 to create the memory dump. 
Cheers
Alex

P.S also volatility_2.6_win64_standalone.exe --info does not list this profile.

**Comment by openfoamtutorials** [comment]
Your error message seems to indicate you typed "Win10x64_Win10x64_15063" instead of "Win10x64_15063". If so, this is an easy fix :)

**Comment by iMHLv2** [comment]
Yes, the correct profile name is Win10x64_15063, and its currently only available in the github source repository (not the 2.6 compiled binaries).

**Comment by alexverboon** [comment]
Thanks for the feedback and updates. Any idea how often / when the standalone version will be updated?

**Comment by itripc** [comment]
Is the github source repository  the master branch? at https://github.com/volatilityfoundation/volatility
lack of knowledge of github

**Comment by jared703** [comment]
I'm pretty confident in that it's the latest stable branch. The binaries
seem to be usually updated at the time of new version release.

**Comment by drlycan** [comment]
so my question is why do none of the 64bit profiles work for Win10?

**Comment by atcuno** [comment]
Hello,

Which version of Volatility are you using? You need to use the latest source code version from GitHub to have access to all of the profiles.

Also, can you please include your full command line input and output in a future reply so that we can see exactly what has happened?
