### ISSUE TITLE
v. 2.6 Windows executable missing PIL

### ISSUE THREAD

**Issue by mdegrazia** [volatilityfoundation/volatility#460]
When using the Windows executable for Volatility 2.6 and the screenshot plugin, the error message "Please install PIL" is displayed. I did not receive this error message when using 2.5 on the same system.

**Comment by gleeda** [comment]
Sorry about the delay.  I'm not sure when we'll release a new standalone, but in the meantime you can create a new one using https://github.com/volatilityfoundation/volatility/wiki/Compiling-Binaries-with-Pyinstaller

just make sure to import PIL/yara etc in vol.py to make sure they're seen.

**Comment by aktas** [comment]
```pip2.7 install Pillow``` I solved my problem with this command.
