### ISSUE TITLE
"No suitable address space mapping found" Windows10 15063.608.

### ISSUE THREAD

**Issue by jun0s** [volatilityfoundation/volatility#463]
Any profile Win10x64* 

junos@dbox:~$ vol.py pslist -f memory.dmp "anywin10profile"
Volatility Foundation Volatility Framework 2.6
No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 QemuCoreDumpElf: No base Address Space
 VMWareAddressSpace: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 SkipDuplicatesAMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Unsupported dump format
 WindowsCrashDumpSpace64: Unsupported dump format
 HPAKAddressSpace: Invalid magic found
 VMWareMetaAddressSpace: VMware metadata file is not available
 VirtualBoxCoreDumpElf64: ELF Header signature invalid
 QemuCoreDumpElf: ELF Header signature invalid
 VMWareAddressSpace: Invalid VMware signature: 0x45474150
 WindowsCrashDumpSpace32: Header signature invalid
 SkipDuplicatesAMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 WindowsAMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 LinuxAMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 AMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 IA32PagedMemoryPae: No valid DTB found
 IA32PagedMemory: No valid DTB found
 OSXPmemELF: ELF Header signature invalid
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: No valid DTB found
____________________________________________
Its a full crashdump file from windows 10x64 15063.608
volatility github version... over Debian 9.1 32bits

unos@dbox:~$ vol.py imageinfo -f memory.dmp
Volatility Foundation Volatility Framework 2.6
INFO    : volatility.debug    : Determining profile based on KDBG search...
          Suggested Profile(s) : No suggestion (Instantiated with Win10x64_15063)
                     AS Layer1 : FileAddressSpace (/home/junos/memory.dmp)
                      PAE type : No PAE
                           DTB : 0x1ab000L
             KUSER_SHARED_DATA : 0xfffff78000000000L

thank you very much!! :)

**Comment by wroersma** [comment]
Did you happen to run the imagecopy plugin first to convert it to a raw memory dump? 
https://github.com/volatilityfoundation/volatility/wiki/Command-Reference#imagecopy

**Comment by jun0s** [comment]
well.. i did this 

unos@dbox:~$ vol.py -f memory.dmp --profile=Win10x64_15063 imagecopy -O memoraw.dmp
Volatility Foundation Volatility Framework 2.6
Writing data (5.00 MB chunks): |.........................................................................................................................................................................................|
junos@dbox:~$

with the same result..... i use the profile "Win10x64_15063" because is the previous version of windows10 x64  Build 15063.608

maybe something change with the last update... 

thank you :)

**Comment by wroersma** [comment]
yeah its one of those strange plugins that don't need the profile and work better without :)

**Comment by jun0s** [comment]
well.. for me no :/ ... i am gonna try with subsystem bash on windows 10x64 thank you @wroersma

**Comment by iMHLv2** [comment]
I can confirm that the Win10x64_15063 profile works on 15063.608 with VMware snapshots and captures taken with Volexity Surge, so that rules out something changing in the OS data types recently. How much RAM does your Windows 10 machine have? Are you sure you have a complete crash dump and not just a kernel crash dump? Did you paste the entire output after "Writing data (5.00 MB chunks):" above? I'm asking because the number of "." is about 185, which if you multiply by 5 MB is slightly less than 1 GB....and I didn't even think it was possible to run Win 10 x64 with that much RAM.

**Comment by jun0s** [comment]
Ok i use a dumpchk utility, and just Kernel address space is available, is just a 1g crash dump file... this is my first time trying to make a malware analysis(checking drivers and process) with volatility, get useful data etc.. then volatility it does not work with kernel dump crash file? sorry my bad.

thank you so much @iMHLv2
