### ISSUE TITLE
Mac Standalone Executable - Changing Profile

### ISSUE THREAD

**Issue by zTemplar85** [volatilityfoundation/volatility#464]
Hi, 

I have downloaded the Mac Standalone Executable and the profile for Yosemite.
I try using the profile as shown in the image attached but was unable to.

Similarly I had tried using the --plugins option.
Any advice on where I did wrong?

Thanks.

![thumbnail_image](https://user-images.githubusercontent.com/5791182/31493612-8cb7e650-af82-11e7-973c-4ad564a5f3cf.jpg)

**Comment by openfoamtutorials** [comment]
I think you need to decompress it and add it to the volatility/plugins/overlays/mac/ directory.

**Comment by zTemplar85** [comment]
Hi openfoamtutorials,

Thanks for the reply.
But I am using the standalone executable. Would this method still work?

**Comment by wroersma** [comment]
Is using the standalone required? It's much better to checkout and run from source if you can.

**Comment by zTemplar85** [comment]
Sorry for the late reply. Well the Mac was suspected to be infected. Thus the intention of using the standalone on USB to capture and do analysis on another machine.

**Comment by atcuno** [comment]
You can use the --plugins option and point it to a directory containing a zip of the profile. This options must be immediately after the executable name in order for it to register.

Note that the standalone executable is very out of date now though. Using the source code version from git would give you more plugins and many bug fixes. 

Please re-open this ticket if you have any issues with --plugins and/or analysis with the source code version.
