### ISSUE TITLE
volatility not working properly for linux memory

### ISSUE THREAD

**Issue by Jakanath** [volatilityfoundation/volatility#465]
hi ..
i'm having a issue with volatility in Linux memory forensic
i use lime to capture memory of Ubuntu trusty_tar system and i  have create a volatility profile for ubuntu system by using /boot/System.map in lime and raw format.
when i run volatility its give me this error.. i have try many times using both lime and raw format of memory image
i have attach the error given by volatility
![vv](https://user-images.githubusercontent.com/22641046/31541971-e04e4a28-b042-11e7-8a84-1ce297445ba1.PNG)

**Comment by atcuno** [comment]
Hello,

Would it be possible to share the profile and memory sample where this occurs?
