### ISSUE TITLE
Adding 2to3 branch (Volatility with Python 3)

### ISSUE THREAD

**Issue by pdautry** [volatilityfoundation/volatility#471]
I suggest to port Volatility from Python 2 to Python 3 in order to take advantage of latest plugins from Python Package Index and Python 3 performance improvements.

[TESTS.md](https://github.com/pdautry/volatility/blob/2to3/TESTS.md) in the forked repository gives an idea of the progression of the portage.

This could be made progressively by adding a `2to3` branch to the official Volatility repository to ensure the change is progressive.

I can observer slight performance improvements just by porting to Python3.
Maybe it's not relevant... What's your opinion about this ?

I'll continue to port if you consider this positively.

```
Test configuration :
> $ python3 --version
Python 3.6.3
> $ pip3 show distorm3
Name: distorm3
Version: 3.3.4
> $ pip3 show yara
Name: yara
Version: 1.7.7
> $ pip3 show pycrypto
Name: pycrypto
Version: 2.6.1
```
I haven't ported the setup script yet. I run it directly `python3 vol.py ...`

**Comment by gleeda** [comment]
We are currently working on this.  I'm going to close this issue for now.
