### ISSUE TITLE
Win 10 need Win10x64_15063 profile, cant seem to locate

### ISSUE THREAD

**Issue by itripc** [volatilityfoundation/volatility#473]
How do I find the updated profiles listed at
https://github.com/volatilityfoundation/volatility/wiki/2.6-Win-Profiles

The build on the system shows I need  Win10x64_15063 , I thought I had downloaded the latest vol 2.6 but I must be wrong, when I run --info   grep Profiles  I do not see the  Win10x64_15063 profile listed. Would you mind providing the link to the latest version that supports the profile by chance? Thank you in advance.

**Comment by jared703** [comment]
https://github.com/volatilityfoundation/volatility/

Best,
Jared

**Comment by atcuno** [comment]
Hello,

You need to update to the latest version of Volatility source code. Please re-open the ticket if you have any issues after git updating (or downloading a zip of the master branch).
