### ISSUE TITLE
[Linux] SwapperScan problem/solution for failed valid address space 

### ISSUE THREAD

**Issue by Sebastienbr** [volatilityfoundation/volatility#475]
Hi, 

Hope all is well for everyone :-)

I found a problem related to the physical aslr kernel scan with Ubuntu 16.04.3 (don't know if it apply to other OS).

Same system, same state, multiple memory dump (approx 10 minutes between each memory dump). Sometimes the analysis works, sometimes not (i.e:  Failed valid Address Space check is yield from LinuxAMD64PagedMemory). 

After digging into the source, I found that the problem is related to the swapperScan part in the function VolatilityDTB.generate_suggestion (linux.py).

The analysis failed because of this verification:

`if pas.read(swapper_address, 4) != "\x00\x00\x00\x00":` ([ref])

When it fails, the swapper value is 00 00 20 00. I did not have the time to find the structure to see what it means... However, I would be curious to know what it means if you have a ref to this structure. 

All my dumps can be analysed if I change the code to this:

```
if pas.read(swapper_address, 4) != "\x00\x00\x00\x00":
    if pas.read(swapper_address, 4) != "\x00\x00\x20\x00":
        continue
```

Best regards,

Sebastien

[ref]: https://github.com/volatilityfoundation/volatility/blob/831ff24ab03910434d630da2394afc6d91c8814d/volatility/plugins/overlays/linux/linux.py#L2338

**Comment by atcuno** [comment]
Hello,

Would it be possible to share the memory sample and profile for this? I really would like to debug it myself. That is a strange state for the swapper process to be in.

**Comment by beleka** [comment]
Hello, i have the invalid adress problem and can't be solved like this uu . I dumped the RAM and created a new profile, any other idea??
