### ISSUE TITLE
AddrSpaceError: No suitable address space mapping found

### ISSUE THREAD

**Issue by hackdefendr** [volatilityfoundation/volatility#484]
Volatility is being called from within my Cuckoo Sandbox, but it appears there is an issue. The memory dump is coming from a Windows 10 Pro (1709) and my configuration is using profile Win10x64.  Is this a profile issue or something else?

  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/plugins/filescan.py", line 361, in calculate
    addr_space = utils.load_as(self._config)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/utils.py", line 65, in load_as
    raise error
AddrSpaceError: No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 QemuCoreDumpElf: No base Address Space
 VMWareAddressSpace: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 SkipDuplicatesAMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VMWareMetaAddressSpace: VMware metadata file is not available
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VMWareMetaAddressSpace: VMware metadata file is not available
 VirtualBoxCoreDumpElf64: ELF Header signature invalid
 QemuCoreDumpElf: ELF Header signature invalid
 VMWareAddressSpace: Invalid VMware signature: 0xf000ff53
 WindowsCrashDumpSpace32: Header signature invalid
 SkipDuplicatesAMD64PagedMemory: No valid DTB found
 WindowsAMD64PagedMemory: No valid DTB found
 LinuxAMD64PagedMemory: Incompatible profile Win10x64 selected
 AMD64PagedMemory: No valid DTB found
 IA32PagedMemoryPae: Incompatible profile Win10x64 selected
 IA32PagedMemory: Incompatible profile Win10x64 selected
 OSXPmemELF: ELF Header signature invalid
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: No valid DTB found`

**Comment by hackdefendr** [comment]
As a test, I just ran another analysis using the profile Win10x64_10586 and the analysis seems to complete with only some warnings.

**Comment by gitayo** [comment]
Same problem is faced by me.

**Comment by gleeda** [comment]
So this seems like it was a matter of choosing a different profile.  If you have any other issues, please reopen.
