### ISSUE TITLE
Profile for Windows 10 : Version 1709 OS Build 16299.125 not working

### ISSUE THREAD

**Issue by petermclaren1** [volatilityfoundation/volatility#489]
I'm using Volatility 2.6 and have run kdbgscan on a live (i.e. using libVMI, pyvmi)  virtual guest with an updated Windows 10 : Version 1709 OS Build 16299.12

In the output, the 3 Windows 10 profiles which have processes, modules and reasonably correct build strings are:
Win10x64, Win10x64_10586, Win10x64_14393. Example below.

However none generates any output for handles,  vadinfo plugins etc.

Also the latter 2 generate garbled process names with the pslist plugin e.g. 0xffffc20899714038 P-r???smss.exe 
The first generates no process names below.

Are there any directions on creating a new profile or are there other suggestions?
Thanks
-----------------------------------------------------------------------------------------------------

Instantiating KDBG using: Unnamed AS Win10x64_14393 (6.4.14393 64bit)
Offset (V)                    : 0xf801bd1634d0
Offset (P)                    : 0x21634d0
KdCopyDataBlock (V)           : 0xf801bd012624
Block encoded                 : Yes
Wait never                    : 0x531c04640a9bf3d4
Wait always                   : 0x4dfb6433a167a005
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win10x64_14393
Service Pack (CmNtCSDVersion) : 0
Build string (NtBuildLab)     : 16299.15.amd64fre.rs3_release.17
PsActiveProcessHead           : 0xfffff801bd172ae0 (62 processes)
PsLoadedModuleList            : 0xfffff801bd179ff0 (209 modules)
KernelBase                    : 0xfffff801bce18000 (Matches MZ: True)
Major (OptionalHeader)        : 10
Minor (OptionalHeader)        : 0
KPCR                          : 0xfffff801bc3d6000 (CPU 0)

**Comment by iMHLv2** [comment]
You're running build 16299 so you would want the Win10x64_16299 profile. It was added several months ago, so you just need to git pull and run from source. There's no executable containing this profile yet.

**Comment by averagejoe365** [comment]
@iMHLv2 
"It was added several months ago, so you just need to git pull and run from source."
Any suggestions on how to do this? I found info on the source, but how to we incorporate this into Kali?
