### ISSUE TITLE
Need support for Windows 10 15063 or above of Volatility

### ISSUE THREAD

**Issue by Anis-muh** [volatilityfoundation/volatility#493]
I run the volatility version 2,6, Also from the other versions fixed by some people here, but unfortunately they did not display the correct pids. I am using Windows 10 15063. Expecting the new profiles or the new Volatility version. Thanks

Volatility Foundation Volatility Framework 2.6
Offset(P)          Proto    Local Address                  Foreign Address      State            Pid      Owner          Created
0xe08c2e217720     UDPv6    ::1:60379                      *:*                                   863654760 svchost.exe    2018-02-06 01:03:29 UTC+0000
0xe08c2e24f2f0     UDPv4    127.0.0.1:49211                *:*                                   843548904 vsservppl.exe  2018-02-05 09:41:19 UTC+0000
0xe08c2e25bb30     UDPv4    127.0.0.1:49208                *:*                                   843548904 vsservppl.exe  2018-02-05 09:41:19 UTC+0000
0xe08c2e4cd8c0     UDPv4    127.0.0.1:60382                *:*                                   863654760 svchost.exe    2018-02-06 01:03:29 UTC+0000
0xe08c2e651010     TCPv4    127.0.0.1:2803                 127.0.0.1:2802       ESTABLISHED      -1
0xe08c2e706ae0     UDPv4    0.0.0.0:3702                   *:*                                   912206056 svchost.exe    2018-02-06 04:35:03 UTC+0000
0xe08c2e767ab0     TCPv4    192.168.1.101:3168             23.51.43.27:80       CLOSE_WAIT       -1
0xe08c2ea739d0     TCPv4    192.168.1.101:3910             18.194.226.16:443    CLOSED           -1

**Comment by gleeda** [comment]
Please update volatility with the latest source and use the appropriate profile:

`python vol.py -f [MEMORY] --profile=Win10x64_15063 netscan`

Please reopen if you are still having issues.
