### ISSUE TITLE
error: no such option: -y for hashdump

### ISSUE THREAD

**Issue by tckelly38** [volatilityfoundation/volatility#496]
trying to dump the hashes from the registry on some raw file. I have tried executing the following command based on some online tutorials and from the command reference page here: 

`python vol.py -f test.raw --profile=Win2008SP2x64 hashdump -y 0xfffff88000033370 -s 0xfffff8800091f010 > hashes.txt`

and get the following output:
```
Volatility Foundation Volatility Framework 2.6
Usage: Volatility - A memory forensics analysis platform.

vol.py: error: no such option: -y
```

Any insight on this?

**Comment by gleeda** [comment]
Hrmm I wasn't able to duplicate.  One thing that I know of that might have been the problem, is if you are copy and pasting the dash options from a word document or PDF file.  Sometimes MS Word makes dashes into a different, longer dash character that the command line doesn't recognize.  Try typing out the arguments manually and see if it still fails.

**Comment by tckelly38** [comment]
@gleeda changed to the following: 

```
python volatility/vol.py hashdump -f test.raw --profile=Win2008SP2x64 sys-offset=0xfffff88000033370 sam-offset=0xfffff8800091f010
```

and it worked

**Comment by gleeda** [comment]
Cool!  Sorry, I don't know what the issue would have been earlier. :-/

**Comment by HopeWooo** [comment]
vol.py: error: no such option: -p
help with this please
