### ISSUE TITLE
Linux Profiles doesn't work

### ISSUE THREAD

**Issue by beleka** [volatilityfoundation/volatility#497]
Hello, i created a custom profile with dwarfdump and System.map for kali 4.14.0-kali3-amd64 version. The memory dump was done using the command:
sudo insmod xxxx.ko "path=xxx/Kali.mem format=lime timeout=0"
I tried with RAW format too. 
The problem is that i created profile twice and tested with two different format but i always get the same error when i execute a volatility command:
python vol.py -f "memory_path --profile="custom profile" linux_pslist

No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 QemuCoreDumpElf: No base Address Space
 VMWareAddressSpace: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 SkipDuplicatesAMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: PO_MEMORY_IMAGE is not available in profile
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VMWareMetaAddressSpace: VMware metadata file is not available
 VirtualBoxCoreDumpElf64: ELF Header signature invalid
 QemuCoreDumpElf: ELF Header signature invalid
 VMWareAddressSpace: Invalid VMware signature: 0x905c689
 WindowsCrashDumpSpace32: Header signature invalid
 SkipDuplicatesAMD64PagedMemory: Incompatible profile LinuxTestx64 selected
 WindowsAMD64PagedMemory: Incompatible profile LinuxTestx64 selected
 LinuxAMD64PagedMemory: Failed valid Address Space check
 AMD64PagedMemory: Failed valid Address Space check
 IA32PagedMemoryPae: Incompatible profile LinuxTestx64 selected
 IA32PagedMemory: Incompatible profile LinuxTestx64 selected
 OSXPmemELF: ELF Header signature invalid
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: Failed valid Address Space check
 
If someone knows how to help me or what can i test more just say it to me plz. Thank you everyone for your time.

EDIT: I tried with Ubuntu (Santoku distro) and i wasn't able to analyze the dump again, following the same process than before. Both are virtual machines. I tested .vmem from vmware folder with their profiles and it doesn't work neither. I hope you can help me with this.

**Comment by cad18** [comment]
Hi,

I am having the same problem. I've pulled the latest copy from git to a clean system but cann't get Kali 2018.1 to work. Any ideas anyone?

Thanks.

**Comment by hahahk** [comment]
Hi, Previously I have the same problem as well, until i saw the README.txt : 
Linux: 
* 32-bit Linux kernels 2.6.11 to 4.2.3
* 64-bit Linux kernels 2.6.11 to 4.2.3
So volatility only support kernel up till 4.2.3, I tried a old lubuntu which kernel version in the range of 2.6.11 to 4.2.3 and it work

**Comment by luckydonald** [comment]
@hahahk What was your exact command line which worked?
I couldn't even find supported linux profiles in the  `--info` listing.

**Comment by noraj** [comment]
@hahahk Thanks I was trying to use a custom profile too and I didn't saw the `4.2.3` max kernel version and I was trying to use a `4.12.14` kernel.

**Comment by atcuno** [comment]
We support 4.12.14. With lime, can you please run it a second time after each boot? It usually has issues with first capture.
