### ISSUE TITLE
How does config.PLUGINS work?

### ISSUE THREAD

**Issue by yymax** [volatilityfoundation/volatility#499]
Hi Volatility Team:

I am trying to use volatility as a library so I don't need to play with the pipe for output parsing. I am able to call standard plugin but I am not sure how to invoke one of the community plugin for AFF4 support. Normally by using the command line, I can just use the --plugins=<community folder> flag and everything will just work seamlessly. However, when trying to do the same by setting config.PLUGINS=<community folder> in my code, I could not produce the same affect. Do you mind to provide some insights into how I could add plugins folders using the library?

**Comment by gleeda** [comment]
Try making it the first variable that you set.  For example, this works for me:

```
import copy, StringIO, json
import volatility.conf as conf
import volatility.registry as registry
import volatility.commands as commands
import volatility.addrspace as addrspace

registry.PluginImporter()

def get_json(config, plugin_class):
   strio = StringIO.StringIO()
   plugin = plugin_class(copy.deepcopy(config))
   plugin.render_json(strio, plugin.calculate())
   return json.loads(strio.getvalue())

def get_config(profile, target_path):
   config = conf.ConfObject()
   registry.register_global_options(config, commands.Command)
   registry.register_global_options(config, addrspace.BaseAddressSpace)
   config.parse_options()
   config.PLUGINS = "file:///location/to/volatility/contrib"
   config.PROFILE = profile
   config.LOCATION = "file://{0}".format(target_path)
   return config 
```

And then I just run it:

```
python customplugin_json.py Win10x64_14393 mem.dmp
```

**Comment by gleeda** [comment]
Feel free to reopen this if you have another issue.
