### ISSUE TITLE
Mac Memory Dump

### ISSUE THREAD

**Issue by beleka** [volatilityfoundation/volatility#504]
Hello i need some help with a macOS memory dump on Volatility. I used the tool from rekall osxpmem and created an aff4 file dumping the RAM of the System. Then i extracted the raw RAM dump from the aff4 file and tried to analyze it with volatility.

The problem is that even using the profile provided from Volatility to that macOS version, i have the "No base Adress Space" problem.  Does anyone know how to help me?

**Comment by gleeda** [comment]
Out of curiosity, were you able to analyze it with rekall ?
