### ISSUE TITLE
Win10x64 build 17133

### ISSUE THREAD

**Issue by mittensML** [volatilityfoundation/volatility#505]
How often are Windows profiles updated or how do I create a new Windows profile. I have build number Windows 10 x64_17133.

See below commands and results.

m@Linux /Stuff/Case/volatility $ python vol.py -f /Stuff/Case/dump.raw imageinfo
Volatility Foundation Volatility Framework 2.6
          Suggested Profile(s) : Win10x64_10586, Win10x64_14393, Win10x64_16299, Win2016x64_14393, Win10x64_15063 (Instantiated with Win10x64_15063)
                     AS Layer1 : SkipDuplicatesAMD64PagedMemory (Kernel AS)
                     AS Layer2 : FileAddressSpace (/Stuff/Case/dump.raw)
                      PAE type : No PAE
                           DTB : 0x1ad002L
                          KDBG : 0xf80301e42520L
          Number of Processors : 6
     Image Type (Service Pack) : 0
                KPCR for CPU 0 : 0xfffff802fff88000L
                KPCR for CPU 1 : 0xffffdd002b9a7000L
                KPCR for CPU 4 : 0xffffdd002bd93000L
                KPCR for CPU 5 : 0xffffdd002c0c0000L
                KPCR for CPU 6 : 0xffffdd002c154000L
                KPCR for CPU 7 : 0xffffdd002c1eb000L
             KUSER_SHARED_DATA : 0xfffff78000000000L
           Image date and time : 2018-03-30 15:50:32 UTC+0000
     Image local date and time : 2018-03-30 11:50:32 -0400

m@Linux /Stuff/Case/volatility $ python vol.py --profile=Win10x64_10586 -f /Stuff/Case/dump.raw pstree
Volatility Foundation Volatility Framework 2.6
Name                                                  Pid   PPid   Thds   Hnds Time
-------------------------------------------------- ------ ------ ------ ------ ----
 0xffffbb8a1c294038:????????? ??????               34...3 35...7 34...3 ------ 1970-01-01 00:00:00 UTC+0000
m@Linux /Stuff/Case/volatility $ python vol.py --profile=Win10x64_14393 -f /Stuff/Case/dump.raw pstree
Volatility Foundation Volatility Framework 2.6
Name                                                  Pid   PPid   Thds   Hnds Time
-------------------------------------------------- ------ ------ ------ ------ ----
 0xffffbb8a1c294038:????????? ??????               34...3 35...7 34...3 ------ 1970-01-01 00:00:00 UTC+0000
m@Linux /Stuff/Case/volatility $ python vol.py --profile=Win10x64_16299 -f /Stuff/Case/dump.raw pstree
Volatility Foundation Volatility Framework 2.6
Name                                                  Pid   PPid   Thds   Hnds Time
-------------------------------------------------- ------ ------ ------ ------ ----
 0xffffbb8a1c294040:? ??????????????               34...3 35...5 35...4 ------ 1970-01-01 00:00:00 UTC+0000
m@Linux /Stuff/Case/volatility $ python vol.py --profile=Win10x64_14393 -f /Stuff/Case/dump.raw pstree
Volatility Foundation Volatility Framework 2.6
Name                                                  Pid   PPid   Thds   Hnds Time
-------------------------------------------------- ------ ------ ------ ------ ----
 0xffffbb8a1c294038:????????? ??????               34...3 35...7 34...3 ------ 1970-01-01 00:00:00 UTC+0000
m@Linux /Stuff/Case/volatility $ python vol.py --profile=Win10x64_15063 -f /Stuff/Case/dump.raw pstree
Volatility Foundation Volatility Framework 2.6
Name                                                  Pid   PPid   Thds   Hnds Time
-------------------------------------------------- ------ ------ ------ ------ ----
 0xffffbb8a1c294040:? ??????????????               34...3 35...5 35...4 ------ 1970-01-01 00:00:00 UTC+0000

**Comment by iMHLv2** [comment]
The profiles are typically updated shortly after the OS version is released mainstream (17133 is still on insider preview). I would suspect in the next week or two we'll have support for it.
