### ISSUE TITLE
AttributeError: Could not list tasks, please verify your --profile with kdbgscan

### ISSUE THREAD

**Issue by nianyush** [volatilityfoundation/volatility#508]
i am using a mac os x standalone version, and it is ok when i tried to imageinfo a file. And then when i tried to use the suggested profile, it always occur the following error.
volatility -f ch2.dmp --profile=Win7SP1x86_23418 envars  
Volatility Foundation Volatility Framework 2.6
Pid      Process              Block      Variable                       Value
-------- -------------------- ---------- ------------------------------ -----
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
  File "vol.py", line 183, in main
  File "volatility/commands.py", line 147, in execute
  File "volatility/plugins/envars.py", line 123, in render_text
  File "volatility/win32/tasks.py", line 88, in pslist
  File "volatility/plugins/overlays/windows/kdbg_vtypes.py", line 42, in processes
AttributeError: Could not list tasks, please verify your --profile with kdbgscan
Failed to execute script vol

**Comment by gleeda** [comment]
Could you also run `kdbgscan` and see if there are any other KDBG locations that are given in the output other than the default one ?

Something like: 

`volatility -f ch2.dmp kdbgscan --force`

**Comment by xiaoyu9964** [comment]
Here's the result.
volatility -f ch2.dmp kdbgscan --force
Volatility Foundation Volatility Framework 2.6
**************************************************
Instantiating KDBG using: Kernel AS Win7SP1x86_23418 (6.1.7601 32bit)
Offset (V)                    : 0x82929be8
Offset (P)                    : 0x2929be8
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win7SP1x86_23418
Version64                     : 0x82929bc0 (Major: 15, Minor: 7600)
Service Pack (CmNtCSDVersion) : 0
Build string (NtBuildLab)     : 7600.16385.x86fre.win7_rtm.09071
PsActiveProcessHead           : 0x82941e98 (0 processes)
PsLoadedModuleList            : 0x82949810 (0 modules)
KernelBase                    : 0x82801000 (Matches MZ: True)
Major (OptionalHeader)        : 6
Minor (OptionalHeader)        : 1
KPCR                          : 0x8292ac00 (CPU 0)

**************************************************
Instantiating KDBG using: Kernel AS Win7SP1x86 (6.1.7601 32bit)
Offset (V)                    : 0x82929be8
Offset (P)                    : 0x2929be8
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win7SP1x86
Version64                     : 0x82929bc0 (Major: 15, Minor: 7600)
Service Pack (CmNtCSDVersion) : 0
Build string (NtBuildLab)     : 7600.16385.x86fre.win7_rtm.09071
PsActiveProcessHead           : 0x82941e98 (0 processes)
PsLoadedModuleList            : 0x82949810 (0 modules)
KernelBase                    : 0x82801000 (Matches MZ: True)
Major (OptionalHeader)        : 6
Minor (OptionalHeader)        : 1
KPCR                          : 0x8292ac00 (CPU 0)

**************************************************
Instantiating KDBG using: Kernel AS Win7SP0x86 (6.1.7600 32bit)
Offset (V)                    : 0x82929be8
Offset (P)                    : 0x2929be8
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win7SP0x86
Version64                     : 0x82929bc0 (Major: 15, Minor: 7600)
Service Pack (CmNtCSDVersion) : 0
Build string (NtBuildLab)     : 7600.16385.x86fre.win7_rtm.09071
PsActiveProcessHead           : 0x82941e98 (0 processes)
PsLoadedModuleList            : 0x82949810 (0 modules)
KernelBase                    : 0x82801000 (Matches MZ: True)
Major (OptionalHeader)        : 6
Minor (OptionalHeader)        : 1
KPCR                          : 0x8292ac00 (CPU 0)

**Comment by Ryan-Gordon** [comment]
any update for this or related issue @gleeda @nianyush ?
Encountering the same issue on Unix with volatility docker

**Comment by Ryan-Gordon** [comment]
@atcuno Has there been any resolution for this ? Or closed due to age
