### ISSUE TITLE
Win7SP1x86_24000 Profile - netscan  plugin PID -1

### ISSUE THREAD

**Issue by nterl0k** [volatilityfoundation/volatility#510]
Using WinSP1x86_24000 profile on Win7 SP1 x86 devices with all recent Microsoft updates. Netscan returns "PID -1" on Closed/Established TCPv4 connections. Older profiles cause more errors, _24000 profile works best but still not completely functional.

Can provide additional info as needed

Imageinfo below
----------------------
Volatility Foundation Volatility Framework 2.6
INFO    : volatility.debug    : Determining profile based on KDBG search...
          Suggested Profile(s) : Win7SP1x86_23418, Win7SP0x86, Win7SP1x86_24000, Win7SP1x86
                     AS Layer1 : IA32PagedMemoryPae (Kernel AS)
                     AS Layer2 : FileAddressSpace (/cases/c2.dmp)
                      PAE type : PAE
                           DTB : 0x185000L
                          KDBG : 0x83178c78L
          Number of Processors : 4
     Image Type (Service Pack) : 1
                KPCR for CPU 0 : 0x83179d00L
                KPCR for CPU 1 : 0x807e0000L
                KPCR for CPU 2 : 0x8f719000L
                KPCR for CPU 3 : 0x8f74f000L
             KUSER_SHARED_DATA : 0xffdf0000L
           Image date and time : 2018-05-01 19:15:28 UTC+0000
     Image local date and time : 2018-05-01 15:15:28 -0400

**Comment by gleeda** [comment]
Can you send the appropriate `ntoskrnl.exe` so we can see if maybe you need a new profile?

**Comment by pheerless** [comment]
Can do, will extract and send asap.



Regrards

Steven


-------- Original message --------

**Comment by pheerless** [comment]
kernel version shows "24024", let me know how else I can assist.


Password is "P@ssw0rd"

________________________________

**Comment by gleeda** [comment]
I think the exe got bounced back if you sent it by email

**Comment by pheerless** [comment]
[ntoskrnl.zip](https://github.com/volatilityfoundation/volatility/files/2034730/ntoskrnl.zip)
Youre Right, email bounced it. Uploaded, same password as above.
