### ISSUE TITLE
Error when running the standalone Windows exe

### ISSUE THREAD

**Issue by Xlon550** [volatilityfoundation/volatility#514]
Hello,

I have recently installed the standalone windows 10 exe and have unpacked it and placed the exe on my desktop. I dont believe i need any further plugins and so have gone to run the application. Upon clicking on it i get the "ERROR:  volatility.debug    You must specify something to do (try -h)". I have just installed the standalone as usual and nothing else and this message is displaying, does anyone know what else i need to do or try? I have Python installed and have tried with admin rights too to run it and nothing?

**Comment by vitnit** [comment]
Hello Xlon550! I am getting the same error. Did you find any solution? 
Error when running the standalone Windows exe.

**Comment by Jest25** [comment]
You have to run it through a terminal (powershell or cmd , etc.).
If you have it installed in C:\Users\abc\volatility_2.6_win64_standalone
once you traverse to that directory in your terminal, just do .\volatility_2.6_win64_standalone.exe 
Keep in mind however that  volatility gives an error by default if you don't provide any arguments or input files, hence why the double click on the exe gives an error.

example command
`.\volatility_2.6_win64_standalone -f samplefile.e01 imageinfo`

Hope this helps

**Comment by tak1l** [comment]
thanks!

**Comment by meeshou78** [comment]
Installed the standalone runs great about 2 or 3 times then says This app can't run on your PC. To find a version for your PC contact the publisher.
