### ISSUE TITLE
Update Windows 10 profiles to inlcude Win10x64_16299

### ISSUE THREAD

**Issue by averagejoe365** [volatilityfoundation/volatility#519]
I am uncertain on how to go about updating Volatility that is installed on my VM Kali Linux running in VMWare. I located the following links that contain updates for vtypes at https://github.com/volatilityfoundation/volatility/commit/f1d1ed283f3052035d2fca85cb24500ad1d703e1 and https://github.com/volatilityfoundation/volatility/commit/179d206d3d0c7d0045ca23ee465416cc44e5f480 . I have attempted to use "git" on both, as well as apt-get xxx.., but nothing seems to be adding these new profiles. 

Can anyone advise if there is a specific way to add this new profile to perform analysis on a memory capture that was pulled from a Windows 10 host running the 16299 build?

**Comment by markaidev** [comment]
Here is the sequence of commands that will work.

git clone https://github.com/volatilityfoundation/volatility.git
cd volatility
chmod 755 setup.py
./setup.py install

Verify that the new profiles were added with ./vol.py --info

**Comment by gleeda** [comment]
Let us know if the solution supplied by @markaidev didn't work for you.

**Comment by hledger** [comment]
Thanks for the note. very helpful to fix the volatility profile issue. If we hit a volatility profile road block, please ensure if are running the latest update. For linux systems, a apt-get update and upgrade should fix.
