### ISSUE TITLE
Getting Overflowerror: range() result has too many items running hivelist

### ISSUE THREAD

**Issue by dragosgr** [volatilityfoundation/volatility#523]
When I run on a memory dump hivelist i get this error. Here's the output
![error](https://user-images.githubusercontent.com/18038041/41348278-d7b6d088-6f14-11e8-9d51-6bbdd7ac145b.PNG)

**Comment by atcuno** [comment]
Hey @dragosgr,

Can you please confirm which version of Volatility you are using (standalone, latest git pull, some git revisions, ...)?

**Comment by dragosgr** [comment]
I was using the standalone version. Now I am using the latest git pull and it worked. Thanks a lot:)!

**Comment by atcuno** [comment]
Great! Thanks for following up!
