### ISSUE TITLE
Win10x64_15063 issue

### ISSUE THREAD

**Issue by AndreasProof** [volatilityfoundation/volatility#525]
Hello all,

I am having problems with viewing the reg files from a Win10x64_15063 memory dump. I have dumped it using FTK Imager  initially, and then tried with DumpIT. And when i run hivelist/hivescan or printkey, i don't get any output. DO you think that this is a Vol issue for this profile or the tool i used to dump the memory?

Thank you all!

**Comment by Beercow** [comment]
Looks like the same issue as #488 and unrelated to the acquisition tool.
