### ISSUE TITLE
Outdated Mac wiki page

### ISSUE THREAD

**Issue by jipegit** [volatilityfoundation/volatility#531]
The Mac wiki page at https://github.com/volatilityfoundation/volatility/wiki/Mac is outdated. 

**Creating a profile**
 DebugKit is a not a dmg file anymore but a pkg file that will install itself in /Library/Devloper/KDKs/KDK_X.Y.Z.kdk

**creating-the-vtypes** Step 1:
mach_kernel.dSYM is now located at [/Library/Devloper/KDKs/KDK_X.Y.Z.kdk]/System/Library/kernels/kernel.dSYM

**symbol-information**
mach_kernel does not exist anymore and is now located at  [/Library/Devloper/KDKs/KDK_X.Y.Z.kdk]/System/Library/kernels/kernel

**Comment by arun057** [comment]
Came here to say this, bump!
