### ISSUE TITLE
linux_tmpfs not extracting files

### ISSUE THREAD

**Issue by Enz197** [volatilityfoundation/volatility#532]
Working with Volatility 2.6 in order to extract info from a memory dump of a linux live distro:
- converted a vmem file
- created ad hoc linux profile

Some plugins are ok, for example linux_pslist and linux_psscan, while the plugin linux_tmpfs works only with the option -L but fails to extract the files.

Those are the warnings and errors.

$ python vol.py --profile=Linux1404-440x64 -f vmem.dump linux_tmpfs -L
Volatility Foundation Volatility Framework 2.6
1 -> /run/lock
2 -> /run
3 -> /run/shm
4 -> /tmp
5 -> /sys/fs/cgroup
6 -> /run/user
7 -> /cow

$ python vol.py --profile=Linux1404-440x64 -f vmem.dump linux_tmpfs -S 2 -D tmpfs
Volatility Foundation Volatility Framework 2.6
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/common.py", line 67, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "/home/sansforensics/Desktop/volatility/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/tmpfs.py", line 155, in render_text
    for (i, path) in data:
  File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/tmpfs.py", line 141, in calculate
    self.walk_sb(root_dentry)
  File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/tmpfs.py", line 101, in walk_sb
    self.process_directory(root_dentry, parent = cur_dir)
  File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/tmpfs.py", line 81, in process_directory
    f = open(new_file, "wb")
IOError: [Errno 21] Is a directory: 'tmpfs/'

$ python vol.py --profile=Linux1404-440x64 -f vmem.dump linux_tmpfs -S 3 -D tmpfs
Volatility Foundation Volatility Framework 2.6
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String

$ python vol.py --profile=Linux1404-440x64 -f vmem.dump linux_tmpfs -S 4 -D tmpfs
Volatility Foundation Volatility Framework 2.6
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String

$ python vol.py --profile=Linux1404-440x64 -f vmem.dump linux_tmpfs -S 5 -D tmpfs
Volatility Foundation Volatility Framework 2.6
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String

$ python vol.py --profile=Linux1404-440x64 -f vmem.dump linux_tmpfs -S 6 -D tmpfs
Volatility Foundation Volatility Framework 2.6
WARNING : volatility.debug    : NoneObject as string: Invalid offset 0 for dereferencing name as String

$ python vol.py --profile=Linux1404-440x64 -f vmem.dump linux_tmpfs -S 7 -D tmpfs
Volatility Foundation Volatility Framework 2.6
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/common.py", line 67, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "/home/sansforensics/Desktop/volatility/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/tmpfs.py", line 155, in render_text
    for (i, path) in data:
  File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/tmpfs.py", line 141, in calculate
    self.walk_sb(root_dentry)
  File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/tmpfs.py", line 101, in walk_sb
    self.process_directory(root_dentry, parent = cur_dir)
  File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/tmpfs.py", line 81, in process_directory
    f = open(new_file, "wb")
IOError: [Errno 21] Is a directory: 'tmpfs/'

Am I doing wrong or is there something to fix?
Thanks in advance.

Enz

**Comment by kry97on** [comment]
> Working with Volatility 2.6 in order to extract info from a memory dump of a linux live distro:
> 
>     * converted a vmem file
> 
>     * created ad hoc linux profile
> 
> 
> Some plugins are ok, for example linux_pslist and linux_psscan, while the plugin linux_tmpfs works only with the option -L but fails to extract the files.
> 
> Those are the warnings and errors.
> 
> $ python vol.py --profile=Linux1404-440x64 -f vmem.dump linux_tmpfs -L
> Volatility Foundation Volatility Framework 2.6
> 1 -> /run/lock
> 2 -> /run
> 3 -> /run/shm
> 4 -> /tmp
> 5 -> /sys/fs/cgroup
> 6 -> /run/user
> 7 -> /cow
> 
> $ python vol.py --profile=Linux1404-440x64 -f vmem.dump linux_tmpfs -S 2 -D tmpfs
> Volatility Foundation Volatility Framework 2.6
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> Traceback (most recent call last):
> File "vol.py", line 192, in
> main()
> File "vol.py", line 183, in main
> command.execute()
> File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/common.py", line 67, in execute
> commands.Command.execute(self, *args, **kwargs)
> File "/home/sansforensics/Desktop/volatility/volatility/commands.py", line 147, in execute
> func(outfd, data)
> File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/tmpfs.py", line 155, in render_text
> for (i, path) in data:
> File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/tmpfs.py", line 141, in calculate
> self.walk_sb(root_dentry)
> File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/tmpfs.py", line 101, in walk_sb
> self.process_directory(root_dentry, parent = cur_dir)
> File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/tmpfs.py", line 81, in process_directory
> f = open(new_file, "wb")
> IOError: [Errno 21] Is a directory: 'tmpfs/'
> 
> $ python vol.py --profile=Linux1404-440x64 -f vmem.dump linux_tmpfs -S 3 -D tmpfs
> Volatility Foundation Volatility Framework 2.6
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> 
> $ python vol.py --profile=Linux1404-440x64 -f vmem.dump linux_tmpfs -S 4 -D tmpfs
> Volatility Foundation Volatility Framework 2.6
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> 
> $ python vol.py --profile=Linux1404-440x64 -f vmem.dump linux_tmpfs -S 5 -D tmpfs
> Volatility Foundation Volatility Framework 2.6
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> 
> $ python vol.py --profile=Linux1404-440x64 -f vmem.dump linux_tmpfs -S 6 -D tmpfs
> Volatility Foundation Volatility Framework 2.6
> WARNING : volatility.debug : NoneObject as string: Invalid offset 0 for dereferencing name as String
> 
> $ python vol.py --profile=Linux1404-440x64 -f vmem.dump linux_tmpfs -S 7 -D tmpfs
> Volatility Foundation Volatility Framework 2.6
> Traceback (most recent call last):
> File "vol.py", line 192, in
> main()
> File "vol.py", line 183, in main
> command.execute()
> File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/common.py", line 67, in execute
> commands.Command.execute(self, *args, **kwargs)
> File "/home/sansforensics/Desktop/volatility/volatility/commands.py", line 147, in execute
> func(outfd, data)
> File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/tmpfs.py", line 155, in render_text
> for (i, path) in data:
> File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/tmpfs.py", line 141, in calculate
> self.walk_sb(root_dentry)
> File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/tmpfs.py", line 101, in walk_sb
> self.process_directory(root_dentry, parent = cur_dir)
> File "/home/sansforensics/Desktop/volatility/volatility/plugins/linux/tmpfs.py", line 81, in process_directory
> f = open(new_file, "wb")
> IOError: [Errno 21] Is a directory: 'tmpfs/'
> 
> Am I doing wrong or is there something to fix?
> Thanks in advance.
> 
> Enz
have you  fixed this,?
then how, please replay, iam now faceing the same

**Comment by rhergenreder** [comment]
I know this issue is already 2 years old, but is there any progress or news related to this issue, as there was no real comment/solution/workaround on this..

**Comment by Enz197** [comment]
I haven't fixed it and nobody answered this request

**Comment by pagabuc** [comment]
Can you share the memory dump and the profile you are using?

**Comment by rhergenreder** [comment]
I analysed a bit further and i noticed, that the memory dump i got is truncated, as alot of memory addresses from executables were not readable. I thought this issue would be a general issue. Unfortunately, I don't know if i'm allowed to share the memory dump (Got it from a hacking challenge site).

**Comment by atcuno** [comment]
If someone can reproduce this with a sample that I can get a copy of then I can investigate it. It seems like it would have to be a pretty broken sample to reach these code paths. Please re-open if you can provide a sample exhibiting the behaviour.
