### ISSUE TITLE
linux_find_file doesn't work

### ISSUE THREAD

**Issue by cpuu** [volatilityfoundation/volatility#534]
I read a post : https://volatility-labs.blogspot.com/2012/09/movp-35-analyzing-2008-dfrws-challenge.html

the page shows that file extraction is possible through **linux_find_file** command

I used the same method with correct value = 0xffff88007bd8e698 
however it does not work!!

What's the problem? of my mistake??

```
sep@sep-gpu1:~/volatility$ python vol.py -f ../neurosurgery/image --profile=LinuxUbuntu16_04_4_4_0-116-genericx64 linux_find_file -F /home/panda/ht0p
Volatility Foundation Volatility Framework 2.6
Inode Number                  Inode File Path
---------------- ------------------ ---------
          390593 0xffff88007bd8e698 /home/panda/ht0p
sep@sep-gpu1:~/volatility$
sep@sep-gpu1:~/volatility$ python vol.py -f ../neurosurgery/image --profile=LinuxUbuntu16_04_4_4_0-116-genericx64 linux_find_file -i 0xffff88007bd8e698 -O ht0p
Volatility Foundation Volatility Framework 2.6
sep@sep-gpu1:~/volatility$
sep@sep-gpu1:~/volatility$ cat ht0p
sep@sep-gpu1:~/volatility$
sep@sep-gpu1:~/volatility$ python vol.py -f ../neurosurgery/image --profile=LinuxUbuntu16_04_4_4_0-116-genericx64 linux_find_file -i 0xffff88007bd8e698
Volatility Foundation Volatility Framework 2.6
ERROR   : volatility.debug    : Incorrect command line parameters given.
```

-O argument gives me an empty file..

**Comment by cpuu** [comment]
Oh..! the release version 2.6 (on 30 Dec 2016) works well!
It looks like some updates caused the bugs..

`~/volatility-2.6$ sudo python vol.py -f ../neurosurgery/image --profile=LinuxUbuntu16_04_4_4_0-116-genericx64 linux_fin
Volatility Foundation Volatility Framework 2.6
sep@sep-gpu1:~/volatility-2.6$ ls
AUTHORS.txt  build  CHANGELOG.txt  contrib  CREDITS.txt  dist  ht0p  LEGAL.txt  LICENSE.txt  Makefile  MANIFEST.in  PKG-INFO  pyinst
sep@sep-gpu1:~/volatility-2.6$ file ht0p
ht0p: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=015d3ac9f4ba5`

**Comment by atcuno** [comment]
Would it be possible to share your memory capture?

**Comment by cpuu** [comment]
This image comes from ‘Timisoara CTF 2018 Quals’.
link : https://drive.google.com/open?id=1IKI7Pn73y8L2u-znw3H7PLYhzSAtYJRK

profile : https://cpuu.postype.com/file/download/3479488
