### ISSUE TITLE
Empty result on psscan with Windows 7 virtualbox memory images

### ISSUE THREAD

**Issue by jestrada78** [volatilityfoundation/volatility#536]
Hello.
I acquire a 4GB memory dump from a virtualbox Windows 7 machine. When I execute "vol.py -f mem.dmp --profile=Win7SP1x64 pslist" I get the proccesses list, but if I run the same but with **psscan** the result is always empty. I have acquired the memory with several tools (dumpit, winpmem, ramcapturer, memoryze) and with vboxmanage but always the same result. I am running virtualbox 5.2.12 on a Windows 10. If you need more information please just ask me. 
I tried the same with a laptop memory sample (the same Windows7), at the begining it seems it was going to be the same but with the correct profile (Win7SP1x64) it works (with the virtualbox sample never works).
Any help would be apreciated.
Thank you.

**Comment by gleeda** [comment]
Have you tried one of the newer profiles:  `Win7SP1x64_23418` or `Win7SP1x64_24000` ?

**Comment by jestrada78** [comment]
First thank you. 
With the 23418 I've got the same and the 24000 seems not being available in what I downloaded.

**Comment by jestrada78** [comment]
Like I don't know how to use the Win7SP1x64_24000 although I can see it there in the filesystem, I changed his name from Win7SP1x64_24000.py and pyc to Win7SP1x64.py and pyc. And now I can see the results, it works!! **psscan runs good**. Can you explain me how to use the Win7SP1x64_24000 without having to do the name changing, excuse me I'm starting with volatility.
Thank you.
