### ISSUE TITLE
Volatility support for Windows 10 Pro Build 17134.191

### ISSUE THREAD

**Issue by srthomson** [volatilityfoundation/volatility#539]
The plugins for volatility do not work correctly for this build of Windows 10 - is there any indication of when a new release might be made available that addresses this?

**Comment by jared703** [comment]
What Windows 10 build are you using? What tool did you acquire your physical memory image with? Looking at the latest Python build the following Win10 profiles are available. Remember the compiled Volatility application doesn't always have the latest profiles baked in. 
-------------------------------------------------------------------------------------------
Win10x64              - A Profile for Windows 10 x64
Win10x64_10240_17770  - A Profile for Windows 10 x64 (10.0.10240.17770 / 2018-02-10)
Win10x64_10586        - A Profile for Windows 10 x64 (10.0.10586.306 / 2016-04-23)
Win10x64_14393        - A Profile for Windows 10 x64 (10.0.14393.0 / 2016-07-16)
Win10x64_15063        - A Profile for Windows 10 x64 (10.0.15063.0 / 2017-04-04)
Win10x64_16299        - A Profile for Windows 10 x64 (10.0.16299.0 / 2017-09-22)
Win10x64_17134        - A Profile for Windows 10 x64 (10.0.17134.1 / 2018-04-11)
Win10x86              - A Profile for Windows 10 x86
Win10x86_10240_17770  - A Profile for Windows 10 x86 (10.0.10240.17770 / 2018-02-10)
Win10x86_10586        - A Profile for Windows 10 x86 (10.0.10586.420 / 2016-05-28)
Win10x86_14393        - A Profile for Windows 10 x86 (10.0.14393.0 / 2016-07-16)
Win10x86_15063        - A Profile for Windows 10 x86 (10.0.15063.0 / 2017-04-04)
Win10x86_16299        - A Profile for Windows 10 x86 (10.0.16299.15 / 2017-09-29)
Win10x86_17134        - A Profile for Windows 10 x86 (10.0.17134.1 / 2018-04-11)

**Comment by srthomson** [comment]
OS Build I am using is 17134.191 - would Win10x63_17134 support this build, even though the OS Build I use is from July 2018, and this profile is from April 2018 - thus I suspect not.
I used F-Response to capture the image, so it is in .E01 format.

**Comment by jared703** [comment]
@srthomson -- i'd try it and see what happens.

**Comment by iMHLv2** [comment]
Its likely that `Win10x63_17134` would work. The difference in minor/revision numbers (i.e. `.191`) doesn't usually change things significantly. The bigger problem is your `.E01` which Volatility doesn't natively support, so you'll need to convert that to a raw memory sample first. If you acquired over a slow network link without compression, its also possible you will have some smearing/corruption in the sample. You might take a look at Surge (https://www.volexity.com/products-overview/surge) if that becomes a common problem that you see. In any case, let us know how it goes. If you need further assistance, any command lines you can provide, along with the output and/or error messages you received, would be critical in helping to troubleshoot.

**Comment by gleeda** [comment]
Actually you can just mount the memory as a network share using EnCase or FTK imager instead of converting to raw: https://github.com/volatilityfoundation/volatility/wiki/EWF-Address-Space#alternative-methods

**Comment by Fahd4world** [comment]
Same issue and I have tried Win10x63_17134 but it didnt recogonize it ( I dont know where you get it guys they didnt provide it here
https://github.com/volatilityfoundation/volatility/wiki/2.6-Win-Profiles/

the error message says:
Volatility Foundation Volatility Framework 2.6
ERROR   : volatility.debug    : Invalid profile Win10x64_17134 selected

command: volatility -f test.raw --profile=Win10x64_17134 netscan

I use RAW files
I am already win 10x64 built 17134.228
I tried many versions but still giving me errors

any solution !?

**Comment by colincowie** [comment]
While using the `Win10x64_17134` profile on Windows 10 17134.228 (8/25/2018) I either receive the error `AttributeError: Could not list modules, please verify your --profile with kdbgscan`  or receive no results at all. 

The memory capture was a snapshot from vmware that was converted to a .raw using imagecopy
