### ISSUE TITLE
Samples on volatility github can not be investigated

### ISSUE THREAD

**Issue by ymxncbv** [volatilityfoundation/volatility#545]
Dear Team, I am new to Volatility and trying to play with the tool. I downloaded several images from the volatility github page (https://github.com/volatilityfoundation/volatility/wiki/Memory-Samples), but the tool can not recognize them. The same goes for the images downloaded from https://www.memoryanalysis.net/amf. 

root@kali:~/Volatility# volatility -f sample001.bin imageinfo
Volatility Foundation Volatility Framework 2.6
INFO    : volatility.debug    : Determining profile based on KDBG search...
          Suggested Profile(s) : No suggestion (Instantiated with no profile)
                     AS Layer1 : FileAddressSpace (/root/Volatility/sample001.bin)
                      PAE type : No PAE

Please advise!

Thank you!

**Comment by atcuno** [comment]
Can you please reopen if this is still an issue? I would suggest redownloading the memory sample(s) if possible.
