### ISSUE TITLE
pslist only shows the system process on a Win7SP1x64 memory image

### ISSUE THREAD

**Issue by adimenia** [volatilityfoundation/volatility#546]
hello, I have a memory image of a Windows 7 x64 machine, taken from a virtual machine.
when running the following command volatility_2.6_win64_standalone.exe --profile=Win7SP1x64 -f C:\infected.vmem pslist, I get the following output:
Volatility Foundation Volatility Framework 2.6
Name                                                  Pid   PPid   Thds   Hnds Time
-------------------------------------------------- ------ ------ ------ ------ ----
 0xfffffa8003c6d9e0:System                              4      0    109 ------ 2018-09-11 10:50:18 UTC+0000

i have tried to execute the kdbgscan --force plugin and i get the following output:
Instantiating KDBG using: Kernel AS Win7SP1x64 (6.1.7601 64bit)
Offset (V)                    : 0xf80002bfc0a0
Offset (P)                    : 0x2bfc0a0
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win7SP1x64
Version64                     : 0xf80002bfc068 (Major: 15, Minor: 7601)
Service Pack (CmNtCSDVersion) : 1
Build string (NtBuildLab)     : 7601.17514.amd64fre.win7sp1_rtm.
PsActiveProcessHead           : 0xfffff80002c32b90 (1 processes)
PsLoadedModuleList            : 0xfffff80002c50e90 (54 modules)
KernelBase                    : 0xfffff80002a0b000 (Matches MZ: True)
Major (OptionalHeader)        : 6
Minor (OptionalHeader)        : 1
KPCR                          : 0xfffff80002bfdd00 (CPU 0)

**************************************************
Instantiating KDBG using: Kernel AS Win7SP0x64 (6.1.7600 64bit)
Offset (V)                    : 0xf80002bfc0a0
Offset (P)                    : 0x2bfc0a0
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win7SP0x64
Version64                     : 0xf80002bfc068 (Major: 15, Minor: 7601)
Service Pack (CmNtCSDVersion) : 1
Build string (NtBuildLab)     : 7601.17514.amd64fre.win7sp1_rtm.
PsActiveProcessHead           : 0xfffff80002c32b90 (1 processes)
PsLoadedModuleList            : 0xfffff80002c50e90 (54 modules)
KernelBase                    : 0xfffff80002a0b000 (Matches MZ: True)
Major (OptionalHeader)        : 6
Minor (OptionalHeader)        : 1
KPCR                          : 0xfffff80002bfdd00 (CPU 0)

**************************************************
Instantiating KDBG using: Kernel AS Win2008R2SP1x64 (6.1.7601 64bit)
Offset (V)                    : 0xf80002bfc0a0
Offset (P)                    : 0x2bfc0a0
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win2008R2SP1x64
Version64                     : 0xf80002bfc068 (Major: 15, Minor: 7601)
Service Pack (CmNtCSDVersion) : 1
Build string (NtBuildLab)     : 7601.17514.amd64fre.win7sp1_rtm.
PsActiveProcessHead           : 0xfffff80002c32b90 (1 processes)
PsLoadedModuleList            : 0xfffff80002c50e90 (54 modules)
KernelBase                    : 0xfffff80002a0b000 (Matches MZ: True)
Major (OptionalHeader)        : 6
Minor (OptionalHeader)        : 1
KPCR                          : 0xfffff80002bfdd00 (CPU 0)

**************************************************
Instantiating KDBG using: Kernel AS Win7SP1x64_23418 (6.1.7601 64bit)
Offset (V)                    : 0xf80002bfc0a0
Offset (P)                    : 0x2bfc0a0
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win7SP1x64_23418
Version64                     : 0xf80002bfc068 (Major: 15, Minor: 7601)
Service Pack (CmNtCSDVersion) : 1
Build string (NtBuildLab)     : 7601.17514.amd64fre.win7sp1_rtm.
PsActiveProcessHead           : 0xfffff80002c32b90 (1 processes)
PsLoadedModuleList            : 0xfffff80002c50e90 (54 modules)
KernelBase                    : 0xfffff80002a0b000 (Matches MZ: True)
Major (OptionalHeader)        : 6
Minor (OptionalHeader)        : 1
KPCR                          : 0xfffff80002bfdd00 (CPU 0)

**************************************************
Instantiating KDBG using: Kernel AS Win2008R2SP0x64 (6.1.7600 64bit)
Offset (V)                    : 0xf80002bfc0a0
Offset (P)                    : 0x2bfc0a0
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win2008R2SP0x64
Version64                     : 0xf80002bfc068 (Major: 15, Minor: 7601)
Service Pack (CmNtCSDVersion) : 1
Build string (NtBuildLab)     : 7601.17514.amd64fre.win7sp1_rtm.
PsActiveProcessHead           : 0xfffff80002c32b90 (1 processes)
PsLoadedModuleList            : 0xfffff80002c50e90 (54 modules)
KernelBase                    : 0xfffff80002a0b000 (Matches MZ: True)
Major (OptionalHeader)        : 6
Minor (OptionalHeader)        : 1
KPCR                          : 0xfffff80002bfdd00 (CPU 0)

**************************************************
Instantiating KDBG using: Kernel AS Win2008R2SP1x64_23418 (6.1.7601 64bit)
Offset (V)                    : 0xf80002bfc0a0
Offset (P)                    : 0x2bfc0a0
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win2008R2SP1x64_23418
Version64                     : 0xf80002bfc068 (Major: 15, Minor: 7601)
Service Pack (CmNtCSDVersion) : 1
Build string (NtBuildLab)     : 7601.17514.amd64fre.win7sp1_rtm.
PsActiveProcessHead           : 0xfffff80002c32b90 (1 processes)
PsLoadedModuleList            : 0xfffff80002c50e90 (54 modules)
KernelBase                    : 0xfffff80002a0b000 (Matches MZ: True)
Major (OptionalHeader)        : 6
Minor (OptionalHeader)        : 1
KPCR                          : 0xfffff80002bfdd00 (CPU 0)

I tried supplying the kdbg offset like this: olatility_2.6_win64_standalone.exe --profile=Win7SP1x64 --kdbg=0xf80002bfc0a0 -f C:\infected.vmem pslist
but it did not solve the issue.

**Comment by adimenia** [comment]
UPDATE
when running the pssan plugin i get a list of the running processes, but pslist and pstree faile to show all the running processes
C:\volatility_2.5.win.standalone>volatility-2.5.standalone.exe --profile=Win7SP1x64 -f C:\infected.vmem psscan
Volatility Foundation Volatility Framework 2.5
Offset(P)          Name                PID   PPID PDB                Time created                   Time exited         
------------------ ---------------- ------ ------ ------------------ ------------------------------ ------------------------------
0x000000000746d9e0 System                4      0 0x0000000000187000 2018-09-11 10:50:18 UTC+0000                       
0x00000000fc805970 chrome.exe         2124   2656 0x0000000111cd6000 2018-09-11 12:12:24 UTC+0000   2018-09-11 12:14:35 UTC+0000
0x00000000fc8209e0 taskeng.exe         768    908 0x000000012ea4c000 2018-09-11 12:12:08 UTC+0000                       
0x00000000fc858b30 cmd.exe             456   1508 0x0000000018b58000 2018-09-11 12:15:38 UTC+0000   2018-09-11 12:15:38 UTC+0000
0x00000000fc85f060 dllhost.exe        2632    636 0x000000005cccf000 2018-09-11 12:14:47 UTC+0000   2018-09-11 12:14:52 UTC+0000
0x00000000fc889b30 SearchProtocol     3644   2476 0x000000000ab63000 2018-09-11 12:13:57 UTC+0000                       
0x00000000fc8a1b30 chrome.exe         3516   2124 0x00000000b72b1000 2018-09-11 12:12:34 UTC+0000   2018-09-11 12:14:35 UTC+0000
0x00000000fc8bdb30 conhost.exe        3572    428 0x00000000273ed000 2018-09-11 11:56:56 UTC+0000   2018-09-11 11:57:09 UTC+0000
0x00000000fc961b30 chrome.exe         2752   2124 0x0000000129bae000 2018-09-11 12:14:13 UTC+0000   2018-09-11 12:14:32 UTC+0000
0x00000000fcac1b30 netsh.exe          4044   3436 0x000000010d8b1000 2018-09-11 11:56:56 UTC+0000   2018-09-11 11:57:01 UTC+0000
0x00000000fcbe8630 taskhost.exe        832    520 0x000000007d07d000 2018-09-11 12:13:52 UTC+0000                       
0x00000000fd094b30 dllhost.exe        2372    636 0x000000002745c000 2018-09-11 12:14:27 UTC+0000   2018-09-11 12:14:32 UTC+0000
0x00000000fd20f4a0 WmiPrvSE.exe       4084    636 0x0000000107e56000 2018-09-11 11:52:30 UTC+0000                       
0x00000000fd3454b0 mscorsvw.exe       2848    520 0x0000000026f6d000 2018-09-11 10:51:56 UTC+0000                       
0x00000000fd351b30 WmiPrvSE.exe       2016    636 0x000000006fbe7000 2018-09-11 10:51:06 UTC+0000                       
0x00000000fd38c630 svchost.exe        1888    520 0x0000000070177000 2018-09-11 10:51:06 UTC+0000                       
0x00000000fd42f190 spoolsv.exe        1184    520 0x0000000060f85000 2018-09-11 10:50:52 UTC+0000                       
0x00000000fd43ca30 svchost.exe        1212    520 0x00000000786cd000 2018-09-11 10:50:53 UTC+0000                       
0x00000000fd492390 svchost.exe        1336    520 0x0000000077d74000 2018-09-11 10:50:53 UTC+0000                       
0x00000000fd4d5730 wmpnetwk.exe       1104    520 0x0000000118711000 2018-09-11 10:52:29 UTC+0000                       
0x00000000fd565b30 VGAuthService.     1460    520 0x000000005dd98000 2018-09-11 10:50:56 UTC+0000                       
0x00000000fd57ab30 vmtoolsd.exe       1508    520 0x000000005c71e000 2018-09-11 10:50:57 UTC+0000                       
0x00000000fd5c1b30 ManagementAgen     1580    520 0x000000005608c000 2018-09-11 10:51:01 UTC+0000                       
0x00000000fd9704f0 svchost.exe         844    520 0x0000000082bb8000 2018-09-11 10:50:44 UTC+0000                       
0x00000000fd9b1690 svchost.exe         876    520 0x00000000826c0000 2018-09-11 10:50:45 UTC+0000                       
0x00000000fd9bdb30 svchost.exe         908    520 0x000000008344a000 2018-09-11 10:50:45 UTC+0000                       
0x00000000fdb4b8d0 audiodg.exe        3564    844 0x000000013a5dd000 2018-09-11 11:52:18 UTC+0000                       
0x00000000fdbe1060 SearchIndexer.     2476    520 0x0000000049c49000 2018-09-11 10:51:20 UTC+0000                       
0x00000000fdc1b1a0 svchost.exe         744    520 0x0000000083afd000 2018-09-11 10:50:44 UTC+0000                       
0x00000000fdc88890 SearchFilterHo     3844   2476 0x00000000010ec000 2018-09-11 12:13:57 UTC+0000                       
0x00000000fdeddb30 wininit.exe         412    368 0x0000000080681000 2018-09-11 10:50:32 UTC+0000                       
0x00000000fdee4b30 csrss.exe           428    420 0x000000008dc66000 2018-09-11 10:50:32 UTC+0000                       
0x00000000fdf11910 winlogon.exe        476    420 0x000000008c16c000 2018-09-11 10:50:32 UTC+0000                       
0x00000000fdf1a360 svchost.exe         636    520 0x00000000844d7000 2018-09-11 10:50:42 UTC+0000                       
0x00000000fdf1e8a0 dllhost.exe        4044    636 0x000000007dbe9000 2018-09-11 12:14:47 UTC+0000   2018-09-11 12:14:52 UTC+0000
0x00000000fdfa3910 services.exe        520    412 0x00000000896cd000 2018-09-11 10:50:33 UTC+0000                       
0x00000000fdfbbb30 lsass.exe           536    412 0x000000008a073000 2018-09-11 10:50:33 UTC+0000                       
0x00000000fdfc4b30 lsm.exe             544    412 0x000000008a17d000 2018-09-11 10:50:33 UTC+0000                       
0x00000000fdfc6360 vmacthlp.exe        700    520 0x0000000083ff1000 2018-09-11 10:50:43 UTC+0000                       
0x00000000fe67f060 ipconfig.exe        936    456 0x0000000018691000 2018-09-11 12:15:38 UTC+0000   2018-09-11 12:15:38 UTC+0000
0x00000000fe686b30 msdtc.exe          1968    520 0x0000000052232000 2018-09-11 10:51:13 UTC+0000                       
0x00000000fe714b30 svchost.exe         372    520 0x000000007c7de000 2018-09-11 10:50:48 UTC+0000                       
0x00000000fe77f780 svchost.exe        1064    520 0x00000000797e8000 2018-09-11 10:50:51 UTC+0000                       
0x00000000fe9443a0 smss.exe            292      4 0x00000000a4c47000 2018-09-11 10:50:18 UTC+0000                       
0x00000000febd3b30 csrss.exe           376    368 0x000000009d3fb000 2018-09-11 10:50:25 UTC+0000                       
0x00000000fee80b30 conhost.exe        2216    376 0x000000004452d000 2018-09-11 12:15:38 UTC+0000   2018-09-11 12:15:38 UTC+0000
0x00000000fef98b30 chrome.exe         3256   2124 0x0000000025287000 2018-09-11 12:12:24 UTC+0000   2018-09-11 12:14:35 UTC+0000
0x00000000ff1fdb30 chrome.exe         1468   2124 0x00000001178c8000 2018-09-11 12:12:24 UTC+0000   2018-09-11 12:14:35 UTC+0000
0x00000000ff893060 chrome.exe         1392   2124 0x000000012ce5f000 2018-09-11 12:13:24 UTC+0000   2018-09-11 12:14:33 UTC+0000
0x00000000ffa6b870 chrome.exe         2956   2124 0x000000013ae43000 2018-09-11 12:14:13 UTC+0000   2018-09-11 12:14:35 UTC+0000
0x00000000ffd42b30 svchost.exe        3512    520 0x0000000130130000 2018-09-11 10:53:03 UTC+0000                       
0x00000000ffe04b30 taskhost.exe       1992    520 0x00000000250c4000 2018-09-11 10:52:02 UTC+0000                       
0x00000000ffe06b30 dwm.exe            2796    876 0x0000000023dd8000 2018-09-11 10:52:02 UTC+0000                       
0x00000000ffe3b530 explorer.exe       2656   2344 0x00000000249d2000 2018-09-11 10:52:02 UTC+0000                       
0x00000000fff7c060 vmtoolsd.exe       2868   2656 0x000000001a16f000 2018-09-11 10:52:17 UTC+0000

**Comment by ecapuano** [comment]
I'm seeing the exact same thing with another Win7SP1x64 box. (build 7601)

![image](https://user-images.githubusercontent.com/4219694/61399849-9c27f000-a894-11e9-86fd-d6a4527e552b.png)

`pslist` only shows the `system` process, but `psscan` shows all.

**Comment by iMHLv2** [comment]
@ecapuano How did you acquire the memory sample? 

@adimenia It looks like in your case, based on `C:\infected.vmem` you moved the vmem outside of the VM folder...where the corresponding vmss or vmsn was located. Thus, Volatility couldn't find all the data it needed to complete the process list.

**Comment by ecapuano** [comment]
Bah! I might've done the same thing.... Let me retest and circle back.

**Comment by ecapuano** [comment]
Yep, shame on me, that's exactly what it was. Reads the image loud and clear now. 

![image](https://user-images.githubusercontent.com/4219694/61401965-b911f280-a897-11e9-93c7-4ccd73da44cd.png)
