### ISSUE TITLE
Clipboard

### ISSUE THREAD

**Issue by Mino54023** [volatilityfoundation/volatility#548]
Hi,
Could somebody please help me? 
I was changing password to encrypted ext. hdd and I copied mistakenly unknown password. I Immediately did memory dump via DumpIT tool. Later on I tried volatility, I have found module clipboard.. But I get no result. 
C:\Users\xxx\Desktop\Desk\volatility-master>vol.py -f "C:\Users\xxx\Desktop\Desk\Dumps\xxxxxxx.dmp" --profile Win10x64_17134 clipboard -v
Volatility Foundation Volatility Framework 2.6
Session    WindowStation Format                         Handle Object             Data                                  
---------- ------------- ------------------ ------------------ ------------------ --------------------------------------------------

My Win 10 OS build is:  17134.285 and the closed win 10 profile in current version of volatlity is:  Win10x64_17134. Also I tried notepad module because I also copied passwords from notepad, but no luck:
ERROR   : volatility.debug    : This command does not support the profile Win10x64_17134

Does anybody have any ideas, tips, what should I try?

**Comment by colincowie** [comment]
@Mino54023 Are other plugins yielding results?

**Comment by atcuno** [comment]
Hello @Mino54023 

if
