### ISSUE TITLE
Volatility problem

### ISSUE THREAD

**Issue by lokibroki** [volatilityfoundation/volatility#550]
I got the memory dump with `Dumpit`, and when I tried to achive this dump profile with `kdbgscan` I encountered with this problem:

> WARNING : volatility.addrspace: Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow

Why does it happening and how do I fix it?
I have vol2.5*

**Comment by gleeda** [comment]
Please update to volatility 2.6 and try again.

**Comment by PiAil** [comment]
Hi, I have the same problem with a `Dumpit` memory dump and whatever command I give to volatility (I tried `imageinfo`, `kdbgscan` etc.). I have 2.6.

**Comment by vegan22** [comment]
I have the same error with vol 2.6

**Comment by praveenp13** [comment]
I am using volatility 2.6 and getting the same error - Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow.

I created the dump using Dumpit.

**Comment by atcuno** [comment]
Are you using the latest checkout of Volatility from Github? The 2.6 executable is over 2 years old now and very outdated. Please always use the latest source code version

**Comment by praveenp13** [comment]
> Are you using the latest checkout of Volatility from Github? The 2.6 executable is over 2 years old now and very outdated. Please always use the latest source code version

I was trying to use volatility_2.6_win64_standalone.exe.
