### ISSUE TITLE
Win 16299 Hibernation file Header Signature Problems.

### ISSUE THREAD

**Issue by hiberfil** [volatilityfoundation/volatility#554]
I am working on a Windows Hibernation Reasearch however I am having few problems with the recent Windows Releases (10 specifically). 

I converted hiberfil.sys file into a raw file using both Volatility & Hibr2Bin & Bin2DMP(formerly know as MoonSols). However I am getting a the following error for both methods for pslist (or for any function). Anyone know why these files are no longer showing the memory processes? Am I missing something or did windows changed something major in hibernation file structure to prevent us from reading the memory processes. Any help suggestion or explanations from expert folks like yall would be appreciated. 

Ps. I also tried redline & magnet axiom no luck.

volatility -f Hiber_RAM.dmp --profile=Win10x64_16299 pslist

Volatility Foundation Volatility Framework 2.6
No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareAddressSpace: No base Address Space
 QemuCoreDumpElf: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 SkipDuplicatesAMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VMWareMetaAddressSpace: VMware metadata file is not available
 VirtualBoxCoreDumpElf64: ELF Header signature invalid
 VMWareAddressSpace: Invalid VMware signature: 0x45474150
 QemuCoreDumpElf: ELF Header signature invalid
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VMWareMetaAddressSpace: VMware metadata file is not available
 VirtualBoxCoreDumpElf64: ELF Header signature invalid
 VMWareAddressSpace: Invalid VMware signature: -
 QemuCoreDumpElf: ELF Header signature invalid
 WindowsCrashDumpSpace32: Header signature invalid
 SkipDuplicatesAMD64PagedMemory: Failed valid Address Space check
 WindowsAMD64PagedMemory: Failed valid Address Space check
 LinuxAMD64PagedMemory: Incompatible profile Win10x64_16299 selected
 AMD64PagedMemory: Failed valid Address Space check
 IA32PagedMemoryPae: Incompatible profile Win10x64_16299 selected
 IA32PagedMemory: Incompatible profile Win10x64_16299 selected
 OSXPmemELF: ELF Header signature invalid
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: Profile does not have valid Address Space check

**Comment by gleeda** [comment]
We actually don't have support for Windows 10 hibernation files yet.  See issue #25 

closing because this is a duplicate.
