### ISSUE TITLE
Hollowfind Plugin Doesn't Exist

### ISSUE THREAD

**Issue by srgnofstrbn** [volatilityfoundation/volatility#556]
So I try to use hollowfind plugin with command 
`volatility -f stuxnet.vmem --profile=WinXPSP2x86 hollowfind`
But suddenly, I got this error
`Volatility Foundation Volatility Framework 2.6`
`ERROR   : volatility.debug    : You must specify something to do (try -h)`

What should I do? Currently I am using Ubuntu 18.04.1 LTS
Thanks for your attention

**Comment by gleeda** [comment]
The `hollowfind` plugin isn't part of the volatility core, but you can download it from here: https://github.com/monnappa22/HollowFind   Then just put it in the `plugins` directory.

**Comment by srgnofstrbn** [comment]
Thank you very much for your help and kindness, my bad for didn't read the whole hollowfind's page

**Comment by gleeda** [comment]
No worries!  I'm going to close the issue for now, if possible :-)
