### ISSUE TITLE
Problem to try execute --dump-dir

### ISSUE THREAD

**Issue by giograjo** [volatilityfoundation/volatility#557]
Hi.
i have a problem to try execute this comand.

python volatility-master/vol.py bitlocker --dump-dir ./keys/

Volatility Foundation Volatility Framework 2.6
Usage: Volatility - A memory forensics analysis platform.

vol.py: error: no such option: --dump-dir

--the folder "keys" exist, i found in google, a similar issue, and there show a link to download a PATCH because in the version 2.1 "--dump-dir" is disable, but the link is broked.
the link is:
code.google.com/p/volatility/source/detail?r=1628

can you help me with this please.
thanks

**Comment by atcuno** [comment]
It sounds like you are using a very old version of Volatility. Could you please use the latest version and re-open the ticket if you are still encountering this problem?
