### ISSUE TITLE
Issue using procdump, Error: Cannot acquire process AS

### ISSUE THREAD

**Issue by pastrom** [volatilityfoundation/volatility#560]
I've identified a process which seems to be unlinked. Psxview lists it's pid and true for all except for pslist and deskthrd. Psxview does not list it's exit time, so i have a theory it actually is running although unlinked and trying to hide.

Ive tried to dump the process with procdump based on it's pid, but it did not work "Cannot find PID xxx". Therefore I tried to dump it using the offset(p) which were found through pslist. No success with this either.

vol.py -f dump.dmp --profile=Win10x64_15063 procdump -D dump/ --offset=0x00000000f93b0200 

> Error: Cannot acquire process AS

I had a theory that it might be using a technique to make it difficult to dump. So I tried running it with the -u option, but no luck.

Last I tried to dump a random legit process based on its offset, but it just gave the same result as above. 

I considered that the process might not be running after all, but then again I should have got to dump a the random legit process.

Any thoughts?

(Btw. this is a Win10x64_15063 8gb mem- dump)

**Comment by gleeda** [comment]
You said you used the offset from `pslist` ?  Try the offset from `psxview` instead.

**Comment by atcuno** [comment]
Hello @pastrom 

If you still have issues after taking Gleeda's advice then please reopen the ticket. Closing for now.
