### ISSUE TITLE
Document that distorm3 is a core requirement for working with Windows 10 images

### ISSUE THREAD

**Issue by justfalter** [volatilityfoundation/volatility#564]
After consulting with @gleeda, it turns out that analyzing Windows 10 memory images requires distorm3 to be installed. Without distorm3 installed, an attempt to run pslist will show no results. True, it will also show that it was not able to import several plugins because distorm3 was not found, however at no point does it suggest that this is also the reason that I am unable to get anything out of my Windows 10 image: 
```
(env) C:\Users\mike\code\volatility>python vol.py --profile=Win10x64_17134 -f d:\dumps\direct_rc8.dump pslist
Volatility Foundation Volatility Framework 2.6
*** Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.malware.threads (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.mac.apihooks_kernel (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.mac.check_syscall_shadow (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.ssdt (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.mac.apihooks (ImportError: No module named distorm3)
Offset(V)          Name                    PID   PPID   Thds     Hnds   Sess  Wow64 Start                          Exit 
------------------ -------------------- ------ ------ ------ -------- ------ ------ ------------------------------ ------------------------------

(env) C:\Users\mike\code\volatility>
```

It would be helpful if an error message were emitted stating that the analysis of Windows 10 images is not possible when distorm3 is not installed. 

Likewise, the [FAQ's section on dependencies](https://github.com/volatilityfoundation/volatility/wiki/FAQ#what-are-the-dependencies-for-running-volatility) only lists distorm3 as a requirement for "Malware Plugins, Volshell". It should be listed as a core requirement, I think.

**Comment by gleeda** [comment]
Done: https://github.com/volatilityfoundation/volatility/wiki/FAQ  Thanks for submitting the issue :-)
