### ISSUE TITLE
Windows powershell output

### ISSUE THREAD

**Issue by YarovoyD** [volatilityfoundation/volatility#567]
Sorry for asking this stupid question. I'm running volatility from source (python vol.py ...) . In powershell I can't get full Name field for processes with longer names. Volatility column just cuts a process name based on width. I spent some times looking around and it seems like people are facing the same problem, but nobody tells how to resolve it.  I would appreciate any suggestions.

**Comment by atcuno** [comment]
Hello @YarovoyD 

This is a limitation of how Windows stores process names in the EPROCESS structure, and is not something that Volatility can "fix".

Specifically,  if you look at the ImageFileName member:

https://github.com/volatilityfoundation/volatility/blob/master/volatility/plugins/overlays/windows/win8_sp0_x64_vtypes.py#L1171

You will see that it is an array of characters with a limit of 15. This is why process names longer than 15 seemingly get chopped.

To work around this you can attempt to retrieve the full path + command line that the process was running from by looking at its command line arguments:

https://github.com/volatilityfoundation/volatility/blob/master/volatility/plugins/cmdline.py#L66

Note that this information is stored in userland and 1) may be paged out and 2) can be (and sometimes is) manipulated by malware.

I will leave open in case you have any follow up questions.

Thank you for taking the time to write up a ticket.
