### ISSUE TITLE
imageinfo does not work on a windows server 2012 R2 image using ubuntu

### ISSUE THREAD

**Issue by tommyob** [volatilityfoundation/volatility#570]
I am currently trying to run imageinfo on a windows server 2012 R2 image using a ubuntu VM and the command hangs there for over 1 hour with no result...

![image](https://user-images.githubusercontent.com/45545704/49346901-ba730f80-f666-11e8-91db-6bd98aa89a86.png)

**Comment by gleeda** [comment]
What happens if you just run the `kdbgscan` plugin ?

**Comment by 0x3f8** [comment]
I'm in a similar situation.  VM is Kali 2019.1 and volatility 2.6.  The file is a crash dump (memory.dmp) from a windows 2012 R2 64 Bit Datacenter Edition server.

Both imageinfo and kdbgscan hang indefinitely.

```
file MEMORY.DMP 
MEMORY.DMP: MS Windows 64bit crash dump, 4992030524978970960 pages
```

```
volatility -f  MEMORY.DMP imageinfo
Volatility Foundation Volatility Framework 2.6
INFO    : volatility.debug    : Determining profile based on KDBG search...
```

**Comment by atcuno** [comment]
Hey @tommyob 

Please comment and re-open this ticket if you are still having any issues. Closing for now.

**Comment by TeddyBlue** [comment]
I am using winpmem to dump aff4 memory images which cannot be parsed with Ubuntu volatility 2.6. No profile can be identified and image info hangs.
