### ISSUE TITLE
No suitable address space mapping found

### ISSUE THREAD

**Issue by MZSN** [volatilityfoundation/volatility#571]
The system is CIS complaint, and to make the profile I have created a zip using system map and module dwarf.  I have also captured dump using LIME in all formats. But none of them is opening with the profile I have created. RAM size is 16GB and OS is ubuntu 16.04 LTS, image is 4.4.0-139-generic, headers are 4.4.0-139-generic

Please guide me what to do

**Comment by MZSN** [comment]
I am using hypervisor for VMs

**Comment by pagabuc** [comment]
Hey @MZSN, have you tried to pass "timeout=0" to LiME?
