### ISSUE TITLE
No suitable address space mapping found Error Message on Physical Mac High Sierra

### ISSUE THREAD

**Issue by volceryn** [volatilityfoundation/volatility#573]
I'm attempting to run Volatility on a physical macOS High Sierra 10.12.6 using the Mac profiles in the repository.  The memory dump I'm using was generated with OSXPmem.  The issue is that I'm getting the following error message when running any plugin.  I tried running a kdbgscan and psscan
but the results came up empty.

Example:  

python vol.py -f /Users/M1/Documents/Memory_Captures/mem.dump imageinfo

No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 QemuCoreDumpElf: No base Address Space
 VMWareAddressSpace: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 SkipDuplicatesAMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 VMWareMetaAddressSpace: VMware metadata file is not available
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VirtualBoxCoreDumpElf64: ELF Header signature invalid
 QemuCoreDumpElf: ELF Header signature invalid
 VMWareAddressSpace: Invalid VMware signature: 0x4034b50
 WindowsCrashDumpSpace32: Header signature invalid
 SkipDuplicatesAMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 WindowsAMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 LinuxAMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 AMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 IA32PagedMemoryPae: No valid DTB found
 IA32PagedMemory: No valid DTB found
 OSXPmemELF: ELF Header signature invalid
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: No valid DTB found

**Comment by gleeda** [comment]
Hello!  Those plugins only work for Windows.  You will need to download the appropriate Mac profile, specify it, and use Mac plugins instead.

In order to find the appropriate profile, you may try to use `mac_get_profile`: https://github.com/volatilityfoundation/volatility/wiki/Mac-Command-Reference#mac_get_profile  Otherwise, if you know what it is, you can just go ahead and download the appropriate one.

You can find Mac profiles here: https://github.com/volatilityfoundation/profiles

Download it to your `volatility/plugins/mac` folder.  You don't have to unzip it.

Then run `$ python vol.py --info` and see if it shows up under the `Profiles` section, like so:

```Profiles
--------
MacHighSierra_10_13_1_17B48x64 - A Profile for Mac HighSierra_10.13.1_17B48 x64
MacHighSierra_10_13_3_17D47x64 - A Profile for Mac HighSierra_10.13.3_17D47 x64
MacSierra_10_12_6_16G1114x64   - A Profile for Mac Sierra_10.12.6_16G1114 x64
VistaSP0x64                    - A Profile for Windows Vista SP0 x64
[...snip...]
```

At that point, you'll be ready to run some Mac plugins.  Here's a list of some of them: https://github.com/volatilityfoundation/volatility/wiki/Mac-Command-Reference

Then you will run each one like:

`$ python vol.py --profile=[PROFILE_NAME] -f  /Users/M1/Documents/Memory_Captures/mem.dump mac_pslist`

**Comment by volceryn** [comment]
Thank you for the response.  I had downloaded all the MacOS 10.12.6 profiles from the repo and created a custom profile per the instructions listed.  I tried running the command referenced with each profile (9 total) and they all produced a variation of this output:


Offset             Name                 Pid      Uid      Gid      PGID     Bits         DTB                Start Time Ppid    
------------------ -------------------- -------- -------- -------- -------- ------------ ------------------ ---------- --------
No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VMWareAddressSpace: No base Address Space
 QemuCoreDumpElf: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 SkipDuplicatesAMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: PO_MEMORY_IMAGE is not available in profile
 WindowsCrashDumpSpace64BitMap: Header signature invalid
 WindowsCrashDumpSpace64: Header signature invalid
 HPAKAddressSpace: Invalid magic found
 VirtualBoxCoreDumpElf64: ELF Header signature invalid
 VMWareMetaAddressSpace: VMware metadata file is not available
 VMWareAddressSpace: Invalid VMware signature: 0x4034b50
 QemuCoreDumpElf: ELF Header signature invalid
 WindowsCrashDumpSpace32: Header signature invalid
 SkipDuplicatesAMD64PagedMemory: Incompatible profile MacSierra_10_12_6_16G18ax64 selected
 WindowsAMD64PagedMemory: Incompatible profile MacSierra_10_12_6_16G18ax64 selected
 LinuxAMD64PagedMemory: Incompatible profile MacSierra_10_12_6_16G18ax64 selected
 AMD64PagedMemory - EXCEPTION: local variable 'shift_address' referenced before assignment
 IA32PagedMemoryPae - EXCEPTION: local variable 'shift_address' referenced before assignment
 IA32PagedMemory - EXCEPTION: local variable 'shift_address' referenced before assignment
 OSXPmemELF: ELF Header signature invalid
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace - EXCEPTION: local variable 'shift_address' referenced before assignment
