### ISSUE TITLE
Windows 10 Profile

### ISSUE THREAD

**Issue by thall63** [volatilityfoundation/volatility#580]
Volatility is producing garbled output, recent changes to Windows Build are not supported in the Volatility 2.6 Version release. Is there a new profile available? Where can it be downloaded? Anyone else seeing this? Memory images/formats have not changed and are working with other forensics tools.

Edition     Windows 10 Enterprise 2016 LTSB
Version     1607
OS Build 14393.2665
64bit

**Comment by iMHLv2** [comment]
Try using the `Win10x64_14393` profile (you can download a zip of the most recent code from github or check it out with `git clone`).

**Comment by thall63** [comment]
> Try using the `Win10x64_14393` profile (you can download a zip of the most recent code from github or check it out with `git clone`).

Thank you, that is what has been working until the latest update. That profile no longer works.

**Comment by iMHLv2** [comment]
We cannot reproduce this problem and need more information to pursue it.  @thall63 if you would like additional help, please provide the details requested above or you can email the Vol-Users list: https://lists.volatilityfoundation.org/mailman/listinfo/vol-users
