### ISSUE TITLE
Windows 10 14393 Profile no longer works after updates/patches

### ISSUE THREAD

**Issue by thall63** [volatilityfoundation/volatility#581]
Volatility is producing garbled output, recent changes to Windows Build are not supported in the Volatility 2.6 Version release. Is there a new profile available? Where can it be downloaded? Anyone else seeing this? Memory images/formats have not changed and are working with other forensics tools.

Edition Windows 10 Enterprise 2016 LTSB
Version 1607
OS Build 14393.2665
64bit

**Comment by iMHLv2** [comment]
Duplicate of #580
