### ISSUE TITLE
how to add linux profile within kali's volatility

### ISSUE THREAD

**Issue by NY1024** [volatilityfoundation/volatility#582]
as you had written in usage:
sudo zip volatility/volatility/plugins/overlays/linux/Ubuntu1204.zip volatility/tools/linux/module.dwarf /boot/System.map-3.2.0-23-generic 
    adding: volatility/tools/linux/module.dwarf (deflated 89%)
    adding: boot/System.map-3.2.0-23-generic (deflated 79%)

which path"volatility/volatility/plugins/overlays/linux/"only exists when we use vol.py,however,when I use kali's volatility,i am not able to find where to add linux profile

**Comment by mntm** [comment]
It may be under /usr/lib/python2.7/site-packages/...

**Comment by iMHLv2** [comment]
I'm not familiar with kali's volatility, but if you `sudo updatedb && sudo locate volatility` then you should be able to find the right location. Alternately, you can put the plugins anywhere you want (i.e. Desktop) as long as you specify the path using the `--plugins` option to volatility. 

https://github.com/volatilityfoundation/volatility/wiki/Volatility-Usage#specifying-additional-plugin-directories
