### ISSUE TITLE
Windows 10 1809

### ISSUE THREAD

**Issue by ivanko021** [volatilityfoundation/volatility#583]
Pslist, psscan, psxview don't seem to work on Windows 10 1809. I tried all profiles in the documentation. I tried using kdbgscan and it came up with many suggestions for possible profiles but these also didn't work. I cloned the latest files from GitHub. Is there something I'm missing or is there no profile support for 1809 just yet?

**Comment by DrDinosaur** [comment]
I have tried this as well. I'm assuming there is no support for it for now, but they will probably support it in 2.7, whenever that is released.

**Comment by iMHLv2** [comment]
It should be `Win10x64_17763` (assuming 64-bit). Did you try that one? Also, you can confirm the `distorm3` python module is installed on the machine where you're running Volatility? 

The full command line you used and the full kdbgscan output would be very helpful to see. Additionally, how did you capture memory?

**Comment by DrDinosaur** [comment]
It looks like this feature was just added, so I didn't have it on my Kali system. After I downloaded the lastest version of the repo, I was able to get at least pslist to work. However, I had to give a kdbg value to volatility. 

```
Volatility Foundation Volatility Framework 2.6.1
**************************************************
Instantiating KDBG using: Unnamed AS Win10x64_17763 (6.4.17763 64bit)
Offset (V)                    : 0xf8066f21b5e0
Offset (P)                    : 0x241b5e0
KdCopyDataBlock (V)           : 0xf8066ef99640
Block encoded                 : Yes
Wait never                    : 0x83080324017cf10b
Wait always                   : 0xbe78df0b001ba000
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win10x64_17763
Service Pack (CmNtCSDVersion) : -
Build string (NtBuildLab)     : -
PsActiveProcessHead           : 0x6f8bfc066f22b680 (0 processes)
PsLoadedModuleList            : 0x6f8bfc066f237a50 (0 modules)
KernelBase                    : 0x6f8bfc066ee1d000 (Matches MZ: False)
Major (OptionalHeader)        : -
Minor (OptionalHeader)        : -

**************************************************
Instantiating KDBG using: Unnamed AS Win10x64_17763 (6.4.17763 64bit)
Offset (V)                    : 0xf8066f21b5e0
Offset (P)                    : 0x241b5e0
KdCopyDataBlock (V)           : 0xf8066f0a6538
Block encoded                 : Yes
Wait never                    : 0x83080324017cf10b
Wait always                   : 0xbe78df0b001ba000
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win10x64_17763
Version64                     : 0xf8066f21edc0 (Major: 15, Minor: 17763)
Service Pack (CmNtCSDVersion) : 0
Build string (NtBuildLab)     : 17763.1.amd64fre.rs5_release.180
PsActiveProcessHead           : 0xfffff8066f22b680 (164 processes)
PsLoadedModuleList            : 0xfffff8066f237a50 (183 modules)
KernelBase                    : 0xfffff8066ee1d000 (Matches MZ: True)
Major (OptionalHeader)        : 10
Minor (OptionalHeader)        : 0
KPCR                          : 0xfffff8066e0cd000 (CPU 0)
KPCR                          : 0xffffa48100624000 (CPU 1)
```

Once I used, ```--kdbg=0xf8066f0a6538``` that I got from kdbgscan, the profile seemed to work. Thanks.

**Comment by superponible** [comment]
There's a patch that may fix the issue you ran into with needing to provide a `kdbg` offset.  Can you try downloading or cloning the `copy_data_block_order` branch (https://github.com/volatilityfoundation/volatility/tree/copy_data_block_order) and see if `pslist` works without the `kdbg`?

**Comment by DrDinosaur** [comment]
Yep, it works without the kdbg.

**Comment by superponible** [comment]
this has been merged into master

**Comment by achilles4828** [comment]
> There's a patch that may fix the issue you ran into with needing to provide a `kdbg` offset. Can you try downloading or cloning the `copy_data_block_order` branch (https://github.com/volatilityfoundation/volatility/tree/copy_data_block_order) and see if `pslist` works without the `kdbg`?

I recently cloned the master branch | this one is 21 commits behind master |  but  no support for AS of  'ERROR   : volatility.debug    : Invalid profile Win10x64_17763 selected'

**Comment by achilles4828** [comment]
`F:\volatility_2.6_win64_standalone\volatility_2.6_win64_standalone>volatility_2.6_win64_standalone.exe -f C:\Users\hardi\AppData\Local\Temp\YourPhone.DMP imageinfo
Volatility Foundation Volatility Framework 2.6
INFO    : volatility.debug    : Determining profile based on KDBG search...
          Suggested Profile(s) : No suggestion (Instantiated with no profile)
                     AS Layer1 : FileAddressSpace (C:\Users\hardi\AppData\Local\Temp\YourPhone.DMP)
                      PAE type : No PAE

F:\volatility_2.6_win64_standalone\volatility_2.6_win64_standalone>volatility_2.6_win64_standalone.exe -f C:\Users\hardi\AppData\Local\Temp\YourPhone.DMP kdbgscan
Volatility Foundation Volatility Framework 2.6

F:\volatility_2.6_win64_standalone\volatility_2.6_win64_standalone>volatility_2.6_win64_standalone.exe -f C:\Users\hardi\AppData\Local\Temp\YourPhone.DMP --profile=Win10x64_17763 pslist
Volatility Foundation Volatility Framework 2.6
ERROR   : volatility.debug    : Invalid profile Win10x64_17763 selected

F:\volatility_2.6_win64_standalone\volatility_2.6_win64_standalone>`


This is the latest standalone binary from the website.  ||
![image](https://user-images.githubusercontent.com/31269811/59341946-743ded80-8d26-11e9-8509-22f4b200ce74.png)

**Comment by JRamos1993** [comment]
Having the same issue as @achilles4828

**Comment by nkhljswl** [comment]
@achilles4828 

I'm facing same issue. Did you get any solution?
