### ISSUE TITLE
Version 2.6.1 fails to install

### ISSUE THREAD

**Issue by nov3mb3r** [volatilityfoundation/volatility#585]
Just downloaded the newest version, installed it (sudo python setup.py install) but the following error appears
![screenshot_2019-02-07_19-06-06](https://user-images.githubusercontent.com/10418973/52429707-45600280-2b0d-11e9-825b-52cff2a38446.png)

**Comment by alichtman** [comment]
This is a python incompatibility problem. Volatility is written in Python 2.7, and you're trying to install with Python 3.7.

`print "\n"` is valid Python 2.7 syntax, but not valid 3.7 syntax.

Unfortunately, I didn't know how to fix this on my own system, so I don't have any solutions for you.

**Comment by iMHLv2** [comment]
There's no solution right now for using Python3 with Volatility2. Volatility2 requires Python2. A version of Volatility that works with Python3 is under development. I'll close this ticket, but please do check back frequently for the Python3 release.
