### ISSUE TITLE
Many macOS plugins are crashed

### ISSUE THREAD

**Issue by mnrkbys** [volatilityfoundation/volatility#589]
I'm testing Volatility with a memory image of macOS High Sierra 10.13.6 17G5019 and confirmed that many Mac plugins are crashed.

Test environment:
Memory acquisition: OSXPmem 2.1 post4 (converted AFF4 -> ELF)
Volatility profile: Created with Kernel Debug Kit 10.13.6 build 17G5006
Volatility version: 2.6.1 (I downloaded it from GitHub repository on Feb 14, 2019)

All of crashed plugins output the error message of "TypeError: int() argument must be a string or a number, not 'NoneType'".
I verified several source codes of the crashed plugins, and I found the cause of this issue.
They can't refer to kernel symbols, because macOS profile doesn't contain in the symbols.
For example, "mac_arp" plugin needs to refer "_llinfo_arp" but the profile doesn't have it.

Could you correct plugins below?

Crashed plugins:
mac_apihooks_kernel
mac_arp
mac_check_fop
mac_check_mig_table
mac_check_syscalls
mac_dump_maps
mac_interest_handlers
mac_ip_filters
mac_kernel_classes
mac_list_kauth_listeners
mac_list_kauth_scopes
mac_lsmod_iokit
mac_notifiers
mac_recover_filesystem
mac_socket_filters
mac_threads_simple
mac_vfsevents

And, I have a fundamental question. All of mac plugins are still maintaining?

**Comment by atcuno** [comment]
Thank you for the report @mnrkbys. OS X 10.13.6 is fully supported.

Our team looked at your report and a few issues stick out.

1) You listed your memory image as version 17G5019 but your profile as 17G5006. The profile must match the version of the memory sample exactly or no plugins will be guaranteed to work.

2) osxpmem is not a stable memory acquistion tool and is prone to producing corrupt memory samples.

3) If using osxpmem, its best to convert your memory sample to raw (please verify with the 'file' command after that you see 'data'). 

Please let us know if any have any questions.

**Comment by mnrkbys** [comment]
Thank you for your advice @atcuno .
I will attempt to analyze my memory image again.

But Apple doesn't provide Kernel Debug Kit build 17G5019 (see the figure below). Which one is better to analyze 17G5006?
![apple_kernel_debug_kit](https://user-images.githubusercontent.com/26597618/53062457-3e20f780-3504-11e9-8611-cba847213ddb.PNG)

And, I have another question.
What tool do you recommend to aqcuire macOS memory images?

**Comment by mnrkbys** [comment]
Just in case, I rtied 17G6006 and 17G6009 but they don't work (No suitable address space mapping found).
