### ISSUE TITLE
Configuration file not being applied

### ISSUE THREAD

**Issue by zkim2** [volatilityfoundation/volatility#591]
I'm trying to utilize volatility as a library. I have specified a config file, "volatilityrc", in the same directory as I run my script. It contains the same default parameters except the location variable is where my memory dump is located. The configuration file is being parsed correctly but I keep getting the "volatility.exceptions.AddrSpaceError: No suitable address space mapping found" error. How does volatility internally set the config.LOCATION given a configuration file? 

Even at the command line if I run: "python vol.py pslist --conf-file=/Users/ZACH/PycharmProjects/Volatility/volatilityrc

I get the same error. I thought that volatility would read the config file and automatically set the config file location?

**Comment by zkim2** [comment]
"If an option is not supplied on command-line, Volatility will try to get it from an environment variable and if that fails - from a configuration file." - from the Volatility usage page. I tried to only do "python vol.py --conf-file/path/to/volatilityrc" and it keeps asking me to supply more arguments. My config file contains the location of my memory dump and also plugins to run.

**Comment by zkim2** [comment]
It turns out that the command line will only read the configuration file provided both the plugin and and memory location are in there as well. It seems like the configuration file is loaded into the cnf_opts variable in a Config object but it doesn't do anything with these arguments. I originally thought that if we specified a PLUGINS field in the config file then it would actually run them. Can anyone confirm this?

**Comment by iMHLv2** [comment]
> I tried to only do "python vol.py --conf-file/path/to/volatilityrc" and it keeps asking me to supply more arguments

I'm not sure if that's a typo, but you definitely either need a space or `=` between `--conf-file/path/to/volatilityrc`

The `PLUGINS` is not a list of plugins to run, its the equivalent of specifying the `--plugins` option. Thus, its how you specify one or more folders containing additional volatility plugins to load. You would still need to tell volatility (on command line) which plugin to actually run.

This may help as well:

https://github.com/volatilityfoundation/volatility/wiki/Volatility-Usage#using-volatility-as-a-library

**Comment by atcuno** [comment]
@zkim2 please re-open this ticket if @iMHLv2 's steps do not fix your issue.

Thanks
