### ISSUE TITLE
Detecting Digital Signature for PEs

### ISSUE THREAD

**Issue by DrDinosaur** [volatilityfoundation/volatility#594]
Is there a way to see if the executable behind a process is digitally signed? I haven't seen any information about this with my searches and it appears that procdump does not have a digital signature of the executables when it outputs them after extracting them from memory. 

It seems like this would be helpful in determining what's more likely to malicious, so I'm surprised I couldn't find any resources on this.

**Comment by DrDinosaur** [comment]
I've tried using dumpcerts, but that didn't seem to do what I was looking for. For example, Notepad++ is digitally signed, but I can't find its cert when using that plugin.

**Comment by mutedmouse** [comment]
If you can extract the pe from memory via procdump, then by using
techniques like in this article (very dated),
https://isc.sans.edu/forums/diary/Extracting+Digital+Signatures+from+Signed+Malware/15779/,
it can be done.  This is a roundabout way of doing it but if you need it
for a few processes this might serve your needs.

Hope this helps.

**Comment by DrDinosaur** [comment]
Have you tested this? I just tried using the extraction tool mentioned in that article on all of the executables I dumped using procdump (both with and without the -x option), and all of the certificates it creates are empty. Some of them it says that the source file is not signed. I tried it on the Notepad++ executable (which does have a digital signature) and it worked fine.

**Comment by mutedmouse** [comment]
Not recently tested but let me fudge around with some things today and I'll
get back you on this thread with my findings. Unless someone else beats me
to it that is.
Once I have a solid method I'll post relevant steps I took here or I can
email direct if that is preferred.

**Comment by DrDinosaur** [comment]
Ok, thanks.
