### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by tincho9** [volatilityfoundation/volatility#598]
I would like to know if python 3 support is in the works, and if not - if I can help :)

**Comment by xambroz** [comment]
Support/patching for python2 will cease on January 2020.
+1 for the python3 support.
Without python3 support the package is going to be probably kicked from Fedora Linux distribution.

**Comment by koromodako** [comment]
Hey guys,

This issue has already been raised, see the answer there: https://github.com/volatilityfoundation/volatility/issues/471

Also check out this announcement:  https://twitter.com/volatility/status/1184556891592155136?s=09

Eager to see version 3 coming out !

**Comment by gleeda** [comment]
Closing this issue, since Volatility 3 has now been released: https://github.com/volatilityfoundation/volatility3
