### ISSUE TITLE
Linux 2.4.27 - Profile Creation when modules are disabled

### ISSUE THREAD

**Issue by Iansus** [volatilityfoundation/volatility#600]
Hi,

I am trying to create a custom Volatility profile on a Linux system where modules seem to be disabled.
Therefore, when executing the `make` command in `tools/linux`, I get the following error:

```
make -C //lib/modules/2.4.27/build CONFIG_DEBUG_INFO=y M="/tmp/volatility-master/tools/linux" modules
make[1]: Entering directory `/xxx'

The present kernel configuration has modules disabled.
Type 'make config' and enable loadable module support.
Then build a kernel with module support enabled.

make[1]: *** [modules] Error 1
make[1]: Leaving directory `/xxx'
make: *** [dwarf] Error 2
```

Is there any other way of retrieving the `module.dwarf` file?

Thanks in advance,
Best regards,

**Comment by Iansus** [comment]
I managed to find the kernel sources, then I ran:

```
make config (I enabled kernel modules)
make dep
cd /tmp/volatility-master/tools/linux
make
```

The `make` command seemed to work, but for every subdirectory in the source, I have: 

```
make[2]: Entering directory `/home/linux-2.4.27/arch/i386/mm'
make[2]: Nothing to be done for `modules'.
```

Have you ever encountered such issue?

Thanks in advance,
Best regards,

**Comment by pagabuc** [comment]
Hey Iansus, normally you also need to export the kernel headers with `make headers_install` after you compile the kernel - but it looks like the kernel 2.4 does not have this option. 
Maybe here you can find some pointer on how to do that: http://archive.linuxfromscratch.org/lfs-museum/4.1/LFS-BOOK-4.1-HTML/chapter06/kernel.html

Anyway, there are huge differences between 2.4 and 2.6 (one for all: in 2.4 `task_struct`s are linked with a `task_struct` pointer (`next_task`), while in 2.6 there is a `list_head` (`tasks`)), so I'm quite sure volatility only supports 2.6 kernels.

Good luck and keep me posted if you are trying to add support for 2.4!

**Comment by atcuno** [comment]
Hello,

Volatility does not support the 2.4 series of kernels. If you end up writing support for 2.4 then please submit any relevant merge requests, and we would be glad to review them.

Thanks.
