### ISSUE TITLE
do not re-release

### ISSUE THREAD

**Issue by blshkv** [volatilityfoundation/volatility#602]
Our users experience a problem with the latest release as described below:
https://github.com/pentoo/pentoo-overlay/issues/456

Many distributions including Pentoo picked up the 2.6.1 release in Nov 2018 and mirrored it, for example:
http://turkey.archive.parrotsec.org/parrot/pool/main/v/volatility/ (the original size 5245879).
However, this released was re-released in December (the new size 5246187).

I have done quick comparison and found that there are a number of changes in the source code which looks valid and intentional. 

Please do not re-tag the same release. This raises an alarm and it is very critical especially for forensic software.

**Comment by blshkv** [comment]
Can bother to acknowledge?

**Comment by gleeda** [comment]
Thanks for the note.  We'll consider this in the future.
