### ISSUE TITLE
Broken linux/mount.py

### ISSUE THREAD

**Issue by mbevilacqua** [volatilityfoundation/volatility#606]
Commit b87c4648eda8fe20e40badddf30002545f565d1a appears to have broken mount.py.
Specifically, the recently added OR results in an 'IndexError: string index out of range' on some very simple testing being performed:
https://github.com/volatilityfoundation/volatility/blob/781d74acf3f72b435e7e76abc21b523cf5178ac1/volatility/plugins/linux/mount.py#L171

**Comment by atcuno** [comment]
Thanks @mbevilacqua . The last patch in that series was mistakenly not committed. It is now: 

https://github.com/volatilityfoundation/volatility/commit/74f1134865d386563acf4221befcacbc767521f4

Please let me know if you still have any issues and thanks for the report.
