### ISSUE TITLE
Cannot load profile

### ISSUE THREAD

**Issue by MauroFoti** [volatilityfoundation/volatility#609]
I've got a linux mint 17.3 VM (kernel version 3.19.0-32-generic). I've built `module.draw`, got `System.map` and copied in a zip file that I've called `linuxmint.zip`, I've taken a memory image with LiME and tried running a scan with Volatility 2.5 (what is found in my repositories).

I've put the zip file inside `/usr/share/volatility/plugins/overlays/linux`

```
volatility -f image.raw --profile=linuxmint imageinfo
```

But that didn't work, so I've tried different folders and used also the `--plugins` parameter with different folders

* `/usr/share/volatility/volatility/plugins/overlays/linux`
* `/usr/share/volatility/plugins/overlays/linux`
* `/usr/lib/python2.7/dist-packages/volatility/plugins/overlays/linux `

```
volatility -f image.raw --profile=linuxmint --plugins="/any/of/the/above/" imageinfo
```

But it would alywas say `ERROR   : volatility.debug    : Invalid profile linuxmint selected`

So I thought something was bad with my profile so I've grabbed [this one](https://github.com/volatilityfoundation/profiles/blob/master/Linux/Ubuntu/x64/Ubuntu14043.zip) that should be the closest possible with kernel `3.19.0-42-generic` but it also gives the same error, so at this point I just don't know what to do to understand what is wrong with my profile (btw I've also tried this one on every path among those I've listed above).

**Comment by pagabuc** [comment]
Hi Mauro,

the name of the profile you are specifying is not correct. To list all the profiles you can simply run `vol.py --info | grep Linux` and pick the one you just created.
Cheers!

**Comment by MauroFoti** [comment]
> Hi Mauro,
> 
> the name of the profile you are specifying is not correct. To list all the profiles you can simply run `vol.py --info | grep Linux` and pick the one you just created.
> Cheers!

It's not showing anywhere. Also, in what folder am I supposed to put it so that's it's recognized?

**Comment by pagabuc** [comment]
I usually use volatility from a folder, without installing it system-wide. In this case the profiles go under `volatility/plugins/overlays/linux`. Can you try this setup? Otherwise, you can also try to specify a folder containing the profile with `--plugins=/path/to/profiles`!

**Comment by MauroFoti** [comment]
Ok thanks! I've put my zips in  `/usr/lib/python2.7/dist-packages/volatility/plugins/overlays/linux` and they showed up with `volatility --info` (although I didn't notice them :P). The real problem is that although the file was called `linuxmint.zip` the profile name was `Linuxlinuxmintx64`
