### ISSUE TITLE
how to use dumpcerts ?

### ISSUE THREAD

**Issue by Waterman178** [volatilityfoundation/volatility#611]
[61] pyrebox(464)> %vol dumpcerts -s root_bundle.crt
VolShell: Error while executing volatility command
option -s: invalid choice: u'root_bundle.crt' (choose from 'atom', 'refcount', 'offset')

What do these three options mean?

**Comment by iMHLv2** [comment]
If you run volatility with `dumpcerts -h` the command line options will be described. It looks like you're running into another pyrebox issue.
