### ISSUE TITLE
choose from 'atom', 'refcount', 'offset'

### ISSUE THREAD

**Issue by Waterman178** [volatilityfoundation/volatility#613]
[160] pyrebox(b74)> %vol impscan -b 0xfffff80003cbf141 -s 100
VolShell: Error while executing volatility command
option -s: invalid choice: u'100' (choose from 'atom', 'refcount', 'offset')

Parameter -s cannot be used

**Comment by Waterman178** [comment]
I understand, it is let me choose a sorting method.

**Comment by iMHLv2** [comment]
This should be filed under the https://github.com/Cisco-Talos/pyrebox/issues tracker.
