### ISSUE TITLE
tools/mac/convert.py: convert_file() parsing problem

### ISSUE THREAD

**Issue by tyrombobrowski** [volatilityfoundation/volatility#616]
The format of the DWARF file that is generated by the dwarfdump program has changed in recent versions of macOS. As a result, when attempting to convert the generated dwarfdump output to a Linux style output so that Volatiltiy can read it, the convert_file() function returns prematurely printing out "State machine broken! level 0!" (tools/mac/convert.py:535) to STDOUT. The dwarfdump output file was generated on macOS version 10.14.5 and I suspect that this may have been an issue since 10.14.X, as doing so on 10.13.X works as expected.

Looking at this quickly, it appears that the header of the file generated by dwarfdump has changed slightly, so that will need to be accounted for moving forward. Additionally, the logic around generating the regular expressions and storing them within the re_compiles list object may need to be reviewed as the string_idx depth looks like it has changed. There's probably other bits that have also changed, but I haven't had the time to actually look into this myself.

**Comment by sonicballz** [comment]
I have absolutely the same problem! Even following the tutorial very carefully for many times...

convert.py end's prematurely in the first line:

`
State machine broken! level 0! /Library/Developer/KDKs/KDK_10.14.5_18F132.kdk/System/Library/Kernels/kernel.dSYM/Contents/Resources/DWARF/kernel:	file format Mach-O 64-bit x86-64
`

Just for the sake of test, I removed the first line, then the script dies on this line:

`
State machine broken! level 0! 0x00000022:   DW_TAG_variable
`

If I comment the following lines...
`if not line_wrote:
      print "State machine broken! level 0! %s" % line
      sys.exit(1)`
I end up with this vtypes file:

`mac_types = {
}

mac_gvars = {
}`


**Here you are an attached dwarfdump file attached. I hope it helps: https://mega.nz/#!cR0w3QDQ!Bhq4brvSe9RPVq5kuPp9iqeU3QjtJR6AKAb02uLoRjA**

Let me know if you need further information.

Thanks in advance.

**Comment by tyrombobrowski** [comment]
I will check this out shortly and confirm whether this had worked for me.

Thanks!
