### ISSUE TITLE
git vs apt

### ISSUE THREAD

**Issue by mathurin68** [volatilityfoundation/volatility#617]
What's the recommended way to install volatility?  git or apt 

does it matter?  Just curious...

I'll be running it on Ubuntu 16

Thanks!

**Comment by iMHLv2** [comment]
I recommend using the `master` branch in git, so you get the latest code. By the way, there's a mailing list for general questions: https://lists.volatilityfoundation.org/mailman/listinfo/vol-users.

**Comment by mathurin68** [comment]
Grazi!
