### ISSUE TITLE
Pico process modules

### ISSUE THREAD

**Issue by nate-ray** [volatilityfoundation/volatility#619]
In paper "Memory Forensics and the Windows Subsystem for Linux" several new modules were discussed for handling the pico processes associated with WSL? Were those modules released or is there an anticipated release where they may be included in the master branch?

**Comment by gleeda** [comment]
Support for pico processes is already in the master branch.

**Comment by abbasheile** [comment]
@gleeda Could you please help me find how to revoke pico commands(picolist, picoscan, picotree, picobash, picocmdline, picoenvars, picothreads)? I could not find it in the repo.
