### ISSUE TITLE
no result when running imageinfo

### ISSUE THREAD

**Issue by WendyBaiYunwei** [volatilityfoundation/volatility#622]
When I run imageinfo command on windows 10, 64 bits, standalone version, I cannot get any result. Here is the screenshot:
![image](https://user-images.githubusercontent.com/46145227/60066190-f7087480-9738-11e9-8c3c-7b61405bd6fa.png)

I am wondering whether my command is wrong, or my captured image has a problem.
I tried to capture the ram image in both raw and mem format. The tools I used were belkasoft and FTK imager. Both cannot work. I captured the image in a win 10 virtual machine with 1G ram, and transferred the image back to my host machine for analysis. 
Please help. Thank you!

**Comment by atcuno** [comment]
Hello,

First - the compiled version of Volatility (assuming you are using the one we distributed) is extremely old. You should instead use the latest version of Volatility from the GitHub master branch.

Second - If you have a VM then its best to capture using the virtual machine facilities. 

Third - Both FTK Imager and Belkasoft are known to produce invalid memory samples from Windows 10 systems.

Please re-open this if you still have issues using the latest code and a better acquisition method.
