### ISSUE TITLE
Buggy volatility/obj.py

### ISSUE THREAD

**Issue by iSmellPowder** [volatilityfoundation/volatility#630]
Memory dump: **ubuntu-18.04.2-server-amd64**
Extra information to note: **Running volatility on a python virtual environment spawned by powershell**
Errors occurred when running: **linux_info_regs** and **linux_check_inline_kernel**. 
All linked to line 733 of obj.py: 
> raise AttributeError("Struct {0} has no member {1}".format(self.obj_name, attr))

### Error message (linux_info_regs)
> (.lma) PS D:\LMA Tool> python2 .\.venv\volatility\vol.py --plugins="D:\experiment\test\artifacts" --profile="Linuxtest_volx64" --output="json" -f .\test\artifacts\test_vol.dump linux_info_regs
> Volatility Foundation Volatility Framework 2.6.1
> Traceback (most recent call last):
>   File ".\.venv\volatility\vol.py", line 192, in <module>
>     main()
>   File ".\.venv\volatility\vol.py", line 183, in main
>     command.execute()
>   File "D:\experiment\.venv\volatility\volatility\plugins\linux\common.py", line 67, in execute
>     commands.Command.execute(self, *args, **kwargs)
>   File "D:\experiment\.venv\volatility\volatility\commands.py", line 147, in execute
>     func(outfd, data)
>   File "D:\experiment\.venv\volatility\volatility\commands.py", line 294, in render_json
>     self._render(outfd, JSONRenderer(), data)
>   File "D:\experiment\.venv\volatility\volatility\commands.py", line 276, in _render
>     renderer.render(outfd, output)
>   File "D:\experiment\.venv\volatility\volatility\renderers\html.py", line 47, in render
>     if data.max_depth() > 1:
>   File "D:\experiment\.venv\volatility\volatility\renderers\__init__.py", line 228, in max_depth
>     return self.visit(None, lambda n, a: max(a, self.path_depth(n)), )
>   File "D:\experiment\.venv\volatility\volatility\renderers\__init__.py", line 248, in visit
>     self.populate()
>   File "D:\experiment\.venv\volatility\volatility\renderers\__init__.py", line 149, in populate
>     for (level, item) in self._generator:
>   File "D:\experiment\.venv\volatility\volatility\plugins\linux\pslist.py", line 118, in generator
>     for task in data:
>   File "D:\experiment\.venv\volatility\volatility\plugins\linux\info_regs.py", line 113, in calculate
>     regs = self.parse_kernel_stack(thread_task)
>   File "D:\experiment\.venv\volatility\volatility\plugins\linux\info_regs.py", line 136, in parse_kernel_stack
>     sp0 = task.thread.sp0
>   File "D:\experiment\.venv\volatility\volatility\obj.py", line 751, in __getattr__
>     return self.m(attr)
>   File "D:\experiment\.venv\volatility\volatility\obj.py", line 733, in m
>     raise AttributeError("Struct {0} has no member {1}".format(self.obj_name, attr))
> AttributeError: Struct thread has no member sp0

### Error message (linux_check_inline_kernel)
> (.lma) PS D:\LMA Tool> python2 .\.venv\volatility\vol.py --plugins="D:\experiment\test\artifacts" --profile="Linuxtest_volx64" --output="json" -f .\test\artifacts\test_vol.dump linux_check_inline_kernel
> Volatility Foundation Volatility Framework 2.6.1
> Traceback (most recent call last):
>   File ".\.venv\volatility\vol.py", line 192, in <module>
>     main()
>   File ".\.venv\volatility\vol.py", line 183, in main
>     command.execute()
>   File "D:\experiment\.venv\volatility\volatility\plugins\linux\common.py", line 67, in execute
>     commands.Command.execute(self, *args, **kwargs)
>   File "D:\experiment\.venv\volatility\volatility\commands.py", line 147, in execute
>     func(outfd, data)
>   File "D:\experiment\.venv\volatility\volatility\commands.py", line 294, in render_json
>     self._render(outfd, JSONRenderer(), data)
>   File "D:\experiment\.venv\volatility\volatility\commands.py", line 276, in _render
>     renderer.render(outfd, output)
>   File "D:\experiment\.venv\volatility\volatility\renderers\html.py", line 47, in render
>     if data.max_depth() > 1:
>   File "D:\experiment\.venv\volatility\volatility\renderers\__init__.py", line 228, in max_depth
>     return self.visit(None, lambda n, a: max(a, self.path_depth(n)), )
>   File "D:\experiment\.venv\volatility\volatility\renderers\__init__.py", line 248, in visit
>     self.populate()
>   File "D:\experiment\.venv\volatility\volatility\renderers\__init__.py", line 149, in populate
>     for (level, item) in self._generator:
>   File "D:\experiment\.venv\volatility\volatility\plugins\linux\check_inline_kernel.py", line 310, in generator
>     for (sym_name, member, hook_type, sym_addr) in data:
>   File "D:\experiment\.venv\volatility\volatility\plugins\linux\check_inline_kernel.py", line 299, in calculate
>     for (sym_name, member, hook_type, sym_addr) in func(modules):
>   File "D:\experiment\.venv\volatility\volatility\plugins\linux\check_inline_kernel.py", line 218, in _check_file_op_pointers
>     for (name, member, hook_type, address) in func(f_op_members, modules):
>   File "D:\experiment\.venv\volatility\volatility\plugins\linux\check_inline_kernel.py", line 206, in check_proc_root_fops
>     for (name, hooked_member, hook_type, hook_address) in self.walk_proc(proc_root, f_op_members, modules):
>   File "D:\experiment\.venv\volatility\volatility\plugins\linux\check_inline_kernel.py", line 191, in walk_proc
>     for (sub_name, hooked_member, hook_type, hook_address) in self.walk_proc(subdir, f_op_members, modules, name):
>   File "D:\experiment\.venv\volatility\volatility\plugins\linux\check_inline_kernel.py", line 178, in walk_proc
>     name = parent + "/" +  self.addr_space.read(cur.name.obj_offset, cur.namelen + 1)
>   File "D:\experiment\.venv\volatility\volatility\obj.py", line 751, in __getattr__
>     return self.m(attr)
>   File "D:\experiment\.venv\volatility\volatility\obj.py", line 733, in m
>     raise AttributeError("Struct {0} has no member {1}".format(self.obj_name, attr))
> AttributeError: Struct subdir has no member name

**Comment by atcuno** [comment]
Can you please verify if this is still an issue and re-open the ticket if so?
