### ISSUE TITLE
linux_bash plugin for /bin/ksh

### ISSUE THREAD

**Issue by PracaGrande** [volatilityfoundation/volatility#644]
Hi, not sure if this has been reported before, couldn't find it.

is my understanding that the linux_bash plugin only works for /bin/bash and will be able to find the history_list address by itself. I have a Red Hat System that has Korn Shell and I'm wondering if there is a way to get volatility to get the Korn Shell history?

Thanks

**Comment by atcuno** [comment]
Volatility does not currently have this support. This would be interesting contribution if you wish to perform the research. Please reach out on Slack if you need or want help with this: https://www.volatilityfoundation.org/slack
