### ISSUE TITLE
Linux Moddump - No section .symtab found. Unable to properly re-create ELF file

### ISSUE THREAD

**Issue by PracaGrande** [volatilityfoundation/volatility#648]
Hi, 

I used linux_hidden_modules plugin to find a malicious module that I would like to dump. 
```
Offset (V)         Name
------------------ ----
0xffffffffa03b2660 module
```
I tried to use linux_moddump but in this case I get the following message:

$python vol.py  --plugins=plugins --profile=Linuxprofile-2_6_32-754_22_1_el6_x86_64x64 linux_moddump -b 0xffffffffa03b2660 -D /tmp/ -f memory.capture

```
Volatility Foundation Volatility Framework 2.6.1
ERROR   : volatility.debug    : No section .symtab found. Unable to properly re-create ELF file.
```
Anything I could try in order to get a module dump?

thanks

**Comment by atcuno** [comment]
Unfortunately not. We need this information to recreate the ELF file.

**Comment by fpusersuggest** [comment]
Then the hidden module found is a false positive ?
