### ISSUE TITLE
it is reported "The context is partially valid. Only x86 user-mode context is available" when windbg open the dump from raw2dmp, But x86 os is good.

### ISSUE THREAD

**Issue by sculida** [volatilityfoundation/volatility#661]
There were some guest oses run in qemu-kvm. I dump the guest os' memory by libvert.

> virsh qemu-monitor-command [id] --hmp dump-guest-memory 1.virsh.dmp

Then I copy _1.virsh.dmp_ to windows, convert it to windbg's format by volatility.

> volatility_2.6_win64_standalone --profile=Win7SP1x64_23418 --plugins=raw2dmp -f _1.virsh.dmp_ raw2dmp --output-image=_1.dmp_

When windbg open the _1.dmp_, it reported error:

> Unknown exception - code 45474150 (first/second chance not available)
The context is partially valid. Only x86 user-mode context is available.
For analysis of this file, run !analyze -v
00000000`00000000 ??              ???
The context is partially valid. Only x86 user-mode context is available.
16.0: kd:x86> !process 0 0
**** NT ACTIVE PROCESS DUMP ****
PROCESS 018ba040  SessionId: none  Cid: 0004    Peb: 00000000  ParentCid: 0000
    DirBase: 00187000  ObjectTable: 000017d0  HandleCount: 558.

But if the guest os is win7x86 or winXpx86. The _1.dmp_ was good.
Could you tell me how to solve the problem? Thank you!

**Comment by sculida** [comment]
calling

> !wow64exts.sw

in windbg can resolute the problem.

**Comment by gleeda** [comment]
This confirmed as an issue with x64 converted crashdumps

**Comment by sculida** [comment]
> calling
> 
> > !wow64exts.sw
> 
> in windbg can resolute the problem.

Great! It is the solution. But when I
`da rsp`
, the windbg is strange
`16.0: kd> da fffffa80`00000000
0000:0000  "????????????????????????????????"
0000:0020  "????????????????????????????????"
0000:0040  "????????????????????????????????"
0000:0060  "????????????????????????????????"`
It seemed that windbg's command `dx` do the address as a 16bit number, either 64bit number

**Comment by sculida** [comment]
> > calling
> > > !wow64exts.sw
> > 
> > 
> > in windbg can resolute the problem.
> 
> Great! It is the solution. But when I
> `da rsp`
> , the windbg is strange
> `16.0: kd> da fffffa8000000000 0000:0000 "????????????????????????????????" 0000:0020 "????????????????????????????????" 0000:0040 "????????????????????????????????" 0000:0060 "????????????????????????????????"`
> It seemed that windbg's command `dx` do the address as a 16bit number, either 64bit number
