### ISSUE TITLE
Wiki - update

### ISSUE THREAD

**Issue by noraj** [volatilityfoundation/volatility#665]
https://github.com/volatilityfoundation/volatility/wiki/Linux#creating-a-new-profile

![image](https://user-images.githubusercontent.com/16578570/68964701-521b3080-07da-11ea-83d8-d39a8eb0ec18.png)
Add `zypper install -t pattern devel_basis` for openSUSE.

**Comment by gleeda** [comment]
done.  thank you for reporting!
