### ISSUE TITLE
newer linux kernel support ?

### ISSUE THREAD

**Issue by noraj** [volatilityfoundation/volatility#666]
I created a custom profile for openSUSE Leap 15.1 - Kernel 4.12.14-lp151.28.32-default

and dumped the live memory with:

```
VBoxManage debugvm 'openSUSE Leap 15.1' dumpvmcore --filename=dump.raw
```

But I can't use it:

~~~
$ volatility -f dump.raw --plugins=plugins/ --profile=LinuxopenSUSELeap151x64 linux_pslist
Volatility Foundation Volatility Framework 2.6.1
ERROR   : volatility.debug    : Invalid profile LinuxopenSUSELeap151x64 selected
~~~

it seems there are dozens of issue like this one because:

> Linux: 
> * 32-bit Linux kernels 2.6.11 to 4.2.3
> * 64-bit Linux kernels 2.6.11 to 4.2.3
> * OpenSuSE, Ubuntu, Debian, CentOS, Fedora, Mandriva, etc

Any plan to newer kernel support? 4.2.3 is pretty old, and there is a bunch a kernels between 4.2.x and 5.3.x.

**Comment by atcuno** [comment]
Hey, thanks for pointing this out - support for only up to 4.2.3 is not current/correct. I can work to get that listing upgraded soon. I have used Volatility on many 5.x samples fine.

As far as your VBox issue -- can you please re-run with -ddd set and then paste all the input/output here (will be a lot of debug statements).

**Comment by noraj** [comment]
I just did the same for openSUSE Leap 42.1 - Kernel 4.1.39-56-default and it doesn't work either.

Adding `-v`, `-d` or `-ddd` to the `volatility` command doesn't show more output.

**Comment by atcuno** [comment]
can you run:

volatility --info | grep -i suse

it seems like you may be specifying the profile wrong. Also, to clarify, are you using the latest master checkout of volatility from github?

**Comment by noraj** [comment]
1. To create the profile I followed the official documentation, so I installed the prerequisites and then:

```
$ cd /tmp
$ git clone https://github.com/volatilityfoundation/volatility.git
$ cd volatility/tools/linux
$ make
$ head module.dwarf
$ cd /tmp
$ sudo zip openSUSELeap151.zip volatility/tools/linux/module.dwarf /boot/System.map-4.12.14-lp151.28.32-default
```

So the profile was built against upstream volatility.

However, I retrieved the profile and I'm using it on another machine which is using volatility 2.6.1 release built [like this](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/volatility).

And of course I'm using the right profile names:

```
$ volatility --plugins=plugins/ --info | grep openSUSELeap151
Volatility Foundation Volatility Framework 2.6.1
LinuxopenSUSELeap151x64 - A Profile for Linux openSUSELeap151 x64
$ volatility --plugins=plugins/ --info | grep openSUSELeap421                        
Volatility Foundation Volatility Framework 2.6.1
LinuxopenSUSELeap421x64 - A Profile for Linux openSUSELeap421 x64
```

**Comment by atcuno** [comment]
I see now. --plugins has to be the first argument after 'volatility' or it will be ignored.

**Comment by noraj** [comment]
@atcuno Thanks, I'll try again with the option first. Could you add a note on the wiki (I would have do it but i dont have perms).

- https://github.com/volatilityfoundation/volatility/wiki/Linux
- https://github.com/volatilityfoundation/volatility/wiki/2.6-Win-Profiles

**Comment by noraj** [comment]
@atcuno With the option first: it works

```
$ volatility --plugins=plugins/ --profile=LinuxopenSUSELeap151x64 -f chall.raw linux_pslist
Volatility Foundation Volatility Framework 2.6.1
Offset             Name                 Pid             PPid            Uid             Gid    DTB                Start Time
------------------ -------------------- --------------- --------------- --------------- ------ ------------------ ----------
0xffff88000dd9e040 systemd              1               0               0               0      0x000000000d162000 2019-11-19 22:52:39 UTC+0000
0xffff88000ddb2080 kthreadd             2               0               0               0      ------------------ 2019-11-19 22:52:39 UTC+0000
0xffff88000ddb6100 kworker/0:0H         4               2               0               0      ------------------ 2019-11-19 22:52:39 UTC+0000
```

**Comment by atcuno** [comment]
Great! Glad its working! Will close now.
