### ISSUE TITLE
Hivelist doesn't work on 8.1 update 1 

### ISSUE THREAD

**Issue by iMHLv2** [volatilityfoundation/volatility#67]
The CMHIVE structure changed. We need new profiles.

**Comment by dmeier-umn** [comment]
I'm having a similar issue with several images that are Windows 2012x64. hivelist, hivescan, filescan all run for a very long time and report no findings. 
I'm using the latest version of 2.4 from the GIT repo on Ubuntu 14.04 and have passed the appropriate virtual address of the KdCopyDataBlock to --kdbg. 

Example: python vol.py -f <RAMFILE> --profile=Win2012x64 --kdbg=0xf803c4df6c54 hivescan
Volatility Foundation Volatility Framework 2.4
Offset(P)
------------------

Any clues?

**Comment by iMHLv2** [comment]
@dmeier-umn please email me at michael @ memoryanalysis [dot] net if you're still having issues (make sure to git pull the latest updates first)
