### ISSUE TITLE
Dead link to Reconstructing a binary in Procdump section of Wiki

### ISSUE THREAD

**Issue by PotatoDrug** [volatilityfoundation/volatility#672]
The link to Andreas Schuster's 4-part series on Reconstructing a binary in [procdump section](https://github.com/volatilityfoundation/volatility/wiki/Command-Reference#procdump) of the wiki is dead.

Dead link: http://computer.forensikblog.de/en/2006/04/reconstructing_a_binary.html#more
Working link: https://computer.forensikblog.de/en/2006/04/reconstructing-a-binary-1.html#more

**Comment by gleeda** [comment]
Thank you for reporting!  It's fixed now :-)
