### ISSUE TITLE
RedHat Linux 7.6, cant make a profile

### ISSUE THREAD

**Issue by shehreyarahmedkohati** [volatilityfoundation/volatility#673]
I have a test machine RHEL 7.6 for which I have acquired memory image using Lime. 

I am unable to make a profile because the dependency libdwarf-tools fails to install. 

Has anyone succeeded with RHEL 6 and 7 profile creation and share the profiles as zip?

**Comment by atcuno** [comment]
Please try to follow the steps here:

https://github.com/volatilityfoundation/volatility/wiki/Linux#creating-a-new-profile

They list options to get dwarfdump, including compiling the open source package. Feel free to re-open the ticket if the wiki doesn't get your results.
