### ISSUE TITLE
can't find zImage file (using emulator)

### ISSUE THREAD

**Issue by adesatriowirawan** [volatilityfoundation/volatility#676]
I try to follow instructions on " https://github.com/volatilityfoundation/volatility/wiki/Android#create-an-avd " on part building the kernel, I couldn't find the zImage file at ~/android-source/arch/arm/boot/zImage . can anyone help? *sorry if my English is bad. and actually i'm new in linux.
![Screenshot from 2020-01-12 08-43-23](https://user-images.githubusercontent.com/15419570/72222270-a52e0d00-3517-11ea-938c-ece551570bca.png)

![Screenshot from 2020-01-12 08-35-24](https://user-images.githubusercontent.com/15419570/72222248-71eb7e00-3517-11ea-8c6b-58c153f2e593.png)
this shows on my boot folder

![Screenshot from 2020-01-12 08-59-25](https://user-images.githubusercontent.com/15419570/72222502-0d7dee00-351a-11ea-9272-628a1a983e80.png)

**Comment by atcuno** [comment]
Did the kernel build fully? your second screenshot shows the beginning but not the end of the process. It would be alot of output and you would need to check the build logs towards the end of the run.
