### ISSUE TITLE
Problem with linux_pslist Linux kernel 5.0.0-23

### ISSUE THREAD

**Issue by tompan1** [volatilityfoundation/volatility#677]
Hello

I am trying to use the linux_pslist plugin on memory dump extracted from Ubunto 18.04.3 with Linux kernel 5.0.0-23 running on an Oracle virtual box.

The memory was extracted using the debugvm & dumpvmcore.
I created Linux profile following the instruction here -> [https://github.com/volatilityfoundation/volatility/wiki/Linux](url)
and I also tried the profile from -> [https://github.com/volatilityfoundation/profiles](url)

but when i trying use the linux_pslist plugin i am getting the error:
"No suitable address space mapping found".

when i tried to do same with older version of Ubuntu -> Ubuntu 12.04 with Linux kernel 3.1.1.0-15, with manually build profile, it worked fine

**Comment by malliman** [comment]
I am experiencing the same issue

**Comment by atcuno** [comment]
Is there anyway you could provide the sample to me (even privately)? That way I can debug if its a profile issue or an address space issue.
