### ISSUE TITLE
offset argument is not valid anymore 

### ISSUE THREAD

**Issue by yehias** [volatilityfoundation/volatility#681]
Hello when I try to use --offset with psscan or any plugin volatility will give an error that argument is valid neither -o is working is there any alternative for it since google it with no luck

**Comment by gleeda** [comment]
the `--offset / -o` options are not valid for `psscan`.  What other plugins were you trying to use?

**Comment by atcuno** [comment]
@yehias Please re-open this ticket if you need further help beyond what @gleeda stated.
