### ISSUE TITLE
Windows 10 18363 - Image Identification Fails 

### ISSUE THREAD

**Issue by mathurin68** [volatilityfoundation/volatility#682]
I'm a total novice with volatility...
I've got a large image over 26GB that keeps failing on 'Image Identification'...
The FireEye HX is identifying it's os/build/patch as
"Windows 10 Enterprise 18363"

Is there anything else I could do or try?  
`Volatility Foundation Volatility Framework 2.6.1`

I installed from git clone...

Appreciate any suggestions, thanks!

**Comment by atcuno** [comment]
hello @mathurin68 

Could you please run volatility as:

```
python vol.py --profile=Win10x64_18362 -f <path to sample> kdbgscan
```

Once kdbgscan finishes can you please paste the full input/output so that we can diagnose?

**Comment by mathurin68** [comment]
Hey @atcuno,

Here you go---

`volatility$ python2 vol.py --profile=Win10x64_18362 -f memory.dmp kdbgscan
Volatility Foundation Volatility Framework 2.6.1
**************************************************
Instantiating KDBG using: Unnamed AS Win10x64_18362 (6.4.18362 64bit)
Offset (V)                    : 0xf8034b0265e0
Offset (P)                    : 0x46265e0
KdCopyDataBlock (V)           : 0xf8034aea2324
Block encoded                 : Yes
Wait never                    : 0x3c025a006d0f8323
Wait always                   : 0x687db65901338003
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win10x64_18362
Version64                     : 0xf8034b02a3c8 (Major: 15, Minor: 18362)
Service Pack (CmNtCSDVersion) : 0
Build string (NtBuildLab)     : 18362.1.amd64fre.19h1_release.19
PsActiveProcessHead           : 0xfffff8034b038b60 (414 processes)
PsLoadedModuleList            : 0xfffff8034b048150 (224 modules)
KernelBase                    : 0xfffff8034ac00000 (Matches MZ: True)
Major (OptionalHeader)        : 10
Minor (OptionalHeader)        : 0
KPCR                          : 0xfffff80347df1000 (CPU 0)
KPCR                          : 0xffffc381b6220000 (CPU 1)
KPCR                          : 0xffffc381b6300000 (CPU 2)
KPCR                          : 0xffffc381b63a7000 (CPU 3)
KPCR                          : 0xffffc381b64c0000 (CPU 4)
KPCR                          : 0xffffc381b6526000 (CPU 5)
KPCR                          : 0xffffc381b6640000 (CPU 6)
KPCR                          : 0xffffc381b66dd000 (CPU 7)`

Thanks for your help! ( I am taking a volatility class in April)
