### ISSUE TITLE
unable to run plugins for target "Ubuntu 16.04.6"

### ISSUE THREAD

**Issue by darshantank** [volatilityfoundation/volatility#683]
Hello All,

I have successfully created new profile for my VM running **Ubuntu 16.04.6 LTS** as described at https://github.com/volatilityfoundation/volatility/wiki/Linux

And move the zip file under 'volatility/plugins/overlays/linux/'

# python vol.py --info | grep Linux
Volatility Foundation Volatility Framework 2.6.1
LinuxUbuntu1604x64    - A Profile for Linux Ubuntu1604 x64
LinuxAMD64PagedMemory          - Linux-specific AMD 64-bit address space.
linux_aslr_shift           - Automatically detect the Linux ASLR shift
linux_banner               - Prints the Linux banner information
linux_yarascan             - A shell in the Linux memory image

But when I run vol.py, it shows the following message on my terminal , and did not get the list of running process.

# python vol.py -l vmi://ubuntu_Guest --profile=LinuxUbuntu1604x64 linux_pslist

Volatility Foundation Volatility Framework 2.6.1
Offset             Name                 Pid             PPid            Uid             Gid    DTB                Start Time
------------------ -------------------- --------------- --------------- --------------- ------ ------------------ ----------
No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 QemuCoreDumpElf: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareAddressSpace: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 SkipDuplicatesAMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace - EXCEPTION: 'CompiledFFI' object has no attribute 'unpack'
 LimeAddressSpace - EXCEPTION: 'CompiledFFI' object has no attribute 'unpack'
 WindowsHiberFileSpace32: PO_MEMORY_IMAGE is not available in profile
 WindowsCrashDumpSpace64BitMap - EXCEPTION: 'CompiledFFI' object has no attribute 'unpack'
 QemuCoreDumpElf - EXCEPTION: 'CompiledFFI' object has no attribute 'unpack'
 WindowsCrashDumpSpace64 - EXCEPTION: 'CompiledFFI' object has no attribute 'unpack'
 HPAKAddressSpace: Location is not of file scheme
 VMWareMetaAddressSpace: Location is not of file scheme
 VirtualBoxCoreDumpElf64 - EXCEPTION: 'CompiledFFI' object has no attribute 'unpack'
 VMWareAddressSpace: Invalid VMware signature: -
 WindowsCrashDumpSpace32 - EXCEPTION: 'CompiledFFI' object has no attribute 'unpack'
 SkipDuplicatesAMD64PagedMemory: Incompatible profile LinuxUbuntu1604x64 selected
 WindowsAMD64PagedMemory: Incompatible profile LinuxUbuntu1604x64 selected
 LinuxAMD64PagedMemory - EXCEPTION: 'CompiledFFI' object has no attribute 'unpack'
 AMD64PagedMemory - EXCEPTION: 'CompiledFFI' object has no attribute 'unpack'
 IA32PagedMemoryPae: Incompatible profile LinuxUbuntu1604x64 selected
 IA32PagedMemory: Incompatible profile LinuxUbuntu1604x64 selected
 OSXPmemELF - EXCEPTION: 'CompiledFFI' object has no attribute 'unpack'
 VMIAddressSpace: Must be first Address Space
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: Failed valid Address Space check

I would greatly appreciate it if you kindly give us some feedback and share your views.

Thanks

**Comment by atcuno** [comment]
Can you please run the following command and paste the output?

$ strings -a <path to memory sample> | grep gcc | grep Linux

Also, on the running vm, can you paste the output of:

1) cat /proc/version

2) uname -a
