### ISSUE TITLE
Windows 10 18362, no found pslist (

### ISSUE THREAD

**Issue by xSanx** [volatilityfoundation/volatility#684]
help please, no found pslist  Windows 10x64_18362-->
INFO    : volatility.debug    : Determining profile based on KDBG search...
          Suggested Profile(s) : No suggestion (Instantiated with Win10x64_18362)
                     AS Layer1 : SkipDuplicatesAMD64PagedMemory (Kernel AS)
                     AS Layer2 : FileAddressSpace (/home/kali/Desktop/DESKTOP-JU6HML9-20200216-124733.raw)
                      PAE type : No PAE
                           DTB : 0x1ad002L
             KUSER_SHARED_DATA : 0xfffff78000000000L
           Image date and time : 2020-02-16 12:47:36 UTC+0000
     Image local date and time : 2020-02-16 17:47:36 +0500
 
then python vol.py  -f /home/kali/Desktop/DESKTOP-JU6HML9-20200216-124733.raw --profile=Win10x64_18362 pslist

Offset(V)          Name                    PID   PPID   Thds     Hnds   Sess  Wow64 Start                          Exit                          

------------------ -------------------- ------ ------ ------ -------- ------ ------ ----------------------------
-- ------------------------------
 
Thank you

**Comment by atcuno** [comment]
Hello,

1) How was memory acquired?

2) Are you on the latest master branch checkout of Volatility?

3) Can you run:

$ python vol.py -f /home/kali/Desktop/DESKTOP-JU6HML9-20200216-124733.raw --profile=Win10x64_18362 kdbgscan

and paste the entire input/output?

Thanks.

**Comment by xSanx** [comment]
1. DumpIT
2. 2.6.1
3. kali@kali:~/volatility$ python vol.py  -f /home/kali/Desktop/DESKTOP-JU6HML9-20200216-124733.raw --profile=Win10x64_18362 kdgscan
Volatility Foundation Volatility Framework 2.6.1
*** Failed to import volatility.plugins.registry.shutdown (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.getservicesids (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.timeliner (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.malware.servicediff (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.userassist (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.getsids (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.shellbags (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.evtlogs (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.tcaudit (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.shimcache (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.dumpregistry (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.lsadump (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.malware.threads (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.mac.apihooks_kernel (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.registry.amcache (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.mac.check_syscall_shadow (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.malware.svcscan (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.auditpol (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.ssdt (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.registry.registryapi (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.mac.apihooks (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.envars (ImportError: No module named Crypto.Hash)
ERROR   : volatility.debug    : You must specify something to do (try -h)
kali@kali:~/volatility$ python vol.py  -f /home/kali/Desktop/DESKTOP-JU6HML9-20200216-124733.raw --profile=Win10x64_18362 kdbgscan
Volatility Foundation Volatility Framework 2.6.1
*** Failed to import volatility.plugins.registry.shutdown (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.getservicesids (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.timeliner (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.malware.servicediff (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.userassist (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.getsids (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.shellbags (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.evtlogs (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.tcaudit (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.shimcache (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.dumpregistry (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.lsadump (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.malware.threads (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.mac.apihooks_kernel (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.registry.amcache (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.mac.check_syscall_shadow (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.malware.svcscan (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.auditpol (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.ssdt (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.registry.registryapi (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.mac.apihooks (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.envars (ImportError: No module named Crypto.Hash)
kali@kali:~/volatility$

**Comment by atcuno** [comment]
```*** Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined)
```

Please install distorm3 with the python bindings and then try again.

**Comment by xSanx** [comment]
Instantiating KDBG using: Unnamed AS Win10x64_18362 (6.4.18362 64bit)
Offset (V)                    : 0xf8002ce265e0
Offset (P)                    : 0x28265e0
KdCopyDataBlock (V)           : 0xf8002cca2424
Block encoded                 : Yes
Wait never                    : 0x6aaf2a0034c55443
Wait always                   : 0x698a9f15d5e840
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win10x64_18362
Version64                     : 0xf8002ce2a3d8 (Major: 15, Minor: 18362)
Service Pack (CmNtCSDVersion) : 0
Build string (NtBuildLab)     : 18362.1.amd64fre.19h1_release.19
PsActiveProcessHead           : 0xfffff8002ce38b40 (1 processes)
PsLoadedModuleList            : 0xfffff8002ce48190 (1 modules)
KernelBase                    : 0xfffff8002ca00000 (Matches MZ: True)
Major (OptionalHeader)        : 10
Minor (OptionalHeader)        : 0
KPCR                          : 0xfffff8002a7e2000 (CPU 0)
KPCR                          : 0xffffa901c0340000 (CPU 1)
KPCR                          : 0xffffa901c03d2000 (CPU 2)
KPCR                          : 0xffffa901c0480000 (CPU 3)

**Comment by xSanx** [comment]
Offset(V)          Name                    PID   PPID   Thds     Hnds   Sess  Wow64 Start                          Exit                          
------------------ -------------------- ------ ------ ------ -------- ------ ------ ------------------------------ ------------------------------
0xffffe4042fce4340                           0      0      0 -------- ------      0

**Comment by atcuno** [comment]
Hello,

Is that the full output of kdbgscan? If so, you have a corrupt memory sample and will need to re-acquire memory, ideally with a more stable acquisition tool.

**Comment by xSanx** [comment]
> Hello,
> 
> Is that the full output of kdbgscan? If so, you have a corrupt memory sample and will need to re-acquire memory, ideally with a more stable acquisition tool.

hello, thank you! stunningly ! ;)
