### ISSUE TITLE
Win10 profile

### ISSUE THREAD

**Issue by mobahi99** [volatilityfoundation/volatility#685]
Hi,
when I tried to use the Win10x64_17134 profile with a raw memory dump from a windows 10 host,  I get the followed error:

 >volatility --profile=Win10x64_17134 -f 20200219.bin malfind
Volatility Foundation Volatility Framework 2.6
ERROR   : volatility.debug    : Invalid profile Win10x64_17134 selected

The error is "Invalid profile Win10x64_17134". The memory dump is from a Windows 10  version 1903, build 18362.657. 

I have also tried with all the Win10x64 profiles (10586,14393,15036,16299,17134,17770) and I got the same message error.

I have tried with a memory dump from a Windows 7, and the Win7SP1x64 profile and I don't have any problem, It works very well.

Could you help me how to get work with the Win10x64 profile? 

Thanks.

**Comment by atcuno** [comment]
Are you using the latest master branch of Volatility from GitHub?

**Comment by MaxZabuty** [comment]
Try using this profile: Win10x64_18362
If it says it doesn't recognize this profile, you probably using an old version of volatility,
you should clone the new one.

**Comment by mobahi99** [comment]
I was using an old version of volatility. I have installed the new one and it works very well. 

Thanks to everyone

**Comment by gleeda** [comment]
@mobahi99 since it seems that you have figured out a solution, I'm going to close this ticket now.
