### ISSUE TITLE
Windows and Linux

### ISSUE THREAD

**Issue by PhalgunNK** [volatilityfoundation/volatility#691]
Hello, 
I have been trying the netscan plugin to identify the active and expired connections.
However, when used with Kali linux, the Foreign IP addresses shows up but when used with the same version of volatility on Windows 10, the Foreign IP address does not show up. 
what can be done for this. Thank you

**Comment by atcuno** [comment]
Are you using the standalone executable on Windows and a more recent source code checkout on Linux? If so, that is expected as the source code is up to date and the stand alone version is very old. Please re-open the ticket if that is not the case.
