### ISSUE TITLE
s390x support

### ISSUE THREAD

**Issue by tnazzaro** [volatilityfoundation/volatility#695]
I have RHEL7 memory dump and profile created from a an instance running on s390x chipset. Volatility (py2 or py3 versions) does not detect it properly. I would like to create s390x support, but I do not know where to begin. I am not a programmer, per se, but do a bit of python scripting for smaller purposes. Is there anybody in the community who can point me in the right direction?

**Comment by atcuno** [comment]
Are you more interested in supporting for Volatility 2 or 3 or both?

I am going to close this as discussing this in tickets is hard, but please join our Slack server for more real-time discussion: https://www.volatilityfoundation.org/slack
