### ISSUE TITLE
There is no option available of -p or --pid in volatility

### ISSUE THREAD

**Issue by Obad94** [volatilityfoundation/volatility#697]
There is no option available of -p or --pid in volatility, tried various versions of volatility including standalone executable and python packages but got no luck. Few months ago I worked with the same options(-p or --pid) but now I have changed my machine and unable to work further.
Search various platforms but unfortunately there is not enough material available.

Python Version : 2.7.13
Volatility Version : 2.6 (Python packages/ Standalone executable)
Operating System : Windows 8.1 pro

**Comment by gleeda** [comment]
What plugins were you trying to run?  Could you please copy/paste your commands here?

**Comment by atcuno** [comment]
I am closing this as not enough information was provided. Please re-open if you can confirm you are using the latest checkout of Volatility as well as the full input/output of your command line invocation.
