### ISSUE TITLE
No suitable address space mapping found

### ISSUE THREAD

**Issue by leandroflxsilva** [volatilityfoundation/volatility#698]
Hello, i have a problem with Volatility version 2.6. I'm using Windows 10 but the copy is Windows 7 32bits.
First command:
<img width="516" alt="01" src="https://user-images.githubusercontent.com/10616268/78818212-b5387a00-79aa-11ea-8cd8-91bd80ff608c.PNG">

Second command:
<img width="375" alt="02" src="https://user-images.githubusercontent.com/10616268/78818265-c71a1d00-79aa-11ea-9995-f8972913d15b.PNG">

**Comment by gleeda** [comment]
Could you try to use the other `Win7SP1x86_23418` profile?  If that doesn't work, could you run `kdbgscan` and see what comes back from that?

**Comment by leandroflxsilva** [comment]
I tried with the profile **Win7SP1x86_23418**
<img width="481" alt="01" src="https://user-images.githubusercontent.com/10616268/81816800-392dd680-9502-11ea-8353-82e96a19fab1.PNG">

The result of the command **kdbgscan** is this:
<img width="520" alt="02" src="https://user-images.githubusercontent.com/10616268/81816976-6da19280-9502-11ea-8336-65720df2174d.PNG">
<img width="517" alt="03" src="https://user-images.githubusercontent.com/10616268/81816988-709c8300-9502-11ea-8c75-66ac9e930668.PNG">

**Comment by atcuno** [comment]
Can you try with --profile= instead of profile: ? I have never seen that form of command line argument and I am not sure if Volatility will support it.

Also, how was memory acquired?

**Comment by leandroflxsilva** [comment]
I tried with the command **"--profile"**
<img width="703" alt="01" src="https://user-images.githubusercontent.com/10616268/81873258-bcc2e400-9551-11ea-8625-5ea1c5aa5b12.PNG">

I acquired the memory with the FTK IMAGER.

**Comment by atcuno** [comment]
it would be --profile=Win7SP1x86_23418

note the = instead of :

**Comment by leandroflxsilva** [comment]
Wow, it worked.Thank you so much. 
<img width="624" alt="01" src="https://user-images.githubusercontent.com/10616268/81876928-352da300-955a-11ea-9254-05d708eb877d.PNG">

**Comment by atcuno** [comment]
Glad it worked!
