### ISSUE TITLE
How to extract file from dmp file?

### ISSUE THREAD

**Issue by xStevex** [volatilityfoundation/volatility#704]
Hi,
I'm using 2.6.1 version

vol.py -f test.dmp --profile=Win10x64 dumpfiles -n -i -r \\.txt --dump-dir=./

I tried it, but this didn't work. I can't export any files. 
Also, I can look to the body of txt files via vol?
P.S. I know my specific profile of windows

**Comment by gleeda** [comment]
Could you try running the `filescan` plugin and finding the offset for the file(s) you'd like to extract and see if you can dump them by supplying that offset?  It's possible that the text files are no longer open by a process, which is how the `dumpfiles` plugin dumps files by default.

**Comment by xStevex** [comment]
I tried, but nothing happened. No errors and no files. 
Do you know how I can dump it by another way or how to look indise to the txt file?
To tell the truth, I don't have to download the file, I need its contents.

**Comment by gleeda** [comment]
Unfortunately, there are times when file contents are no longer cached, or the pointers to contents are corrupt.  In these cases we are unable to dump the file.  

You may still get lucky and find some of the file contents in unallocated memory, however.  You could try looking at strings from memory if you know kind of what you're looking for.

Or if it's a small file, you might find it in the `$Mft` resident in memory.  In this case, you could either dump the `$Mft` from memory and run the `mftparser` plugin against it, or you could just run the `mftparser` plugin across the entire memory sample.  If you find a record for that text file, you can dump the contents (if they are resident) using the appropriate offset.

**Comment by xStevex** [comment]
I found the file in MFT, but in MFT the file is already changed and I need the previous version of this file that show me filescan, but as I said I can't dump the file. 

I also found old issue that dumpfiles can work incorect. There is a proofconcept:
https://github.com/volatilityfoundation/volatility/issues/588 (third comment with screenshot)

In my case there is one nuance, the file or his content can be get 100%. Because it's a verified task and people before me have done it (I have no way of asking them, heh).

But I'm already confused about whether the program is working correctly or if I need to continue searching in a different direction. 

How I can test dumpfiles to be sure that plugin is working correct? There is an option to dump all possible files? I mean, if I can dump at least some files, I will be sure that plugin works good. I tried to dump few random files by offset, but no luck. I need something option "--all".

**Comment by xStevex** [comment]
Nevermind, the plugin is working correct.
I found my file via plugin Shellbags. There is only one record with my file. Now I need to get him somehow.

**Comment by atcuno** [comment]
Unfortunately as @gleeda mentioned, dumpfiles is reliant on files being cached in order to recover them. 

You can run dumpfiles with just -D <directory> in order to gather all cached files.

Also, how was memory acquired?

**Comment by xStevex** [comment]
Hi @atcuno 
Sorry, the plugin is working good, It was CTF and there was another way to get my data. I'm sorry to mislead you all.

**Comment by PiscoMule** [comment]
Hey, I'm very interested by this "other way" you mentionned. Is there any way we discuss about it ?
