### ISSUE TITLE
Volatility 2.6 gives error on imageinfo command even though it is correct !

### ISSUE THREAD

**Issue by MehdiKa20** [volatilityfoundation/volatility#708]
I don't understand a simple command as :
volatility imageinfo -f file.mem
gives me the following error:
![Capture](https://user-images.githubusercontent.com/58915841/81996013-7a75d180-963b-11ea-879a-a7f3811deb1c.PNG)
I've tried it on Parrot and Kali still no luck ! This is driving me crazy all the other commands work no problem except for this one it always gives me the same Error

**Comment by atcuno** [comment]
Can you please paste a non-cropped screenshot so we can see the input and output?

Also, what OS is the sample from?
