### ISSUE TITLE
Windows 10 Version 1909 Build 18363.778

### ISSUE THREAD

**Issue by Peter412pa** [volatilityfoundation/volatility#709]
Hello,

Does volatility support Windows 10 Version 1909 Build 18363.778?  I captured the memory from this machine using FTK Imager and then saved as a .mem file.  

I have tried to do a KDBG search but it stalls in search mode until I have to interrupt the process.

I have also tried to run normal commands against the image with the Volatility Standalone Windows version without any success. All I receive is "No suitable address space mapping found."

I have tried using all available win profiles that I have found online.  Perhaps I am missing one, unless this built is not yet supported.

Any assistance that you can provide would be greatly appreciated.

Pete

**Comment by atcuno** [comment]
Hello,

The standalone version is over 3 years old. Please use the latest master checkout from here (GitHub), and that version of Windows will be supported.

Please re-open the ticket if you have any analysis issues with the source code version.
