### ISSUE TITLE
imageinfo / kdbgscan return with no information

### ISSUE THREAD

**Issue by zredaxz** [volatilityfoundation/volatility#722]
Hi,

Scenario: Volatility 2.6.1 is installed on Ubuntu 18.04.
The memory is dump is collected with pcileech from Windows 10 x64.

I tried to run the volatility imageinfo / kdbgscan etc. with or without providing profile. The result is the same, after ~20-30 minutes I got the prompt back and that's it, please see the screenshot below.

Any idea what is wrong here? 

![image](https://user-images.githubusercontent.com/53194916/83978954-d68ce800-a8bf-11ea-9f1a-34225f97dcf8.png)

**Comment by AqibMukhtar** [comment]
Why haven't you wrote `python` before `vol.py`?
