### ISSUE TITLE
volatility Application.evntx

### ISSUE THREAD

**Issue by winliroot7** [volatilityfoundation/volatility#733]
Hi,
Im just triying out to get the .evntx log from .raw file with volatility tool but nothing works so far, someone can help me to figure it out how to do it. 
Thank you

**Comment by atcuno** [comment]
Can you please provide the input and output of any commands you try to achieve this with?

**Comment by winliroot7** [comment]
I'm new at this, and i read some topics but actually i don't find any pluggin that helps me to get the windows event log as a .txt. Application.evtx.
I tried this input:

root@kali:/home/kali/Desktop/C183RWall# volatility -f memoryram.raw --profile=Win10x64_10586 evtxtract

**Comment by fpusersuggest** [comment]
As I know the only plugin to have info about events from a windows sample is:

    eventhooks                 - Print details on windows event hooks
    evtlogs                    - Extract Windows Event Logs (XP/2003 only)

**evtxtract** doesn't exist. Also you should give more details, for example how you make the dump and copy/paste all logs output.
I searched **evtxtract** on google and I found [this](https://github.com/williballenthin/EVTXtract). Then in my opinion you confused two different software.
