### ISSUE TITLE
pslist don't show the full process name.

### ISSUE THREAD

**Issue by N1neSun** [volatilityfoundation/volatility#734]
pslist command don't show the full process name.

**Comment by atcuno** [comment]
The data structure used to track process names in the kernel only has room for the first 16 characters of the process name. You can try the cmdline plugin in an attempt to get the full process name, but be aware that 1) this data can be paged out 2) it can be manipulated by malware running in a process' address space. You can also try the vadinfo plugin to see the full path from where a process started. Be aware of potential process hollowing though.

**Comment by N1neSun** [comment]
thanks!
