### ISSUE TITLE
Win10x64_18362 no found pslist

### ISSUE THREAD

**Issue by abrDCP** [volatilityfoundation/volatility#738]
When I want to get the processes, as a start of the analysis process, it is not able to extract any process, it only works with the pluggin "netscan"

1) I used the "dumpIt" tool
2) Kdbgscan result:

"Volatility Foundation Volatility Framework 2.6.1
**************************************************
Instantiating KDBG using: Unnamed AS Win10x64_18362 (6.4.18362 64bit)
Offset (V)                    : 0xf8043f8265e0
Offset (P)                    : 0x32265e0
KdCopyDataBlock (V)           : 0xf8043f6a2754
Block encoded                 : Yes
Wait never                    : 0xbe80000ac1378609
Wait always                   : 0x560995858f40a800
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win10x64_18362
Version64                     : 0xf8043f82a3c8 (Major: 15, Minor: 18362)
Service Pack (CmNtCSDVersion) : 0
Build string (NtBuildLab)     : 18362.1.amd64fre.19h1_release.19
PsActiveProcessHead           : 0xfffff8043f838b80 (0 processes)
PsLoadedModuleList            : 0xfffff8043f848190 (0 modules)
KernelBase                    : 0xfffff8043f400000 (Matches MZ: True)
Major (OptionalHeader)        : 10
Minor (OptionalHeader)        : 0
KPCR                          : 0xfffff8043ca09000 (CPU 0)
KPCR                          : 0xffffbc00fd4c5000 (CPU 1)
KPCR                          : 0xffffbc00fd579000 (CPU 2)
KPCR                          : 0xffffbc00fd5d1000 (CPU 3)"

3) pslist:
python vol.py -f 20200713-092611.raw --profile=Win10x64_18362 pslist
Volatility Foundation Volatility Framework 2.6.1
Offset(V)          Name                    PID   PPID   Thds     Hnds   Sess  Wow64 Start                          Exit                          
------------------ -------------------- ------ ------ ------ -------- ------ ------ ------------------------------ ------------------------------

How can I solve this problem?

Thank you
Best Regards.

**Comment by atcuno** [comment]
Did you let kdbgscan run until completition? Or did you stop it after that first result?

**Comment by abrDCP** [comment]
Hi atcuno, 

Run until completition.

Thank you
Best Regards,

**Comment by abrDCP** [comment]
> Did you let kdbgscan run until completition? Or did you stop it after that first result?

Hi atcuno,

Run until completition.
What could be the issue?

Thank you
Best Regards,

**Comment by atcuno** [comment]
The one kdbg structure found lists 0 processes and 0 modules:

```
PsActiveProcessHead : 0xfffff8043f838b80 (0 processes)
PsLoadedModuleList : 0xfffff8043f848190 (0 modules)
```

This is a strong indication of memory smear.

Can you acquire memory with a different tool / method? If its a virtual machine you can just suspend it and then analyze the suspend files.

Also, if you run:

python vol.py -f 20200713-092611.raw --profile=Win10x64_18362 psscan

Do you get any results?

**Comment by abrDCP** [comment]
> The one kdbg structure found lists 0 processes and 0 modules:
> 
> ```
> PsActiveProcessHead : 0xfffff8043f838b80 (0 processes)
> PsLoadedModuleList : 0xfffff8043f848190 (0 modules)
> ```
> 
> This is a strong indication of memory smear.
> 
> Can you acquire memory with a different tool / method? If its a virtual machine you can just suspend it and then analyze the suspend files.
> 
> Also, if you run:
> 
> python vol.py -f 20200713-092611.raw --profile=Win10x64_18362 psscan
> 
> Do you get any results?

Hi Andrew,

I tried another PC and the result was the same, I ran psscan and the same problem.
I tried another tool, and it works fine.
Thank you very much for your time, I should have tried more tools before I bothered you here.

Thank you
Best Regards,

**Comment by 12089897411** [comment]
@abrDCP I also ran into the same problem,  what tool you have changed

**Comment by abrDCP** [comment]
Hi,

With Belkasoft RAM Capturer it work fine  ;)

Best Regards,

**Comment by abrDCP** [comment]
> @abrDCP I also ran into the same problem, what tool you have changed

Hi,

With Belkasoft RAM Capturer it work fine ;)

Best Regards,

**Comment by 12089897411** [comment]
Thanks
