### ISSUE TITLE
Appropriate profile for Windows 10 64bit

### ISSUE THREAD

**Issue by vanamaria** [volatilityfoundation/volatility#739]
Hello,
I am using kali linux where I have cloned the volatility from github. I have already python 2.7 on kali. I want to use volatility on kali for an image I have acquired on Windows 10

I used FTK Imager and Magent Ram Capture to obtain .mem and . raw files respectfully from Windows 10 on VirtualBox.  The size of the file is 3GB and Windows 10 is 64bit, version 2004 and OS Build 19041.264. 
 
I have tried the following commands:
-python vol.py imageinfo -f /path/to/file/mem.raw
-python vol.py imageinfo -f /path/to/file/memdump.mem 
The result I get is (attached image): 
Volatility Foundation Volatility Framework 2.6.1
INFO : volatility.debug : Determining profile based on KDBG search...
Suggested profile(s): No suggestion (Instantiated with no profile)
AS Layer1 : FileAddressSpace (/home/kali/Desktop/mem1.raw)
PAE type : No PAE

When I am trying the command:
-python vol.py -f /path/to/file/mem.raw --profile=Win10x64 pslist
The profile is not recognized (attached image)

I have already checked the permissions of my file, it is read and write (attached image)

Any help would be appreciated.

![vol1](https://user-images.githubusercontent.com/67200891/88221416-2277ce80-cc6d-11ea-98a7-c7eed57303e6.png)
![Untitled](https://user-images.githubusercontent.com/67200891/88221431-2ad00980-cc6d-11ea-8d2f-016223413088.png)
![permissions](https://user-images.githubusercontent.com/67200891/88221451-30c5ea80-cc6d-11ea-9c73-8a64e8506fcd.png)

**Comment by atcuno** [comment]
Can you please try:

python vol.py --profile=Win10x64_19041 -f /path/to/file/mem.raw kdbgscan

Please paste the entire input/output when running the command. Also please wait for the plugin to fully finish.

Do this for each sample.

**Comment by vanamaria** [comment]
I tried it but I don't get anything as output! It doesn't produce any result!

**Comment by padie80** [comment]
Same problem here.  Major errors when a plugin is used and no data at all when kdbgscan is run.
![kdbgscan](https://user-images.githubusercontent.com/71952800/94353790-3233da80-0043-11eb-9e02-327ede508e97.JPG)

**Comment by pebryant** [comment]
See solution to issues 719 regarding distorm3 breaking volatility. You also need to do a pip install pycrypto.

**Comment by gleeda** [comment]
As mentioned in the previous comment, you need to install `distorm3` in order to get this working properly.  Closing for now, but feel free to reopen if are still having trouble.
