### ISSUE TITLE
MacOS X Catalina 10.15.6 memdump error.

### ISSUE THREAD

**Issue by juagarc4** [volatilityfoundation/volatility#740]
I'm using volatility on MacOS X Catalina 10.15.6. 

The versions I tried are 2.5 and 2.6 downloaded from https://www.volatilityfoundation.org/releases
and the version 2.6.1 installed with brew.

The Python version is 2.7.16

I tried the follow commands :

./volatility -f Desktop_cs3.raw --profile=Win10x64_10586 memdump –p 3336 –-dump-dir=dumps/
./volatility -f Desktop_cs3.raw --profile=Win10x64_10586 memdump –p 3336 –D dumps/

and I always receive the same error:

```
Volatility Foundation Volatility Framework 2.6
ERROR   : volatility.debug    : Please specify a dump directory (--dump-dir)
```

No way to get it working. Someone have had the same problem? Any solution? 
Am I doing something wrong?
Thanks in advance.

**Comment by atcuno** [comment]
The compiled releases are very old. Please use the latest source code.

Can you report what happens when using the latest source code from here (Github)?

**Comment by juagarc4** [comment]
Hi @atcuno,  

I have cloned the repository, installed distorm3 and executed:

`python volatility/vol.py -f Desktop_cs3.raw imageinfo
`
Volatility Foundation Volatility Framework 2.6.1
*** Failed to import volatility.plugins.registry.shutdown (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.getservicesids (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.timeliner (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.malware.servicediff (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.userassist (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.getsids (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.shellbags (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.evtlogs (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.tcaudit (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.dumpregistry (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.lsadump (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.malware.threads (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.mac.apihooks_kernel (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.registry.amcache (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.mac.check_syscall_shadow (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.malware.svcscan (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.auditpol (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.ssdt (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.registry.registryapi (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.mac.apihooks (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.envars (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.shimcache (ImportError: No module named Crypto.Hash)
INFO    : volatility.debug    : Determining profile based on KDBG search...
Suggested Profile(s) : No suggestion (Instantiated with Win10x64_15063)
                     AS Layer1 : SkipDuplicatesAMD64PagedMemory (Kernel AS)
                     AS Layer2 : FileAddressSpace (/Users/rgarcia/Downloads/Desktop_cs3.raw)
                      PAE type : No PAE
                           DTB : 0x1ad002L
             KUSER_SHARED_DATA : 0xfffff78000000000L
           Image date and time : 2020-06-20 11:37:21 UTC+0000
     Image local date and time : 2020-06-20 13:37:21 +0200

After that I executed: 

`python volatility/vol.py -f Desktop_cs3.raw --profile=Win10x64_15063 pstree
`
Volatility Foundation Volatility Framework 2.6.1
*** Failed to import volatility.plugins.registry.shutdown (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.getservicesids (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.timeliner (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.malware.servicediff (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.userassist (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.getsids (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.shellbags (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.evtlogs (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.tcaudit (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.dumpregistry (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.lsadump (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.malware.threads (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.mac.apihooks_kernel (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.registry.amcache (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.mac.check_syscall_shadow (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.malware.svcscan (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.auditpol (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.ssdt (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.registry.registryapi (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.mac.apihooks (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.envars (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.shimcache (ImportError: No module named Crypto.Hash)
Name                                                  Pid   PPid   Thds   Hnds Time
-------------------------------------------------- ------ ------ ------ ------ ----

It seems not recognizing the library distorm3 but it is installed:

➜  Downloads pip3 list
Package           Version
----------------- ---------
aiodns            2.0.0
aiohttp           3.6.2
aiohttp-socks     0.5.3
async-timeout     3.0.1
attrs             19.3.0
beautifulsoup4    4.9.1
cchardet          2.1.6
certifi           2020.6.20
cffi              1.14.1
chardet           3.0.4
**distorm3          3.5.0 <=**

I have installed volatility too form the source (Github cloned repo) using: 

`python setup.py install
`
The results are the same.

And I'm sure that the raw image ist right because I did the same in a Linux computer and it worked fine.

**Comment by fuomag9** [comment]
Same issue here

**Comment by atcuno** [comment]
Hello,

imageinfo and pstree are for Windows samples. Try mac_pslist please.
