### ISSUE TITLE
why linux_procdump can not dump pid 2 proccess?

### ISSUE THREAD

**Issue by N1neSun** [volatilityfoundation/volatility#745]
why linux_procdump can not dump pid=2 proccess?

**Comment by atcuno** [comment]
Hello,

Sorry for just seeing this. PID 2 is very likely going to be a kernel thread, which is has no userland memory and instead is a place for kernel threads to execute/operate. For this reason we cannot dump out a process executable as there is no executable associated with the thread. You can check for the output to have [ ] surrounding the process name.

I am going to close the ticket, but please re-open if you have any further questions.

**Comment by N1neSun** [comment]
I find if the process which PPID=2 also can't dump, also this reason cause？

**Comment by atcuno** [comment]
Can you paste the output of linux_pslist? For most samples, PID 2 will be the kernel thread daemon, named kthreadd / [kthreadd]. It what runs/manages all other kernel threads, so if a process has a PPID of 2, then it is also a kernel thread.

**Comment by N1neSun** [comment]
Offset             Name                 Pid             PPid            Uid             Gid    DTB                Start Time
------------------ -------------------- --------------- --------------- --------------- ------ ------------------ ----------
0xffff88001b018000 systemd              1               0               0               0      0x000000001a287000 2020-06-16 12:13:53 UTC+0000
0xffff88001b018fd0 kthreadd             2               0               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001b019fa0 ksoftirqd/0          3               2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001b01bf40 kworker/0:0H         5               2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001b01cf10 kworker/u256:0       6               2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001b01dee0 migration/0          7               2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001b01eeb0 rcu_bh               8               2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001b188000 rcu_sched            9               2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001b188fd0 watchdog/0           10              2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001ad09fa0 kdevtmpfs            12              2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001ad0af70 netns                13              2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001ad0bf40 khungtaskd           14              2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001ad0cf10 writeback            15              2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001ad0dee0 kintegrityd          16              2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001ad0eeb0 bioset               17              2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001ae10000 kblockd              18              2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001ae10fd0 md                   19              2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001ae16eb0 kswapd0              25              2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001ad08fd0 ksmd                 26              2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff8800176d0000 crypto               27              2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001ae14f10 kthrotld             35              2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001ae13f40 kmpath_rdacd         37              2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001ae12f70 kpsmoused            38              2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff8800176d5ee0 ipv6_addrconf        40              2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001ef34f10 deferwq              59              2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001ef31fa0 kauditd              91              2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88000004cf10 ata_sff              269             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88000004dee0 mpt_poll_0           270             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88000004bf40 mpt/0                272             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001f034f10 scsi_eh_0            280             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001f035ee0 scsi_tmf_0           281             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001f031fa0 scsi_eh_1            282             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001f036eb0 scsi_tmf_1           285             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001f033f40 scsi_eh_2            287             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001f030000 kworker/u256:2       288             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff880000049fa0 scsi_tmf_2           290             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001f032f70 ttm_swap             291             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff8800176d4f10 kdmflush             363             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff8800176d0fd0 bioset               364             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff8800176d1fa0 kdmflush             375             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff8800176d2f70 bioset               376             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff8800163fcf10 bioset               389             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff8800163f9fa0 xfsalloc             390             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff8800163faf70 xfs_mru_cache        391             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff8800163f8000 xfs-buf/dm-0         392             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff8800163f8fd0 xfs-data/dm-0        393             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff8800176d3f40 xfs-conv/dm-0        394             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001f196eb0 xfs-cil/dm-0         395             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001f194f10 xfs-reclaim/dm-      396             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001f190fd0 xfs-log/dm-0         397             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001f191fa0 xfs-eofblocks/d      398             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001f192f70 xfsaild/dm-0         399             2               0               0      ------------------ 2020-06-16 12:13:53 UTC+0000
0xffff88001ef0eeb0 systemd-journal      466             1               0               0      0x0000000019b3b000 2020-06-16 12:13:54 UTC+0000
0xffff880015ef2f70 lvmetad              483             1               0               0      0x000000001a34c000 2020-06-16 12:13:54 UTC+0000
0xffff88001ef08000 systemd-udevd        491             1               0               0      0x00000000197bb000 2020-06-16 12:13:54 UTC+0000
0xffff88001ef08fd0 rpciod               496             2               0               0      ------------------ 2020-06-16 12:13:54 UTC+0000
0xffff88001ef0bf40 xprtiod              497             2               0               0      ------------------ 2020-06-16 12:13:54 UTC+0000
0xffff8800163fbf40 nfit                 519             2               0               0      ------------------ 2020-06-16 12:13:54 UTC+0000
0xffff880019f1cf10 xfs-buf/sda1         565             2               0               0      ------------------ 2020-06-16 12:13:54 UTC+0000
0xffff8800163fdee0 xfs-data/sda1        569             2               0               0      ------------------ 2020-06-16 12:13:54 UTC+0000
0xffff880019f1af70 xfs-conv/sda1        570             2               0               0      ------------------ 2020-06-16 12:13:54 UTC+0000
0xffff880000048fd0 xfs-cil/sda1         572             2               0               0      ------------------ 2020-06-16 12:13:54 UTC+0000
0xffff880015ef1fa0 xfs-reclaim/sda      574             2               0               0      ------------------ 2020-06-16 12:13:54 UTC+0000
0xffff880019f1bf40 xfs-log/sda1         577             2               0               0      ------------------ 2020-06-16 12:13:54 UTC+0000
0xffff88001ef33f40 xfs-eofblocks/s      580             2               0               0      ------------------ 2020-06-16 12:13:54 UTC+0000
0xffff88001ef0dee0 xfsaild/sda1         583             2               0               0      ------------------ 2020-06-16 12:13:54 UTC+0000
0xffff880019216eb0 kworker/0:1H         602             2               0               0      ------------------ 2020-06-16 12:13:56 UTC+0000
0xffff880015ef6eb0 auditd               650             1               0               0      0x000000001ab58000 2020-06-16 12:14:00 UTC+0000
0xffff880019212f70 VGAuthService        676             1               0               0      0x0000000019203000 2020-06-16 12:14:00 UTC+0000
0xffff880019210000 vmtoolsd             677             1               0               0      0x0000000019202000 2020-06-16 12:14:00 UTC+0000
0xffff880015ef0fd0 smartd               680             1               0               0      0x000000001a3c8000 2020-06-16 12:14:00 UTC+0000
0xffff880015ef0000 systemd-logind       681             1               0               0      0x0000000019c68000 2020-06-16 12:14:00 UTC+0000
0xffff880015ef3f40 abrtd                682             1               0               0      0x000000001931a000 2020-06-16 12:14:00 UTC+0000
0xffff8800163feeb0 polkitd              684             1               999             997    0x000000001a3ca000 2020-06-16 12:14:00 UTC+0000
0xffff88001f190000 rsyslogd             686             1               0               0      0x000000001a244000 2020-06-16 12:14:00 UTC+0000
0xffff88001ef09fa0 rngd                 687             1               0               0      0x0000000017b1f000 2020-06-16 12:14:00 UTC+0000
0xffff88001ef0cf10 lsmd                 688             1               998             996    0x000000001a3f1000 2020-06-16 12:14:00 UTC+0000
0xffff880019f1eeb0 dbus-daemon          692             1               81              81     0x0000000019c70000 2020-06-16 12:14:00 UTC+0000
0xffff88001ef30fd0 gssproxy             700             1               0               0      0x0000000018c36000 2020-06-16 12:14:00 UTC+0000
0xffff880015383f40 abrt-watch-log       717             1               0               0      0x0000000018a18000 2020-06-16 12:14:00 UTC+0000
0xffff880019213f40 atd                  732             1               0               0      0x00000000198ca000 2020-06-16 12:14:01 UTC+0000
0xffff880019828fd0 crond                735             1               0               0      0x00000000198a5000 2020-06-16 12:14:01 UTC+0000
0xffff88001982af70 firewalld            737             1               0               0      0x0000000019875000 2020-06-16 12:14:01 UTC+0000
0xffff880019f1dee0 NetworkManager       774             1               0               0      0x00000000189ae000 2020-06-16 12:14:01 UTC+0000
0xffff880018f29fa0 tuned                1029            1               0               0      0x0000000017df8000 2020-06-16 12:14:01 UTC+0000
0xffff880018f2dee0 sshd                 1030            1               0               0      0x0000000017dfd000 2020-06-16 12:14:01 UTC+0000
0xffff880018f2bf40 cupsd                1031            1               0               0      0x0000000017dfb000 2020-06-16 12:14:01 UTC+0000
0xffff880019f18000 master               1184            1               0               0      0x0000000017f69000 2020-06-16 12:14:01 UTC+0000
0xffff880000048000 qmgr                 1188            1184            89              89     0x0000000017f3f000 2020-06-16 12:14:01 UTC+0000
0xffff880018de9fa0 dhclient             1990            774             0               0      0x000000000ce5c000 2020-06-16 12:23:48 UTC+0000
0xffff88000cf28fd0 sshd                 2051            1030            0               0      0x000000000ce7f000 2020-06-16 12:24:59 UTC+0000
0xffff88000cf29fa0 bash                 2055            2051            0               0      0x000000000ccb3000 2020-06-16 12:25:11 UTC+0000
0xffff88000ce11fa0 agetty               2096            1               0               0      0x00000000188e8000 2020-06-16 12:25:54 UTC+0000
0xffff88000ce10fd0 pickup               44683           1184            89              89     0x000000001aa9b000 2020-06-18 14:15:47 UTC+0000
0xffff880018f2eeb0 kworker/0:1          44862           2               0               0      ------------------ 2020-06-18 15:17:06 UTC+0000
0xffff88000ce12f70 kworker/0:2          44869           2               0               0      ------------------ 2020-06-18 15:20:06 UTC+0000
0xffff88000ce15ee0 kworker/0:0          44870           2               0               0      ------------------ 2020-06-18 15:25:07 UTC+0000
0xffff880018f2cf10 kworker/0:3          45213           2               0               0      ------------------ 2020-06-18 15:28:08 UTC+0000
0xffff88000ce16eb0 insmod               45221           2055            0               0      0x000000000cfc7000 2020-06-18 15:30:58 UTC+0000

**Comment by atcuno** [comment]
@N1neSun yes, these are kernel threads. You can see the parent PID of 2 and that they don't have their own DTB (they are part of the kernel). If you run linux_psaux you should see the [ ] around their names.
