### ISSUE TITLE
vol.py (volatility 2.6) won't work in macOS Catalina 10.15.6 with python version 3.6.5

### ISSUE THREAD

**Issue by ErickGiffoni** [volatilityfoundation/volatility#748]
### The problem

I've downloaded [volatility 2.6](https://github.com/volatilityfoundation/volatility/releases/tag/2.6) zip and tried running it on macOS Catalina 10.15.6, python version 3.6.5, like this : 

```
volatility-2.6$ python vol.py 
  File "vol.py", line 118
    print "\n"
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\n")?
```
I notice that volatility requires python 2.6, but I thought it would work on later python versions.
`vol.py` : 
```
33| if sys.version_info < (2, 6, 0):
34|    sys.stderr.write("Volatility requires python version 2.6, please upgrade your python installation.")
35|    sys.exit(1)
```

Am I doing something wrong or the above proceeds ?

### Solution ?

Maybe I could simple edit `vol.py` and add parentheses to all `print` calls, but that's a lot and and there has to be a better solution.

Would anyone like to complement this with a solution ?

**Comment by mmxmb** [comment]
See **Requirements** section. This project uses Python 2.

See https://github.com/volatilityfoundation/volatility3 if you want to use Python 3.

**Comment by atcuno** [comment]
@mmxmb thank you for responding with the Volatility 3 link. Closing this now.

**Comment by ErickGiffoni** [comment]
thank you all
