### ISSUE TITLE
Dumpcerts plugin says yara NOT installed!?!?

### ISSUE THREAD

**Issue by tschla1** [volatilityfoundation/volatility#750]
I cannot run the _dumpcerts_ plugin; I am getting an error that yara is not installed, even though I have already installed it.

![image](https://user-images.githubusercontent.com/13107188/92141201-6801ec80-ee12-11ea-82ab-863ef247d4e2.png)

Any assistance is appreciated!!

**Comment by N1neSun** [comment]
you may try "pip install yara-python"

**Comment by atcuno** [comment]
You need to install the python yara bindings as mentioned by @N1neSun
