### ISSUE TITLE
volatility unable to analyze windows 10 memory dump

### ISSUE THREAD

**Issue by jharry78** [volatilityfoundation/volatility#751]
Hi,
I have made a memory dump with livekd64 on Windows 10 and when I use volatility to scan the different connection with the command:
`python2 vol.py -f memory.dmp connscan`
and here is the output
`WARNING : volatility.debug    : Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow
WARNING : volatility.debug    : Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow
WARNING : volatility.debug    : Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow
WARNING : volatility.debug    : Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow
WARNING : volatility.debug    : Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow
WARNING : volatility.debug    : Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow
WARNING : volatility.debug    : Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow
WARNING : volatility.debug    : Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow
WARNING : volatility.debug    : Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow
WARNING : volatility.debug    : Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow
WARNING : volatility.debug    : Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow
WARNING : volatility.debug    : Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow
WARNING : volatility.debug    : Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow
WARNING : volatility.debug    : Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow
WARNING : volatility.debug    : Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow
WARNING : volatility.debug    : Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow
WARNING : volatility.debug    : Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow
WARNING : volatility.debug    : Alignment of WindowsCrashDumpSpace64 is too small, plugins will be extremely slow
No suitable address space mapping found
Tried to open image as:
 MachOAddressSpace: mac: need base
 LimeAddressSpace: lime: need base
 WindowsHiberFileSpace32: No base Address Space
 WindowsCrashDumpSpace64BitMap: No base Address Space
 WindowsCrashDumpSpace64: No base Address Space
 HPAKAddressSpace: No base Address Space
 VirtualBoxCoreDumpElf64: No base Address Space
 VMWareMetaAddressSpace: No base Address Space
 VMWareAddressSpace: No base Address Space
 QemuCoreDumpElf: No base Address Space
 WindowsCrashDumpSpace32: No base Address Space
 SkipDuplicatesAMD64PagedMemory: No base Address Space
 WindowsAMD64PagedMemory: No base Address Space
 LinuxAMD64PagedMemory: No base Address Space
 AMD64PagedMemory: No base Address Space
 IA32PagedMemoryPae: No base Address Space
 IA32PagedMemory: No base Address Space
 OSXPmemELF: No base Address Space
 MachOAddressSpace: MachO Header signature invalid
 LimeAddressSpace: Invalid Lime header signature
 WindowsHiberFileSpace32: No xpress signature found
 WindowsCrashDumpSpace64BitMap: Unsupported dump format
 MachOAddressSpace - EXCEPTION: integer division or modulo by zero
 LimeAddressSpace - EXCEPTION: integer division or modulo by zero
 WindowsHiberFileSpace32 - EXCEPTION: integer division or modulo by zero
 WindowsCrashDumpSpace64BitMap - EXCEPTION: integer division or modulo by zero
 WindowsCrashDumpSpace64 - EXCEPTION: integer division or modulo by zero
 HPAKAddressSpace: Invalid magic found
 VirtualBoxCoreDumpElf64 - EXCEPTION: integer division or modulo by zero
 VMWareMetaAddressSpace: VMware metadata file is not available
 VMWareAddressSpace: Invalid VMware signature: -
 QemuCoreDumpElf - EXCEPTION: integer division or modulo by zero
 WindowsCrashDumpSpace32 - EXCEPTION: integer division or modulo by zero
 SkipDuplicatesAMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 WindowsAMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 LinuxAMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 AMD64PagedMemory: Incompatible profile WinXPSP2x86 selected
 IA32PagedMemoryPae - EXCEPTION: long division or modulo by zero
 IA32PagedMemory - EXCEPTION: long division or modulo by zero
 OSXPmemELF - EXCEPTION: integer division or modulo by zero
 FileAddressSpace: Must be first Address Space
 ArmAddressSpace: Profile does not have valid Address Space check`
I don't understand how to fix this.
Thank you in advance.

**Comment by iMHLv2** [comment]
If its a Windows 10 sample, you'd want to use one of the Windows 10 profiles (i.e., --profile=Win10x64_14393). Also see https://github.com/volatilityfoundation/volatility/wiki/2.6-Win-Profiles. Lastly, connscan is for XP/2003 only....use netscan instead.
