### ISSUE TITLE
DW_DLE_VERSION_STAMP_ERROR

### ISSUE THREAD

**Issue by Harshasa** [volatilityfoundation/volatility#755]
Hi ,
I am getting below error while running dwarfdump cmd. Am trying this step on 3.10 host machine module.o is cross compiled for x86 for linux 4.x embedded box. 
Is there any workaround for this step?

dwarfdump -di ./module.o > module.dwarf
dwarfdump ERROR:  attempting to print .debug_info:  DW_DLE_VERSION_STAMP_ERROR (48) (48)

 ERROR:  attempting to print .debug_info:  DW_DLE_VERSION_STAMP_ERROR (48) (48)

Thanks in advance.

**Comment by atcuno** [comment]
Can you try upgrading your version of dwarfdump? We do not develop dwarfdump, we just rely on it for profile generation.
