### ISSUE TITLE
Volatility is not working well with WinPmem

### ISSUE THREAD

**Issue by dougcello** [volatilityfoundation/volatility#756]
Hi! I extracted images with WinPmem 3.3 software from Windows 8.1 6.3.9600 64 bits and Windows 7 6.1.7601 SP1 64 bits, and with the Framework I was unable to analyze any of these images. Out of conscience I got to test ALL profiles. I am in doubt if the problem is in WinPmem or if Volatility really became incompatible with these samples. I used the pslist plugin. I ask for help.
![Pslist - Error Win7](https://user-images.githubusercontent.com/60231024/94996473-5fb8e080-057b-11eb-8de6-72b9886e7717.JPG)
![Pslist - Error Win8](https://user-images.githubusercontent.com/60231024/94996476-621b3a80-057b-11eb-8c9e-786fb3c2568a.JPG)

**Comment by dougcello** [comment]
The same thing was happen with a WinXP memory. 
I am learning to use this tool for the first time, but I have been wondering for a few weeks if the problem is in the framework or in winpmem. In winpmem I tested ALL possible extraction formats with the tool, but the incompatibility remains. I look forward to an answer.

![Pslist - Error WinXP](https://user-images.githubusercontent.com/60231024/94997858-4cf6d980-0584-11eb-8477-75394a053653.JPG)

**Comment by atcuno** [comment]
Can you run:

xxd <path to memory sample> | head -10

and paste the result?

Can you also run:

file <path to memory sample>

And paste the result?

I would like to see if the file is AFF4 or RAW.

**Comment by dougcello** [comment]
Hi!
Unfortunately I deleted two of the 3 files. I kept only the Windows 7 dump, extracted with the --format raw function. See below:

00000000: 504b 0304 1400 0800 0000 8160 4951 0000  PK.........`IQ..
00000010: 0000 0000 0000 0000 0000 1500 2000 636f  ............ .co
00000020: 6e74 6169 6e65 722e 6465 7363 7269 7074  ntainer.descript
00000030: 696f 6e01 001c 002b 0000 0000 0000 002b  ion....+.......+
00000040: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000050: 0000 0061 6666 343a 2f2f 3130 6166 6235  ...aff4://10afb5
00000060: 3338 2d33 3362 372d 3463 6236 2d38 3839  38-33b7-4cb6-889
00000070: 662d 3737 3432 3263 3535 3337 3938 504b  f-77422c553798PK
00000080: 0708 af3d 3e8b 2b00 0000 0000 0000 2b00  ...=>.+.......+.
00000090: 0000 0000 0000 504b 0304 1400 0800 0000  ......PK........

**Comment by atcuno** [comment]
ok, this is an AFF4 zip file. You can see based on the PK header and the aff4:// stream uri. 

The raw option to pmem is very confusing (it confuses everyone, not just you), as --format raw makes the output memory sample raw, but still puts it into an AFF4 container. You will need to extract the memory sample stream from the container to then analyze it.

**Comment by dougcello** [comment]
What made me extremely confused is that with the --volume_format function it works perfectly. Can you explain me why?

**Comment by atcuno** [comment]
with "--volume_format raw" you are telling pmem to create a fully raw image, not an AFF4 container.

By using the 'file' command or xxd like you did before, you can always tell the format the sample is in.

**Comment by dougcello** [comment]
The function of the command "xxd", as well as the "file" already knew. But I was happy for your explanations. Thank you!

Best regards .

**Comment by Black-Thanos** [comment]
Hi Dougcello. 

FYI, there is a new version of WinPmem, have you tried it? https://github.com/Velocidex/WinPmem/releases

Here is a discussion I had with EricZ regarding the newer version
https://github.com/EricZimmerman/KapeFiles/issues/292#issue-722178996

Respect.

**Comment by dougcello** [comment]
> Hi Dougcello.
> 
> FYI, there is a new version of WinPmem, have you tried it? https://github.com/Velocidex/WinPmem/releases
> 
> Here is a discussion I had with EricZ regarding the newer version
> [EricZimmerman/KapeFiles#292 (comment)](https://github.com/EricZimmerman/KapeFiles/issues/292#issue-722178996)
> 
> Respect.

Thank you for notifying me of this new version. I honestly wouldn't know before I needed to study a new case.

Best.
