### ISSUE TITLE
Problem about _get_image_mem

### ISSUE THREAD

**Issue by balabalablueqwq** [volatilityfoundation/volatility#758]
what is _IMAGE_DOS_HEADER._get_image_mem designed for? 
it doesn't return the contents of memory,which is quite different from _get_image_exe

**Comment by atcuno** [comment]
@balabalablueqwq 

Volatility has two different options for recovering PE files from memory. The first (_get_image_exe) uses the sizes of the sections as specified in the original file on disk. The second (_get_image_mem) gets the entire pages/regions that sections are on as this helps to uncover strings/data generated by runtime unpackers.
