### ISSUE TITLE
Windows 10 plugin Isses/Errors

### ISSUE THREAD

**Issue by jackdyson1399** [volatilityfoundation/volatility#759]
Hello, 
I am relatively new to RAM Capture and Analysis and am trying to understand Volatility and Volatility3's capabilities.
I recently undertook several RAM Captures using a variety of tool on a variety of Windows Virtual Machines with VMware Workstation. I am using the latest downloads of the Capture tools an am using the latest GIT Repository for Volatility. Out of interest I also used the Volatility standalone executable but got the same results.
I have attached my results in this excel spreadsheet here 
[Volatility2 Testing Log.xlsx](https://github.com/volatilityfoundation/volatility/files/5459567/Volatility2.Testing.Log.xlsx)

As you can see, Win7 sees success on the most part, however many of the Windows10 captures returned unsuccessful outputs. I am just wanting to know if this is normal for Volatility? Does it generally struggle with Windows 10 RAM captures?

**Comment by atcuno** [comment]
Hey @jackdyson1399 

Thank you for the very detailed breakdown!

Volatility supports all Windows 10 versions in general, but as you found, a couple capabilities will not work and/or be possible.

For example, the formats of hashdump and lsadump changed and the plugins need updating to the new versions. This same for consoles/cmdscan.

The mimikatz plugin still works, but by default Windows 10 does not store plaintext passwords in memory. This requires changing a registry key, which there is no legitimate reason to do - so this key is only changed if attackers/malware alter it. You would see the same issue if you ran the real mimikatz application on the live system.

For VMware, did you have the vmss and vmem files both in the same directory?

For netscan, we often have to update the offsets for the data structures. It seems like these may be behind on the latest version. This is something we can look into.

**Comment by jackdyson1399** [comment]
Hi, 
Thanks for your reply. 
I did take both the .vmem and the .vmss files and place them in the same directory with the same names as I saw on various pages that this was an issue.

So how do I go about updating the hashdump, lsadump, consoles and cmdscan plugins so they produce some results for Windows10?
