### ISSUE TITLE
Syntax Error missing parenthesis on Kali Linux

### ISSUE THREAD

**Issue by frenchiveruti** [volatilityfoundation/volatility#764]
![imagen](https://user-images.githubusercontent.com/1095997/101197624-20714380-3641-11eb-8c59-ceb2f14fe8eb.png)
As you can see, I cloned the folder, running with Py3 and still.

**Comment by frenchiveruti** [comment]
![Uploading imagen.png…]()

**Comment by frenchiveruti** [comment]
![imagen](https://user-images.githubusercontent.com/1095997/101198027-99709b00-3641-11eb-86cc-82aa140dd837.png)

**Comment by frenchiveruti** [comment]
![imagen](https://user-images.githubusercontent.com/1095997/101198548-637fe680-3642-11eb-865a-801ce4d67e14.png)

**Comment by iMHLv2** [comment]
You're running volatility2 with python3. Try using volatility3 instead: https://github.com/volatilityfoundation/volatility3

**Comment by frenchiveruti** [comment]
Yes, thanks.
