### ISSUE TITLE
error loading vol.py 

### ISSUE THREAD

**Issue by modz2014** [volatilityfoundation/volatility#779]
Volatility Foundation Volatility Framework 2.6.1
*** Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.malware.threads (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.mac.apihooks_kernel (ImportError: Error loading the diStorm dynamic library (or cannot load library into process).)
*** Failed to import volatility.plugins.mac.check_syscall_shadow (ImportError: Error loading the diStorm dynamic library (or cannot load library into process).)
*** Failed to import volatility.plugins.ssdt (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.mac.apihooks (ImportError: Error loading the diStorm dynamic library (or cannot load library into process).)

this is with installing the packages even distorm linux couldn't seem to find a fix everything i find says install distorm when i have already installed it

**Comment by CaptWake** [comment]
Hi, could you give me some more information about which python version are you using and the command line are you trying to execute?
