### ISSUE TITLE
(SOLVED) No module.dwarf installed after executing apt install dwarfdump, build-essential, linux-headers-generic, & make

### ISSUE THREAD

**Issue by AryaSecLab** [volatilityfoundation/volatility#822]
Solved! 

On Sep 19, 2022

>>> Prerequisites:
root@arya-VirtualBox:/# apt update 
root@arya-VirtualBox:/# uname -mrs
root@arya-VirtualBox:/# inxi -v8
root@arya-VirtualBox:/# apt -y install git
root@arya-VirtualBox:/# apt -y install gcc 
root@arya-VirtualBox:/# apt -y install python
root@arya-VirtualBox:/# apt -y install make
root@arya-VirtualBox:/# apt -y install zip 
root@arya-VirtualBox:/# apt -y install autoconf
Install YARA https://yara.readthedocs.io/en/stable/gettingstarted.html
root@arya-VirtualBox:/# pip3 install pycrypto ; pip install distorm3

>>> Installing Volatility:
root@arya-VirtualBox:/# cd /opt ; ls
root@arya-VirtualBox:/# git clone https://github.com/volatilityfoundation/volatility.git
root@arya-VirtualBox:/# cd volatility/tools/linux ; ls
root@arya-VirtualBox:/volatility/tools/linux# apt -y install dwarfdump
root@arya-VirtualBox:/volatility/tools/linux# cd .. ; ls
root@arya-VirtualBox:/volatility/tools# chown -R arya linux 
root@arya-VirtualBox:/volatility/tools# ls -lisa 
root@arya-VirtualBox:/volatility/tools# cd .. ; ls
root@arya-VirtualBox:/volatility# make
root@arya-VirtualBox:/volatility# cd /boot ; ls
root@arya-VirtualBox:/boot# zip /opt/volatility/volatility/plugins/overlays/linux/Ubuntu-20.04.2_5.15.0-46-generic.zip /opt/volatility/tools/linux/module.dwarf /boot/System.map-5.15.0-46-generic 
root@arya-VirtualBox:/boot# cd /opt/volatility ; ls 
root@arya-VirtualBox:/volatility# git clone https://github.com/gdabah/distorm.git
root@arya-VirtualBox:/volatility# cd distorm ; ls
root@arya-VirtualBox:/volatility/distorm# python setup.py build
root@arya-VirtualBox:/volatility/distorm# python setup.py build install
root@arya-VirtualBox:/volatility/distorm# cd .. ; ls
root@arya-VirtualBox:/volatility# wget https://ftp.dlitz.net/pub/dlitz/crypto/pycrypto/pycrypto-2.6.1.tar.gz
root@arya-VirtualBox:/volatility# tar -vxfz pycrypto-2.6.1.tar.gz 
root@arya-VirtualBox:/volatility# cd pycrypto-2.6.1 ; ls
root@arya-VirtualBox:/volatility# python setup.py build
root@arya-VirtualBox:/volatility# python setup.py build install
root@arya-VirtualBox:/volatility# reboot

>>> Executing Volatility:
root@arya-VirtualBox:/volatility# python vol.py --info | grep linux
root@arya-VirtualBox:/volatility# python vol.py --info | grep linux
root@arya-VirtualBox:/volatility# python vol.py -f /home/arya/Documents/MAR_pmud/Windows_RAM.mem imageinfo

**Comment by miszr** [comment]
Please close issue if solved.

**Comment by AryaSecLab** [comment]
This issue has been solved. It's close now.
