### ISSUE TITLE
Error when I make profile in Window 8 Pro (64 bits)

### ISSUE THREAD

**Issue by bakiez** [volatilityfoundation/volatility#91]
I make my memory image with dumpit.
when I make, profile, I got this error.
I used Volatility 2.4 and I test upon Kali Linux.
The default version is 2.3.1 in Kali Linux so I download dedicated 2.4 version.

python vol.py -f '/media/L.P.ostaoak/mem/MADI/ACY-20140914-143336.raw' imageinfo
Volatility Foundation Volatility Framework 2.4
**\* Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined)
**\* Failed to import volatility.plugins.ssdt (NameError: name 'distorm3' is not defined)
**\* Failed to import volatility.plugins.mac.apihooks_kernel (ImportError: No module named distorm3)
**\* Failed to import volatility.plugins.linux.apihooks (ImportError: No module named distorm3)
**\* Failed to import volatility.plugins.malware.threads (NameError: name 'distorm3' is not defined)
**\* Failed to import volatility.plugins.mac.check_syscall_shadow (ImportError: No module named distorm3)
**\* Failed to import volatility.plugins.mac.apihooks (ImportError: No module named distorm3)
Determining profile based on KDBG search...

```
      Suggested Profile(s) : No suggestion (Instantiated with Win8SP1x64)
                 AS Layer1 : AMD64PagedMemory (Kernel AS)
                 AS Layer2 : FileAddressSpace (/media/L.P.ostaoak/mem/MADI/ACY-20140914-143336.raw)
                  PAE type : No PAE
                       DTB : 0x1aa000L
         KUSER_SHARED_DATA : 0xfffff78000000000L
       Image date and time : 2014-09-14 11:23:49 UTC+0000
 Image local date and time : 2014-09-14 17:53:49 +0630
```
# 

And then I make kdbgscan again, 

python vol.py -f '/media/L.P.ostaoak/mem/MADI/ACY-20140914-143336.raw' kdbgscan
Volatility Foundation Volatility Framework 2.4
**\* Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined)
**\* Failed to import volatility.plugins.ssdt (NameError: name 'distorm3' is not defined)
**\* Failed to import volatility.plugins.mac.apihooks_kernel (ImportError: No module named distorm3)
**\* Failed to import volatility.plugins.malware.threads (NameError: name 'distorm3' is not defined)
**\* Failed to import volatility.plugins.linux.apihooks (ImportError: No module named distorm3)
**\* Failed to import volatility.plugins.mac.check_syscall_shadow (ImportError: No module named distorm3)
**\* Failed to import volatility.plugins.mac.apihooks (ImportError: No module named distorm3)

But I cannot get any results for this.
Please help to fix my errors. Why is that ?

**Comment by bisbits** [comment]
Please make sure you install all dependencies: 
$ pip install openpyxl
$ pip install ujson
$ pip install pycrypto
$ pip install distorm3
$ pip install pytz
