### ISSUE TITLE
yarascan changes to work with yara 3.0+

### ISSUE THREAD

**Issue by crankyflamingo** [volatilityfoundation/volatility#98]
Ahoy. I was running into wierd errors with a fresh linux install, python 2.7.x, vol 2.4 and newly synced yara 3.0 (and later 3.1) binaries and python extensions. Essentially it looks like the class changed slightly such that this throws error (match is now a string):

malfind.py:108

```
  for match in rule.match(data = data):
                    # We currently don't use name or value from the 
                    # yara results but they can be yielded in the 
                    # future if necessary. 
                    for moffset, _name, _value in match.strings:
                        if moffset < constants.SCAN_BLOCKSIZE:
                            yield match, moffset + i
```

Made some tweaks to get it to work with yara V3 that you may want to incorporate. In release code you could probably check the version and decide which mechanism you'd like to use to extract the data. Relevant changes to malfind.py:

class BaseYaraScanner3(object):
    """An address space scanner for Yara signatures."""
    overlap = 1024

```
def __init__(self, address_space = None, rules = None):
    self.rules = rules
    self.address_space = address_space
    self.matches = []
    self.offs = 0

def _match_callback(self, data):
    if data['matches']:
        for match in data['strings']:
            if match['offset'] < constants.SCAN_BLOCKSIZE:
                self.matches.append((match['data'],
                                     match['offset'] + self.offs))

    return yara.CALLBACK_CONTINUE

def scan(self, offset, maxlen):
    # Start scanning from offset until maxlen:
    i = offset

    if isinstance(self.rules, list):
        rules = self.rules
    else:
        rules = [self.rules]

    while i < offset + maxlen:
        # Read some data and match it.match
        to_read = min(constants.SCAN_BLOCKSIZE + self.overlap, offset + maxlen - i)
        data = self.address_space.zread(i, to_read)
        self.offs = i
        if data:
            for rule in rules:
                rule.match(data = data,callback=self._match_callback)

            while self.matches:
                yield self.matches.pop()

        i += constants.SCAN_BLOCKSIZE
```

...

def render_text(self, outfd, data):

```
    if self._config.DUMP_DIR and not os.path.isdir(self._config.DUMP_DIR):
        debug.error(self._config.DUMP_DIR + " is not a directory")

    for o, addr, hit, content in data:
        outfd.write("Rule: {0}\n".format(hit))
```

**Comment by allewwaly** [comment]
Actually I've meet the same problem. While running volatility with yarascan, it reminds me that yara was not installed. However I did installed yara successfully according to http://yara.readthedocs.org/en/v3.3.0/gettingstarted.html. And yara -v shows "yara 3.3.0", so how can I configure volatility to find the yara which has been installed?

**Comment by allewwaly** [comment]
I've also tried the old version of yara-1.7, it meets the same problem.

**Comment by kongo86** [comment]
You need to update your library path to look where yara was installed

**Comment by kongo86** [comment]
# echo "/usr/local/lib" >> /etc/ld.so.conf
# ldconfig

Taken from https://code.google.com/p/volatility/wiki/FullInstallation

Hope this helps

**Comment by allewwaly** [comment]
Thanks for you replying. I've reinstalled volatility and yara and tried what you said, it still notified:

john@ubuntu:~$ python volatility/vol.py -f memory.07070c1c.img yarascan --yara-rules="windows-update-http.com"
Volatility Foundation Volatility Framework 2.4
*** Failed to import volatility.plugins.dumpcerts (NameError: name 'yara' is not defined)
*** Failed to import volatility.plugins.linux.netscan (ImportError: libyara.so.0: cannot open shared object file: No such file or directory)
ERROR   : volatility.plugins.malware.malfind: Please install Yara from https://plusvic.github.io/yara/

**Comment by kongo86** [comment]
Mmmm... so you tried
#yara  -v
And you get version info?
What if you do:
# python
>import yara

I'm on my phone and no access to a system right now. :(

**Comment by allewwaly** [comment]
Finally worked with yara-1.7 reinstalled. So it must be the version problem of yara. Thanks anyway.

**Comment by kongo86** [comment]
For the record I'm running volatility and latest yara. :)

**Comment by ksanchezcld** [comment]
pip install yara
Downloading/unpacking yara
  Downloading yara-1.7.7.tar.gz (387kB): 387kB downloaded
  Running setup.py (path:/tmp/pip_build_root/yara/setup.py) egg_info for package yara
    
Installing collected packages: yara
  Running setup.py install for yara
    
    Installing yara-ctypes script to /usr/local/bin
Successfully installed yara

**Comment by ksanchezcld** [comment]
apt-get install yara

**Comment by r3g31rk** [comment]
I met the same problem on Ubuntu 20.04 + Python 3.8
Yara has been installed in 2 different ways (not simultaneously):
- first according to the documentation found on https://plusvic.github.io/yara/ => the command `yara -v` returns 4.2
- then with the synaptic packet manager, I installed `yara` + `python3-yara` + `libyara3` => the command `yara -v` returns 3.9

I also run the commands `echo "/usr/local/lib" >> /etc/ld.so.conf` and `ldconfig`.

When I run something like `vol.py -f dump.dmp --profile=Win7SP1x86 yarascan -p 666 -Y "awesome_rule"` I get something like `ERROR   : volatility.debug    : Please install Yara from https://plusvic.github.io/yara/`

If somebody found a workaround, please poke me!
